### ISSUE TITLE
[Feature] Metabase support for Doris

### ISSUE THREAD

**Issue by lllwan** [apache/doris#10085]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Description

As one of the most widely used BI tools. Metabase support helps improve the ecology. However, it is currently impossible to add Doris data sources in metabase using mysql. This may be because metabase is sensitive to information_ Schema dependency. On the one hand, you can contribute Doris connectors to the metabase community, or provide MySQL information_ Schema support.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by stalary** [comment]
Let me have a look.

**Comment by lllwan** [comment]
@stalary Add MySQL directly to metabase and use the connection configuration of Doris. In fact, it cannot be added. After consulting some documents, it is found that metabase needs to pass information_ Schema to get the metadata information of the table.

**Comment by stalary** [comment]
> @stalary Add MySQL directly to metabase and use the connection configuration of Doris. In fact, it cannot be added. After consulting some documents, it is found that metabase needs to pass information_ Schema to get the metadata information of the table.

I have accessed it through mysql, but found that only part of SQL functions have compatibility problems.

**Comment by lllwan** [comment]
> > @stalary Add MySQL directly to metabase and use the connection configuration of Doris. In fact, it cannot be added. After consulting some documents, it is found that metabase needs to pass information_ Schema to get the metadata information of the table.
> 
> I have accessed it through mysql, but found that only part of SQL functions have compatibility problems.

The problem is that there is no information in Doris_ Schema, but metabase is used. Of course, this may be a metabase problem, but I understand that perhaps the community can consider contributing metabase connectors to improve the ecology.

**Comment by lllwan** [comment]
Unfortunately, neither Doris nor metabase uses technologies that I am familiar with.

**Comment by stalary** [comment]
> > > @stalary Add MySQL directly to metabase and use the connection configuration of Doris. In fact, it cannot be added. After consulting some documents, it is found that metabase needs to pass information_ Schema to get the metadata information of the table.
> > 
> > 
> > I have accessed it through mysql, but found that only part of SQL functions have compatibility problems.
> 
> The problem is that there is no information in information_ Schema, but metabase is used. Of course, this may be a metabase problem, but I understand that perhaps the community can consider contributing metabase connectors to improve the ecology.

I can normally use Doris in Metabase, I am not quite clear about the problem you mentioned, it is better to provide some screenshots or error information.

**Comment by lllwan** [comment]
@stalary What metabase version do you use?

**Comment by stalary** [comment]
> @stalary What metabase version do you use?

docker latest image

**Comment by lllwan** [comment]
Yes, the latest version is used and the connection is normal. Thank you.

**Comment by will0815** [comment]
Why do I report an error when syncing doris metadata in metabase, won't you?

doris log(v doris-2.0-beta ):
[ConnectProcessor.handleQueryException():468] Process one query failed because.
org.apache.doris.common.UserException: errCode = 2, detailMessage = (13.10.12.16)[CANCELLED][INVALID_ARGUMENT]unknown filter
	at org.apache.doris.qe.Coordinator.getNext(Coordinator.java:1185) ~[doris-fe.jar:1.2-SNAPSHOT]
	at org.apache.doris.qe.StmtExecutor.sendResult(StmtExecutor.java:1393) ~[doris-fe.jar:1.2-SNAPSHOT]
	at org.apache.doris.qe.StmtExecutor.handleQueryStmt(StmtExecutor.java:1344) ~[doris-fe.jar:1.2-SNAPSHOT]
	at org.apache.doris.qe.StmtExecutor.handleQueryWithRetry(StmtExecutor.java:593) ~[doris-fe.jar:1.2-SNAPSHOT]
	at org.apache.doris.qe.StmtExecutor.executeByNereids(StmtExecutor.java:540) ~[doris-fe.jar:1.2-SNAPSHOT]
	at org.apache.doris.qe.StmtExecutor.execute(StmtExecutor.java:419) ~[doris-fe.jar:1.2-SNAPSHOT]
	at org.apache.doris.qe.StmtExecutor.execute(StmtExecutor.java:409) ~[doris-fe.jar:1.2-SNAPSHOT]
	at org.apache.doris.qe.ConnectProcessor.handleQuery(ConnectProcessor.java:432) ~[doris-fe.jar:1.2-SNAPSHOT]
	at org.apache.doris.qe.ConnectProcessor.dispatch(ConnectProcessor.java:580) ~[doris-fe.jar:1.2-SNAPSHOT]
	at org.apache.doris.qe.ConnectProcessor.processOnce(ConnectProcessor.java:818) ~[doris-fe.jar:1.2-SNAPSHOT]
	at org.apache.doris.mysql.ReadListener.lambda$handleEvent$0(ReadListener.java:52) ~[doris-fe.jar:1.2-SNAPSHOT]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_271]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_271]

metabase(v46.6.2) log:
WARN sync.util :: sync table ,739'test_tbl'"fields error
java.sql.SQLTransientConnectionException: (conn=243) errCode = 2, detailMessage = [CANCELLED][INVALID_ARGUMENT]unknown filter
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionFactory.createException(ExceptionFactory.java:79)
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionFactory.create(ExceptionFactory.java:158)
	at org.mariadb.jdbc.MariaDbStatement.executeExceptionEpilogue(MariaDbStatement.java:262)
	at org.mariadb.jdbc.MariaDbStatement.executeInternal(MariaDbStatement.java:362)
	at org.mariadb.jdbc.MariaDbStatement.executeQuery(MariaDbStatement.java:611)
	at org.mariadb.jdbc.MariaDbDatabaseMetaData.executeQuery(MariaDbDatabaseMetaData.java:497)
	at org.mariadb.jdbc.MariaDbDatabaseMetaData.getPrimaryKeys(MariaDbDatabaseMetaData.java:604)
	at com.mchange.v2.c3p0.impl.NewProxyDatabaseMetaData.getPrimaryKeys(NewProxyDatabaseMetaData.java:3198)
	at metabase.driver.sql_jdbc.sync.describe_table$fn__77379$fn__77380.invoke(describe_table.clj:198)
