### ISSUE TITLE
[Feature] 

### ISSUE THREAD

**Issue by zhanghaicheng1** [apache/doris#10328]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Description

单机快速部署，注册BE的 alive状态是false，怎么去排查问题

```
2022-06-22 10:47:24,746 WARN (heartbeat mgr|34) [HeartbeatMgr.runAfterCatalogReady():139] get bad heartbeat response: type: BACKEND, status: BAD, msg: java.net.ConnectException: Connection refused (Connection refused), beId: 11001, bePort: 0, httpPort: 0, brpcPort: 0
2022-06-22 10:47:24,746 WARN (heartbeat-mgr-pool-7|164) [HeartbeatMgr$BackendHeartbeatHandler.call():260] backend heartbeat got exception
org.apache.thrift.transport.TTransportException: java.net.ConnectException: Connection refused (Connection refused)
	at org.apache.thrift.transport.TSocket.open(TSocket.java:226) ~[spark-dpp-0.15-SNAPSHOT.jar:0.15-SNAPSHOT]
	at org.apache.doris.common.GenericPool$ThriftClientFactory.create(GenericPool.java:142) ~[palo-fe.jar:0.15-SNAPSHOT]
	at org.apache.doris.common.GenericPool$ThriftClientFactory.create(GenericPool.java:126) ~[palo-fe.jar:0.15-SNAPSHOT]
	at org.apache.commons.pool2.BaseKeyedPooledObjectFactory.makeObject(BaseKeyedPooledObjectFactory.java:62) ~[commons-pool2-2.2.jar:2.2]
	at org.apache.commons.pool2.impl.GenericKeyedObjectPool.create(GenericKeyedObjectPool.java:1012) ~[commons-pool2-2.2.jar:2.2]
	at org.apache.commons.pool2.impl.GenericKeyedObjectPool.borrowObject(GenericKeyedObjectPool.java:356) ~[commons-pool2-2.2.jar:2.2]
	at org.apache.commons.pool2.impl.GenericKeyedObjectPool.borrowObject(GenericKeyedObjectPool.java:277) ~[commons-pool2-2.2.jar:2.2]
	at org.apache.doris.common.GenericPool.borrowObject(GenericPool.java:95) ~[palo-fe.jar:0.15-SNAPSHOT]
	at org.apache.doris.system.HeartbeatMgr$BackendHeartbeatHandler.call(HeartbeatMgr.java:224) [palo-fe.jar:0.15-SNAPSHOT]
	at org.apache.doris.system.HeartbeatMgr$BackendHeartbeatHandler.call(HeartbeatMgr.java:202) [palo-fe.jar:0.15-SNAPSHOT]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_172]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_172]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_172]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_172]
Caused by: java.net.ConnectException: Connection refused (Connection refused)
	at java.net.PlainSocketImpl.socketConnect(Native Method) ~[?:1.8.0_172]
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350) ~[?:1.8.0_172]
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206) ~[?:1.8.0_172]
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188) ~[?:1.8.0_172]
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[?:1.8.0_172]
	at java.net.Socket.connect(Socket.java:589) ~[?:1.8.0_172]
	at org.apache.thrift.transport.TSocket.open(TSocket.java:221) ~[spark-dpp-0.15-SNAPSHOT.jar:0.15-SNAPSHOT]
	... 13 more
2022-06-22 10:47:24,747 WARN (heartbeat mgr|34) [HeartbeatMgr.runAfterCatalogReady():139] get bad heartbeat response: type: BACKEND, status: BAD, msg: java.net.ConnectException: Connection refused (Connection refused), beId: 10002, bePort: 0, httpPort: 0, brpcPort: 0
```

### Use case

![Uploading image.png…]()

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zhanghaicheng1** [comment]
看了下警告日志提示如下：
```
E0622 09:51:21.122166 54569 storage_engine.cpp:418] File descriptor number is less than 60000. Please use (ulimit -n) to set a value equal or greater than 60000
W0622 09:51:21.122720 54569 storage_engine.cpp:180] check fd number failed, error: Internal error: file descriptors limit is too small
W0622 09:51:21.122738 54569 storage_engine.cpp:102] open engine failed, error: Internal error: file descriptors limit is too small
F0622 09:51:21.123497 54569 doris_main.cpp:406] fail to open StorageEngine, res=file descriptors limit is too small
E0622 10:26:57.538239 11737 storage_engine.cpp:418] File descriptor number is less than 60000. Please use (ulimit -n) to set a value equal or greater than 60000
W0622 10:26:57.538352 11737 storage_engine.cpp:180] check fd number failed, error: Internal error: file descriptors limit is too small
W0622 10:26:57.538369 11737 storage_engine.cpp:102] open engine failed, error: Internal error: file descriptors limit is too small
F0622 10:26:57.539428 11737 doris_main.cpp:406] fail to open StorageEngine, res=file descriptors limit is too small
E0622 10:43:22.816769 19587 storage_engine.cpp:418] File descriptor number is less than 60000. Please use (ulimit -n) to set a value equal or greater than 60000
W0622 10:43:22.816854 19587 storage_engine.cpp:180] check fd number failed, error: Internal error: file descriptors limit is too small
W0622 10:43:22.816869 19587 storage_engine.cpp:102] open engine failed, error: Internal error: file descriptors limit is too small
F0622 10:43:22.817775 19587 doris_main.cpp:406] fail to open StorageEngine, res=file descriptors limit is too small
```

**Comment by zhanghaicheng1** [comment]
修改open files数即可。
