### ISSUE TITLE
[Bug] be crashes when sql contains row_number function in SetOperationNode

### ISSUE THREAD

**Issue by ChPi** [apache/doris#10433]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Version

1.0

### What's Wrong?

log
```
descriptors.cpp:372] Check failed: id < _tuple_idx_map.size() (6 vs. 5) RowDescriptor: tuple_desc_map: [Tuple(id=4 size=24 slots=[Slot(id=6 type=INT col=-1 offset=4 null=(offset=0 mask=80)), Slot(id=7 type=INT col=-1 offset=8 null=(offset=0 mask=40)), Slot(id=8 type=BIGINT col=-1 offset=16 null=(offset=0 mask=0))] has_varlen_slots=0)] tuple_id_map: [-1, -1, -1, -1, 0] tuple_is_nullable: [0]
```
stack
```
#0  0x00007f1d24d3b387 in raise () from /lib64/libc.so.6
#1  0x00007f1d24d3ca78 in abort () from /lib64/libc.so.6
#2  0x0000558386da9f74 in google::DumpStackTraceAndExit () at src/utilities.cc:160
#3  0x0000558389099e4d in google::LogMessage::Fail () at src/logging.cc:1650
#4  0x000055838909c389 in google::LogMessage::SendToLog (this=0x7f1c852acd60) at src/logging.cc:1607
#5  0x00005583890999b6 in google::LogMessage::Flush (this=0x7f1c852acd60) at src/logging.cc:1476
#6  0x000055838909c9f9 in google::LogMessageFatal::~LogMessageFatal (this=this@entry=0x7f1c852acd60, __in_chrg=<optimized out>) at src/logging.cc:2226
#7  0x000055838741d575 in doris::RowDescriptor::get_tuple_idx (this=this@entry=0x558391dc0b80, id=6)
    at /var/local/ldb-toolchain/include/c++/11/ext/new_allocator.h:89
#8  0x0000558387c0b5c6 in doris::SetOperationNode::prepare (this=0x558391dc0b00, state=<optimized out>) at /root/doris/be/src/exec/set_operation_node.cpp:61
#9  0x00005583874ce941 in doris::PlanFragmentExecutor::prepare (this=this@entry=0x55838e490d70, request=..., fragments_ctx=<optimized out>)
    at /var/local/ldb-toolchain/include/c++/11/bits/unique_ptr.h:173
#10 0x000055838744dec9 in doris::FragmentExecState::prepare (params=..., this=0x55838e490d00) at /root/doris/be/src/runtime/fragment_mgr.cpp:225
#11 doris::FragmentMgr::exec_plan_fragment(doris::TExecPlanFragmentParams const&, std::function<void (doris::PlanFragmentExecutor*)>) (this=0x55838e1d4fc0,
    params=..., cb=...) at /root/doris/be/src/runtime/fragment_mgr.cpp:622
#12 0x000055838744fd00 in doris::FragmentMgr::exec_plan_fragment (this=0x55838e1d4fc0, params=...) at /root/doris/be/src/runtime/fragment_mgr.cpp:518
#13 0x000055838753b23a in doris::PInternalServiceImpl<doris::PBackendService>::_exec_plan_fragment (this=this@entry=0x558390a45d40, ser_request=...,
    compact=<optimized out>) at /root/doris/be/src/service/internal_service.cpp:180
#14 0x000055838753b305 in doris::PInternalServiceImpl<doris::PBackendService>::exec_plan_fragment (this=0x558390a45d40, cntl_base=<optimized out>,
    request=<optimized out>, response=0x5583916ccb00, done=0x558391e92c80) at /root/doris/be/src/service/internal_service.cpp:109
#15 0x000055838928188a in brpc::policy::ProcessHttpRequest (msg=<optimized out>)
    at /var/local/incubator-doris/thirdparty/src/incubator-brpc-1.0.0/src/brpc/policy/http_rpc_protocol.cpp:1499
#16 0x000055838924c677 in brpc::ProcessInputMessage (void_arg=void_arg@entry=0x558391a8b210)
    at /var/local/incubator-doris/thirdparty/src/incubator-brpc-1.0.0/src/brpc/input_messenger.cpp:135
#17 0x000055838924d4f1 in brpc::RunLastMessage::operator() (last_msg=0x558391a8b210, this=<optimized out>)
    at /var/local/incubator-doris/thirdparty/src/incubator-brpc-1.0.0/src/brpc/input_messenger.cpp:141
#18 std::unique_ptr<brpc::InputMessageBase, brpc::RunLastMessage>::~unique_ptr (this=<synthetic pointer>, __in_chrg=<optimized out>)
    at /var/local/ldb-toolchain/include/c++/11/bits/unique_ptr.h:361
#19 brpc::InputMessenger::OnNewMessages (m=0x558391fae000) at /var/local/incubator-doris/thirdparty/src/incubator-brpc-1.0.0/src/brpc/input_messenger.cpp:335
#20 0x00005583892fb24e in brpc::Socket::ProcessEvent (arg=0x558391fae000)
    at /var/local/incubator-doris/thirdparty/src/incubator-brpc-1.0.0/src/brpc/socket.cpp:1018
#21 0x00005583893bb23f in bthread::TaskGroup::task_runner (skip_remained=<optimized out>)
    at /var/local/incubator-doris/thirdparty/src/incubator-brpc-1.0.0/src/bthread/task_group.cpp:295
#22 0x00005583893abe41 in bthread_make_fcontext ()
```

### What You Expected?

query is successful

### How to Reproduce?

create table
```sql
CREATE TABLE `test` (
  `k1` int(11) NULL COMMENT "",
  `k2` int(11) NULL COMMENT ""
) ENGINE=OLAP
DUPLICATE KEY(`k1`, `k2`)
COMMENT "OLAP"
DISTRIBUTED BY HASH(`k1`) BUCKETS 1
PROPERTIES (
"replication_allocation" = "tag.location.default: 1",
"in_memory" = "false",
"storage_format" = "V2"
);
```
query
```sql
select  *,row_number() over 
(PARTITION BY k1 order by k2 desc ) AS ROWNAM from test
MINUS
select  *,1 + row_number() over 
(PARTITION BY k1 order by k2 desc ) AS ROWNAM from test
```
be crashes

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by morningman** [comment]
Fixed in v1.1 with vectorized engine. But still has problem in non-vec engine in v1.1
