### ISSUE TITLE
[Bug] DCHECK fail on aggregate

### ISSUE THREAD

**Issue by BiteTheDDDDt** [apache/doris#10541]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Version

master

### What's Wrong?

```sql
CREATE TABLE `test` (
  `k1` tinyint(4) NULL,
  `k2` smallint(6) NULL,
  `k3` int(11) NULL,
  `k4` bigint(20) NULL,
  `k5` decimal(9, 3) NULL,
  `k6` char(5) NULL,
  `k10` date NULL,
  `k11` datetime NULL,
  `k7` varchar(20) NULL,
  `k8` double MAX NULL,
  `k9` float SUM NULL
) ENGINE=OLAP
AGGREGATE KEY(`k1`, `k2`, `k3`, `k4`, `k5`, `k6`, `k10`, `k11`, `k7`)
COMMENT 'OLAP'
PARTITION BY RANGE(`k1`)
(PARTITION p1 VALUES [("-128"), ("-64")),
PARTITION p2 VALUES [("-64"), ("0")),
PARTITION p3 VALUES [("0"), ("64")),
PARTITION p4 VALUES [("64"), (MAXVALUE)))
DISTRIBUTED BY HASH(`k1`) BUCKETS 5
PROPERTIES (
"replication_allocation" = "tag.location.default: 1",
"in_memory" = "false",
"storage_format" = "V2"
);

select avg(distinct k1), avg(k1) from test;
```

```cpp
#0  0x00007fc906ec24f5 in raise () from /lib64/libc.so.6
#1  0x00007fc906ec3cd5 in abort () from /lib64/libc.so.6
#2  0x00007fc91100d2a9 in google::DumpStackTraceAndExit () at src/utilities.cc:160
#3  0x00007fc9110028bd in google::LogMessage::Fail () at src/logging.cc:1650
#4  0x00007fc911004df9 in google::LogMessage::SendToLog (this=0x7fc8af369350) at src/logging.cc:1607
#5  0x00007fc911002426 in google::LogMessage::Flush (this=0x7fc8af369350) at src/logging.cc:1476
#6  0x00007fc911005469 in google::LogMessageFatal::~LogMessageFatal (this=<optimized out>, __in_chrg=<optimized out>) at src/logging.cc:2226
#7  0x00007fc90f4c5580 in doris::vectorized::AggregationNode::_merge_without_key (this=0x7fc91c6e2480, block=0x7fc8af369f00)
    at /home/disk4/zhangstar/incubator-doris/be/src/vec/exec/vaggregation_node.cpp:536
#8  0x00007fc90f52877e in std::__invoke_impl<doris::Status, doris::Status (doris::vectorized::AggregationNode::*&)(doris::vectorized::Block*), doris::vectorized::AggregationNode*&, doris::vectorized::Block*> (__f=
    @0x7fc91c70af00: (doris::Status (doris::vectorized::AggregationNode::*)(doris::vectorized::AggregationNode * const, doris::vectorized::Block *)) 0x7fc90f4c5304 <doris::vectorized::AggregationNode::_merge_without_key(doris::vectorized::Block*)>, __t=@0x7fc91c70af10: 0x7fc91c6e2480) at /home/disk4/zhangstar/baidu/bdg/doris/palo-toolchain/ldb_toolchain/include/c++/11/bits/invoke.h:74
#9  0x00007fc90f527aa9 in std::__invoke_r<doris::Status, doris::Status (doris::vectorized::AggregationNode::*&)(doris::vectorized::Block*), doris::vectorized::AggregationNode*&, doris::vectorized::Block*> (__fn=
    @0x7fc91c70af00: (doris::Status (doris::vectorized::AggregationNode::*)(doris::vectorized::AggregationNode * const, doris::vectorized::Block *)) 0x7fc90f4c5304 <doris::vectorized::AggregationNode::_merge_without_key(doris::vectorized::Block*)>) at /home/disk4/zhangstar/baidu/bdg/doris/palo-toolchain/ldb_toolchain/include/c++/11/bits/invoke.h:116
#10 0x00007fc90f526d85 in std::_Bind_result<doris::Status, doris::Status (doris::vectorized::AggregationNode::*(doris::vectorized::AggregationNode*, std::_Placeholder<1>))(doris::vectorized::Block*)>::__call<doris::Status, doris::vectorized::Block*&&, 0ul, 1ul>(std::tuple<doris::vectorized::Block*&&>&&, std::_Index_tuple<0ul, 1ul>) (this=0x7fc91c70af00, __args=...)
    at /home/disk4/zhangstar/baidu/bdg/doris/palo-toolchain/ldb_toolchain/include/c++/11/functional:571
#11 0x00007fc90f5259aa in std::_Bind_result<doris::Status, doris::Status (doris::vectorized::AggregationNode::*(doris::vectorized::AggregationNode*, std::_Placeholder<1>))(doris::vectorized::Block*)>::operator()<doris::vectorized::Block*>(doris::vectorized::Block*&&) (this=0x7fc91c70af00) at /home/disk4/zhangstar/baidu/bdg/doris/palo-toolchain/ldb_toolchain/include/c++/11/functional:631
#12 0x00007fc90f52302b in std::__invoke_impl<doris::Status, std::_Bind_result<doris::Status, doris::Status (doris::vectorized::AggregationNode::*(doris::vectorized::AggregationNode*, std::_Placeholder<1>))(doris::vectorized::Block*)>&, doris::vectorized::Block*>(std::__invoke_other, std::_Bind_result<doris::Status, doris::Status (doris::vectorized::AggregationNode::*(doris::vectorized::AggregationNode*, std::_Placeholder<1>))(doris::vectorized::Block*)>&, doris::vectorized::Block*&&) (__f=...) at /home/disk4/zhangstar/baidu/bdg/doris/palo-toolchain/ldb_toolchain/include/c++/11/bits/invoke.h:61
#13 0x00007fc90f51eb85 in std::__invoke_r<doris::Status, std::_Bind_result<doris::Status, doris::Status (doris::vectorized::AggregationNode::*(doris::vectorized::AggregationNode*, std::_Placeholder<1>))(doris::vectorized::Block*)>&, doris::vectorized::Block*>(std::_Bind_result<doris::Status, doris::Status (doris::vectorized::AggregationNode::*(doris::vectorized::AggregationNode*, std::_Placeholder<1>))(doris::vectorized::Block*)>&, doris::vectorized::Block*&&) (__fn=...) at /home/disk4/zhangstar/baidu/bdg/doris/palo-toolchain/ldb_toolchain/include/c++/11/bits/invoke.h:116
#14 0x00007fc90f51cc7f in std::_Function_handler<doris::Status (doris::vectorized::Block*), std::_Bind_result<doris::Status, doris::Status (doris::vectorized::AggregationNode::*(doris::vectorized::AggregationNode*, std::_Placeholder<1>))(doris::vectorized::Block*)> >::_M_invoke(std::_Any_data const&, doris::vectorized::Block*&&) (__functor=..., __args#0=@0x7fc8af369e08: 0x7fc8af369f00)
    at /home/disk4/zhangstar/baidu/bdg/doris/palo-toolchain/ldb_toolchain/include/c++/11/bits/std_function.h:292
#15 0x00007fc90f51779e in std::function<doris::Status (doris::vectorized::Block*)>::operator()(doris::vectorized::Block*) const (this=0x7fc91c6e2848, __args#0=0x7fc8af369f00)
    at /home/disk4/zhangstar/baidu/bdg/doris/palo-toolchain/ldb_toolchain/include/c++/11/bits/std_function.h:560
#16 0x00007fc90f4c33d3 in doris::vectorized::AggregationNode::open (this=0x7fc91c6e2480, state=0x7fc91c6ed000) at /home/disk4/zhangstar/incubator-doris/be/src/vec/exec/vaggregation_node.cpp:363
#17 0x00007fc90e9208ad in doris::PlanFragmentExecutor::open_vectorized_internal (this=0x7fc91c6ce870) at /home/disk4/zhangstar/incubator-doris/be/src/runtime/plan_fragment_executor.cpp:255
#18 0x00007fc90e9204c1 in doris::PlanFragmentExecutor::open (this=0x7fc91c6ce870) at /home/disk4/zhangstar/incubator-doris/be/src/runtime/plan_fragment_executor.cpp:228
#19 0x00007fc90e8fd30e in doris::FragmentExecState::execute (this=0x7fc91c6ce800) at /home/disk4/zhangstar/incubator-doris/be/src/runtime/fragment_mgr.cpp:242
#20 0x00007fc90e900330 in doris::FragmentMgr::_exec_actual(std::shared_ptr<doris::FragmentExecState>, std::function<void (doris::PlanFragmentExecutor*)>) (this=0x7fc915ba0e00,
    exec_state=std::shared_ptr<doris::FragmentExecState> (use count 3, weak count 0) = {...}, cb=...) at /home/disk4/zhangstar/incubator-doris/be/src/runtime/fragment_mgr.cpp:483
#21 0x00007fc90e91cfd1 in std::__invoke_impl<void, void (doris::FragmentMgr::*&)(std::shared_ptr<doris::FragmentExecState>, std::function<void (doris::PlanFragmentExecutor*)>), doris::FragmentMgr*&, std::shared_ptr<doris::FragmentExecState>&, std::function<void (doris::PlanFragmentExecutor*)>&>(std::__invoke_memfun_deref, void (doris::FragmentMgr::*&)(std::shared_ptr<doris::FragmentExecState>, std::function<void (doris::PlanFragmentExecutor*)>), doris::FragmentMgr*&, std::shared_ptr<doris::FragmentExecState>&, std::function<void (doris::PlanFragmentExecutor*)>&) (__f=
    @0x7fc91c7420a0: (void (doris::FragmentMgr::*)(doris::FragmentMgr * const, std::shared_ptr<doris::FragmentExecState>, std::function<void(doris::PlanFragmentExecutor*)>)) 0x7fc90e900076 <doris::FragmentMgr::_exec_actual(std::shared_ptr<doris::FragmentExecState>, std::function<void (doris::PlanFragmentExecutor*)>)>, __t=@0x7fc91c7420e0: 0x7fc915ba0e00)
--Type <RET> for more, q to quit, c to continue without paging--
```

### What You Expected?

FIX

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by BiteTheDDDDt** [comment]
fixed on #10650
