### ISSUE TITLE
[Bug]  Fe crash by bdbje

### ISSUE THREAD

**Issue by yangzhg** [apache/doris#10705]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Version

master

### What's Wrong?
```
2022-07-05 23:27:27,685 WARN (replayer|79) [Catalog.replayJournal():2506] replay journal cost too much time: 1001 replayedJournalId: 1160191
2022-07-05 23:27:27,687 INFO (replayer|79) [Catalog.replayJournal():2478] replayed journal id is 1160191, replay to journal id is 1160192
2022-07-05 23:27:28,687 WARN (replayer|79) [BDBJournalCursor.next():148] Catch an exception when get next JournalEntity. key:1160192
com.sleepycat.je.LockTimeoutException: (JE 7.3.7) Lock expired. Locker 497486454 -1_replayer_ReplicaThreadLocker: waited for lock on database=1150001 LockAddr:1459556016 LSN=0x43/0x6648b type=READ grant=WAIT_NEW timeoutMillis=1000 startTime=1657034847687 endTime=1657034848687
Owners: [<LockInfo locker="<ReplayTxn id="-1495664">604669736 -1495664_ReplayThread_ReplayTxn" type="WRITE"/>]
Waiters: [<LockInfo locker="497486454 -1_replayer_ReplicaThreadLocker" type="READ"/>]

        at com.sleepycat.je.txn.LockManager.makeTimeoutException(LockManager.java:1117) ~[je-7.3.7.jar:7.3.7]
        at com.sleepycat.je.txn.LockManager.waitForLock(LockManager.java:606) ~[je-7.3.7.jar:7.3.7]
        at com.sleepycat.je.txn.LockManager.lock(LockManager.java:345) ~[je-7.3.7.jar:7.3.7]
        at com.sleepycat.je.txn.BasicLocker.lockInternal(BasicLocker.java:124) ~[je-7.3.7.jar:7.3.7]
        at com.sleepycat.je.rep.txn.ReplicaThreadLocker.lockInternal(ReplicaThreadLocker.java:63) ~[je-7.3.7.jar:7.3.7]
        at com.sleepycat.je.txn.Locker.lock(Locker.java:499) ~[je-7.3.7.jar:7.3.7]
        at com.sleepycat.je.dbi.CursorImpl.lockLN(CursorImpl.java:3585) ~[je-7.3.7.jar:7.3.7]
        at com.sleepycat.je.dbi.CursorImpl.lockLN(CursorImpl.java:3316) ~[je-7.3.7.jar:7.3.7]
        at com.sleepycat.je.dbi.CursorImpl.lockLNAndCheckDefunct(CursorImpl.java:2138) ~[je-7.3.7.jar:7.3.7]
        at com.sleepycat.je.dbi.CursorImpl.searchExact(CursorImpl.java:1950) ~[je-7.3.7.jar:7.3.7]
        at com.sleepycat.je.Cursor.searchExact(Cursor.java:4194) ~[je-7.3.7.jar:7.3.7]
        at com.sleepycat.je.Cursor.searchNoDups(Cursor.java:4055) ~[je-7.3.7.jar:7.3.7]
        at com.sleepycat.je.Cursor.search(Cursor.java:3857) ~[je-7.3.7.jar:7.3.7]
        at com.sleepycat.je.Cursor.getInternal(Cursor.java:1284) ~[je-7.3.7.jar:7.3.7]
        at com.sleepycat.je.Database.get(Database.java:1271) ~[je-7.3.7.jar:7.3.7]
        at com.sleepycat.je.Database.get(Database.java:1330) ~[je-7.3.7.jar:7.3.7]
        at org.apache.doris.journal.bdbje.BDBJournalCursor.next(BDBJournalCursor.java:108) [palo-fe.jar:0.15-SNAPSHOT]
        at org.apache.doris.catalog.Catalog.replayJournal(Catalog.java:2488) [palo-fe.jar:0.15-SNAPSHOT]
        at org.apache.doris.catalog.Catalog$3.runOneCycle(Catalog.java:2277) [palo-fe.jar:0.15-SNAPSHOT]
        at org.apache.doris.common.util.Daemon.run(Daemon.java:116) [palo-fe.jar:0.15-SNAPSHOT]
```

### What You Expected?

normal

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by hujiaoxiang** [comment]
老师 请问一下问题是怎么解决的
