### ISSUE TITLE
[Bug][Rollup] fe crash because npe on rollupBatchTask

### ISSUE THREAD

**Issue by BiteTheDDDDt** [apache/doris#10808]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Version

master

### What's Wrong?

```java
2022-07-13 17:28:33,292 ERROR (stateListener|84) [EditLog.loadJournal():881] Operation Type 121
java.lang.NullPointerException: null
	at org.apache.doris.task.AgentTaskQueue.removeBatchTask(AgentTaskQueue.java:76) ~[doris-fe.jar:1.0-SNAPSHOT]
	at org.apache.doris.alter.RollupJobV2.cancelInternal(RollupJobV2.java:543) ~[doris-fe.jar:1.0-SNAPSHOT]
	at org.apache.doris.alter.RollupJobV2.replayCancelled(RollupJobV2.java:665) ~[doris-fe.jar:1.0-SNAPSHOT]
	at org.apache.doris.alter.RollupJobV2.replay(RollupJobV2.java:687) ~[doris-fe.jar:1.0-SNAPSHOT]
	at org.apache.doris.alter.AlterHandler.replayAlterJobV2(AlterHandler.java:252) ~[doris-fe.jar:1.0-SNAPSHOT]
	at org.apache.doris.alter.MaterializedViewHandler.replayAlterJobV2(MaterializedViewHandler.java:906) ~[doris-fe.jar:1.0-SNAPSHOT]
	at org.apache.doris.persist.EditLog.loadJournal(EditLog.java:708) ~[doris-fe.jar:1.0-SNAPSHOT]
	at org.apache.doris.catalog.Catalog.replayJournal(Catalog.java:2417) ~[doris-fe.jar:1.0-SNAPSHOT]
	at org.apache.doris.catalog.Catalog.transferToMaster(Catalog.java:1234) ~[doris-fe.jar:1.0-SNAPSHOT]
	at org.apache.doris.catalog.Catalog.access$1200(Catalog.java:265) ~[doris-fe.jar:1.0-SNAPSHOT]
	at org.apache.doris.catalog.Catalog$4.runOneCycle(Catalog.java:2333) ~[doris-fe.jar:1.0-SNAPSHOT]
	at org.apache.doris.common.util.Daemon.run(Daemon.java:116) ~[doris-fe.jar:1.0-SNAPSHOT]

```

```java
java.lang.NullPointerException: null
	at org.apache.doris.task.AgentTaskQueue.removeBatchTask(AgentTaskQueue.java:76) ~[doris-fe.jar:1.0-SNAPSHOT]
	at org.apache.doris.alter.SchemaChangeJobV2.cancelInternal(SchemaChangeJobV2.java:679) ~[doris-fe.jar:1.0-SNAPSHOT]
	at org.apache.doris.alter.SchemaChangeJobV2.replayCancelled(SchemaChangeJobV2.java:806) ~[doris-fe.jar:1.0-SNAPSHOT]
	at org.apache.doris.alter.SchemaChangeJobV2.replay(SchemaChangeJobV2.java:828) ~[doris-fe.jar:1.0-SNAPSHOT]
	at org.apache.doris.alter.AlterHandler.replayAlterJobV2(AlterHandler.java:252) ~[doris-fe.jar:1.0-SNAPSHOT]
	at org.apache.doris.alter.SchemaChangeHandler.replayAlterJobV2(SchemaChangeHandler.java:2086) ~[doris-fe.jar:1.0-SNAPSHOT]
	at org.apache.doris.persist.EditLog.loadJournal(EditLog.java:711) ~[doris-fe.jar:1.0-SNAPSHOT]
	at org.apache.doris.catalog.Catalog.replayJournal(Catalog.java:2417) ~[doris-fe.jar:1.0-SNAPSHOT]
	at org.apache.doris.catalog.Catalog.transferToMaster(Catalog.java:1234) ~[doris-fe.jar:1.0-SNAPSHOT]
	at org.apache.doris.catalog.Catalog.access$1200(Catalog.java:265) ~[doris-fe.jar:1.0-SNAPSHOT]
	at org.apache.doris.catalog.Catalog$4.runOneCycle(Catalog.java:2333) ~[doris-fe.jar:1.0-SNAPSHOT]
	at org.apache.doris.common.util.Daemon.run(Daemon.java:116) ~[doris-fe.jar:1.0-SNAPSHOT]

```

### What You Expected?

fix

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by SWJTU-ZhangLei** [comment]
> ```java
> replayCancelled
> ```

can you provide more information about the situation, why fe get into replayCancelled?
