### ISSUE TITLE
have no queryable replicas. err: 15606's backend 10002 does not exist or not alive

### ISSUE THREAD

**Issue by yunfeng79** [apache/doris#10909]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Version

1.doris 1.0 rc3 升级1.1.0-rc05
三个fe和be节点

### What's Wrong?
一个节点fe和be节点都挂了
SQL 错误 [1105] [HY000]: errCode = 2, detailMessage = 15605 have no queryable replicas. err: 15606's backend 10002 does not exist or not alive
  errCode = 2, detailMessage = 15605 have no queryable replicas. err: 15606's backend 10002 does not exist or not alive
  errCode = 2, detailMessage = 15605 have no queryable replicas. err: 15606's backend 10002 does not exist or not alive

![image](https://user-images.githubusercontent.com/21050635/179343704-1731d501-62e1-4490-9348-bcf2a2b2ef9e.png)

![Uploading image.png…]()

2022-07-16 14:28:20,838 WARN (heartbeat mgr|21) [HeartbeatMgr.runAfterCatalogReady():139] get bad heartbeat response: type: BACKEND, status: BAD, msg: java.net.ConnectException: 拒绝连接 (Connection refused), beId: 10002, bePort: 0, httpPort: 0, brpcPort: 0
2022-07-16 14:28:25,842 WARN (heartbeat-mgr-pool-4|141) [HeartbeatMgr$BackendHeartbeatHandler.call():260] backend heartbeat got exception
org.apache.thrift.transport.TTransportException: java.net.ConnectException: 拒绝连接 (Connection refused)
        at org.apache.thrift.transport.TSocket.open(TSocket.java:226) ~[spark-dpp-1.0-SNAPSHOT.jar:1.0-SNAPSHOT]
        at org.apache.doris.common.GenericPool$ThriftClientFactory.create(GenericPool.java:142) ~[doris-fe.jar:1.0-SNAPSHOT]
        at org.apache.doris.common.GenericPool$ThriftClientFactory.create(GenericPool.java:126) ~[doris-fe.jar:1.0-SNAPSHOT]
        at org.apache.commons.pool2.BaseKeyedPooledObjectFactory.makeObject(BaseKeyedPooledObjectFactory.java:62) ~[commons-pool2-2.2.jar:2.2]
        at org.apache.commons.pool2.impl.GenericKeyedObjectPool.create(GenericKeyedObjectPool.java:1012) ~[commons-pool2-2.2.jar:2.2]
        at org.apache.commons.pool2.impl.GenericKeyedObjectPool.borrowObject(GenericKeyedObjectPool.java:356) ~[commons-pool2-2.2.jar:2.2]
        at org.apache.commons.pool2.impl.GenericKeyedObjectPool.borrowObject(GenericKeyedObjectPool.java:277) ~[commons-pool2-2.2.jar:2.2]
        at org.apache.doris.common.GenericPool.borrowObject(GenericPool.java:95) ~[doris-fe.jar:1.0-SNAPSHOT]
        at org.apache.doris.system.HeartbeatMgr$BackendHeartbeatHandler.call(HeartbeatMgr.java:224) ~[doris-fe.jar:1.0-SNAPSHOT]
        at org.apache.doris.system.HeartbeatMgr$BackendHeartbeatHandler.call(HeartbeatMgr.java:202) ~[doris-fe.jar:1.0-SNAPSHOT]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_301]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_301]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_301]
        at java.lang.Thread.run(Thread.java:748) ~[?:1.8.0_301]
Caused by: java.net.ConnectException: 拒绝连接 (Connection refused)
        at java.net.PlainSocketImpl.socketConnect(Native Method) ~[?:1.8.0_301]
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:476) ~[?:1.8.0_301]
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:218) ~[?:1.8.0_301]
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:200) ~[?:1.8.0_301]
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:394) ~[?:1.8.0_301]
        at java.net.Socket.connect(Socket.java:606) ~[?:1.8.0_301]
        at org.apache.thrift.transport.TSocket.open(TSocket.java:221) ~[spark-dpp-1.0-SNAPSHOT.jar:1.0-SNAPSHOT]
        ... 13 more

### What You Expected?

使用routine load导入kafka 1亿5千条数据，导入过程中出错。

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by erDogLi** [comment]
解决了吗 我是加入就报错

**Comment by StefanXiepj** [comment]
Any updates ？
