### ISSUE TITLE
[Bug] show create table ssb100_1.lineorder_flat; ERROR 1105 (HY000): NullPointerException, msg: null

### ISSUE THREAD

**Issue by hello-stephen** [apache/doris#10904]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Version

7.15 last version
ba1c527a23bf56f8a216acefdfd18910e9ab78ba

### What's Wrong?

fe.warn.log
```
2022-07-16 08:49:55,324 WARN (doris-mysql-nio-pool-2|269) [StmtExecutor.execute():513] execute Exception. stmt[64, 763768a53c0f4e28-83542b5ac06637b9]
java.lang.NullPointerException: null
        at org.apache.doris.catalog.Catalog.getDdlStmt(Catalog.java:2872) ~[doris-fe.jar:1.0-SNAPSHOT]
        at org.apache.doris.catalog.Catalog.getDdlStmt(Catalog.java:2665) ~[doris-fe.jar:1.0-SNAPSHOT]
        at org.apache.doris.qe.ShowExecutor.handleShowCreateTable(ShowExecutor.java:838) ~[doris-fe.jar:1.0-SNAPSHOT]
        at org.apache.doris.qe.ShowExecutor.execute(ShowExecutor.java:238) ~[doris-fe.jar:1.0-SNAPSHOT]
        at org.apache.doris.qe.StmtExecutor.handleShow(StmtExecutor.java:1588) ~[doris-fe.jar:1.0-SNAPSHOT]
        at org.apache.doris.qe.StmtExecutor.execute(StmtExecutor.java:487) ~[doris-fe.jar:1.0-SNAPSHOT]
        at org.apache.doris.qe.StmtExecutor.execute(StmtExecutor.java:336) ~[doris-fe.jar:1.0-SNAPSHOT]
        at org.apache.doris.qe.ConnectProcessor.handleQuery(ConnectProcessor.java:226) ~[doris-fe.jar:1.0-SNAPSHOT]
        at org.apache.doris.qe.ConnectProcessor.dispatch(ConnectProcessor.java:360) ~[doris-fe.jar:1.0-SNAPSHOT]
        at org.apache.doris.qe.ConnectProcessor.processOnce(ConnectProcessor.java:555) ~[doris-fe.jar:1.0-SNAPSHOT]
        at org.apache.doris.mysql.nio.ReadListener.lambda$handleEvent$0(ReadListener.java:52) ~[doris-fe.jar:1.0-SNAPSHOT]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
        at java.lang.Thread.run(Thread.java:829) ~[?:?]
```

### What You Expected?

return ddl string

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by deardeng** [comment]
well, i fix it

https://github.com/apache/doris/pull/10906/files
