### ISSUE TITLE
[Bug] sql execute error after change the replication_num in colocate table

### ISSUE THREAD

**Issue by wangruin** [apache/doris#11875]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Version

trunk-98243e9

### What's Wrong?

```
mysql> alter table lineorder_flat set ('default.replication_num' = '3');
Query OK, 0 rows affected (0.01 sec)

mysql> SELECT SUM(LO_EXTENDEDPRICE * LO_DISCOUNT) AS revenue FROM lineorder_flat WHERE  LO_ORDERDATE >= 19930101  AND LO_ORDERDATE <= 19931231 AND LO_DISCOUNT BETWEEN 1 AND 3  AND LO_QUANTITY < 25;
ERROR 1105 (HY000): errCode = 2, detailMessage = Failed to get scan range, no queryable replica found in tablet: 12911
mysql> show tablet 12911;
+--------------------------+----------------+---------------+----------------+-------+---------+-------------+---------+--------+-------+------------------------------------------------------------+
| DbName                   | TableName      | PartitionName | IndexName      | DbId  | TableId | PartitionId | IndexId | IsSync | Order | DetailCmd                                                  |
+--------------------------+----------------+---------------+----------------+-------+---------+-------------+---------+--------+-------+------------------------------------------------------------+
| default_cluster:ssb_100g | lineorder_flat | p2            | lineorder_flat | 10005 | 10785   | 12910       | 10786   | true   | 0     | SHOW PROC '/dbs/10005/10785/partitions/12910/10786/12911'; |
+--------------------------+----------------+---------------+----------------+-------+---------+-------------+---------+--------+-------+------------------------------------------------------------+
1 row in set (0.01 sec)

mysql> SHOW PROC '/dbs/10005/10785/partitions/12910/10786/12911';
Empty set (0.01 sec)

mysql>
mysql> show create table lineorder_flat;
ERROR 1105 (HY000): NullPointerException, msg: null
mysql>
```

### What You Expected?

execute successfully or not allow me to change the replication_num of colocate table

### How to Reproduce?

I am not sure this steps can reproduce
create lineorder_flat table
alter table lineorder_flat set ('default.replication_num' = '3');
execute sql

### Anything Else?

```
2022-08-17 21:36:31,202 ERROR (colocate group clone checker|89) [Daemon.run():118] daemon thread got exception. name: colocate group clone checker
java.lang.IllegalStateException: 1 vs. 3
        at com.google.common.base.Preconditions.checkState(Preconditions.java:508) ~[spark-dpp-1.0-SNAPSHOT.jar:1.0-SNAPSHOT]
        at org.apache.doris.clone.ColocateTableCheckerAndBalancer.matchGroup(ColocateTableCheckerAndBalancer.java:249) ~[doris-fe.jar:1.0-SNAPSHOT]
        at org.apache.doris.clone.ColocateTableCheckerAndBalancer.runAfterCatalogReady(ColocateTableCheckerAndBalancer.java:96) ~[doris-fe.jar:1.0-SNAPSHOT]
        at org.apache.doris.common.util.MasterDaemon.runOneCycle(MasterDaemon.java:58) ~[doris-fe.jar:1.0-SNAPSHOT]
        at org.apache.doris.common.util.Daemon.run(Daemon.java:116) ~[doris-fe.jar:1.0-SNAPSHOT]
2022-08-17 21:36:45,001 WARN (mysql-nio-pool-1|306) [StmtExecutor.execute():520] execute Exception. stmt[39, 61014a313fe54790-86b3f2b165bc9bad]
java.lang.NullPointerException: null
        at org.apache.doris.catalog.TableProperty.disableAutoCompaction(TableProperty.java:164) ~[doris-fe.jar:1.0-SNAPSHOT]
        at org.apache.doris.catalog.OlapTable.disableAutoCompaction(OlapTable.java:1596) ~[doris-fe.jar:1.0-SNAPSHOT]
        at org.apache.doris.catalog.Env.getDdlStmt(Env.java:2920) ~[doris-fe.jar:1.0-SNAPSHOT]
        at org.apache.doris.catalog.Env.getDdlStmt(Env.java:2687) ~[doris-fe.jar:1.0-SNAPSHOT]
        at org.apache.doris.qe.ShowExecutor.handleShowCreateTable(ShowExecutor.java:852) ~[doris-fe.jar:1.0-SNAPSHOT]
        at org.apache.doris.qe.ShowExecutor.execute(ShowExecutor.java:241) ~[doris-fe.jar:1.0-SNAPSHOT]
        at org.apache.doris.qe.StmtExecutor.handleShow(StmtExecutor.java:1586) ~[doris-fe.jar:1.0-SNAPSHOT]
        at org.apache.doris.qe.StmtExecutor.execute(StmtExecutor.java:494) ~[doris-fe.jar:1.0-SNAPSHOT]
        at org.apache.doris.qe.StmtExecutor.execute(StmtExecutor.java:353) ~[doris-fe.jar:1.0-SNAPSHOT]
        at org.apache.doris.qe.ConnectProcessor.handleQuery(ConnectProcessor.java:262) ~[doris-fe.jar:1.0-SNAPSHOT]
        at org.apache.doris.qe.ConnectProcessor.dispatch(ConnectProcessor.java:399) ~[doris-fe.jar:1.0-SNAPSHOT]
        at org.apache.doris.qe.ConnectProcessor.processOnce(ConnectProcessor.java:603) ~[doris-fe.jar:1.0-SNAPSHOT]
        at org.apache.doris.mysql.nio.ReadListener.lambda$handleEvent$0(ReadListener.java:52) ~[doris-fe.jar:1.0-SNAPSHOT]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_322]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_322]
        at java.lang.Thread.run(Thread.java:750) ~[?:1.8.0_322]
(END)
```

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by 1018ji** [comment]
大佬这问题咋解决的啊
