### ISSUE TITLE
[Bug] NPE LoadLabelCleaner

### ISSUE THREAD

**Issue by sangetang** [apache/doris#11957]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Version

1.1.1-rc03

### What's Wrong?

ERROR (LoadLabelCleaner|60) [Daemon.run():118] daemon thread got exception. name: LoadLabelCleaner
java.lang.NullPointerException: null
	at org.apache.doris.load.loadv2.SparkLoadJob.clearSparkLauncherLog(SparkLoadJob.java:737) ~[doris-fe.jar:1.0-SNAPSHOT]
	at org.apache.doris.load.loadv2.LoadManager.removeOldLoadJob(LoadManager.java:426) ~[doris-fe.jar:1.0-SNAPSHOT]
	at org.apache.doris.catalog.Catalog$1.runAfterCatalogReady(Catalog.java:2220) ~[doris-fe.jar:1.0-SNAPSHOT]
	at org.apache.doris.common.util.MasterDaemon.runOneCycle(MasterDaemon.java:58) ~[doris-fe.jar:1.0-SNAPSHOT]

### What You Expected?

no error

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by sangetang** [comment]
邮件已收到，谢谢！祝你生活愉快！
