### ISSUE TITLE
[Bug] restart FE failed after update from the latest master

### ISSUE THREAD

**Issue by carlvinhust2012** [apache/doris#12136]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Version

the current master.

### What's Wrong?

restart FE failed.

### What You Expected?

restart FE success.

### How to Reproduce?

update the code from master branch and restart the FE.

### Anything Else?

2022-08-28 23:47:54,813 DEBUG (main|1) [OlapTable.rebuildFullSchema():333] after rebuild full schema. table 26423, schema: [`user_id` largeint(40) NOT NULL COMMENT '用户id', `date` date NOT NULL COMMENT '数据灌入日期时间', `city` varchar(20) NULL COMMENT '用户所在城市', `age` smallint(6) NULL COMMENT '用户年龄', `last_visit_date` datetime NULL DEFAULT "1970-01-01 00:00:00" COMMENT '用户最后一次访问时间', `last_update_date` datetime NULL DEFAULT "1970-01-01 00:00:00" COMMENT '用户最后一次更新时间', `last_visit_date_not_null` datetime NOT NULL DEFAULT "1970-01-01 00:00:00" COMMENT '用户最后一次访问时间', `cost` bigint(20) NULL DEFAULT "0" COMMENT '用户总消费', `max_dwell_time` int(11) NULL DEFAULT "0" COMMENT '用户最大停留时间', `min_dwell_time` int(11) NULL DEFAULT "99999" COMMENT '用户最小停留时间', `new_column` int(11) NULL DEFAULT "1"]
java.io.IOException: java.lang.reflect.InvocationTargetException
        at org.apache.doris.persist.meta.MetaReader.read(MetaReader.java:97)
        at org.apache.doris.catalog.Env.loadImage(Env.java:1615)
        at org.apache.doris.catalog.Env.initialize(Env.java:830)
        at org.apache.doris.PaloFe.start(PaloFe.java:132)
        at org.apache.doris.PaloFe.main(PaloFe.java:67)
Caused by: java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.doris.persist.meta.MetaReader.read(MetaReader.java:94)
        ... 4 more
Caused by: com.google.gson.JsonSyntaxException: java.io.IOException: error happens when parsing create materialized view stmt: org.apache.doris.qe.OriginStatement@60723d6a
        at com.google.gson.Gson.fromJson(Gson.java:947)
        at com.google.gson.Gson.fromJson(Gson.java:897)
        at com.google.gson.Gson.fromJson(Gson.java:846)
        at com.google.gson.Gson.fromJson(Gson.java:817)
        at org.apache.doris.catalog.MaterializedIndexMeta.read(MaterializedIndexMeta.java:188)
        at org.apache.doris.catalog.OlapTable.readFields(OlapTable.java:1173)
        at org.apache.doris.catalog.Table.read(Table.java:339)
        at org.apache.doris.catalog.Database.readFields(Database.java:566)
        at org.apache.doris.datasource.InternalCatalog.loadDb(InternalCatalog.java:3237)
        at org.apache.doris.catalog.Env.loadDb(Env.java:1678)
        ... 9 more
Caused by: java.io.IOException: error happens when parsing create materialized view stmt: org.apache.doris.qe.OriginStatement@60723d6a
        at org.apache.doris.catalog.MaterializedIndexMeta.gsonPostProcess(MaterializedIndexMeta.java:207)
        at org.apache.doris.persist.gson.GsonUtils$PostProcessTypeAdapterFactory$1.read(GsonUtils.java:422)
        at com.google.gson.Gson.fromJson(Gson.java:932)
        ... 18 more
Caused by: java.lang.NullPointerException

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by morrySnow** [comment]
caused by #9745 , and revert by #12135 . need to find a compatible way to change syntax
