### ISSUE TITLE
[Bug] Routine load Invalid number format

### ISSUE THREAD

**Issue by 2994265077** [apache/doris#12215]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Version

1.0.0

### What's Wrong?

FE exception when start routine load
Taking routine load task from queue has been interrupted
org.apache.doris.common.AnalysisException: errCode = 2, detailMessage = Invalid number format: 
	at org.apache.doris.analysis.IntLiteral.<init>(IntLiteral.java:82) ~[palo-fe.jar:0.15-SNAPSHOT]
	at org.apache.doris.analysis.StringLiteral.uncheckedCastTo(StringLiteral.java:203) ~[palo-fe.jar:0.15-SNAPSHOT]
	at org.apache.doris.analysis.Expr.castTo(Expr.java:1322) ~[palo-fe.jar:0.15-SNAPSHOT]
	at org.apache.doris.planner.ScanNode.castToSlot(ScanNode.java:105) ~[palo-fe.jar:0.15-SNAPSHOT]
	at org.apache.doris.planner.LoadScanNode.finalizeParams(LoadScanNode.java:180) ~[palo-fe.jar:0.15-SNAPSHOT]
	at org.apache.doris.planner.StreamLoadScanNode.finalize(StreamLoadScanNode.java:176) ~[palo-fe.jar:0.15-SNAPSHOT]
	at org.apache.doris.planner.StreamLoadPlanner.plan(StreamLoadPlanner.java:142) ~[palo-fe.jar:0.15-SNAPSHOT]
	at org.apache.doris.load.routineload.RoutineLoadJob.plan(RoutineLoadJob.java:782) ~[palo-fe.jar:0.15-SNAPSHOT]
	at org.apache.doris.load.routineload.KafkaTaskInfo.rePlan(KafkaTaskInfo.java:124) ~[palo-fe.jar:0.15-SNAPSHOT]
	at org.apache.doris.load.routineload.KafkaTaskInfo.createRoutineLoadTask(KafkaTaskInfo.java:97) ~[palo-fe.jar:0.15-SNAPSHOT]
	at org.apache.doris.load.routineload.RoutineLoadTaskScheduler.scheduleOneTask(RoutineLoadTaskScheduler.java:183) ~[palo-fe.jar:0.15-SNAPSHOT]
	at org.apache.doris.load.routineload.RoutineLoadTaskScheduler.process(RoutineLoadTaskScheduler.java:110) [palo-fe.jar:0.15-SNAPSHOT]
	at org.apache.doris.load.routineload.RoutineLoadTaskScheduler.runAfterCatalogReady(RoutineLoadTaskScheduler.java:83) [palo-fe.jar:0.15-SNAPSHOT]
	at org.apache.doris.common.util.MasterDaemon.runOneCycle(MasterDaemon.java:58) [palo-fe.jar:0.15-SNAPSHOT]
	at org.apache.doris.common.util.Daemon.run(Daemon.java:116) [palo-fe.jar:0.15-SNAPSHOT]
![image](https://user-images.githubusercontent.com/23015971/187594289-d0d93775-37b8-4232-a33e-f2d0d911df42.png)

### What You Expected?

fix the problem

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by stalary** [comment]
You should check your data whether valid.

**Comment by 2994265077** [comment]
My data is validated. This problem actually occurs before the routine load task is created, so its not a data problem. I solved the problem by drop a materialized view of my table. Maybe the status of materialized view  is not normal. In case anyone else has the same problem and can't find the answer, reply this.
