### ISSUE TITLE
Communications link failure. Can not read response from server. Expected to read 4 bytes, read 0 bytes before connection was unexpectedly lost.

### ISSUE THREAD

**Issue by ningbing** [apache/doris#12278]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Version

1.1

### What's Wrong?

使用JDBC,通过mysql-connector驱动，提示：Communications link failure. Can not read response from server. Expected to read 4 bytes, read 0 bytes before connection was unexpectedly lost.

### What You Expected?

能正常使用mysql-connect 驱动连接Doris

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by spihiker** [comment]
我们这边用5和8版本的驱动都能正常连接。检查下驱动程序和配置信息！

**Comment by ningbing** [comment]
@spihiker 我测试5和8的驱动，都一样的问题。。能否提供一下你们的配置信息我参考一下？

**Comment by ningbing** [comment]
@spihiker 问题是，我用Navicat或者Dbware这些客户端链接，是正常可以访问的。不清楚用JDBC链接，有什么参数配置的差别。

**Comment by stalary** [comment]
@ningbing Fe have some error log?

**Comment by ChPi** [comment]
检查下jdk版本

**Comment by ningbing** [comment]
@stalary the JDK is 1.8+, the Error Log is:

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
	at com.mysql.cj.jdbc.exceptions.SQLError.createCommunicationsException(SQLError.java:174)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:64)
	at com.mysql.cj.jdbc.ConnectionImpl.pingInternal(ConnectionImpl.java:1517)
	at com.mysql.cj.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:842)
	... 57 more
Caused by: com.mysql.cj.exceptions.CJCommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:61)
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:105)
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:151)
	at com.mysql.cj.exceptions.ExceptionFactory.createCommunicationsException(ExceptionFactory.java:167)
	at com.mysql.cj.protocol.a.NativeProtocol.readMessage(NativeProtocol.java:541)
	at com.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:711)
	at com.mysql.cj.protocol.a.NativeProtocol.sendCommand(NativeProtocol.java:650)
	at com.mysql.cj.protocol.a.NativeProtocol.sendCommand(NativeProtocol.java:130)
	at com.mysql.cj.NativeSession.sendCommand(NativeSession.java:317)
	at com.mysql.cj.NativeSession.ping(NativeSession.java:1189)
	at com.mysql.cj.jdbc.ConnectionImpl.pingInternal(ConnectionImpl.java:1516)
	... 58 more
Caused by: java.io.EOFException: Can not read response from server. Expected to read 4 bytes, read 0 bytes before connection was unexpectedly lost.
	at com.mysql.cj.protocol.FullReadInputStream.readFully(FullReadInputStream.java:67)
	at com.mysql.cj.protocol.a.SimplePacketReader.readHeader(SimplePacketReader.java:63)
	at com.mysql.cj.protocol.a.SimplePacketReader.readHeader(SimplePacketReader.java:45)
	at com.mysql.cj.protocol.a.TimeTrackingPacketReader.readHeader(TimeTrackingPacketReader.java:52)
	at com.mysql.cj.protocol.a.TimeTrackingPacketReader.readHeader(TimeTrackingPacketReader.java:41)
	at com.mysql.cj.protocol.a.MultiPacketReader.readHeader(MultiPacketReader.java:54)
	at com.mysql.cj.protocol.a.MultiPacketReader.readHeader(MultiPacketReader.java:44)
	at com.mysql.cj.protocol.a.NativeProtocol.readMessage(NativeProtocol.java:535)
	... 64 more

**Comment by bingfenglai** [comment]
We encountered the same situation.

**Comment by ningbing** [comment]
@stalary @ChPi 这个问题有进展吗？我们想实现通过JDBC自定义insert into Doris，按照你们官网的jdbc的例子，也是提示上面的错误。。应该是驱动，或者哪个环节跟你们的不一样。。但是我们无法定位这个问题，麻烦帮忙看下如何解决。（另外，我们不熟的Doris服务是正常的，通过Dbware等客户端，是可以正常访问的）

**Comment by ningbing** [comment]
问题已经查清楚，是链接字符串不正确。但是目前的错误返回提示，不太清晰。如果能提示清楚一些就更好了。
