### ISSUE TITLE
[Bug] Failed to start the standalone cluster.

### ISSUE THREAD

**Issue by xuhanfeng2219** [apache/doris#12528]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Version

1.1.1

### What's Wrong?

2022-02-17 21:18:35,458 ERROR (UNKNOWN 172.16.136.130_9010_1645103903699(-1)|1) [BDBEnvironment.setup():198] error to open replicated environment. will exit.
com.sleepycat.je.rep.ReplicaWriteException: (JE 18.3.12) Problem closing transaction 20. The current state is:UNKNOWN. The node transitioned to this state at:Thu Feb 17 21:18:30 CST 2022
        at com.sleepycat.je.rep.txn.ReadonlyTxn.disallowReplicaWrite(ReadonlyTxn.java:114) ~[je-18.3.12.jar:18.3.12]
        at com.sleepycat.je.dbi.DbTree.checkReplicaWrite(DbTree.java:880) ~[je-18.3.12.jar:18.3.12]
        at com.sleepycat.je.dbi.DbTree.doCreateDb(DbTree.java:579) ~[je-18.3.12.jar:18.3.12]
        at com.sleepycat.je.dbi.DbTree.createDb(DbTree.java:486) ~[je-18.3.12.jar:18.3.12]
        at com.sleepycat.je.Database.initNew(Database.java:174) ~[je-18.3.12.jar:18.3.12]
        at com.sleepycat.je.Environment.setupDatabase(Environment.java:864) ~[je-18.3.12.jar:18.3.12]
        at com.sleepycat.je.Environment.openDatabase(Environment.java:668) ~[je-18.3.12.jar:18.3.12]
        at org.apache.doris.journal.bdbje.BDBEnvironment.setup(BDBEnvironment.java:179) ~[doris-fe.jar:1.0-SNAPSHOT]
        at org.apache.doris.journal.bdbje.BDBJEJournal.open(BDBJEJournal.java:303) ~[doris-fe.jar:1.0-SNAPSHOT]
        at org.apache.doris.persist.EditLog.open(EditLog.java:847) ~[doris-fe.jar:1.0-SNAPSHOT]
        at org.apache.doris.catalog.Catalog.initialize(Catalog.java:852) ~[doris-fe.jar:1.0-SNAPSHOT]
        at org.apache.doris.PaloFe.start(PaloFe.java:128) ~[doris-fe.jar:1.0-SNAPSHOT]
        at org.apache.doris.PaloFe.main(PaloFe.java:63) ~[doris-fe.jar:1.0-SNAPSHOT]

### What You Expected?

我单机第一次启动fe报错，什么原因，看过相关的issue但是没有解决！

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by stalary** [comment]
Clean fe meta and try to restart it.

**Comment by shermin** [comment]
> Clean fe meta and try to restart it.

does not work. same error again.

**Comment by shermin** [comment]
磁盘空间不足造成的

**Comment by lifengfan13** [comment]
how to solve the problem？

2023-04-09 10:38:16,206 WARN (UNKNOWN fe80::ce81:b1c:bd2c:69e_9010_1681007870817(-1)|1) [Env.notifyNewFETypeTransfer():2283] notify new FE type transfer: UNKNOWN
2023-04-09 10:38:21,213 WARN (UNKNOWN fe80::ce81:b1c:bd2c:69e_9010_1681007870817(-1)|1) [Env.notifyNewFETypeTransfer():2283] notify new FE type transfer: UNKNOWN
2023-04-09 10:38:21,213 ERROR (UNKNOWN fe80::ce81:b1c:bd2c:69e_9010_1681007870817(-1)|1) [BDBEnvironment.setup():196] error to open replicated environment. will exit.
com.sleepycat.je.rep.ReplicaWriteException: (JE 18.3.12) Problem closing transaction 20. The current state is:UNKNOWN. The node transitioned to this state at:Sun Apr 09 10:38:06 CST 2023
	at com.sleepycat.je.rep.txn.ReadonlyTxn.disallowReplicaWrite(ReadonlyTxn.java:114) ~[je-18.3.14-doris-SNAPSHOT.jar:18.3.14-doris-SNAPSHOT]
	at com.sleepycat.je.dbi.DbTree.checkReplicaWrite(DbTree.java:880) ~[je-18.3.14-doris-SNAPSHOT.jar:18.3.14-doris-SNAPSHOT]
	at com.sleepycat.je.dbi.DbTree.doCreateDb(DbTree.java:579) ~[je-18.3.14-doris-SNAPSHOT.jar:18.3.14-doris-SNAPSHOT]
	at com.sleepycat.je.dbi.DbTree.createDb(DbTree.java:486) ~[je-18.3.14-doris-SNAPSHOT.jar:18.3.14-doris-SNAPSHOT]
	at com.sleepycat.je.Database.initNew(Database.java:174) ~[je-18.3.14-doris-SNAPSHOT.jar:18.3.14-doris-SNAPSHOT]
	at com.sleepycat.je.Environment.setupDatabase(Environment.java:864) ~[je-18.3.14-doris-SNAPSHOT.jar:18.3.14-doris-SNAPSHOT]
	at com.sleepycat.je.Environment.openDatabase(Environment.java:668) ~[je-18.3.14-doris-SNAPSHOT.jar:18.3.14-doris-SNAPSHOT]
	at org.apache.doris.journal.bdbje.BDBEnvironment.setup(BDBEnvironment.java:177) ~[doris-fe.jar:1.2-SNAPSHOT]
	at org.apache.doris.journal.bdbje.BDBJEJournal.open(BDBJEJournal.java:317) ~[doris-fe.jar:1.2-SNAPSHOT]
	at org.apache.doris.persist.EditLog.open(EditLog.java:1055) ~[doris-fe.jar:1.2-SNAPSHOT]
	at org.apache.doris.catalog.Env.initialize(Env.java:851) ~[doris-fe.jar:1.2-SNAPSHOT]

**Comment by Bruceve1n** [comment]
> 磁盘空间不足造成的

第一次启动FE为什么需要8G以上的磁盘呢？我给FE分配了5G磁盘，启动失败；分配了8G磁盘，启动成功。起来后我df -h看了一下，实际上并没有占很大的磁盘

**Comment by chaoxxin** [comment]
> > 磁盘空间不足造成的
> 
> 第一次启动FE为什么需要8G以上的磁盘呢？我给FE分配了5G磁盘，启动失败；分配了8G磁盘，启动成功。起来后我df -h看了一下，实际上并没有占很大的磁盘

真的是磁盘空间不足造成的吗？我磁盘空间还有 200G 都不行啊？请问有没有其他解决方法？

**Comment by JasonLi-cn** [comment]
> > > 磁盘空间不足造成的
> > 
> > 
> > 第一次启动FE为什么需要8G以上的磁盘呢？我给FE分配了5G磁盘，启动失败；分配了8G磁盘，启动成功。起来后我df -h看了一下，实际上并没有占很大的磁盘
> 
> 真的是磁盘空间不足造成的吗？我磁盘空间还有 200G 都不行啊？请问有没有其他解决方法？

我也遇到了同样的问题。。。磁盘完全足够啊。。
