### ISSUE TITLE
[Feature] Support the use of group_concat function and the use of separator

### ISSUE THREAD

**Issue by leafgodgood** [apache/doris#12525]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Description

An error is reported when the navicat connection opens the information_schema library：

2022-09-11 00:03:24,976 WARN (mysql-nio-pool-8|227) [ConnectProcessor.handleQuery():276] Process one query failed because.
org.apache.doris.common.AnalysisException: errCode = 2, detailMessage = Syntax error in line 1:
...ORDER BY ORDINAL_POSITION SEPARATOR ', ') PARAMETER, R...
                             ^
Encountered: IDENTIFIER
Expected: ||, COMMA

        at org.apache.doris.qe.ConnectProcessor.parse(ConnectProcessor.java:327) ~[classes/:?]
        at org.apache.doris.qe.ConnectProcessor.handleQuery(ConnectProcessor.java:249) ~[classes/:?]
        at org.apache.doris.qe.ConnectProcessor.dispatch(ConnectProcessor.java:399) ~[classes/:?]
        at org.apache.doris.qe.ConnectProcessor.processOnce(ConnectProcessor.java:603) ~[classes/:?]
        at org.apache.doris.mysql.nio.ReadListener.lambda$handleEvent$0(ReadListener.java:52) ~[classes/:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
        at java.lang.Thread.run(Thread.java:834) ~[?:?]
Caused by: org.apache.doris.common.AnalysisException: errCode = 2, detailMessage = Syntax error
        at org.apache.doris.analysis.SqlParser.unrecovered_syntax_error(SqlParser.java:2254) ~[classes/:?]
        at java_cup.runtime.lr_parser.parse(lr_parser.java:619) ~[java-cup-runtime-0.11-a-czt01-cdh.jar:?]
        at org.apache.doris.common.util.SqlParserUtils.getMultiStmts(SqlParserUtils.java:60) ~[classes/:?]
        at org.apache.doris.qe.ConnectProcessor.parse(ConnectProcessor.java:318) ~[classes/:?]
        ... 7 more
2022-09-11 00:03:30,421 INFO (tablet checker|34) [TabletChecker.checkTablets():331] finished to check tablets. unhealth/total/added/in_sched/not_ready: 0/0/0/0/0, cost: 0 ms

SQL:SELECT DISTINCT
	ROUTINE_SCHEMA,
	ROUTINE_NAME,
	PARAMS.PARAMETER 
FROM
	information_schema.ROUTINES
	LEFT JOIN (
SELECT
	SPECIFIC_SCHEMA,
	SPECIFIC_NAME,
	GROUP_CONCAT( CONCAT( DATA_TYPE, ' ', PARAMETER_NAME ) ORDER BY ORDINAL_POSITION SEPARATOR ', ' ) PARAMETER,
	ROUTINE_TYPE 
FROM
	information_schema.PARAMETERS 
GROUP BY
	SPECIFIC_SCHEMA,
	SPECIFIC_NAME,
	ROUTINE_TYPE 
	) PARAMS ON ROUTINES.ROUTINE_SCHEMA = PARAMS.SPECIFIC_SCHEMA 
	AND ROUTINES.ROUTINE_NAME = PARAMS.SPECIFIC_NAME 
	AND ROUTINES.ROUTINE_TYPE = PARAMS.ROUTINE_TYPE 
WHERE
	ROUTINE_SCHEMA = 'information_schema' 
ORDER BY
	ROUTINE_SCHEMA;

### Use case

test sql:
select GROUP_CONCAT(SPECIFIC_SCHEMA order by SPECIFIC_SCHEMA separator ';') test_schema, SPECIFIC_NAME from information_schema.ROUTINES GROUP BY test_schema;

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by stalary** [comment]
What version is used?

**Comment by leafgodgood** [comment]
> master branch，navicat is 15.0.27
