### ISSUE TITLE
[Bug] org.apache.doris.analysis.CastExpr cannot be cast to org.apache.doris.analysis.LiteralExpr

### ISSUE THREAD

**Issue by Peng-89** [apache/doris#12559]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Version

1.1.1

### What's Wrong?

描述：period_id int类型的分区字段

场景：
1、cast(period_id as string) in ('202208','202209') 
报错：org.apache.doris.analysis.CastExpr cannot be cast to org.apache.doris.analysis.LiteralExpr
java.lang.ClassCastException: org.apache.doris.analysis.CastExpr cannot be cast to org.apache.doris.analysis.LiteralExpr
        at org.apache.doris.catalog.PartitionKey.compareLiteralExpr(PartitionKey.java:180) ~[doris-fe.jar:1.0-SNAPSHOT]
        at org.apache.doris.planner.ColumnBound.compareTo(ColumnBound.java:36) ~[doris-fe.jar:1.0-SNAPSHOT]
        at org.apache.doris.planner.ColumnBound.compareTo(ColumnBound.java:27) ~[doris-fe.jar:1.0-SNAPSHOT]
        at com.google.common.collect.Range.compareOrThrow(Range.java:695) ~[spark-dpp-1.0-SNAPSHOT.jar:1.0-SNAPSHOT]
        at com.google.common.collect.Cut.compareTo(Cut.java:77) ~[spark-dpp-1.0-SNAPSHOT.jar:1.0-SNAPSHOT]
        at com.google.common.collect.Cut$BelowValue.compareTo(Cut.java:303) ~[spark-dpp-1.0-SNAPSHOT.jar:1.0-SNAPSHOT]
        at java.util.TreeMap.compare(TreeMap.java:1294) ~[?:1.8.0_152]
        at java.util.TreeMap.getFloorEntry(TreeMap.java:429) ~[?:1.8.0_152]
        at java.util.TreeMap.floorKey(TreeMap.java:733) ~[?:1.8.0_152]
        at com.google.common.collect.TreeRangeMap$SubRangeMap$SubRangeMapAsMap.entryIterator(TreeRangeMap.java:747) ~[spark-dpp-1.0-SNAPSHOT.jar:1.0-SNAPSHOT]
        at com.google.common.collect.TreeRangeMap$SubRangeMap$SubRangeMapAsMap$2.iterator(TreeRangeMap.java:721) ~[spark-dpp-1.0-SNAPSHOT.jar:1.0-SNAPSHOT]
        at com.google.common.collect.Maps$Values.iterator(Maps.java:3882) ~[spark-dpp-1.0-SNAPSHOT.jar:1.0-SNAPSHOT]
        at java.util.Spliterators$IteratorSpliterator.estimateSize(Spliterators.java:1821) ~[?:1.8.0_152]
        at java.util.Spliterator.getExactSizeIfKnown(Spliterator.java:408) ~[?:1.8.0_152]
        
2、SUBSTRING(period_id,1,6) in ('202208','202209') 这种写法OK，但是不走分区筛选，底层是全分区扫描

### What You Expected?

希望提供解决思路

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by stalary** [comment]
Can you provide some `period_id` case?

**Comment by Peng-89** [comment]
> Can you provide some `period_id` case?
 
period_id is int type:
202208, 202209, 202210
