### ISSUE TITLE
[Bug] be core dump

### ISSUE THREAD

**Issue by ChPi** [apache/doris#12640]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Version

1.1.2

### What's Wrong?

```
#0  fn_context (this=0x15d43c800, i=<optimized out>) at /mnt/disk2/apache-doris/be/src/vec/exprs/vexpr_context.h:54
#1  doris::vectorized::VCaseExpr::close(doris::RuntimeState*, doris::vectorized::VExprContext*, doris_udf::FunctionContext::FunctionStateScope) (
    this=0x15ebc9c00, state=0x1608a8000, context=0x15d43c800, scope=FRAGMENT_LOCAL) at /mnt/disk2/apache-doris/be/src/vec/exprs/vcase_expr.cpp:84
#2  0x00000000029577ca in doris::vectorized::VExprContext::close(doris::RuntimeState*) (this=0x15d43c800, state=0x1608a8000)
    at /mnt/disk2/apache-doris/be/src/vec/exprs/vexpr_context.cpp:71
#3  0x0000000002f08c9c in doris::vectorized::VExpr::close(std::vector<doris::vectorized::VExprContext*, std::allocator<doris::vectorized::VExprContext*> > const&, doris::RuntimeState*) (ctxs=..., state=0x1608a8000) at /mnt/disk2/apache-doris/be/src/vec/exprs/vexpr.cpp:218
#4  0x0000000003ae9518 in doris::stream_load::VOlapTableSink::close(doris::RuntimeState*, doris::Status) (this=0x11cfaa400, state=0x1608a8000,
    exec_status=...) at /mnt/disk2/apache-doris/be/src/vec/sink/vtablet_sink.cpp:174
#5  0x000000000249d4c1 in doris::PlanFragmentExecutor::close() (this=0x18616070) at /mnt/disk2/apache-doris/be/src/runtime/plan_fragment_executor.cpp:684
#6  0x000000000249d062 in doris::PlanFragmentExecutor::~PlanFragmentExecutor() (this=0x18616070)
    at /mnt/disk2/apache-doris/be/src/runtime/plan_fragment_executor.cpp:68
#7  0x0000000002448053 in doris::FragmentExecState::~FragmentExecState() (this=this@entry=0x18616000)
    at /mnt/disk2/apache-doris/be/src/runtime/fragment_mgr.cpp:78
#8  0x00000000024480a7 in std::_Sp_counted_ptr<doris::FragmentExecState*, (__gnu_cxx::_Lock_policy)2>::_M_dispose() (this=<optimized out>)
    at /mnt/disk2/ygl/installs/ldbtools/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/shared_ptr_base.h:348
#9  0x000000000243a8bd in _M_release (this=0x15eb3c2e0)
    at /mnt/disk2/ygl/installs/ldbtools/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/shared_ptr_base.h:168
#10 ~__shared_count (this=0x7f968ce90c98)
    at /mnt/disk2/ygl/installs/ldbtools/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/shared_ptr_base.h:702
#11 ~__shared_ptr (this=0x7f968ce90c90)
    at /mnt/disk2/ygl/installs/ldbtools/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/shared_ptr_base.h:1149
#12 doris::FragmentMgr::exec_plan_fragment(doris::TExecPlanFragmentParams const&, std::function<void (doris::PlanFragmentExecutor*)>) (this=<optimized out>,
    this@entry=0x979a540, params=..., cb=...) at /mnt/disk2/apache-doris/be/src/runtime/fragment_mgr.cpp:679
#13 0x0000000002438d77 in doris::FragmentMgr::exec_plan_fragment(doris::TExecPlanFragmentParams const&) (this=0x979a540, params=...)
    at /mnt/disk2/apache-doris/be/src/runtime/fragment_mgr.cpp:529
#14 0x00000000024eadc7 in doris::PInternalServiceImpl<doris::PBackendService>::_exec_plan_fragment(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, doris::PFragmentRequestVersion, bool) (this=this@entry=0xa3141a0, ser_request=..., version=<optimized out>,
    compact=<optimized out>) at /mnt/disk2/apache-doris/be/src/service/internal_service.cpp:317
#15 0x00000000024eaa7a in doris::PInternalServiceImpl<doris::PBackendService>::exec_plan_fragment(google::protobuf::RpcController*, doris::PExecPlanFragmentRequest const*, doris::PExecPlanFragmentResult*, google::protobuf::Closure*) (this=0xa3141a0, cntl_base=<optimized out>, request=0xf6344900,
    response=0x15f15baa0, done=0x136f5f440) at /mnt/disk2/apache-doris/be/src/service/internal_service.cpp:190
#16 0x00000000040e2842 in brpc::policy::ProcessHttpRequest(brpc::InputMessageBase*) ()
#17 0x00000000040b5955 in brpc::InputMessenger::OnNewMessages(brpc::Socket*) ()
#18 0x000000000414eb50 in brpc::Socket::ProcessEvent(void*) ()
#19 0x000000000406479d in bthread::TaskGroup::task_runner(long) ()
#20 0x00000000041e95d1 in bthread_make_fcontext ()
```

### What You Expected?

not crash

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by ChPi** [comment]
udf makes be crash on vectorized engine
