### ISSUE TITLE
[Bug]  HDFS Broker NPT

### ISSUE THREAD

**Issue by liujinhui1994** [apache/doris#12745]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Version

mastert

### What's Wrong?

`2022-09-19 19:30:40,230 WARN (mysql-nio-pool-0|208) [StmtExecutor.execute():528] execute Exception. stmt[7, bd4fd32877f14807-b5b31274476b499b], errCode = 2, detailMessage = Unknown table 'PROFILING'
2022-09-19 19:30:48,223 WARN (pending-load-task-scheduler-pool-0|209) [LoadTask.exec():73] LOAD_JOB=17006, error_msg={Unexpected failed to execute load task}
java.lang.NullPointerException: null
	at org.apache.doris.load.Load.initColumns(Load.java:988) ~[classes/:?]
	at org.apache.doris.load.Load.initColumns(Load.java:813) ~[classes/:?]
	at org.apache.doris.planner.BrokerScanNode.initColumns(BrokerScanNode.java:286) ~[classes/:?]
	at org.apache.doris.planner.BrokerScanNode.initParams(BrokerScanNode.java:248) ~[classes/:?]
	at org.apache.doris.planner.BrokerScanNode.init(BrokerScanNode.java:189) ~[classes/:?]
	at org.apache.doris.load.loadv2.LoadingTaskPlanner.plan(LoadingTaskPlanner.java:158) ~[classes/:?]
	at org.apache.doris.load.loadv2.LoadLoadingTask.init(LoadLoadingTask.java:109) ~[classes/:?]
	at org.apache.doris.load.loadv2.BrokerLoadJob.createLoadingTask(BrokerLoadJob.java:207) ~[classes/:?]
	at org.apache.doris.load.loadv2.BrokerLoadJob.onPendingTaskFinished(BrokerLoadJob.java:164) ~[classes/:?]
	at org.apache.doris.load.loadv2.BrokerLoadJob.onTaskFinished(BrokerLoadJob.java:123) ~[classes/:?]
	at org.apache.doris.load.loadv2.LoadTask.exec(LoadTask.java:65) ~[classes/:?]
	at org.apache.doris.task.MasterTask.run(MasterTask.java:31) ~[classes/:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_231]
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266) ~[?:1.8.0_231]
	at java.util.concurrent.FutureTask.run(FutureTask.java) ~[?:1.8.0_231]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_231]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_231]
	at java.lang.Thread.run(Thread.java:748) ~[?:1.8.0_231]
2022-09-19 19:30:48,278 WARN (pending-load-task-scheduler-pool-1|216) [LoadTask.exec():69] LOAD_JOB=17006, error_msg={Failed to execute load task}
org.apache.doris.common.LabelAlreadyUsedException: errCode = 2, detailMessage = Label [test011101] has already been used, relate to txn [5006]
	at org.apache.doris.transaction.DatabaseTransactionMgr.beginTransaction(DatabaseTransactionMgr.java:322) ~[classes/:?]
	at org.apache.doris.transaction.GlobalTransactionMgr.beginTransaction(GlobalTransactionMgr.java:145) ~[classes/:?]
	at org.apache.doris.load.loadv2.BrokerLoadJob.beginTxn(BrokerLoadJob.java:98) ~[classes/:?]
	at org.apache.doris.load.loadv2.BrokerLoadPendingTask.executeTask(BrokerLoadPendingTask.java:61) ~[classes/:?]
	at org.apache.doris.load.loadv2.LoadTask.exec(LoadTask.java:63) ~[classes/:?]
	at org.apache.doris.task.MasterTask.run(MasterTask.java:31) ~[classes/:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_231]
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266) ~[?:1.8.0_231]
	at java.util.concurrent.FutureTask.run(FutureTask.java) ~[?:1.8.0_231]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_231]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_231]
	at java.lang.Thread.run(Thread.java:748) ~[?:1.8.0_231]
2022-09-19 19:30:48,325 WARN (pending-load-task-scheduler-pool-2|218) [LoadTask.exec():69] LOAD_JOB=17006, error_msg={Failed to execute load task}
org.apache.doris.common.LabelAlreadyUsedException: errCode = 2, detailMessage = Label [test011101] has already been used, relate to txn [5006]
	at org.apache.doris.transaction.DatabaseTransactionMgr.beginTransaction(DatabaseTransactionMgr.java:322) ~[classes/:?]
	at org.apache.doris.transaction.GlobalTransactionMgr.beginTransaction(GlobalTransactionMgr.java:145) ~[classes/:?]
	at org.apache.doris.load.loadv2.BrokerLoadJob.beginTxn(BrokerLoadJob.java:98) ~[classes/:?]
	at org.apache.doris.load.loadv2.BrokerLoadPendingTask.executeTask(BrokerLoadPendingTask.java:61) ~[classes/:?]
	at org.apache.doris.load.loadv2.LoadTask.exec(LoadTask.java:63) ~[classes/:?]
	at org.apache.doris.task.MasterTask.run(MasterTask.java:31) ~[classes/:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_231]
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266) ~[?:1.8.0_231]
	at java.util.concurrent.FutureTask.run(FutureTask.java) ~[?:1.8.0_231]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_231]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_231]
	at java.lang.Thread.run(Thread.java:748) ~[?:1.8.0_231]
2022-09-19 19:30:48,372 WARN (pending-load-task-scheduler-pool-3|220) [LoadTask.exec():69] LOAD_JOB=17006, error_msg={Failed to execute load task}
org.apache.doris.common.LabelAlreadyUsedException: errCode = 2, detailMessage = Label [test011101] has already been used, relate to txn [5006]
	at org.apache.doris.transaction.DatabaseTransactionMgr.beginTransaction(DatabaseTransactionMgr.java:322) ~[classes/:?]
	at org.apache.doris.transaction.GlobalTransactionMgr.beginTransaction(GlobalTransactionMgr.java:145) ~[classes/:?]
	at org.apache.doris.load.loadv2.BrokerLoadJob.beginTxn(BrokerLoadJob.java:98) ~[classes/:?]
	at org.apache.doris.load.loadv2.BrokerLoadPendingTask.executeTask(BrokerLoadPendingTask.java:61) ~[classes/:?]
	at org.apache.doris.load.loadv2.LoadTask.exec(LoadTask.java:63) ~[classes/:?]
	at org.apache.doris.task.MasterTask.run(MasterTask.java:31) ~[classes/:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_231]
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266) ~[?:1.8.0_231]
	at java.util.concurrent.FutureTask.run(FutureTask.java) ~[?:1.8.0_231]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_231]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_231]
	at java.lang.Thread.run(Thread.java:748) ~[?:1.8.0_231]
`
### What You Expected?

LOAD LABEL test011101
(
    DATA INFILE("hdfs://xxxxxx/doris_test/ds=20220829/*")
    INTO TABLE personas_topic_static_hive_bitmap
    FORMAT AS "parquet"
	  (label_code, label_value, mobile)  
	  COLUMNS FROM PATH AS (`ds`)
   SET 
   (label_code=label_code, label_value=label_value, ds = str_to_date(`ds`,'%Y%m%d'), mobile = to_bitmap(mobile) )
)
with HDFS (
						
      "hadoop.username"="liujh",
		
			"fs.defaultFS"="hdfs://xxxx"
			
        )
PROPERTIES
(
    "timeout"="14400",
    "max_filter_ratio"="0"
);

Normally there should be no problem, the exception here

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by dataalive** [comment]
> error_msg={Failed to execute load task} org.apache.doris.common.LabelAlreadyUsedException: errCode = 2, detailMessage = Label [test011101] has already been used

the actual reason is label reused?

**Comment by liujinhui1994** [comment]
I have resolved this, and will submit an issue PR tomorrow.





------------------ Original ------------------
From: dataalive ***@***.***&gt;
Date: Mon,Sep 19,2022 10:10 PM
To: apache/doris ***@***.***&gt;
Cc: liujinhui ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [apache/doris] [Bug]  HDFS Broker NPT (Issue #12745)





  
error_msg={Failed to execute load task} org.apache.doris.common.LabelAlreadyUsedException: errCode = 2, detailMessage = Label [test011101] has already been used
  
the actual reason is label reused?

**Comment by liujinhui1994** [comment]
The master branch has been fixed. close this issues
