### ISSUE TITLE
k8s部署Doris，存储卷挂载于 ceph | glusterfs，fe pod 无法启动

### ISSUE THREAD

**Issue by Olave** [apache/doris#12914]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Version

doris 1.1

### What's Wrong?

k8s 部署doris ,配置存储卷挂载 ceph | glusterfs ，fe pod 启动报 ReplicationWriteException，如下图：
![image](https://user-images.githubusercontent.com/23080394/191919693-68805bcd-8bca-4adb-b411-179931679106.png)
![image](https://user-images.githubusercontent.com/23080394/191919719-c4bf6a9d-6eaf-463c-86f3-76a0bcf8cf72.png)
![2022-09-22_174645](https://user-images.githubusercontent.com/23080394/191921522-55a1df89-46e3-4fda-9224-c57361d9d667.png)

```2022-09-23 16:10:22,489 ERROR (UNKNOWN 172.16.51.231_9010_1663920597668(-1)|1) [BDBEnvironment.setup():198] error to open replicated environment. will exit.
com.sleepycat.je.rep.ReplicaWriteException: (JE 18.3.12) Problem closing transaction 20. The current state is:UNKNOWN. The node transitioned to this state at:Fri Sep 23 16:10:15 CST 2022
        at com.sleepycat.je.rep.txn.ReadonlyTxn.disallowReplicaWrite(ReadonlyTxn.java:114) ~[je-18.3.12.jar:18.3.12]
        at com.sleepycat.je.dbi.DbTree.checkReplicaWrite(DbTree.java:880) ~[je-18.3.12.jar:18.3.12]
        at com.sleepycat.je.dbi.DbTree.doCreateDb(DbTree.java:579) ~[je-18.3.12.jar:18.3.12]
        at com.sleepycat.je.dbi.DbTree.createDb(DbTree.java:486) ~[je-18.3.12.jar:18.3.12]
        at com.sleepycat.je.Database.initNew(Database.java:174) ~[je-18.3.12.jar:18.3.12]
        at com.sleepycat.je.Environment.setupDatabase(Environment.java:864) ~[je-18.3.12.jar:18.3.12]
        at com.sleepycat.je.Environment.openDatabase(Environment.java:668) ~[je-18.3.12.jar:18.3.12]
        at org.apache.doris.journal.bdbje.BDBEnvironment.setup(BDBEnvironment.java:179) ~[doris-fe.jar:1.0-SNAPSHOT]
        at org.apache.doris.journal.bdbje.BDBJEJournal.open(BDBJEJournal.java:303) ~[doris-fe.jar:1.0-SNAPSHOT]
        at org.apache.doris.persist.EditLog.open(EditLog.java:847) ~[doris-fe.jar:1.0-SNAPSHOT]
        at org.apache.doris.catalog.Catalog.initialize(Catalog.java:852) ~[doris-fe.jar:1.0-SNAPSHOT]
        at org.apache.doris.PaloFe.start(PaloFe.java:128) ~[doris-fe.jar:1.0-SNAPSHOT]
        at org.apache.doris.PaloFe.main(PaloFe.java:63) ~[doris-fe.jar:1.0-SNAPSHOT]
```
============================
但是选择挂载 nfs，却可以正常启动  
![image](https://user-images.githubusercontent.com/23080394/191921719-d6da8222-cf38-4db3-b1a2-2c05c6278235.png)

![nfs](https://user-images.githubusercontent.com/23080394/191921675-bffa8129-a3e9-4dac-88b8-2b085bf58a71.png)
============================
doris be存储卷挂载在ceph | glusterfs 正常启动

### What You Expected?

fe pod 挂载 ceph | glusterfs 能和挂载nfs 一样正常启动

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by dataalive** [comment]
可能是因为cephFS和glusterFS的一些FS操作的原子语义实现不完整导致了兼容性问题？
