### ISSUE TITLE
[Bug] Spark load failed when partition column is not a key in duplicate model

### ISSUE THREAD

**Issue by xiaoDjun** [apache/doris#14600]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

1.1.3-rc02

### What's Wrong?

In spark load, importing to a duplicate model, the job failed when the partition column is not in the key column list. 

We traced the sparkDpp.java and found that, the partition columns ware built with the key index in base metadata. But when partition column was out of key column list, an IndexOutOfBoundsException occurs when obtaining it through below:

![image](https://user-images.githubusercontent.com/36905671/203985397-560802a0-f6fc-4cb4-8662-bc668892c28f.png)

![image](https://user-images.githubusercontent.com/36905671/203986776-e9771b65-eb7d-4d4b-bdbc-41f1fa616503.png)

Later I will post the exception log.

### What You Expected?

Able to import using spark load in this case.

### How to Reproduce?

1. create a duplicate model, and partition column is not key Index.
2. submit a spark load etl job.

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by xiaoDjun** [comment]
The exception:
```
java.lang.IndexOutOfBoundsException: Index: 3, Size: 1 
at java.util.ArrayList.rangeCheck(ArrayList.java:657) 
at java.util.ArrayList.get(ArrayList.java:433) 
at org.apache.doris.load.loadv2.dpp.DppColumns.<init>(DppColumns.java:39) 
at org.apache.doris.load.loadv2.dpp.DorisRangePartitioner.getPartition(DorisRangePartitioner.java:56) 
at org.apache.doris.load.loadv2.dpp.SparkDpp$2.call(SparkDpp.java:487) 
at org.apache.doris.load.loadv2.dpp.SparkDpp$2.call(SparkDpp.java:460) 
at org.apache.spark.api.java.JavaRDDLike$$anonfun$fn$3$1.apply(JavaRDDLike.scala:143) 
at org.apache.spark.api.java.JavaRDDLike$$anonfun$fn$3$1.apply(JavaRDDLike.scala:143) 
at scala.collection.Iterator$$anon$12.nextCur(Iterator.scala:434) 
at scala.collection.Iterator$$anon$12.hasNext(Iterator.scala:440) 
at org.apache.spark.shuffle.sort.BypassMergeSortShuffleWriter.write(BypassMergeSortShuffleWriter.java:125) 
at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:96) 
at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:53) 
at org.apache.spark.scheduler.Task.run(Task.scala:109) 
at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:345) 
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) 
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) 
at java.lang.Thread.run(Thread.java:748) 
Driver stacktrace:
```
