### ISSUE TITLE
[Bug] 启动doris 1.1.4 FE 报错

### ISSUE THREAD

**Issue by 981433814** [apache/doris#14670]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

1.1.4

### What's Wrong?

2022-11-29 18:14:17,063 INFO (main|1) [PaloFe.start():114] Palo FE starting...
2022-11-29 18:14:17,069 INFO (main|1) [FrontendOptions.analyzePriorityCidrs():108] configured prior_cidrs value: 192.168.216.129/24
2022-11-29 18:14:17,079 INFO (main|1) [FrontendOptions.init():88] local address: /192.168.216.129.
2022-11-29 18:14:17,188 INFO (main|1) [ConsistencyChecker.initWorkTime():107] consistency checker will work from 23:00 to 23:00
2022-11-29 18:14:17,428 INFO (main|1) [PrivTable.addEntry():63] add priv entry: global priv. host: %, user: root, priv: , set by resolver: false, domain user ident: null
2022-11-29 18:14:17,434 INFO (main|1) [PaloAuth.setPasswordInternal():1059] finished to set password for 'root'@'%'. is replay: true
2022-11-29 18:14:17,436 INFO (main|1) [PaloAuth.grantInternal():771] finished to grant privilege. is replay: true
2022-11-29 18:14:17,436 INFO (main|1) [PaloAuth.grantInternal():801] finished to grant resource privilege. is replay: true
2022-11-29 18:14:17,445 INFO (main|1) [PaloAuth.createUserInternal():634] finished to create user: 'root'@'%', is replay: true
2022-11-29 18:14:17,445 INFO (main|1) [PrivTable.addEntry():63] add priv entry: global priv. host: %, user: admin, priv: , set by resolver: false, domain user ident: null
2022-11-29 18:14:17,445 INFO (main|1) [PaloAuth.setPasswordInternal():1059] finished to set password for 'admin'@'%'. is replay: true
2022-11-29 18:14:17,446 INFO (main|1) [PaloAuth.grantInternal():771] finished to grant privilege. is replay: true
2022-11-29 18:14:17,446 INFO (main|1) [PaloAuth.grantInternal():801] finished to grant resource privilege. is replay: true
2022-11-29 18:14:17,446 INFO (main|1) [PaloAuth.createUserInternal():634] finished to create user: 'admin'@'%', is replay: true
2022-11-29 18:14:17,562 INFO (main|1) [Catalog.getHelperNodes():1206] get helper nodes: [192.168.216.129:9010]
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/opt/apache-doris-fe-1.1.4-bin/lib/slf4j-log4j12-1.7.9.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/opt/apache-doris-fe-1.1.4-bin/lib/log4j-slf4j-impl-2.18.0.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.slf4j.impl.Log4jLoggerFactory]
2022-11-29 18:14:17,584 INFO (main|1) [Catalog.getClusterIdAndRole():1079] finished to get cluster id: 2043166912, role: MASTER and node name: 192.168.216.129_9010_1669711709282
2022-11-29 18:14:17,591 INFO (main|1) [Catalog.loadImage():1617] image does not exist: /opt/apache-doris-fe-1.1.4-bin/doris-meta/image/image.0
2022-11-29 18:14:18,513 INFO (UNKNOWN 192.168.216.129_9010_1669711709282(-1)|1) [BDBEnvironment.setup():161] add helper[192.168.216.129:9010] as ReplicationGroupAdmin
2022-11-29 18:14:18,517 WARN (UNKNOWN 192.168.216.129_9010_1669711709282(-1)|1) [Catalog.notifyNewFETypeTransfer():2318] notify new FE type transfer: UNKNOWN
[2022-11-29 18:14:18] notify new FE type transfer: UNKNOWN
2022-11-29 18:14:23,542 INFO (UNKNOWN 192.168.216.129_9010_1669711709282(-1)|1) [BDBEnvironment.setup():161] add helper[192.168.216.129:9010] as ReplicationGroupAdmin
2022-11-29 18:14:23,542 WARN (UNKNOWN 192.168.216.129_9010_1669711709282(-1)|1) [Catalog.notifyNewFETypeTransfer():2318] notify new FE type transfer: UNKNOWN
[2022-11-29 18:14:23] notify new FE type transfer: UNKNOWN
2022-11-29 18:14:28,545 INFO (UNKNOWN 192.168.216.129_9010_1669711709282(-1)|1) [BDBEnvironment.setup():161] add helper[192.168.216.129:9010] as ReplicationGroupAdmin
2022-11-29 18:14:28,545 WARN (UNKNOWN 192.168.216.129_9010_1669711709282(-1)|1) [Catalog.notifyNewFETypeTransfer():2318] notify new FE type transfer: UNKNOWN
[2022-11-29 18:14:28] notify new FE type transfer: UNKNOWN
2022-11-29 18:14:28,546 ERROR (UNKNOWN 192.168.216.129_9010_1669711709282(-1)|1) [BDBEnvironment.setup():200] error to open replicated environment. will exit.
com.sleepycat.je.DatabaseNotFoundException: (JE 18.3.12) Database epochDB not found.
        at com.sleepycat.je.Environment.setupDatabase(Environment.java:854) ~[je-18.3.13-doris-SNAPSHOT.jar:18.3.13-doris-SNAPSHOT]
        at com.sleepycat.je.Environment.openDatabase(Environment.java:668) ~[je-18.3.13-doris-SNAPSHOT.jar:18.3.13-doris-SNAPSHOT]
        at org.apache.doris.journal.bdbje.BDBEnvironment.setup(BDBEnvironment.java:181) ~[doris-fe.jar:1.0-SNAPSHOT]
        at org.apache.doris.journal.bdbje.BDBJEJournal.open(BDBJEJournal.java:303) ~[doris-fe.jar:1.0-SNAPSHOT]
        at org.apache.doris.persist.EditLog.open(EditLog.java:847) ~[doris-fe.jar:1.0-SNAPSHOT]
        at org.apache.doris.catalog.Catalog.initialize(Catalog.java:852) ~[doris-fe.jar:1.0-SNAPSHOT]
        at org.apache.doris.PaloFe.start(PaloFe.java:128) ~[doris-fe.jar:1.0-SNAPSHOT]
        at org.apache.doris.PaloFe.main(PaloFe.java:63) ~[doris-fe.jar:1.0-SNAPSHOT]

### What You Expected?

为什么首次启动FE会报错 Database epochDB not found.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by yuanyuan8983** [comment]
It seems that it is not the first time to start it. It should be the one with data in the doris meta before. Whether it is the FE package copied from other machines. If it is, you need to clean the doris meta first. You can add me to WeChat：cyllyy810222

**Comment by df007df** [comment]
How do I solve the same problem with docker-compose?

**Comment by datayesJava2** [comment]
> How do I solve the same problem with docker-compose?

I encountered the same problem, how did you solve？

**Comment by jeeinn** [comment]
> 



> > How do I solve the same problem with docker-compose?
> 
> I encountered the same problem, how did you solve?

It seems that it is not the first time to start it . use `rm -rf fe/doris-meta/*` and restart
