### ISSUE TITLE
[Bug] Failure allocating buffer

### ISSUE THREAD

**Issue by gaoyan1998** [apache/doris#14715]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

1.1

### What's Wrong?

use flink sql read doris failed ,  

Caused by: org.apache.doris.flink.exception.DorisRuntimeException: Failure allocating buffer.
	at org.apache.doris.flink.serialization.RowBatch.readArrow(RowBatch.java:128) ~[flink-doris-connector-1.15-1.2.0.jar:1.2.0]
	at org.apache.doris.flink.source.reader.DorisValueReader.hasNext(DorisValueReader.java:202) ~[flink-doris-connector-1.15-1.2.0.jar:1.2.0]
	at org.apache.doris.flink.source.split.DorisSplitRecords.nextRecordFromSplit(DorisSplitRecords.java:70) ~[flink-doris-connector-1.15-1.2.0.jar:1.2.0]
	at org.apache.doris.flink.source.split.DorisSplitRecords.nextRecordFromSplit(DorisSplitRecords.java:32) ~[flink-doris-connector-1.15-1.2.0.jar:1.2.0]
	at org.apache.flink.connector.base.source.reader.SourceReaderBase.pollNext(SourceReaderBase.java:139) ~[flink-connector-base-1.15.2.jar:1.15.2]
	at org.apache.flink.streaming.api.operators.SourceOperator.emitNext(SourceOperator.java:385) ~[flink-streaming-java-1.15.2.jar:1.15.2]
	at org.apache.flink.streaming.runtime.io.StreamTaskSourceInput.emitNext(StreamTaskSourceInput.java:68) ~[flink-streaming-java-1.15.2.jar:1.15.2]
	at org.apache.flink.streaming.runtime.io.StreamOneInputProcessor.processInput(StreamOneInputProcessor.java:65) ~[flink-streaming-java-1.15.2.jar:1.15.2]
	at org.apache.flink.streaming.runtime.tasks.StreamTask.processInput(StreamTask.java:519) ~[flink-streaming-java-1.15.2.jar:1.15.2]
	at org.apache.flink.streaming.runtime.tasks.mailbox.MailboxProcessor.runMailboxLoop(MailboxProcessor.java:203) ~[flink-streaming-java-1.15.2.jar:1.15.2]
	at org.apache.flink.streaming.runtime.tasks.StreamTask.runMailboxLoop(StreamTask.java:804) ~[flink-streaming-java-1.15.2.jar:1.15.2]
	at org.apache.flink.streaming.runtime.tasks.StreamTask.invoke(StreamTask.java:753) ~[flink-streaming-java-1.15.2.jar:1.15.2]
	at org.apache.flink.runtime.taskmanager.Task.runWithSystemExitMonitoring(Task.java:948) ~[flink-runtime-1.15.2.jar:1.15.2]
	at org.apache.flink.runtime.taskmanager.Task.restoreAndInvoke(Task.java:927) ~[flink-runtime-1.15.2.jar:1.15.2]
	at org.apache.flink.runtime.taskmanager.Task.doRun(Task.java:741) ~[flink-runtime-1.15.2.jar:1.15.2]
	at org.apache.flink.runtime.taskmanager.Task.run(Task.java:563) ~[flink-runtime-1.15.2.jar:1.15.2]
	at java.lang.Thread.run(Unknown Source) ~[?:?]

### What You Expected?

read data batch

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by DongLiang-0** [comment]
Which version of doris-flink-connector

**Comment by ikiler** [comment]
> Contributor

1.2.0

**Comment by ikiler** [comment]
> > Contributor
> 
> 1.2.0
flink version 1.15.2

**Comment by DongLiang-0** [comment]
The reason for this is you jvm  `-XX:MaxDirectMemorySize`  not enough,  you can increase `-Xmx `  to solve this problem.
reference: [-XX:MaxDirectMemorySize](https://www.eclipse.org/openj9/docs/xxmaxdirectmemorysize/)

Try again after adjusted to see if it still happens

**Comment by ikiler** [comment]
> The reason for this is you jvm `-XX:MaxDirectMemorySize` not enough, you can increase `-Xmx ` to solve this problem. reference: [-XX:MaxDirectMemorySize](https://www.eclipse.org/openj9/docs/xxmaxdirectmemorysize/)
> 
> Try again after adjusted to see if it still happens

both of be and fe ?

**Comment by DongLiang-0** [comment]
> 

fe

**Comment by ikiler** [comment]
> > 
> 
> fe

thx.

**Comment by DongLiang-0** [comment]
> > The reason for this is you jvm `-XX:MaxDirectMemorySize` not enough, you can increase `-Xmx ` to solve this problem. reference: [-XX:MaxDirectMemorySize](https://www.eclipse.org/openj9/docs/xxmaxdirectmemorysize/)
> > Try again after adjusted to see if it still happens
> 
> both of be and fe ?


try both
