### ISSUE TITLE
[Bug] 使用1.2版本，JSONB数据类型，查询时所有BE节点崩溃，无法使用insert into插入json数据

### ISSUE THREAD

**Issue by ediconss** [apache/doris#14947]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

Doris 1.2.0  noavx2版本；jdk8

### What's Wrong?

升级1.2后，使用jsonb类型报时
CREATE TABLE test_jsonb (
  id INT,
  j JSONB
)
DUPLICATE KEY(id)
DISTRIBUTED BY HASH(id) BUCKETS 10
PROPERTIES("replication_num" = "1");

1.无法使用insert into插入数据
  INSERT INTO test_jsonb VALUES(26, '{"k1":"v1", "k2": 200}');
报错：Unknown expr node type: 25

org.apache.doris.common.UserException: errCode = 2, detailMessage = Unknown expr node type: 25
        at org.apache.doris.qe.Coordinator.waitRpc(Coordinator.java:755) ~[doris-fe.jar:1.0-SNAPSHOT]
        at org.apache.doris.qe.Coordinator.sendFragment(Coordinator.java:676) ~[doris-fe.jar:1.0-SNAPSHOT]
        at org.apache.doris.qe.Coordinator.exec(Coordinator.java:552) ~[doris-fe.jar:1.0-SNAPSHOT]
        at org.apache.doris.qe.StmtExecutor.handleInsertStmt(StmtExecutor.java:1441) ~[doris-fe.jar:1.0-SNAPSHOT]
        at org.apache.doris.qe.StmtExecutor.execute(StmtExecutor.java:551) ~[doris-fe.jar:1.0-SNAPSHOT]
        at org.apache.doris.qe.StmtExecutor.execute(StmtExecutor.java:407) ~[doris-fe.jar:1.0-SNAPSHOT]
        at org.apache.doris.qe.ConnectProcessor.handleQuery(ConnectProcessor.java:298) ~[doris-fe.jar:1.0-SNAPSHOT]
        at org.apache.doris.qe.ConnectProcessor.dispatch(ConnectProcessor.java:437) ~[doris-fe.jar:1.0-SNAPSHOT]
        at org.apache.doris.qe.ConnectProcessor.processOnce(ConnectProcessor.java:664) ~[doris-fe.jar:1.0-SNAPSHOT]
        at org.apache.doris.mysql.nio.ReadListener.lambda$handleEvent$0(ReadListener.java:52) ~[doris-fe.jar:1.0-SNAPSHOT]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
使用stream load导入数据成功
2.查询时，所有BE节点挂掉
SELECT j from public.test_jsonb;

I1208 21:11:01.416397  9593 fragment_mgr.cpp:629] query_id: 68b3218111f345ef-8f34cae8a77bcdef coord_addr TNetworkAddress(hostname=192.168.10.249, port=9020) total fragment num on current host: 1
I1208 21:11:01.416551  9593 fragment_mgr.cpp:679] Register query/load memory tracker, query/load id: 68b3218111f345ef-8f34cae8a77bcdef limit: 2.00 GB
I1208 21:11:01.416749  9593 plan_fragment_executor.cpp:87] PlanFragmentExecutor::prepare|query_id=68b3218111f345ef-8f34cae8a77bcdef|instance_id=68b3218111f345ef-8f34cae8a77bcdf0|backend_num=1|pthread_id=140175188797184
I1208 21:11:01.418221  9164 fragment_mgr.cpp:493] PlanFragmentExecutor::_exec_actual|query_id=68b3218111f345ef-8f34cae8a77bcdef|instance_id=68b3218111f345ef-8f34cae8a77bcdf0|pthread_id=140178332854016
I1208 21:11:01.422863  9164 plan_fragment_executor.cpp:232] PlanFragmentExecutor::open|query_id=68b3218111f345ef-8f34cae8a77bcdef|instance_id=68b3218111f345ef-8f34cae8a77bcdf0|mem_limit=2.00 GB
W1208 21:11:01.546495  9036 mem_tracker_limiter.cpp:216] System Mem Exceed Limit Check Faild, Try Alloc: 481036343968
Process Memory Summary:
    physical memory 7.64 GB, process memory used 329.87 MB limit 6.11 GB, sys mem available 6.55 GB low water mark 782.10 MB
Alloc Stacktrace:
    @     0x564a14f81708  doris::MemTrackerLimiter::print_log_process_usage()
    @     0x564a145f26cb  doris::MemTrackerLimiter::try_consume()
    @     0x564a14f90de6  malloc
    @     0x564a1b4ac558  operator new()
    @     0x564a1495e005  doris::RowBlock::init()
    @     0x564a14d8cd90  doris::BetaRowsetReader::init()
    @     0x564a1489769f  doris::TupleReader::_init_collect_iter()
    @     0x564a14897e26  doris::TupleReader::init()
    @     0x564a14c0051e  doris::OlapScanner::open()
    @     0x564a14b6238f  doris::OlapScanNode::scanner_thread()
    @     0x564a150c29d5  doris::ThreadPool::dispatch_thread()
    @     0x564a150b90bf  doris::Thread::supervise_thread()
    @     0x7f7e700f3ea5  start_thread
    @     0x7f7e70406b0d  __clone
    @              (nil)  (unknown)

Memory Tracker Summary:
    Type=consistency, Used=0(0 B), Peak=0(0 B)
    Type=batch_load, Used=0(0 B), Peak=0(0 B)
    Type=clone, Used=0(0 B), Peak=0(0 B)
    Type=schema_change, Used=0(0 B), Peak=0(0 B)
    Type=compaction, Used=0(0 B), Peak=0(0 B)
    Type=load, Used=0(0 B), Peak=0(0 B)
    Type=query, Used=139.52 KB(142864 B), Peak=139.52 KB(142864 B)
    Type=global, Used=123.27 MB(129260952 B), Peak=123.27 MB(129260952 B)
    Type=tc/jemalloc_cache, Used=22.36 MB(23443760 B), Peak=-1.00 B(-1 B)
    Type=process, Used=145.77 MB(152847576 B), Peak=-1.00 B(-1 B)
    MemTrackerLimiter Label=Orphan, Type=global, Limit=-1.00 B(-1 B), Used=123.27 MB(129260952 B), Peak=123.28 MB(129264408 B)
    MemTracker Label=BufferAllocator, Parent Label=Orphan, Used=0(0 B), Peak=0(0 B)
    MemTracker Label=LoadChannelMgr, Parent Label=Orphan, Used=0(0 B), Peak=0(0 B)
    MemTracker Label=StorageEngine, Parent Label=Orphan, Used=1.08 MB(1131144 B), Peak=330.80 KB(338736 B)
    MemTracker Label=SegCompaction, Parent Label=Orphan, Used=0(0 B), Peak=0(0 B)
    MemTracker Label=SegmentMeta, Parent Label=Orphan, Used=0(0 B), Peak=0(0 B)
    MemTracker Label=TabletManager, Parent Label=Orphan, Used=0(0 B), Peak=0(0 B)
    MemTrackerLimiter Label=DataPageCache, Type=global, Limit=-1.00 B(-1 B), Used=0(0 B), Peak=0(0 B)
    MemTrackerLimiter Label=IndexPageCache, Type=global, Limit=-1.00 B(-1 B), Used=0(0 B), Peak=0(0 B)
    MemTrackerLimiter Label=SegmentCache, Type=global, Limit=-1.00 B(-1 B), Used=0(0 B), Peak=0(0 B)
    MemTrackerLimiter Label=DiskIO, Type=global, Limit=6.11 GB(6560733593 B), Used=0(0 B), Peak=0(0 B)
    MemTrackerLimiter Label=ChunkAllocator, Type=global, Limit=-1.00 B(-1 B), Used=0(0 B), Peak=0(0 B)
    MemTrackerLimiter Label=LastestSuccessChannelCache, Type=global, Limit=-1.00 B(-1 B), Used=0(0 B), Peak=0(0 B)
    MemTrackerLimiter Label=DeleteBitmap AggCache, Type=global, Limit=-1.00 B(-1 B), Used=0(0 B), Peak=0(0 B)
*** Query id: 0-0 ***
*** Aborted at 1670505061 (unix time) try "date -d @1670505061" if you are using GNU date ***
*** Current BE git commitID: Unknown ***
*** SIGSEGV address not mapped to object (@0x0) received by PID 8904 (TID 0x7f7e11b8d700) from PID 0; stack trace: ***
I1208 21:11:01.567687  8922 daemon.cpp:214] physical memory 7.64 GB, process memory used 349.22 MB limit 6.11 GB, sys mem available 6.53 GB low water mark 782.10 MB
I1208 21:11:02.690578  9593 internal_service.cpp:393] cancel fragment, fragment_instance_id=68b3218111f345ef-8f34cae8a77bcdf0, reason: 3
I1208 21:11:02.690667  9593 plan_fragment_executor.cpp:627] PlanFragmentExecutor::cancel|query_id=68b3218111f345ef-8f34cae8a77bcdef|instance_id=68b3218111f345ef-8f34cae8a77bcdf0|reason=3|error message=
 0# doris::signal::(anonymous namespace)::FailureSignalHandler(int, siginfo_t*, void*) at /root/doris/be/src/common/signal_handler.h:420
 1# os::Linux::chained_handler(int, siginfo*, void*) in /usr/lib/jvm/jdk1.8.0_351/jre/lib/amd64/server/libjvm.so
 2# JVM_handle_linux_signal in /usr/lib/jvm/jdk1.8.0_351/jre/lib/amd64/server/libjvm.so
 3# signalHandler(int, siginfo*, void*) in /usr/lib/jvm/jdk1.8.0_351/jre/lib/amd64/server/libjvm.so
 4# 0x00007F7E7033E400 in /lib64/libc.so.6
 5# doris::memory_copy(void*, void const*, unsigned long) at /root/doris/be/src/util/mem_util.hpp:110
 6# doris::FieldTypeTraits<(doris::FieldType)13>::direct_copy(void*, void const*) at /root/doris/be/src/olap/types.h:1439
 7# void doris::direct_copy_row<doris::RowCursor, doris::RowCursor>(doris::RowCursor*, doris::RowCursor const&) at /root/doris/be/src/olap/row.h:120
 8# doris::TupleReader::_direct_next_row(doris::RowCursor*, doris::MemPool*, doris::ObjectPool*, bool*) at /root/doris/be/src/olap/tuple_reader.cpp:112
 9# doris::OlapScanner::get_batch(doris::RuntimeState*, doris::RowBatch*, bool*) at /root/doris/be/src/exec/olap_scanner.cpp:372
10# doris::OlapScanNode::scanner_thread(doris::OlapScanner*) at /root/doris/be/src/exec/olap_scan_node.cpp:1752
11# doris::ThreadPool::dispatch_thread() at /root/doris/be/src/util/threadpool.cpp:542
12# doris::Thread::supervise_thread(void*) at /root/doris/be/src/util/thread.cpp:455
13# start_thread in /lib64/libpthread.so.0
14# clone in /lib64/libc.so.6

./apache-doris-be-1.2.0-bin-x86_64-noavx2/bin/start_be.sh: line 235:  8904 Segmentation fault      "${DORIS_HOME}/lib/doris_be" "$@" 2>&1 < /dev/null

### What You Expected?

正常使用json数据类型

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by ediconss** [comment]
开启向量化后解决
set global enable_vectorized_engine=true
