### ISSUE TITLE
[Bug] doris::vectorized::RowGroupReader::_do_lazy_read endless loop stack explosion

### ISSUE THREAD

**Issue by deardeng** [apache/doris#15258]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

master e65b577f905eb0f6d3f789d9f216aed0439f73b5

### What's Wrong?

```
(gdb) bt
#0  0x00005606543984ed in __sanitizer::StackDepotBase<__sanitizer::StackDepotNode, 1, 20>::Put(__sanitizer::StackTrace, bool*) ()
#1  0x0000560654398008 in __sanitizer::StackDepotPut(__sanitizer::StackTrace) ()
#2  0x00005606542f08d7 in __asan::Allocator::Allocate(unsigned long, unsigned long, __sanitizer::BufferedStackTrace*, __asan::AllocType, bool) ()
#3  0x00005606542ec889 in __asan::asan_memalign(unsigned long, unsigned long, __sanitizer::BufferedStackTrace*, __asan::AllocType) ()
#4  0x00005606543796c0 in operator new(unsigned long) ()
#5  0x0000560658ecf3d6 in __gnu_cxx::new_allocator<phmap::priv::Allocate<8ul, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, unsigned long> > >(std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, unsigned long> >*, unsigned long)::M>::allocate(unsigned long, void const*) (this=0x7f309e8e39f0, __n=8) at /var/local/ldb_toolchain/include/c++/11/ext/new_allocator.h:121
#6  0x0000560658ecf0fd in phmap::allocator_traits<std::allocator<phmap::priv::Allocate<8ul, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, unsigned long> > >(std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, unsigned long> >*, unsigned long)::M> >::allocate(std::allocator<phmap::priv::Allocate<8ul, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, unsigned long> > >(std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, unsigned long> >*, unsigned long)::M>&, unsigned long) (a=..., n=8)
    at /home/zcp/repo_center/doris_master/doris/thirdparty/installed/include/parallel_hashmap/phmap_base.h:1468
#7  0x0000560658ecec52 in phmap::priv::Allocate<8ul, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, unsigned long> > > (alloc=0x7f309e8e49a0, n=64) at /home/zcp/repo_center/doris_master/doris/thirdparty/installed/include/parallel_hashmap/phmap_base.h:4363
#8  0x0000560658ece63f in phmap::priv::raw_hash_set<phmap::priv::FlatHashMapPolicy<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, unsigned long>, phmap::priv::StringHashT<char>, phmap::priv::StringHashEqT<char>::Eq, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, unsigned long> > >::initialize_slots (this=0x7f309e8e4978)
    at /home/zcp/repo_center/doris_master/doris/thirdparty/installed/include/parallel_hashmap/phmap.h:1845
#9  0x0000560658ecd176 in phmap::priv::raw_hash_set<phmap::priv::FlatHashMapPolicy<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, unsigned long>, phmap::priv::StringHashT<char>, phmap::priv::StringHashEqT<char>::Eq, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, unsigned long> > >::resize (this=0x7f309e8e4978, new_capacity=1)
    at /home/zcp/repo_center/doris_master/doris/thirdparty/installed/include/parallel_hashmap/phmap.h:1877
#10 0x0000560658eccc32 in phmap::priv::raw_hash_set<phmap::priv::FlatHashMapPolicy<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, unsigned long>, phmap::priv::StringHashT<char>, phmap::priv::StringHashEqT<char>::Eq, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, unsigned long> > >::rehash_and_grow_if_necessary (this=0x7f309e8e4978)
    at /home/zcp/repo_center/doris_master/doris/thirdparty/installed/include/parallel_hashmap/phmap.h:1963
#11 0x0000560658ecc315 in phmap::priv::raw_hash_set<phmap::priv::FlatHashMapPolicy<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, unsigned long>, phmap::priv::StringHashT<char>, phmap::priv::StringHashEqT<char>::Eq, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, unsigned long> > >::prepare_insert (this=0x7f309e8e4978, hashval=5911023153216484498)
    at /home/zcp/repo_center/doris_master/doris/thirdparty/installed/include/parallel_hashmap/phmap.h:2060
#12 0x0000560658ecbad3 in phmap::priv::raw_hash_set<phmap::priv::FlatHashMapPolicy<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, unsigned long>, phmap::priv::StringHashT<char>, phmap::priv::StringHashEqT<char>::Eq, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, unsigned long> > >::find_or_prepare_insert<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > (
    this=0x7f309e8e4978, key=..., hashval=5911023153216484498) at /home/zcp/repo_center/doris_master/doris/thirdparty/installed/include/parallel_hashmap/phmap.h:2048
#13 0x00005606596638ce in phmap::priv::raw_hash_set<phmap::priv::FlatHashMapPolicy<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, unsigned long>, phmap::priv::StringHashT<char>, phmap::priv::StringHashEqT<char>::Eq, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, unsigned long> > >::emplace_decomposable<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::piecewise_construct_t const&, std::tuple<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&>, std::tuple<unsigned long&&> > (this=0x7f309e8e4978,
    key=..., hashval=5911023153216484498) at /home/zcp/repo_center/doris_master/doris/thirdparty/installed/include/parallel_hashmap/phmap.h:1758
#14 0x0000560659662d34 in phmap::priv::raw_hash_set<phmap::priv::FlatHashMapPolicy<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, unsigned long>, phmap::priv::StringHashT<char>, phmap::priv::StringHashEqT<char>::Eq, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, unsigned long> > >::EmplaceDecomposable::operator()<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::piecewi--Type <RET> for more, q to quit, c to continue without paging--
se_construct_t const&, std::tuple<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&>, std::tuple<unsigned long&&> > (
    this=0x7f309e8e42f0, key=...) at /home/zcp/repo_center/doris_master/doris/thirdparty/installed/include/parallel_hashmap/phmap.h:1769
#15 0x00005606596621f3 in phmap::priv::memory_internal::DecomposePairImpl<phmap::priv::raw_hash_set<phmap::priv::FlatHashMapPolicy<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, unsigned long>, phmap::priv::StringHashT<char>, phmap::priv::StringHashEqT<char>::Eq, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, unsigned long> > >::EmplaceDecomposable, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::tuple<unsigned long&&> > (f=..., p=...)
    at /home/zcp/repo_center/doris_master/doris/thirdparty/installed/include/parallel_hashmap/phmap.h:674
#16 0x00005606596611f8 in phmap::priv::DecomposePair<phmap::priv::raw_hash_set<phmap::priv::FlatHashMapPolicy<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, unsigned long>, phmap::priv::StringHashT<char>, phmap::priv::StringHashEqT<char>::Eq, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, unsigned long> > >::EmplaceDecomposable, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned long> (f=...) at /home/zcp/repo_center/doris_master/doris/thirdparty/installed/include/parallel_hashmap/phmap.h:3815
#17 0x000056065965e8d1 in phmap::priv::FlatHashMapPolicy<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, unsigned long>::apply<phmap::priv::raw_hash_set<phmap::priv::FlatHashMapPolicy<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, unsigned long>, phmap::priv::StringHashT<char>, phmap::priv::StringHashEqT<char>::Eq, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, unsigned long> > >::EmplaceDecomposable, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned long> (f=...)
    at /home/zcp/repo_center/doris_master/doris/thirdparty/installed/include/parallel_hashmap/phmap.h:3918
#18 0x0000560659659732 in phmap::priv::hash_policy_traits<phmap::priv::FlatHashMapPolicy<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, unsigned long>, void>::apply<phmap::priv::raw_hash_set<phmap::priv::FlatHashMapPolicy<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, unsigned long>, phmap::priv::StringHashT<char>, phmap::priv::StringHashEqT<char>::Eq, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, unsigned long> > >::EmplaceDecomposable, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned long, phmap::priv::FlatHashMapPolicy<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, unsigned long> > (f=...)
    at /home/zcp/repo_center/doris_master/doris/thirdparty/installed/include/parallel_hashmap/phmap_base.h:548
#19 0x0000560659655baa in phmap::priv::raw_hash_set<phmap::priv::FlatHashMapPolicy<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, unsigned long>, phmap::priv::StringHashT<char>, phmap::priv::StringHashEqT<char>::Eq, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, unsigned long> > >::emplace<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned long, 0> (
    this=0x7f309e8e4978) at /home/zcp/repo_center/doris_master/doris/thirdparty/installed/include/parallel_hashmap/phmap.h:1358
#20 0x000056065963c9df in doris::vectorized::Block::insert (this=0x7f309e8e4960, elem=...) at /home/zcp/repo_center/doris_master/doris/be/src/vec/core/block.cpp:150
#21 0x000056065dc14d6e in doris::vectorized::create_block_with_nested_columns_impl (block=..., args=...)
    at /home/zcp/repo_center/doris_master/doris/be/src/vec/functions/function_helpers.cpp:89
#22 0x000056065dc155cc in doris::vectorized::create_block_with_nested_columns (block=..., args=..., result=5)
    at /home/zcp/repo_center/doris_master/doris/be/src/vec/functions/function_helpers.cpp:104
#23 0x000056065dc04d43 in doris::vectorized::PreparedFunctionImpl::default_implementation_for_nulls (this=0x6040035b80e0, context=0x602000bf1110, block=..., args=...,
    result=5, input_rows_count=992, dry_run=false, executed=0x7f309e8e4b40) at /home/zcp/repo_center/doris_master/doris/be/src/vec/functions/function.cpp:220
#24 0x000056065dc0548d in doris::vectorized::PreparedFunctionImpl::execute_without_low_cardinality_columns (this=0x6040035b80e0, context=0x602000bf1110, block=...,
    args=..., result=5, input_rows_count=992, dry_run=false) at /home/zcp/repo_center/doris_master/doris/be/src/vec/functions/function.cpp:242

#25 0x000056065dc057ff in doris::vectorized::PreparedFunctionImpl::execute (this=0x6040035b80e0, context=0x602000bf1110, block=..., args=..., result=5,
    input_rows_count=992, dry_run=false) at /home/zcp/repo_center/doris_master/doris/be/src/vec/functions/function.cpp:273
#26 0x000056065c533933 in doris::vectorized::IFunctionBase::execute (this=0x607004094820, context=0x602000bf1110, block=..., arguments=..., result=5,
    input_rows_count=992, dry_run=false) at /home/zcp/repo_center/doris_master/doris/be/src/vec/functions/function.h:136
#27 0x000056065c44f434 in doris::vectorized::VectorizedFnCall::execute (this=0x619004bb9080, context=0x6060164a1580, block=0x6080025ad3a0,
    result_column_id=0x7f309e8e4fc0) at /home/zcp/repo_center/doris_master/doris/be/src/vec/exprs/vectorized_fn_call.cpp:107
#28 0x000056065c44f0aa in doris::vectorized::VectorizedFnCall::execute (this=0x619000305c80, context=0x6060164a1580, block=0x6080025ad3a0,
    result_column_id=0x7f309e8e5590) at /home/zcp/repo_center/doris_master/doris/be/src/vec/exprs/vectorized_fn_call.cpp:100
#29 0x000056065c43f882 in doris::vectorized::VcompoundPred::execute (this=0x619000305c80, context=0x6060164a1580, block=0x6080025ad3a0, result_column_id=0x7f309e8e5590)
--Type <RET> for more, q to quit, c to continue without paging--
    at /home/zcp/repo_center/doris_master/doris/be/src/vec/exprs/vcompound_pred.h:56
#30 0x000056065c45eb73 in doris::vectorized::VExprContext::execute (this=0x6060164a1580, block=0x6080025ad3a0, result_column_id=0x7f309e8e5590)
    at /home/zcp/repo_center/doris_master/doris/be/src/vec/exprs/vexpr_context.cpp:43
#31 0x00005606628610c4 in doris::vectorized::RowGroupReader::_do_lazy_read (this=0x60d002e0ca10, block=0x6080025ad3a0, batch_size=992, read_rows=0x7f309f0d9d00,
    batch_eof=0x7f309f0d9b00) at /home/zcp/repo_center/doris_master/doris/be/src/vec/exec/format/parquet/vparquet_group_reader.cpp:165
#32 0x0000560662861c53 in doris::vectorized::RowGroupReader::_do_lazy_read (this=0x60d002e0ca10, block=0x6080025ad3a0, batch_size=992, read_rows=0x7f309f0d9d00,
    batch_eof=0x7f309f0d9b00) at /home/zcp/repo_center/doris_master/doris/be/src/vec/exec/format/parquet/vparquet_group_reader.cpp:190
#33 0x0000560662861c53 in doris::vectorized::RowGroupReader::_do_lazy_read (this=0x60d002e0ca10, block=0x6080025ad3a0, batch_size=992, read_rows=0x7f309f0d9d00,
    batch_eof=0x7f309f0d9b00) at /home/zcp/repo_center/doris_master/doris/be/src/vec/exec/format/parquet/vparquet_group_reader.cpp:190
#34 0x0000560662861c53 in doris::vectorized::RowGroupReader::_do_lazy_read (this=0x60d002e0ca10, block=0x6080025ad3a0, batch_size=992, read_rows=0x7f309f0d9d00,
    batch_eof=0x7f309f0d9b00) at /home/zcp/repo_center/doris_master/doris/be/src/vec/exec/format/parquet/vparquet_group_reader.cpp:190
#35 0x0000560662861c53 in doris::vectorized::RowGroupReader::_do_lazy_read (this=0x60d002e0ca10, block=0x6080025ad3a0, batch_size=992, read_rows=0x7f309f0d9d00,
    batch_eof=0x7f309f0d9b00) at /home/zcp/repo_center/doris_master/doris/be/src/vec/exec/format/parquet/vparquet_group_reader.cpp:190
#36 0x0000560662861c53 in doris::vectorized::RowGroupReader::_do_lazy_read (this=0x60d002e0ca10, block=0x6080025ad3a0, batch_size=992, read_rows=0x7f309f0d9d00,
    batch_eof=0x7f309f0d9b00) at /home/zcp/repo_center/doris_master/doris/be/src/vec/exec/format/parquet/vparquet_group_reader.cpp:190
#37 0x0000560662861c53 in doris::vectorized::RowGroupReader::_do_lazy_read (this=0x60d002e0ca10, block=0x6080025ad3a0, batch_size=992, read_rows=0x7f309f0d9d00,
    batch_eof=0x7f309f0d9b00) at /home/zcp/repo_center/doris_master/doris/be/src/vec/exec/format/parquet/vparquet_group_reader.cpp:190
#38 0x0000560662861c53 in doris::vectorized::RowGroupReader::_do_lazy_read (this=0x60d002e0ca10, block=0x6080025ad3a0, batch_size=992, read_rows=0x7f309f0d9d00,
    batch_eof=0x7f309f0d9b00) at /home/zcp/repo_center/doris_master/doris/be/src/vec/exec/format/parquet/vparquet_group_reader.cpp:190
#39 0x0000560662861c53 in doris::vectorized::RowGroupReader::_do_lazy_read (this=0x60d002e0ca10, block=0x6080025ad3a0, batch_size=992, read_rows=0x7f309f0d9d00,
    batch_eof=0x7f309f0d9b00) at /home/zcp/repo_center/doris_master/doris/be/src/vec/exec/format/parquet/vparquet_group_reader.cpp:190
#40 0x0000560662861c53 in doris::vectorized::RowGroupReader::_do_lazy_read (this=0x60d002e0ca10, block=0x6080025ad3a0, batch_size=992, read_rows=0x7f309f0d9d00,
    batch_eof=0x7f309f0d9b00) at /home/zcp/repo_center/doris_master/doris/be/src/vec/exec/format/parquet/vparquet_group_reader.cpp:190
#41 0x0000560662861c53 in doris::vectorized::RowGroupReader::_do_lazy_read (this=0x60d002e0ca10, block=0x6080025ad3a0, batch_size=992, read_rows=0x7f309f0d9d00,
    batch_eof=0x7f309f0d9b00) at /home/zcp/repo_center/doris_master/doris/be/src/vec/exec/format/parquet/vparquet_group_reader.cpp:190
#42 0x0000560662861c53 in doris::vectorized::RowGroupReader::_do_lazy_read (this=0x60d002e0ca10, block=0x6080025ad3a0, batch_size=992, read_rows=0x7f309f0d9d00,
    batch_eof=0x7f309f0d9b00) at /home/zcp/repo_center/doris_master/doris/be/src/vec/exec/format/parquet/vparquet_group_reader.cpp:190
#43 0x0000560662861c53 in doris::vectorized::RowGroupReader::_do_lazy_read (this=0x60d002e0ca10, block=0x6080025ad3a0, batch_size=992, read_rows=0x7f309f0d9d00,
    batch_eof=0x7f309f0d9b00) at /home/zcp/repo_center/doris_master/doris/be/src/vec/exec/format/parquet/vparquet_group_reader.cpp:190
#44 0x0000560662861c53 in doris::vectorized::RowGroupReader::_do_lazy_read (this=0x60d002e0ca10, block=0x6080025ad3a0, batch_size=992, read_rows=0x7f309f0d9d00,
    batch_eof=0x7f309f0d9b00) at /home/zcp/repo_center/doris_master/doris/be/src/vec/exec/format/parquet/vparquet_group_reader.cpp:190
#45 0x0000560662861c53 in doris::vectorized::RowGroupReader::_do_lazy_read (this=0x60d002e0ca10, block=0x6080025ad3a0, batch_size=992, read_rows=0x7f309f0d9d00,
    batch_eof=0x7f309f0d9b00) at /home/zcp/repo_center/doris_master/doris/be/src/vec/exec/format/parquet/vparquet_group_reader.cpp:190
#46 0x0000560662861c53 in doris::vectorized::RowGroupReader::_do_lazy_read (this=0x60d002e0ca10, block=0x6080025ad3a0, batch_size=992, read_rows=0x7f309f0d9d00,
    batch_eof=0x7f309f0d9b00) at /home/zcp/repo_center/doris_master/doris/be/src/vec/exec/format/parquet/vparquet_group_reader.cpp:190
#47 0x0000560662861c53 in doris::vectorized::RowGroupReader::_do_lazy_read (this=0x60d002e0ca10, block=0x6080025ad3a0, batch_size=992, read_rows=0x7f309f0d9d00,
    batch_eof=0x7f309f0d9b00) at /home/zcp/repo_center/doris_master/doris/be/src/vec/exec/format/parquet/vparquet_group_reader.cpp:190
#48 0x0000560662861c53 in doris::vectorized::RowGroupReader::_do_lazy_read (this=0x60d002e0ca10, block=0x6080025ad3a0, batch_size=992, read_rows=0x7f309f0d9d00,
    batch_eof=0x7f309f0d9b00) at /home/zcp/repo_center/doris_master/doris/be/src/vec/exec/format/parquet/vparquet_group_reader.cpp:190
#49 0x0000560662861c53 in doris::vectorized::RowGroupReader::_do_lazy_read (this=0x60d002e0ca10, block=0x6080025ad3a0, batch_size=992, read_rows=0x7f309f0d9d00,
    batch_eof=0x7f309f0d9b00) at /home/zcp/repo_center/doris_master/doris/be/src/vec/exec/format/parquet/vparquet_group_reader.cpp:190
#50 0x0000560662861c53 in doris::vectorized::RowGroupReader::_do_lazy_read (this=0x60d002e0ca10, block=0x6080025ad3a0, batch_size=992, read_rows=0x7f309f0d9d00,
    batch_eof=0x7f309f0d9b00) at /home/zcp/repo_center/doris_master/doris/be/src/vec/exec/format/parquet/vparquet_group_reader.cpp:190
#51 0x0000560662861c53 in doris::vectorized::RowGroupReader::_do_lazy_read (this=0x60d002e0ca10, block=0x6080025ad3a0, batch_size=992, read_rows=0x7f309f0d9d00,
--Type <RET> for more, q to quit, c to continue without paging--
    batch_eof=0x7f309f0d9b00) at /home/zcp/repo_center/doris_master/doris/be/src/vec/exec/format/parquet/vparquet_group_reader.cpp:190
#52 0x0000560662861c53 in doris::vectorized::RowGroupReader::_do_lazy_read (this=0x60d002e0ca10, block=0x6080025ad3a0, batch_size=992, read_rows=0x7f309f0d9d00,
    batch_eof=0x7f309f0d9b00) at /home/zcp/repo_center/doris_master/doris/be/src/vec/exec/format/parquet/vparquet_group_reader.cpp:190
#53 0x0000560662861c53 in doris::vectorized::RowGroupReader::_do_lazy_read (this=0x60d002e0ca10, block=0x6080025ad3a0, batch_size=992, read_rows=0x7f309f0d9d00,
    batch_eof=0x7f309f0d9b00) at /home/zcp/repo_center/doris_master/doris/be/src/vec/exec/format/parquet/vparquet_group_reader.cpp:190
#54 0x0000560662861c53 in doris::vectorized::RowGroupReader::_do_lazy_read (this=0x60d002e0ca10, block=0x6080025ad3a0, batch_size=992, read_rows=0x7f309f0d9d00,
    batch_eof=0x7f309f0d9b00) at /home/zcp/repo_center/doris_master/doris/be/src/vec/exec/format/parquet/vparquet_group_reader.cpp:190
#55 0x0000560662861c53 in doris::vectorized::RowGroupReader::_do_lazy_read (this=0x60d002e0ca10, block=0x6080025ad3a0, batch_size=992, read_rows=0x7f309f0d9d00,
    batch_eof=0x7f309f0d9b00) at /home/zcp/repo_center/doris_master/doris/be/src/vec/exec/format/parquet/vparquet_group_reader.cpp:190
#56 0x0000560662861c53 in doris::vectorized::RowGroupReader::_do_lazy_read (this=0x60d002e0ca10, block=0x6080025ad3a0, batch_size=992, read_rows=0x7f309f0d9d00,
    batch_eof=0x7f309f0d9b00) at /home/zcp/repo_center/doris_master/doris/be/src/vec/exec/format/parquet/vparquet_group_reader.cpp:190
#57 0x0000560662861c53 in doris::vectorized::RowGroupReader::_do_lazy_read (this=0x60d002e0ca10, block=0x6080025ad3a0, batch_size=992, read_rows=0x7f309f0d9d00,
    batch_eof=0x7f309f0d9b00) at /home/zcp/repo_center/doris_master/doris/be/src/vec/exec/format/parquet/vparquet_group_reader.cpp:190
#58 0x0000560662861c53 in doris::vectorized::RowGroupReader::_do_lazy_read (this=0x60d002e0ca10, block=0x6080025ad3a0, batch_size=992, read_rows=0x7f309f0d9d00,
    batch_eof=0x7f309f0d9b00) at /home/zcp/repo_center/doris_master/doris/be/src/vec/exec/format/parquet/vparquet_group_reader.cpp:190
#59 0x0000560662861c53 in doris::vectorized::RowGroupReader::_do_lazy_read (this=0x60d002e0ca10, block=0x6080025ad3a0, batch_size=992, read_rows=0x7f309f0d9d00,
    batch_eof=0x7f309f0d9b00) at /home/zcp/repo_center/doris_master/doris/be/src/vec/exec/format/parquet/vparquet_group_reader.cpp:190
#60 0x0000560662861c53 in doris::vectorized::RowGroupReader::_do_lazy_read (this=0x60d002e0ca10, block=0x6080025ad3a0, batch_size=992, read_rows=0x7f309f0d9d00,
    batch_eof=0x7f309f0d9b00) at /home/zcp/repo_center/doris_master/doris/be/src/vec/exec/format/parquet/vparquet_group_reader.cpp:190
#61 0x0000560662861c53 in doris::vectorized::RowGroupReader::_do_lazy_read (this=0x60d002e0ca10, block=0x6080025ad3a0, batch_size=992, read_rows=0x7f309f0d9d00,
    batch_eof=0x7f309f0d9b00) at /home/zcp/repo_center/doris_master/doris/be/src/vec/exec/format/parquet/vparquet_group_reader.cpp:190
#62 0x0000560662861c53 in doris::vectorized::RowGroupReader::_do_lazy_read (this=0x60d002e0ca10, block=0x6080025ad3a0, batch_size=992, read_rows=0x7f309f0d9d00,
    batch_eof=0x7f309f0d9b00) at /home/zcp/repo_center/doris_master/doris/be/src/vec/exec/format/parquet/vparquet_group_reader.cpp:190
#63 0x0000560662861c53 in doris::vectorized::RowGroupReader::_do_lazy_read (this=0x60d002e0ca10, block=0x6080025ad3a0, batch_size=992, read_rows=0x7f309f0d9d00,
    batch_eof=0x7f309f0d9b00) at /home/zcp/repo_center/doris_master/doris/be/src/vec/exec/format/parquet/vparquet_group_reader.cpp:190
#64 0x0000560662861c53 in doris::vectorized::RowGroupReader::_do_lazy_read (this=0x60d002e0ca10, block=0x6080025ad3a0, batch_size=992, read_rows=0x7f309f0d9d00,
    batch_eof=0x7f309f0d9b00) at /home/zcp/repo_center/doris_master/doris/be/src/vec/exec/format/parquet/vparquet_group_reader.cpp:190
#65 0x0000560662861c53 in doris::vectorized::RowGroupReader::_do_lazy_read (this=0x60d002e0ca10, block=0x6080025ad3a0, batch_size=992, read_rows=0x7f309f0d9d00,
    batch_eof=0x7f309f0d9b00) at /home/zcp/repo_center/doris_master/doris/be/src/vec/exec/format/parquet/vparquet_group_reader.cpp:190
#66 0x0000560662861c53 in doris::vectorized::RowGroupReader::_do_lazy_read (this=0x60d002e0ca10, block=0x6080025ad3a0, batch_size=992, read_rows=0x7f309f0d9d00,
    batch_eof=0x7f309f0d9b00) at /home/zcp/repo_center/doris_master/doris/be/src/vec/exec/format/parquet/vparquet_group_reader.cpp:190
#67 0x0000560662861c53 in doris::vectorized::RowGroupReader::_do_lazy_read (this=0x60d002e0ca10, block=0x6080025ad3a0, batch_size=992, read_rows=0x7f309f0d9d00,
    batch_eof=0x7f309f0d9b00) at /home/zcp/repo_center/doris_master/doris/be/src/vec/exec/format/parquet/vparquet_group_reader.cpp:190
#68 0x0000560662861c53 in doris::vectorized::RowGroupReader::_do_lazy_read (this=0x60d002e0ca10, block=0x6080025ad3a0, batch_size=992, read_rows=0x7f309f0d9d00,
    batch_eof=0x7f309f0d9b00) at /home/zcp/repo_center/doris_master/doris/be/src/vec/exec/format/parquet/vparquet_group_reader.cpp:190
#69 0x0000560662861c53 in doris::vectorized::RowGroupReader::_do_lazy_read (this=0x60d002e0ca10, block=0x6080025ad3a0, batch_size=992, read_rows=0x7f309f0d9d00,
    batch_eof=0x7f309f0d9b00) at /home/zcp/repo_center/doris_master/doris/be/src/vec/exec/format/parquet/vparquet_group_reader.cpp:190
#70 0x0000560662861c53 in doris::vectorized::RowGroupReader::_do_lazy_read (this=0x60d002e0ca10, block=0x6080025ad3a0, batch_size=992, read_rows=0x7f309f0d9d00,
    batch_eof=0x7f309f0d9b00) at /home/zcp/repo_center/doris_master/doris/be/src/vec/exec/format/parquet/vparquet_group_reader.cpp:190
#71 0x0000560662861c53 in doris::vectorized::RowGroupReader::_do_lazy_read (this=0x60d002e0ca10, block=0x6080025ad3a0, batch_size=992, read_rows=0x7f309f0d9d00,
    batch_eof=0x7f309f0d9b00) at /home/zcp/repo_center/doris_master/doris/be/src/vec/exec/format/parquet/vparquet_group_reader.cpp:190
#72 0x0000560662861c53 in doris::vectorized::RowGroupReader::_do_lazy_read (this=0x60d002e0ca10, block=0x6080025ad3a0, batch_size=992, read_rows=0x7f309f0d9d00,
    batch_eof=0x7f309f0d9b00) at /home/zcp/repo_center/doris_master/doris/be/src/vec/exec/format/parquet/vparquet_group_reader.cpp:190
#73 0x0000560662861c53 in doris::vectorized::RowGroupReader::_do_lazy_read (this=0x60d002e0ca10, block=0x6080025ad3a0, batch_size=992, read_rows=0x7f309f0d9d00,
```

### What You Expected?

no core

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by AshinGau** [comment]
resolved by https://github.com/apache/doris/pull/15274
