### ISSUE TITLE
[Bug] (multi-catalog) close connection when use jdbc.db which table has unsupport type

### ISSUE THREAD

**Issue by nextdreamblue** [apache/doris#15301]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

master

### What's Wrong?

when use a db of jdbc catalog, if a table of mysql has a column with the type that can not convert  to doris data type, will throw a exception and close this session

```
MySQL [test]> use jdbc.default;
Reading table information for completion of table and column names
You can turn off this feature to get a quicker startup with -A

Database changed
MySQL [jdbc.default]> show tables;
ERROR 2006 (HY000): MySQL server has gone away
No connection. Trying to reconnect...
Connection id:    1
Current database: jdbc.default

ERROR 2006 (HY000): MySQL server has gone away
No connection. Trying to reconnect...
Connection id:    2
Current database: jdbc.default

ERROR 2006 (HY000): MySQL server has gone away
MySQL [jdbc.default]> 
```

in the fe.warn.log
```
2022-12-22 21:37:07,501 WARN (mysql-nio-pool-0|228) [ReadListener.lambda$handleEvent$0():60] Exception happened in one session([remote ip: 127.0.0.1]).
com.google.common.util.concurrent.UncheckedExecutionException: org.apache.doris.external.jdbc.JdbcClientException: Can not convert mysql data type to doris data type for type [ENUM]
        at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2051) ~[spark-dpp-1.0-SNAPSHOT.jar:1.0-SNAPSHOT]
        at com.google.common.cache.LocalCache.get(LocalCache.java:3951) ~[spark-dpp-1.0-SNAPSHOT.jar:1.0-SNAPSHOT]
        at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3974) ~[spark-dpp-1.0-SNAPSHOT.jar:1.0-SNAPSHOT]
        at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4958) ~[spark-dpp-1.0-SNAPSHOT.jar:1.0-SNAPSHOT]
        at org.apache.doris.datasource.ExternalSchemaCache.getSchema(ExternalSchemaCache.java:91) ~[doris-fe.jar:1.0-SNAPSHOT]
        at org.apache.doris.catalog.external.ExternalTable.getFullSchema(ExternalTable.java:220) ~[doris-fe.jar:1.0-SNAPSHOT]
        at org.apache.doris.catalog.external.ExternalTable.getBaseSchema(ExternalTable.java:225) ~[doris-fe.jar:1.0-SNAPSHOT]
        at org.apache.doris.qe.ConnectProcessor.handleFieldList(ConnectProcessor.java:425) ~[doris-fe.jar:1.0-SNAPSHOT]
        at org.apache.doris.qe.ConnectProcessor.dispatch(ConnectProcessor.java:470) ~[doris-fe.jar:1.0-SNAPSHOT]
        at org.apache.doris.qe.ConnectProcessor.processOnce(ConnectProcessor.java:688) ~[doris-fe.jar:1.0-SNAPSHOT]
        at org.apache.doris.mysql.nio.ReadListener.lambda$handleEvent$0(ReadListener.java:52) ~[doris-fe.jar:1.0-SNAPSHOT]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_322]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_322]
        at java.lang.Thread.run(Thread.java:750) ~[?:1.8.0_322]
```

### What You Expected?

client do not close the connection with doris server.

### How to Reproduce?

create a table with some special type, for example, enum、multipoint、point、multilinestring, that can not convert  to doris data type

create catalog of jdbc, and switch jdbc and use the database has the above table.

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by nextdreamblue** [comment]
其实这个问题大概有两种解法，
一种是把所有特殊的mysql类型都转为text类型，即获取schema的时候不抛出来异常
还有一种是走COM_FIELD_LIST这个协议类型的时候，不把异常抛到最外层，不去执行mysqlChannel.close()，关闭连接

目前采用的第二种方法
