### ISSUE TITLE
[Bug] Failed to deserialize column statistics

### ISSUE THREAD

**Issue by zhouhoo** [apache/doris#15582]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

1.2.1

### What's Wrong?

When successfully upgrade from 1.1.5 to 1.2.1 and run a sql query , warning occured as bellow:
`2023-01-04 08:59:48,133 WARN (ForkJoinPool.commonPool-worker-7|10741) [StatisticsCacheLoader.lambda$asyncLoad$0():76] Failed to deserialize column statistics
java.lang.NullPointerException: null
        at org.apache.doris.statistics.util.StatisticsUtil.deserializeToColumnStatistics(StatisticsUtil.java:105) ~[doris-fe.jar:1.0-SNAPSHOT]
        at org.apache.doris.statistics.StatisticsCacheLoader.lambda$asyncLoad$0(StatisticsCacheLoader.java:74) ~[doris-fe.jar:1.0-SNAPSHOT]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590) ~[?:1.8.0_181]
        at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1582) ~[?:1.8.0_181]
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) ~[?:1.8.0_181]
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) ~[?:1.8.0_181]
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692) ~[?:1.8.0_181]
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) ~[?:1.8.0_181]

`

It seem like the StatisticsCacheLoader failed, the query result is ok but  more slow than before.

### What You Expected?

no warning

### How to Reproduce?

Every time run a nomal sql query, the warning occured.

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Kikyou1997** [comment]
I can't reproduced it, Do you sure you are using 1.2.1 instead os 1.2.0?

**Comment by zhouhoo** [comment]
selectdb-doris-1.2.0-1-caeed14 ， show backends telling this @Kikyou1997

**Comment by luguangming** [comment]
seem like https://github.com/apache/doris/issues/16672 ?
