### ISSUE TITLE
[Bug]  be dead when execute hive  catalog dml

### ISSUE THREAD

**Issue by zhengshubin** [apache/doris#16142]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

hive 3.1.3  doris 1.2.1

### What's Wrong?

I had create  hive catalog like this:
CREATE RESOURCE hms_resource PROPERTIES (
    'type'='hms',
    'hive.metastore.uris' = 'thrift://ip:9083',
    'hadoop.username' = 'web',
    'dfs.nameservices'='cluster01',
    'dfs.ha.namenodes.cluster01'='nn1,nn2',
    'dfs.namenode.rpc-address.cluster01.nn1'='ip:8020',
    'dfs.namenode.rpc-address.cluster01.nn2'='ip:8020',
    'dfs.client.failover.proxy.provider.cluster01'='org.apache.hadoop.hdfs.server.namenode.ha.ConfiguredFailoverProxyProvider'
);
CREATE CATALOG hive WITH RESOURCE hms_resource;
use hive.`default`;
When I use  like show tables,it work. But when I use dml like :
SELECT count(1) FROM ms_3; 
The one of the  be would dead.
FE.WARN.log  : 
2023-01-26 14:36:15,089 WARN (heartbeat-mgr-pool-0|102) [HeartbeatMgr$BackendHeartbeatHandler.call():268] backend heartbeat got exception
org.apache.thrift.transport.TTransportException: java.net.SocketTimeoutException: Read timed out
        at org.apache.thrift.transport.TIOStreamTransport.read(TIOStreamTransport.java:127) ~[spark-dpp-1.0-SNAPSHOT.jar:1.0-SNAPSHOT]
        at org.apache.thrift.transport.TTransport.readAll(TTransport.java:86) ~[spark-dpp-1.0-SNAPSHOT.jar:1.0-SNAPSHOT]
        at org.apache.thrift.protocol.TBinaryProtocol.readAll(TBinaryProtocol.java:455) ~[spark-dpp-1.0-SNAPSHOT.jar:1.0-SNAPSHOT]
        at org.apache.thrift.protocol.TBinaryProtocol.readI32(TBinaryProtocol.java:354) ~[spark-dpp-1.0-SNAPSHOT.jar:1.0-SNAPSHOT]
        at org.apache.thrift.protocol.TBinaryProtocol.readMessageBegin(TBinaryProtocol.java:243) ~[spark-dpp-1.0-SNAPSHOT.jar:1.0-SNAPSHOT]
        at org.apache.thrift.TServiceClient.receiveBase(TServiceClient.java:77) ~[spark-dpp-1.0-SNAPSHOT.jar:1.0-SNAPSHOT]
        at org.apache.doris.thrift.HeartbeatService$Client.recvHeartbeat(HeartbeatService.java:61) ~[spark-dpp-1.0-SNAPSHOT.jar:1.0-SNAPSHOT]
        at org.apache.doris.thrift.HeartbeatService$Client.heartbeat(HeartbeatService.java:48) ~[spark-dpp-1.0-SNAPSHOT.jar:1.0-SNAPSHOT]
        at org.apache.doris.system.HeartbeatMgr$BackendHeartbeatHandler.call(HeartbeatMgr.java:226) ~[doris-fe.jar:1.0-SNAPSHOT]
        at org.apache.doris.system.HeartbeatMgr$BackendHeartbeatHandler.call(HeartbeatMgr.java:203) ~[doris-fe.jar:1.0-SNAPSHOT]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_282]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_282]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_282]
        at java.lang.Thread.run(Thread.java:748) ~[?:1.8.0_282]
Caused by: java.net.SocketTimeoutException: Read timed out
        at java.net.SocketInputStream.socketRead0(Native Method) ~[?:1.8.0_282]
        at java.net.SocketInputStream.socketRead(SocketInputStream.java:116) ~[?:1.8.0_282]
        at java.net.SocketInputStream.read(SocketInputStream.java:171) ~[?:1.8.0_282]
        at java.net.SocketInputStream.read(SocketInputStream.java:141) ~[?:1.8.0_282]
        at java.io.BufferedInputStream.fill(BufferedInputStream.java:246) ~[?:1.8.0_282]
        at java.io.BufferedInputStream.read1(BufferedInputStream.java:286) ~[?:1.8.0_282]
        at java.io.BufferedInputStream.read(BufferedInputStream.java:345) ~[?:1.8.0_282]
        at org.apache.thrift.transport.TIOStreamTransport.read(TIOStreamTransport.java:125) ~[spark-dpp-1.0-SNAPSHOT.jar:1.0-SNAPSHOT]
        ... 13 more
2023-01-26 14:36:15,092 WARN (heartbeat mgr|31) [HeartbeatMgr.runAfterCatalogReady():139] get bad heartbeat response: type: BACKEND, status: BAD, msg: java.net.SocketTimeoutException: Read timed out, beId: 16006, beHost: 1.2.3.4, bePort: 0, httpPort: 0, brpcPort: 0
2023-01-26 14:36:28,166 WARN (ForkJoinPool-2-worker-11|218959) [TabletStatMgr.lambda$null$0():70] task exec error. backend[16006]
org.apache.thrift.transport.TTransportException: java.net.SocketException: Connection reset
        at org.apache.thrift.transport.TIOStreamTransport.read(TIOStreamTransport.java:127) ~[spark-dpp-1.0-SNAPSHOT.jar:1.0-SNAPSHOT]
        at org.apache.thrift.transport.TTransport.readAll(TTransport.java:86) ~[spark-dpp-1.0-SNAPSHOT.jar:1.0-SNAPSHOT]
        at org.apache.thrift.protocol.TBinaryProtocol.readAll(TBinaryProtocol.java:455) ~[spark-dpp-1.0-SNAPSHOT.jar:1.0-SNAPSHOT]
        at org.apache.thrift.protocol.TBinaryProtocol.readI32(TBinaryProtocol.java:354) ~[spark-dpp-1.0-SNAPSHOT.jar:1.0-SNAPSHOT]
        at org.apache.thrift.protocol.TBinaryProtocol.readMessageBegin(TBinaryProtocol.java:243) ~[spark-dpp-1.0-SNAPSHOT.jar:1.0-SNAPSHOT]
        at org.apache.thrift.TServiceClient.receiveBase(TServiceClient.java:77) ~[spark-dpp-1.0-SNAPSHOT.jar:1.0-SNAPSHOT]
        at org.apache.doris.thrift.BackendService$Client.recvGetTabletStat(BackendService.java:393) ~[spark-dpp-1.0-SNAPSHOT.jar:1.0-SNAPSHOT]
        at org.apache.doris.thrift.BackendService$Client.getTabletStat(BackendService.java:381) ~[spark-dpp-1.0-SNAPSHOT.jar:1.0-SNAPSHOT]
        at org.apache.doris.catalog.TabletStatMgr.lambda$null$0(TabletStatMgr.java:64) ~[doris-fe.jar:1.0-SNAPSHOT]
        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) ~[?:1.8.0_282]
        at com.google.common.collect.CollectSpliterators$1WithCharacteristics.lambda$forEachRemaining$1(CollectSpliterators.java:67) ~[spark-dpp-1.0-SNAPSHOT.jar:1.0-SNAPSHOT]
        at java.util.stream.Streams$RangeIntSpliterator.forEachRemaining(Streams.java:110) ~[?:1.8.0_282]
        at com.google.common.collect.CollectSpliterators$1WithCharacteristics.forEachRemaining(CollectSpliterators.java:67) ~[spark-dpp-1.0-SNAPSHOT.jar:1.0-SNAPSHOT]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482) ~[?:1.8.0_282]
        at java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:290) ~[?:1.8.0_282]
        at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731) ~[?:1.8.0_282]
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) ~[?:1.8.0_282]
        at java.util.concurrent.ForkJoinTask.doInvoke(ForkJoinTask.java:401) ~[?:1.8.0_282]
        at java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:734) ~[?:1.8.0_282]
        at java.util.stream.ForEachOps$ForEachOp.evaluateParallel(ForEachOps.java:159) ~[?:1.8.0_282]
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateParallel(ForEachOps.java:173) ~[?:1.8.0_282]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:233) ~[?:1.8.0_282]
        at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:485) ~[?:1.8.0_282]
        at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:650) ~[?:1.8.0_282]
        at org.apache.doris.catalog.TabletStatMgr.lambda$runAfterCatalogReady$1(TabletStatMgr.java:57) ~[doris-fe.jar:1.0-SNAPSHOT]
        at java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1386) ~[?:1.8.0_282]
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) ~[?:1.8.0_282]
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) ~[?:1.8.0_282]
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692) ~[?:1.8.0_282]
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:175) ~[?:1.8.0_282]
Caused by: java.net.SocketException: Connection reset
        at java.net.SocketInputStream.read(SocketInputStream.java:210) ~[?:1.8.0_282]
        at java.net.SocketInputStream.read(SocketInputStream.java:141) ~[?:1.8.0_282]
        at java.io.BufferedInputStream.fill(BufferedInputStream.java:246) ~[?:1.8.0_282]
        at java.io.BufferedInputStream.read1(BufferedInputStream.java:286) ~[?:1.8.0_282]
        at java.io.BufferedInputStream.read(BufferedInputStream.java:345) ~[?:1.8.0_282]
        at org.apache.thrift.transport.TIOStreamTransport.read(TIOStreamTransport.java:125) ~[spark-dpp-1.0-SNAPSHOT.jar:1.0-SNAPSHOT]
        ... 29 more
2023-01-26 14:36:28,171 WARN (mysql-nio-pool-20|218966) [ResultReceiver.getNext():126] fetch result execution exception, finstId=hi: 3682082794844733810
lo: -7866955055177896462

java.util.concurrent.ExecutionException: io.grpc.StatusRuntimeException: UNAVAILABLE: Network closed for unknown reason
        at com.google.common.util.concurrent.AbstractFuture.getDoneValue(AbstractFuture.java:564) ~[spark-dpp-1.0-SNAPSHOT.jar:1.0-SNAPSHOT]
        at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:443) ~[spark-dpp-1.0-SNAPSHOT.jar:1.0-SNAPSHOT]
        at org.apache.doris.qe.ResultReceiver.getNext(ResultReceiver.java:80) ~[doris-fe.jar:1.0-SNAPSHOT]
        at org.apache.doris.qe.Coordinator.getNext(Coordinator.java:889) ~[doris-fe.jar:1.0-SNAPSHOT]
        at org.apache.doris.qe.StmtExecutor.sendResult(StmtExecutor.java:1154) ~[doris-fe.jar:1.0-SNAPSHOT]
        at org.apache.doris.qe.StmtExecutor.handleQueryStmt(StmtExecutor.java:1120) ~[doris-fe.jar:1.0-SNAPSHOT]
        at org.apache.doris.qe.StmtExecutor.execute(StmtExecutor.java:520) ~[doris-fe.jar:1.0-SNAPSHOT]
        at org.apache.doris.qe.StmtExecutor.execute(StmtExecutor.java:407) ~[doris-fe.jar:1.0-SNAPSHOT]
        at org.apache.doris.qe.ConnectProcessor.handleQuery(ConnectProcessor.java:322) ~[doris-fe.jar:1.0-SNAPSHOT]
        at org.apache.doris.qe.ConnectProcessor.dispatch(ConnectProcessor.java:463) ~[doris-fe.jar:1.0-SNAPSHOT]
        at org.apache.doris.qe.ConnectProcessor.processOnce(ConnectProcessor.java:690) ~[doris-fe.jar:1.0-SNAPSHOT]
        at org.apache.doris.mysql.nio.ReadListener.lambda$handleEvent$0(ReadListener.java:52) ~[doris-fe.jar:1.0-SNAPSHOT]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_282]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_282]
        at java.lang.Thread.run(Thread.java:748) ~[?:1.8.0_282]
Caused by: io.grpc.StatusRuntimeException: UNAVAILABLE: Network closed for unknown reason
        at io.grpc.Status.asRuntimeException(Status.java:533) ~[grpc-api-1.30.0.jar:1.30.0]
        at io.grpc.stub.ClientCalls$UnaryStreamToFuture.onClose(ClientCalls.java:515) ~[grpc-stub-1.30.0.jar:1.30.0]
        at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:426) ~[grpc-core-1.30.0.jar:1.30.0]
        at io.grpc.internal.ClientCallImpl.access$500(ClientCallImpl.java:66) ~[grpc-core-1.30.0.jar:1.30.0]
        at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.close(ClientCallImpl.java:689) ~[grpc-core-1.30.0.jar:1.30.0]
        at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.access$900(ClientCallImpl.java:577) ~[grpc-core-1.30.0.jar:1.30.0]
        at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:751) ~[grpc-core-1.30.0.jar:1.30.0]
        at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:740) ~[grpc-core-1.30.0.jar:1.30.0]
        at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37) ~[grpc-core-1.30.0.jar:1.30.0]
        at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123) ~[grpc-core-1.30.0.jar:1.30.0]
        ... 3 more

### What You Expected?

 BE don't dead whether  hive catalog dml  execute successfully or not 

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by lorenking** [comment]
问题解决了吗？我也是一样的问题，我的doris版本是1.2，执行 查询就报错：
ERROR 1105 (HY000): errCode = 2, detailMessage = failed to init reader for file /usr/hive/warehouse/ads_dev.db/ads_wms_count/data_dt=2021-01/000000_0, err: Seek to offset failed. (BE: 192.168.21.24) offset=3, err: (errno: 22) Invalid argument

而且我的 show create catalog hive；命令执行就报错
![image](https://github.com/apache/doris/assets/12979103/45d9bcd0-317f-4c20-8d42-e778c84bb83e)
