### ISSUE TITLE
[Bug] execute count from table, Unknown database 'default_cluster:__internal_schema'

### ISSUE THREAD

**Issue by luguangming** [apache/doris#16426]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

1.2.0

### What's Wrong?

execute sql : select count(*) from table, we can see fe.log :

2023-02-06 10:23:38,370 WARN (ForkJoinPool.commonPool-worker-5|57515) [StmtExecutor.executeInternalQuery():1799] Internal SQL execution failed, SQL: org.apache.doris.qe.OriginStatement@6eca8c46
org.apache.doris.common.AnalysisException: errCode = 2, detailMessage = Unknown database 'default_cluster:__internal_schema'
	at org.apache.doris.datasource.CatalogIf.lambda$getDbOrAnalysisException$4(CatalogIf.java:107) ~[doris-fe.jar:1.0-SNAPSHOT]
	at org.apache.doris.datasource.CatalogIf.getDbOrException(CatalogIf.java:72) ~[doris-fe.jar:1.0-SNAPSHOT]
	at org.apache.doris.datasource.CatalogIf.getDbOrAnalysisException(CatalogIf.java:106) ~[doris-fe.jar:1.0-SNAPSHOT]
	at org.apache.doris.analysis.SelectStmt.getTables(SelectStmt.java:322) ~[doris-fe.jar:1.0-SNAPSHOT]
	at org.apache.doris.qe.StmtExecutor.analyze(StmtExecutor.java:702) ~[doris-fe.jar:1.0-SNAPSHOT]
	at org.apache.doris.qe.StmtExecutor.executeInternalQuery(StmtExecutor.java:1797) ~[doris-fe.jar:1.0-SNAPSHOT]
	at org.apache.doris.statistics.util.StatisticsUtil.execStatisticQuery(StatisticsUtil.java:84) ~[doris-fe.jar:1.0-SNAPSHOT]
	at org.apache.doris.statistics.StatisticsCacheLoader.lambda$asyncLoad$0(StatisticsCacheLoader.java:69) ~[doris-fe.jar:1.0-SNAPSHOT]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1604) ~[?:1.8.0_332]
	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1596) ~[?:1.8.0_332]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) ~[?:1.8.0_332]
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) ~[?:1.8.0_332]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692) ~[?:1.8.0_332]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:175) ~[?:1.8.0_332]
2023-02-06 10:23:38,370 WARN (ForkJoinPool.commonPool-worker-5|57515) [StatisticsCacheLoader.lambda$asyncLoad$0():75] Failed to deserialize column statistics
java.lang.NullPointerException: null
	at org.apache.doris.statistics.util.StatisticsUtil.deserializeToColumnStatistics(StatisticsUtil.java:105) ~[doris-fe.jar:1.0-SNAPSHOT]
	at org.apache.doris.statistics.StatisticsCacheLoader.lambda$asyncLoad$0(StatisticsCacheLoader.java:73) ~[doris-fe.jar:1.0-SNAPSHOT]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1604) ~[?:1.8.0_332]
	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1596) ~[?:1.8.0_332]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) ~[?:1.8.0_332]
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) ~[?:1.8.0_332]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692) ~[?:1.8.0_332]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:175) ~[?:1.8.0_332]

### What You Expected?

I can't find the database 'default_cluster:__internal_schema'. When was it created,  Why do we not have an 'enable_statistic_collect' statistic switch similar to starrocks?

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by stalary** [comment]
What tool did you use to connect doris?

**Comment by luguangming** [comment]
Mysql client or fe http request

**Comment by luguangming** [comment]
> What tool did you use to connect doris?

Mysql client and fe http request

**Comment by luguangming** [comment]
Why we disable statistic tables at version 1.2.0?

**Comment by luguangming** [comment]
[stalary](https://github.com/stalary)
Why is this list closed
