### ISSUE TITLE
[Bug] Doris 1.1.4 all FE nodes restart failed due to there is a NullPointerException when executing loadJournal

### ISSUE THREAD

**Issue by lide-reed** [apache/doris#16604]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

Doris 1.1.4  commit number: 408db56

### What's Wrong?

FE cannot startup and the log as following:

`2023-02-09 20:24:22,050 INFO (stateListener|67) [Partition.visualiseShadowIndex():294] visualise the shadow index: 90072650
2023-02-09 20:24:22,050 ERROR (stateListener|67) [EditLog.loadJournal():828] Operation Type 121
java.lang.NullPointerException: null
        at org.apache.doris.catalog.OlapTable.renameIndexForSchemaChange(OlapTable.java:413) ~[doris-fe.jar:1.0-SNAPSHOT]
        at org.apache.doris.alter.SchemaChangeJobV2.onFinished(SchemaChangeJobV2.java:559) ~[doris-fe.jar:1.0-SNAPSHOT]
        at org.apache.doris.alter.SchemaChangeJobV2.replayRunningJob(SchemaChangeJobV2.java:720) ~[doris-fe.jar:1.0-SNAPSHOT]
        at org.apache.doris.alter.SchemaChangeJobV2.replay(SchemaChangeJobV2.java:755) ~[doris-fe.jar:1.0-SNAPSHOT]
        at org.apache.doris.alter.AlterHandler.replayAlterJobV2(AlterHandler.java:250) ~[doris-fe.jar:1.0-SNAPSHOT]
        at org.apache.doris.alter.SchemaChangeHandler.replayAlterJobV2(SchemaChangeHandler.java:1913) ~[doris-fe.jar:1.0-SNAPSHOT]
        at org.apache.doris.persist.EditLog.loadJournal(EditLog.java:702) ~[doris-fe.jar:1.0-SNAPSHOT]
        at org.apache.doris.catalog.Catalog.replayJournal(Catalog.java:2458) ~[doris-fe.jar:1.0-SNAPSHOT]
        at org.apache.doris.catalog.Catalog.transferToMaster(Catalog.java:1262) ~[doris-fe.jar:1.0-SNAPSHOT]
        at org.apache.doris.catalog.Catalog.access$1200(Catalog.java:300) ~[doris-fe.jar:1.0-SNAPSHOT]
        at org.apache.doris.catalog.Catalog$4.runOneCycle(Catalog.java:2375) ~[doris-fe.jar:1.0-SNAPSHOT]
        at org.apache.doris.common.util.Daemon.run(Daemon.java:116) ~[doris-fe.jar:1.0-SNAPSHOT]`

### What You Expected?

FE start successfully

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by lide-reed** [comment]
we found alter table statement in audit log:
alter table xxx add column c1 varchar(1000) not null default '' comment '';

**Comment by lide-reed** [comment]
It start successfully after made following patch:

`diff --git a/fe/fe-core/src/main/java/org/apache/doris/catalog/OlapTable.java b/fe/fe-core/src/main/java/org/apache/doris/catalog/OlapTable.java
index 60d8c3337..a4f13776b 100644
--- a/fe/fe-core/src/main/java/org/apache/doris/catalog/OlapTable.java
+++ b/fe/fe-core/src/main/java/org/apache/doris/catalog/OlapTable.java
@@ -410,8 +410,11 @@ public class OlapTable extends Table {
 
     // this is only for schema change.
     public void renameIndexForSchemaChange(String name, String newName) {
-        long idxId = indexNameToId.remove(name);
-        indexNameToId.put(newName, idxId);
+       if (indexNameToId != null && name != null) {
+            long idxId = indexNameToId.remove(name);
+            indexNameToId.put(newName, idxId);
+       }
+       LOG.info("indexNameToId="+ indexNameToId + ",name=" + name);
     }
 
     public void renameColumnNamePrefix(long idxId) {`

**Comment by lide-reed** [comment]
There is a log as following when FE started up successfully 
fe.log:431538:2023-02-10 14:30:43,569 INFO (leaderCheckpointer|68) [OlapTable.renameIndexForSchemaChange():417] indexNameToId={__doris_shadow_cdp_behavior_stat_user=90072723},name=null

**Comment by lide-reed** [comment]
@nextdreamblue
