### ISSUE TITLE
[Bug] java.lang.OutOfMemoryError: Compressed class space

### ISSUE THREAD

**Issue by gojumprope** [apache/doris#16683]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

1.2.1

### What's Wrong?

start time: Mon Feb 13 01:02:49 UTC 2023
start time: Mon Feb 13 02:12:43 UTC 2023
OpenJDK 64-Bit Server VM warning: CodeCache is full. Compiler has been disabled.
OpenJDK 64-Bit Server VM warning: Try increasing the code cache size using -XX:ReservedCodeCacheSize=
CodeCache: size=245760Kb used=242720Kb max_used=242735Kb free=3040Kb
 bounds [0x00007f443467f000, 0x00007f444367f000, 0x00007f444367f000]
 total_blobs=92728 nmethods=92227 adapters=408
 compilation: disabled (not enough contiguous free space left)
04:04:11.021 [Thread-17] ERROR com.zaxxer.hikari.pool.HikariPool - HikariPool-1669 - Error thrown while acquiring connection from data source
com.microsoft.sqlserver.jdbc.SQLServerException: The connection is closed.
        at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDriverError(SQLServerException.java:237) ~[1414212399189005683.5d53b0cb64ec2e5268a5f7a349889d35.jar:?]
        at com.microsoft.sqlserver.jdbc.SQLServerConnection.checkClosed(SQLServerConnection.java:1555) ~[1414212399189005683.5d53b0cb64ec2e5268a5f7a349889d35.jar:?]
        at com.microsoft.sqlserver.jdbc.SQLServerConnection.setTransactionIsolation(SQLServerConnection.java:4424) ~[1414212399189005683.5d53b0cb64ec2e5268a5f7a349889d35.jar:?]
        at com.zaxxer.hikari.pool.PoolBase.setupConnection(PoolBase.java:413) ~[java-udf-jar-with-dependencies.jar:?]
        at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:363) ~[java-udf-jar-with-dependencies.jar:?]
        at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:206) ~[java-udf-jar-with-dependencies.jar:?]
        at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:477) ~[java-udf-jar-with-dependencies.jar:?]
        at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:560) ~[java-udf-jar-with-dependencies.jar:?]
        at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:115) ~[java-udf-jar-with-dependencies.jar:?]
        at com.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:81) ~[java-udf-jar-with-dependencies.jar:?]
        at org.apache.doris.udf.JdbcExecutor.init(JdbcExecutor.java:229) ~[java-udf-jar-with-dependencies.jar:?]
        at org.apache.doris.udf.JdbcExecutor.<init>(JdbcExecutor.java:66) ~[java-udf-jar-with-dependencies.jar:?]
04:04:11.040 [Thread-17] ERROR com.zaxxer.hikari.pool.HikariPool - HikariPool-1669 - Exception during pool initialization.
com.microsoft.sqlserver.jdbc.SQLServerException: The connection is closed.
        at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDriverError(SQLServerException.java:237) ~[1414212399189005683.5d53b0cb64ec2e5268a5f7a349889d35.jar:?]
        at com.microsoft.sqlserver.jdbc.SQLServerConnection.checkClosed(SQLServerConnection.java:1555) ~[1414212399189005683.5d53b0cb64ec2e5268a5f7a349889d35.jar:?]
        at com.microsoft.sqlserver.jdbc.SQLServerConnection.setTransactionIsolation(SQLServerConnection.java:4424) ~[1414212399189005683.5d53b0cb64ec2e5268a5f7a349889d35.jar:?]
        at com.zaxxer.hikari.pool.PoolBase.setupConnection(PoolBase.java:413) ~[java-udf-jar-with-dependencies.jar:?]
        at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:363) ~[java-udf-jar-with-dependencies.jar:?]
        at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:206) ~[java-udf-jar-with-dependencies.jar:?]
        at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:477) ~[java-udf-jar-with-dependencies.jar:?]
        at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:560) ~[java-udf-jar-with-dependencies.jar:?]
        at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:115) ~[java-udf-jar-with-dependencies.jar:?]
        at com.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:81) ~[java-udf-jar-with-dependencies.jar:?]
        at org.apache.doris.udf.JdbcExecutor.init(JdbcExecutor.java:229) ~[java-udf-jar-with-dependencies.jar:?]
        at org.apache.doris.udf.JdbcExecutor.<init>(JdbcExecutor.java:66) ~[java-udf-jar-with-dependencies.jar:?]
13:26:40.345 [Thread-113] ERROR com.zaxxer.hikari.pool.PoolBase - HikariPool-6143 - Failed to execute isValid() for connection, configure connection test query (Self-suppression not permitted).
13:26:45.987 [Thread-113] ERROR com.zaxxer.hikari.pool.HikariPool - HikariPool-6143 - Exception during pool initialization.
java.lang.IllegalArgumentException: Self-suppression not permitted
        at java.lang.Throwable.addSuppressed(Throwable.java:1072) ~[?:1.8.0_352]
        at com.microsoft.sqlserver.jdbc.SQLServerConnection.isValid(SQLServerConnection.java:6863) ~[8890365683452405163.5d53b0cb64ec2e5268a5f7a349889d35.jar:?]
        at com.zaxxer.hikari.pool.PoolBase.checkValidationSupport(PoolBase.java:458) ~[java-udf-jar-with-dependencies.jar:?]
        at com.zaxxer.hikari.pool.PoolBase.checkDriverSupport(PoolBase.java:441) ~[java-udf-jar-with-dependencies.jar:?]
        at com.zaxxer.hikari.pool.PoolBase.setupConnection(PoolBase.java:410) ~[java-udf-jar-with-dependencies.jar:?]
        at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:363) ~[java-udf-jar-with-dependencies.jar:?]
        at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:206) ~[java-udf-jar-with-dependencies.jar:?]
        at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:477) ~[java-udf-jar-with-dependencies.jar:?]
        at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:560) ~[java-udf-jar-with-dependencies.jar:?]
        at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:115) ~[java-udf-jar-with-dependencies.jar:?]
        at com.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:81) ~[java-udf-jar-with-dependencies.jar:?]
        at org.apache.doris.udf.JdbcExecutor.init(JdbcExecutor.java:229) ~[java-udf-jar-with-dependencies.jar:?]
        at org.apache.doris.udf.JdbcExecutor.<init>(JdbcExecutor.java:66) ~[java-udf-jar-with-dependencies.jar:?]
Caused by: java.lang.OutOfMemoryError: Compressed class space
13:26:55.990 [Thread-18] ERROR com.zaxxer.hikari.pool.PoolBase - HikariPool-6145 - Failed to execute isValid() for connection, configure connection test query (Self-suppression not permitted).
13:27:03.231 [Thread-18] ERROR com.zaxxer.hikari.pool.HikariPool - HikariPool-6145 - Exception during pool initialization.
java.lang.IllegalArgumentException: Self-suppression not permitted
        at java.lang.Throwable.addSuppressed(Throwable.java:1072) ~[?:1.8.0_352]
        at com.microsoft.sqlserver.jdbc.SQLServerConnection.isValid(SQLServerConnection.java:6863) ~[8890365683452405163.5d53b0cb64ec2e5268a5f7a349889d35.jar:?]
        at com.zaxxer.hikari.pool.PoolBase.checkValidationSupport(PoolBase.java:458) ~[java-udf-jar-with-dependencies.jar:?]
        at com.zaxxer.hikari.pool.PoolBase.checkDriverSupport(PoolBase.java:441) ~[java-udf-jar-with-dependencies.jar:?]
        at com.zaxxer.hikari.pool.PoolBase.setupConnection(PoolBase.java:410) ~[java-udf-jar-with-dependencies.jar:?]
        at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:363) ~[java-udf-jar-with-dependencies.jar:?]
        at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:206) ~[java-udf-jar-with-dependencies.jar:?]
        at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:477) ~[java-udf-jar-with-dependencies.jar:?]
        at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:560) ~[java-udf-jar-with-dependencies.jar:?]
        at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:115) ~[java-udf-jar-with-dependencies.jar:?]
        at com.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:81) ~[java-udf-jar-with-dependencies.jar:?]
        at org.apache.doris.udf.JdbcExecutor.init(JdbcExecutor.java:229) ~[java-udf-jar-with-dependencies.jar:?]
        at org.apache.doris.udf.JdbcExecutor.<init>(JdbcExecutor.java:66) ~[java-udf-jar-with-dependencies.jar:?]
Caused by: java.lang.OutOfMemoryError: Compressed class space

### What You Expected?

Cache should be flushed/cleared after full and memory should not leak

after restart backend, everything is okay, should be memory leak when query external jdbc table (SQL Server)

### How to Reproduce?

query external jdbc table (sql server)

### Anything Else?

jvm settings: 
JAVA_OPTS="-Xmx8G -XX:+UseMembar -XX:SurvivorRatio=8 -XX:MaxTenuringThreshold=7 -XX:+PrintGCDateStamps -XX:+PrintGCDetails -XX:+UseConcMarkSweepGC -XX:+UseParNewGC -XX:+CMSClassUnloadingEnabled -XX:-CMSParallelRemarkEnabled -XX:CMSInitiatingOccupancyFraction=80 -XX:SoftRefLRUPolicyMSPerMB=0 -Xloggc:$DORIS_HOME/log/fe.gc.log.$DATE"

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zhangstar333** [comment]
the jdbc about memory will be leak before, we have refactored it in master
