### ISSUE TITLE
[Bug] Label Already Exists

### ISSUE THREAD

**Issue by kaybinwong** [apache/doris#17572]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

1.2.2

### What's Wrong?

after flink(1.14.3) restart, error occurs.

```
2023-03-08 19:17:37,474 INFO  org.apache.doris.flink.sink.writer.DorisStreamLoad           [] - load Result {
    "TxnId": -1,
    "Label": "doris_dev_user_1_23",
    "TwoPhaseCommit": "true",
    "Status": "Label Already Exists",
    "ExistingJobStatus": "FINISHED",
    "Message": "errCode = 2, detailMessage = Label [doris_dev_user_1_23] has already been used, relate to txn [50985]",
    "NumberTotalRows": 0,
    "NumberLoadedRows": 0,
    "NumberFilteredRows": 0,
    "NumberUnselectedRows": 0,
    "LoadBytes": 0,
    "LoadTimeMs": 0,
    "BeginTxnTimeMs": 0,
    "StreamLoadPutTimeMs": 0,
    "ReadDataTimeMs": 0,
    "WriteDataTimeMs": 0,
    "CommitAndPublishTimeMs": 0
}

2023-03-08 19:17:37,474 WARN  org.apache.doris.flink.sink.writer.DorisStreamLoad           [] - failed to stream load data
org.apache.doris.flink.exception.DorisException: Load status is Label Already Exists and load job finished, change you label prefix or restore from latest savepoint!
        at org.apache.doris.flink.sink.writer.DorisStreamLoad.abortPreCommit(DorisStreamLoad.java:154) ~[flink-doris-connector-1.14_2.12-1.1.1.jar:1.1.1]
        at org.apache.doris.flink.sink.writer.DorisWriter.initializeLoad(DorisWriter.java:112) ~[flink-doris-connector-1.14_2.12-1.1.1.jar:1.1.1]
        at org.apache.doris.flink.sink.DorisSink.createWriter(DorisSink.java:64) ~[flink-doris-connector-1.14_2.12-1.1.1.jar:1.1.1]
        at org.apache.flink.streaming.runtime.operators.sink.SinkOperator.initializeState(SinkOperator.java:145) ~[flink-dist_2.12-1.14.3.jar:1.14.3]
        at org.apache.flink.streaming.api.operators.StreamOperatorStateHandler.initializeOperatorState(StreamOperatorStateHandler.java:119) ~[flink-dist_2.12-1.14.3.jar:1.14.3]
        at org.apache.flink.streaming.api.operators.AbstractStreamOperator.initializeState(AbstractStreamOperator.java:286) ~[flink-dist_2.12-1.14.3.jar:1.14.3]
        at org.apache.flink.streaming.runtime.tasks.RegularOperatorChain.initializeStateAndOpenOperators(RegularOperatorChain.java:109) ~[flink-dist_2.12-1.14.3.jar:1.14.3]
        at org.apache.flink.streaming.runtime.tasks.StreamTask.restoreGates(StreamTask.java:711) ~[flink-dist_2.12-1.14.3.jar:1.14.3]
        at org.apache.flink.streaming.runtime.tasks.StreamTaskActionExecutor$1.call(StreamTaskActionExecutor.java:55) ~[flink-dist_2.12-1.14.3.jar:1.14.3]
        at org.apache.flink.streaming.runtime.tasks.StreamTask.restoreInternal(StreamTask.java:687) ~[flink-dist_2.12-1.14.3.jar:1.14.3]
        at org.apache.flink.streaming.runtime.tasks.StreamTask.restore(StreamTask.java:654) ~[flink-dist_2.12-1.14.3.jar:1.14.3]
        at org.apache.flink.runtime.taskmanager.Task.runWithSystemExitMonitoring(Task.java:958) [flink-dist_2.12-1.14.3.jar:1.14.3]
        at org.apache.flink.runtime.taskmanager.Task.restoreAndInvoke(Task.java:927) [flink-dist_2.12-1.14.3.jar:1.14.3]
        at org.apache.flink.runtime.taskmanager.Task.doRun(Task.java:766) [flink-dist_2.12-1.14.3.jar:1.14.3]
        at org.apache.flink.runtime.taskmanager.Task.run(Task.java:575) [flink-dist_2.12-1.14.3.jar:1.14.3]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_291]
2023-03-08 19:17:37,474 INFO  org.apache.flink.connector.base.source.reader.SourceReaderBase [] - Closing Source Reader.
```
but actually, there is no lable in doris.
![image](https://user-images.githubusercontent.com/5570216/223701428-1a67c510-1ffa-4c67-b25e-69c3f8bf592d.png)

bug or something done wrong?

### What You Expected?

without exception after flink restart

### How to Reproduce?

```

-- create source table
CREATE TABLE `user` (
    `id` int,
    `country_code` varchar(8) NOT NULL,
    `mobile_number` varchar(16) NOT NULL,
    `email` varchar(128) NOT NULL,
    `login_pword` varchar(225) NOT NULL,
    `capital_pword` varchar(64) NOT NULL,
    `auth_type` tinyint NOT NULL,
    `auth_level` tinyint NOT NULL,
    `nickname` varchar(256) NOT NULL,
    `login_status` tinyint NOT NULL,
    `loginexpire_time` TIMESTAMP NOT NULL,
    `exc_status` tinyint NOT NULL,
    `excexpire_time` TIMESTAMP NOT NULL,
    `withdraw_status` tinyint NOT NULL,
    `withdrawexpire_time` TIMESTAMP NOT NULL,
    `lockexpire_time` TIMESTAMP NOT NULL,
    `ctime` TIMESTAMP NOT NULL,
    `mtime` TIMESTAMP NOT NULL,
    `realname_time` TIMESTAMP NOT NULL,
    `certificate_time` TIMESTAMP NOT NULL,
    `last_login_time` TIMESTAMP NOT NULL ,
    `google_authenticator_status` tinyint NOT NULL,
    `google_authenticator_key` varchar(1000) NOT NULL,
    `mobile_authenticator_status` tinyint NOT NULL,
    `user_type` smallint NOT NULL,
    `channel_id` varchar(64) NOT NULL,
    PRIMARY KEY (`id`) NOT ENFORCED
)
WITH (
    'connector' = 'mysql-cdc',
    'hostname' = 'sqlhost',
    'port' = '3307',
    'username' = '',
    'password' = '',
    'database-name' = 'db',
    'table-name' = 'user'
);

-- create target table
CREATE TABLE user_sink (
    `id` int,
    `country_code` varchar(8) NOT NULL,
    `mobile_number` varchar(16) NOT NULL,
    `email` varchar(128) NOT NULL,
    `login_pword` varchar(225) NOT NULL,
    `capital_pword` varchar(64) NOT NULL,
    `auth_type` tinyint NOT NULL,
    `auth_level` tinyint NOT NULL,
    `nickname` varchar(256) NOT NULL,
    `login_status` tinyint NOT NULL,
    `loginexpire_time` TIMESTAMP NOT NULL,
    `exc_status` tinyint NOT NULL,
    `excexpire_time` TIMESTAMP NOT NULL,
    `withdraw_status` tinyint NOT NULL,
    `withdrawexpire_time` TIMESTAMP NOT NULL,
    `lockexpire_time` TIMESTAMP NOT NULL,
    `ctime` TIMESTAMP NOT NULL,
    `mtime` TIMESTAMP NOT NULL,
    `realname_time` TIMESTAMP NOT NULL,
    `certificate_time` TIMESTAMP NOT NULL,
    `last_login_time` TIMESTAMP NOT NULL ,
    `google_authenticator_status` tinyint NOT NULL,
    `google_authenticator_key` varchar(1000) NOT NULL,
    `mobile_authenticator_status` tinyint NOT NULL,
    `user_type` smallint NOT NULL,
    `channel_id` varchar(64) NOT NULL
) 
WITH (
    'connector' = 'doris',
    'fenodes' = 'doris:8030',
    'table.identifier' = 'cdc_dev.user',
    'username' = 'root',
    'password' = '',
    'sink.properties.two_phase_commit'='true',
    'sink.label-prefix'='doris_dev_user'
);
-- insert datas into target table
insert into user_sink select * from `user`;
```

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by yuanyuan8983** [comment]
The underlying method of Flink Doris Connector is streamload, so to view streamload, you need to set a parameter in be.conf: enable_ stream_ load_ Record=true, the record of stream load will be displayed. You can add me WeChat to see: cylly810222
