### ISSUE TITLE
[Bug] ClickHouse Catalog report “NoClassDefFoundError: com/mysql/jdbc/StringUtils”

### ISSUE THREAD

**Issue by pigstomach** [apache/doris#17614]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

Apache Doris 1.2.2

### What's Wrong?

When I create a clickhouse catalog and use it, I get an error if I execute the "select * from user" statement。
Error：

```
mysql> select * from user;
ERROR 1105 (HY000): errCode = 2, detailMessage = NoClassDefFoundError: com/mysql/jdbc/StringUtils
```

```
W0309 17:18:20.193675 49040 jni-util.cpp:193] java.lang.NoClassDefFoundError: com/mysql/jdbc/StringUtils
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:306)
	at org.apache.doris.udf.FakeDriver.connect(FakeDriver.java:38)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:247)
	at org.apache.doris.udf.JdbcExecutor.init(JdbcExecutor.java:258)
	at org.apache.doris.udf.JdbcExecutor.<init>(JdbcExecutor.java:71)
W0309 17:18:20.194088 49040 fragment_mgr.cpp:395] report error status: Internal error: NoClassDefFoundError: com/mysql/jdbc/StringUtils to coordinator: TNetworkAddress(hostname=192.168.200.22, port=19020), query id: 6344083d9a1f4b78-aebe9f1a9b4877e4, instance id: 6344083d9a1f4b78-aebe9f1a9b4877e5
W0309 17:18:20.197248 49040 fragment_mgr.cpp:251] Got error while opening fragment 6344083d9a1f4b78-aebe9f1a9b4877e5, query id: 6344083d9a1f4b78-aebe9f1a9b4877e4: Internal error: NoClassDefFoundError: com/mysql/jdbc/StringUtils
```

### What You Expected?

I hope：
1.Please tell me the solution. Our Doris is the production environment.
2.Can be fixed in the new version.

### Are you willing to submit PR?

- [x] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zhangstar333** [comment]
this maybe have fixed in the new version
