### ISSUE TITLE
[Bug] NullPointerException when analyze sql

### ISSUE THREAD

**Issue by Yulei-Yang** [apache/doris#18155]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

branch-1.2-lts  / master

### What's Wrong?

CREATE TABLE `t1` (
    `id` int(11) NOT NULL COMMENT ''
) ENGINE=OLAP
UNIQUE KEY(`id`)
COMMENT "OLAP"
DISTRIBUTED BY HASH(`id`) BUCKETS 1
PROPERTIES (
"replication_allocation" = "tag.location.default: 1"
);

CREATE TABLE `t2` (
    `name` varchar(128) COMMENT ''
) ENGINE=OLAP
UNIQUE KEY(`name`)
COMMENT "OLAP"
DISTRIBUTED BY HASH(`name`) BUCKETS 1
PROPERTIES (
"replication_allocation" = "tag.location.default: 1"
);

**this sql will get wrong**
SELECT cd
FROM
  (SELECT CURDATE() cd
   FROM t1) tbl1
JOIN
  (select cast(now() as string) td
      from t2 b
   GROUP BY now()) tbl2 
ON tbl1.cd = tbl2.td;

2023-03-28 02:17:36,484 WARN (mysql-nio-pool-15|6590) [StmtExecutor.analyze():738] Analyze failed. stmt[74, 479271bfc4d04735-8af390c3
37bef803]
java.lang.NullPointerException: null
        at java.lang.String$CaseInsensitiveComparator.compare(String.java:1192) ~[?:1.8.0_362]
        at java.lang.String$CaseInsensitiveComparator.compare(String.java:1186) ~[?:1.8.0_362]
        at java.util.TreeMap.getEntryUsingComparator(TreeMap.java:376) ~[?:1.8.0_362]
        at java.util.TreeMap.getEntry(TreeMap.java:345) ~[?:1.8.0_362]
        at java.util.TreeMap.get(TreeMap.java:278) ~[?:1.8.0_362]
        at org.apache.doris.catalog.Table.getColumn(Table.java:315) ~[doris-fe.jar:1.2-SNAPSHOT]
        at org.apache.doris.analysis.Analyzer.resolveColumnRef(Analyzer.java:971) ~[doris-fe.jar:1.2-SNAPSHOT]
        at org.apache.doris.analysis.Analyzer.registerColumnRef(Analyzer.java:848) ~[doris-fe.jar:1.2-SNAPSHOT]
        at org.apache.doris.analysis.SlotRef.analyzeImpl(SlotRef.java:194) ~[doris-fe.jar:1.2-SNAPSHOT]
        at org.apache.doris.analysis.Expr.analyze(Expr.java:421) ~[doris-fe.jar:1.2-SNAPSHOT]
        at org.apache.doris.analysis.Expr.analyze(Expr.java:413) ~[doris-fe.jar:1.2-SNAPSHOT]
        at org.apache.doris.analysis.Expr.analyze(Expr.java:413) ~[doris-fe.jar:1.2-SNAPSHOT]
        at org.apache.doris.analysis.TableRef.analyzeJoin(TableRef.java:652) ~[doris-fe.jar:1.2-SNAPSHOT]
        at org.apache.doris.analysis.InlineViewRef.analyze(InlineViewRef.java:252) ~[doris-fe.jar:1.2-SNAPSHOT]
        at org.apache.doris.analysis.FromClause.analyze(FromClause.java:137) ~[doris-fe.jar:1.2-SNAPSHOT]
        at org.apache.doris.analysis.SelectStmt.analyze(SelectStmt.java:409) ~[doris-fe.jar:1.2-SNAPSHOT]
        at org.apache.doris.qe.StmtExecutor.analyzeAndGenerateQueryPlan(StmtExecutor.java:862) ~[doris-fe.jar:1.2-SNAPSHOT]
        at org.apache.doris.qe.StmtExecutor.analyze(StmtExecutor.java:721) ~[doris-fe.jar:1.2-SNAPSHOT]
        at org.apache.doris.qe.StmtExecutor.execute(StmtExecutor.java:446) ~[doris-fe.jar:1.2-SNAPSHOT]
        at org.apache.doris.qe.StmtExecutor.execute(StmtExecutor.java:409) ~[doris-fe.jar:1.2-SNAPSHOT]
        at org.apache.doris.qe.ConnectProcessor.handleQuery(ConnectProcessor.java:330) ~[doris-fe.jar:1.2-SNAPSHOT]
        at org.apache.doris.qe.ConnectProcessor.dispatch(ConnectProcessor.java:473) ~[doris-fe.jar:1.2-SNAPSHOT]
        at org.apache.doris.qe.ConnectProcessor.processOnce(ConnectProcessor.java:700) ~[doris-fe.jar:1.2-SNAPSHOT]
        at org.apache.doris.mysql.ReadListener.lambda$handleEvent$0(ReadListener.java:52) ~[doris-fe.jar:1.2-SNAPSHOT]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_362]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_362]
        at java.lang.Thread.run(Thread.java:750) ~[?:1.8.0_362]
2023-03-28 02:17:36,484 WARN (mysql-nio-pool-15|6590) [StmtExecutor.execute():589] execute Exception. stmt[74, 479271bfc4d04735-8af390c337bef803]
org.apache.doris.common.AnalysisException: errCode = 2, detailMessage = Unexpected exception: null
        at org.apache.doris.qe.StmtExecutor.analyze(StmtExecutor.java:742) ~[doris-fe.jar:1.2-SNAPSHOT]
        at org.apache.doris.qe.StmtExecutor.execute(StmtExecutor.java:446) ~[doris-fe.jar:1.2-SNAPSHOT]
        at org.apache.doris.qe.StmtExecutor.execute(StmtExecutor.java:409) ~[doris-fe.jar:1.2-SNAPSHOT]
        at org.apache.doris.qe.ConnectProcessor.handleQuery(ConnectProcessor.java:330) ~[doris-fe.jar:1.2-SNAPSHOT]
        at org.apache.doris.qe.ConnectProcessor.dispatch(ConnectProcessor.java:473) ~[doris-fe.jar:1.2-SNAPSHOT]
        at org.apache.doris.qe.ConnectProcessor.processOnce(ConnectProcessor.java:700) ~[doris-fe.jar:1.2-SNAPSHOT]

### What You Expected?

fix it

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by lide-reed** [comment]
CREATE TABLE t (
name varchar(128) 
) ENGINE=OLAP
UNIQUE KEY(name)
DISTRIBUTED BY HASH(name) BUCKETS 1;

insert into t values('abc');

SELECT cd
FROM
(SELECT cast(now() as string) cd FROM t) t1
JOIN
(select cast(now() as string) td from t GROUP BY now()) t2
ON t1.cd = t2.td;

ERROR 1105 (HY000): errCode = 2, detailMessage = Unexpected exception: null
