### ISSUE TITLE
[Bug] NPE when analyze and create sort group plan

### ISSUE THREAD

**Issue by lide-reed** [apache/doris#18429]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

下面这个版本有错误：
commit 2b69335c12b794fa9d2b81c797443066c5bd1723
Author: siriume <siriume@gmail.com>
Date:   Fri Mar 31 09:07:02 2023 +0800

    [chore](build) Build java udf by default (#18254)

下面这个版本没问题：
commit de2bc98fa26d30136b9864275e184d28ae72e96b
Author: morningman <morningman@163.com>
Date:   Thu Mar 16 17:48:24 2023 +0800

    [bugfix](compaction) remove useless check #17804
    
    cherry-pick #17804

### What's Wrong?

CREATE TABLE `mytable` (
  `c1` varchar(255) NULL COMMENT '',
  `c2` varchar(10) NOT NULL COMMENT '',
  `c3` varchar(10) NULL COMMENT '',
  `c4` varchar(10) NULL COMMENT '',
  `c5` varchar(255) NULL COMMENT '',
  `c6` bigint(20) NULL COMMENT '',
  `c7` bigint(20) NULL COMMENT ''
) ENGINE=OLAP
UNIQUE KEY(`c1`, `c2`, `c3`, `c4`)
DISTRIBUTED BY HASH(`c2`, `c4`) BUCKETS 3;

SELECT t1.*,
         row_number() OVER(PARTITION BY c4,c5,diff ORDER BY  c2 DESC) AS row_num_1, 
         row_number() OVER(PARTITION BY c4,c5 ORDER BY  c2 DESC) AS row_num_2
FROM 
    (SELECT c4, c5, c2,
        CASE WHEN c6>c7 THEN 1
        WHEN c6<c7 THEN -1
        ELSE 0
        END AS diff
    FROM mytable)t1;

MySQL [testdb]> SELECT t1.*,
    ->          row_number() OVER(PARTITION BY c4,c5,diff ORDER BY  c2 DESC) AS row_num_1, 
    ->          row_number() OVER(PARTITION BY c4,c5 ORDER BY  c2 DESC) AS row_num_2
    -> FROM 
    ->     (SELECT c4, c5, c2,
    ->         CASE WHEN c6>c7 THEN 1
    ->         WHEN c6<c7 THEN -1
    ->         ELSE 0
    ->         END AS diff
    ->     FROM mytable)t1;
ERROR 1105 (HY000): errCode = 2, detailMessage = Unexpected exception: null

### What You Expected?

execute right

### How to Reproduce?

CREATE TABLE `mytable` (
  `c1` varchar(255) NULL COMMENT '',
  `c2` varchar(10) NOT NULL COMMENT '',
  `c3` varchar(10) NULL COMMENT '',
  `c4` varchar(10) NULL COMMENT '',
  `c5` varchar(255) NULL COMMENT '',
  `c6` bigint(20) NULL COMMENT '',
  `c7` bigint(20) NULL COMMENT ''
) ENGINE=OLAP
UNIQUE KEY(`c1`, `c2`, `c3`, `c4`)
DISTRIBUTED BY HASH(`c2`, `c4`) BUCKETS 3;

SELECT t1.*,
         row_number() OVER(PARTITION BY c4,c5,diff ORDER BY  c2 DESC) AS row_num_1, 
         row_number() OVER(PARTITION BY c4,c5 ORDER BY  c2 DESC) AS row_num_2
FROM 
    (SELECT c4, c5, c2,
        CASE WHEN c6>c7 THEN 1
        WHEN c6<c7 THEN -1
        ELSE 0
        END AS diff
    FROM mytable)t1;

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by lide-reed** [comment]
2023-04-06 15:32:51,632 WARN (mysql-nio-pool-2026|48524) [StmtExecutor.analyze():738] Analyze failed. stmt[645217, bdd8209ffb564a83-a9e8938c985de6c8]
java.lang.IllegalStateException: null
        at com.google.common.base.Preconditions.checkState(Preconditions.java:492) ~[guava-29.0-jre.jar:?]
        at org.apache.doris.planner.AnalyticPlanner.createNullMatchingEqualsAux(AnalyticPlanner.java:526) ~[doris-fe.jar:1.2-SNAPSHOT]
        at org.apache.doris.planner.AnalyticPlanner.createNullMatchingEquals(AnalyticPlanner.java:503) ~[doris-fe.jar:1.2-SNAPSHOT]
        at org.apache.doris.planner.AnalyticPlanner.createSortGroupPlan(AnalyticPlanner.java:466) ~[doris-fe.jar:1.2-SNAPSHOT]
        at org.apache.doris.planner.AnalyticPlanner.createSingleNodePlan(AnalyticPlanner.java:130) ~[doris-fe.jar:1.2-SNAPSHOT]
        at org.apache.doris.planner.SingleNodePlanner.createQueryPlan(SingleNodePlanner.java:261) ~[doris-fe.jar:1.2-SNAPSHOT]
        at org.apache.doris.planner.SingleNodePlanner.createSingleNodePlan(SingleNodePlanner.java:175) ~[doris-fe.jar:1.2-SNAPSHOT]
        at org.apache.doris.planner.OriginalPlanner.createPlanFragments(OriginalPlanner.java:147) ~[doris-fe.jar:1.2-SNAPSHOT]
        at org.apache.doris.planner.OriginalPlanner.plan(OriginalPlanner.java:85) ~[doris-fe.jar:1.2-SNAPSHOT]
        at org.apache.doris.qe.StmtExecutor.analyzeAndGenerateQueryPlan(StmtExecutor.java:886) ~[doris-fe.jar:1.2-SNAPSHOT]
        at org.apache.doris.qe.StmtExecutor.analyze(StmtExecutor.java:721) ~[doris-fe.jar:1.2-SNAPSHOT]
        at org.apache.doris.qe.StmtExecutor.execute(StmtExecutor.java:446) ~[doris-fe.jar:1.2-SNAPSHOT]
        at org.apache.doris.qe.StmtExecutor.execute(StmtExecutor.java:409) ~[doris-fe.jar:1.2-SNAPSHOT]
        at org.apache.doris.qe.ConnectProcessor.handleQuery(ConnectProcessor.java:330) ~[doris-fe.jar:1.2-SNAPSHOT]
        at org.apache.doris.qe.ConnectProcessor.dispatch(ConnectProcessor.java:473) ~[doris-fe.jar:1.2-SNAPSHOT]
        at org.apache.doris.qe.ConnectProcessor.processOnce(ConnectProcessor.java:700) ~[doris-fe.jar:1.2-SNAPSHOT]
        at org.apache.doris.mysql.ReadListener.lambda$handleEvent$0(ReadListener.java:52) ~[doris-fe.jar:1.2-SNAPSHOT]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_272]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_272]
        at java.lang.Thread.run(Thread.java:748) ~[?:1.8.0_272]
2023-04-06 15:32:51,632 WARN (mysql-nio-pool-2026|48524) [StmtExecutor.execute():589] execute Exception. stmt[645217, bdd8209ffb564a83-a9e8938c985de6c8]
org.apache.doris.common.AnalysisException: errCode = 2, detailMessage = Unexpected exception: null
        at org.apache.doris.qe.StmtExecutor.analyze(StmtExecutor.java:742) ~[doris-fe.jar:1.2-SNAPSHOT]
        at org.apache.doris.qe.StmtExecutor.execute(StmtExecutor.java:446) ~[doris-fe.jar:1.2-SNAPSHOT]
        at org.apache.doris.qe.StmtExecutor.execute(StmtExecutor.java:409) ~[doris-fe.jar:1.2-SNAPSHOT]
        at org.apache.doris.qe.ConnectProcessor.handleQuery(ConnectProcessor.java:330) ~[doris-fe.jar:1.2-SNAPSHOT]
        at org.apache.doris.qe.ConnectProcessor.dispatch(ConnectProcessor.java:473) ~[doris-fe.jar:1.2-SNAPSHOT]
        at org.apache.doris.qe.ConnectProcessor.processOnce(ConnectProcessor.java:700) ~[doris-fe.jar:1.2-SNAPSHOT]
        at org.apache.doris.mysql.ReadListener.lambda$handleEvent$0(ReadListener.java:52) ~[doris-fe.jar:1.2-SNAPSHOT]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_272]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_272]
        at java.lang.Thread.run(Thread.java:748) ~[?:1.8.0_272]

**Comment by lide-reed** [comment]
2023-04-06 16:01:32,310 WARN (mysql-nio-pool-2048|48772) [StmtExecutor.analyze():738] Analyze failed. stmt[663626, 8a8ea71357fe4ddd-a6e690b4da6da320]
java.lang.IllegalStateException: null
        at com.google.common.base.Preconditions.checkState(Preconditions.java:492) ~[guava-29.0-jre.jar:?]
        at org.apache.doris.planner.AnalyticPlanner.createNullMatchingEqualsAux(AnalyticPlanner.java:526) ~[doris-fe.jar:1.2-SNAPSHOT]
        at org.apache.doris.planner.AnalyticPlanner.createNullMatchingEquals(AnalyticPlanner.java:503) ~[doris-fe.jar:1.2-SNAPSHOT]
        at org.apache.doris.planner.AnalyticPlanner.createSortGroupPlan(AnalyticPlanner.java:466) ~[doris-fe.jar:1.2-SNAPSHOT]
        at org.apache.doris.planner.AnalyticPlanner.createSingleNodePlan(AnalyticPlanner.java:130) ~[doris-fe.jar:1.2-SNAPSHOT]
        at org.apache.doris.planner.SingleNodePlanner.createQueryPlan(SingleNodePlanner.java:261) ~[doris-fe.jar:1.2-SNAPSHOT]
        at org.apache.doris.planner.SingleNodePlanner.createSingleNodePlan(SingleNodePlanner.java:175) ~[doris-fe.jar:1.2-SNAPSHOT]
        at org.apache.doris.planner.OriginalPlanner.createPlanFragments(OriginalPlanner.java:147) ~[doris-fe.jar:1.2-SNAPSHOT]
        at org.apache.doris.planner.OriginalPlanner.plan(OriginalPlanner.java:85) ~[doris-fe.jar:1.2-SNAPSHOT]
        at org.apache.doris.qe.StmtExecutor.analyzeAndGenerateQueryPlan(StmtExecutor.java:886) ~[doris-fe.jar:1.2-SNAPSHOT]
        at org.apache.doris.qe.StmtExecutor.analyze(StmtExecutor.java:721) ~[doris-fe.jar:1.2-SNAPSHOT]
        at org.apache.doris.qe.StmtExecutor.execute(StmtExecutor.java:446) ~[doris-fe.jar:1.2-SNAPSHOT]
        at org.apache.doris.qe.StmtExecutor.execute(StmtExecutor.java:409) ~[doris-fe.jar:1.2-SNAPSHOT]
        at org.apache.doris.qe.ConnectProcessor.handleQuery(ConnectProcessor.java:330) ~[doris-fe.jar:1.2-SNAPSHOT]
        at org.apache.doris.qe.ConnectProcessor.dispatch(ConnectProcessor.java:473) ~[doris-fe.jar:1.2-SNAPSHOT]
        at org.apache.doris.qe.ConnectProcessor.processOnce(ConnectProcessor.java:700) ~[doris-fe.jar:1.2-SNAPSHOT]
        at org.apache.doris.mysql.ReadListener.lambda$handleEvent$0(ReadListener.java:52) ~[doris-fe.jar:1.2-SNAPSHOT]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_272]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_272]
        at java.lang.Thread.run(Thread.java:748) ~[?:1.8.0_272]
2023-04-06 16:01:32,310 WARN (mysql-nio-pool-2048|48772) [StmtExecutor.execute():589] execute Exception. stmt[663626, 8a8ea71357fe4ddd-a6e690b4da6da320]
org.apache.doris.common.AnalysisException: errCode = 2, detailMessage = Unexpected exception: null
        at org.apache.doris.qe.StmtExecutor.analyze(StmtExecutor.java:742) ~[doris-fe.jar:1.2-SNAPSHOT]
        at org.apache.doris.qe.StmtExecutor.execute(StmtExecutor.java:446) ~[doris-fe.jar:1.2-SNAPSHOT]
        at org.apache.doris.qe.StmtExecutor.execute(StmtExecutor.java:409) ~[doris-fe.jar:1.2-SNAPSHOT]
        at org.apache.doris.qe.ConnectProcessor.handleQuery(ConnectProcessor.java:330) ~[doris-fe.jar:1.2-SNAPSHOT]
        at org.apache.doris.qe.ConnectProcessor.dispatch(ConnectProcessor.java:473) ~[doris-fe.jar:1.2-SNAPSHOT]
        at org.apache.doris.qe.ConnectProcessor.processOnce(ConnectProcessor.java:700) ~[doris-fe.jar:1.2-SNAPSHOT]
        at org.apache.doris.mysql.ReadListener.lambda$handleEvent$0(ReadListener.java:52) ~[doris-fe.jar:1.2-SNAPSHOT]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_272]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_272]
        at java.lang.Thread.run(Thread.java:748) ~[?:1.8.0_272]

**Comment by morrySnow** [comment]
#18220
