### ISSUE TITLE
[Bug] Failed to start the fe in mac m1

### ISSUE THREAD

**Issue by laofan13** [apache/doris#18656]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

github master branch

### What's Wrong?

2023-04-13 23:58:43,769 INFO (main|1) [Env.loadImage():1658] image does not exist: /Users/lifengfan/Desktop/GitHub/doris/output/fe/doris-meta/image/image.0
2023-04-13 23:59:09,391 WARN (UNKNOWN fe80::ce81:b1c:bd2c:69e_9010_1681401523757(-1)|1) [Env.notifyNewFETypeTransfer():2283] notify new FE type transfer: UNKNOWN
2023-04-13 23:59:14,401 WARN (UNKNOWN fe80::ce81:b1c:bd2c:69e_9010_1681401523757(-1)|1) [Env.notifyNewFETypeTransfer():2283] notify new FE type transfer: UNKNOWN
2023-04-13 23:59:14,402 ERROR (UNKNOWN fe80::ce81:b1c:bd2c:69e_9010_1681401523757(-1)|1) [BDBEnvironment.setup():196] error to open replicated environment. will exit.
com.sleepycat.je.rep.ReplicaWriteException: (JE 18.3.12) Problem closing transaction 20. The current state is:UNKNOWN. The node transitioned to this state at:Thu Apr 13 23:58:59 CST 2023
	at com.sleepycat.je.rep.txn.ReadonlyTxn.disallowReplicaWrite(ReadonlyTxn.java:114) ~[je-18.3.14-doris-SNAPSHOT.jar:18.3.14-doris-SNAPSHOT]
	at com.sleepycat.je.dbi.DbTree.checkReplicaWrite(DbTree.java:880) ~[je-18.3.14-doris-SNAPSHOT.jar:18.3.14-doris-SNAPSHOT]
	at com.sleepycat.je.dbi.DbTree.doCreateDb(DbTree.java:579) ~[je-18.3.14-doris-SNAPSHOT.jar:18.3.14-doris-SNAPSHOT]
	at com.sleepycat.je.dbi.DbTree.createDb(DbTree.java:486) ~[je-18.3.14-doris-SNAPSHOT.jar:18.3.14-doris-SNAPSHOT]
	at com.sleepycat.je.Database.initNew(Database.java:174) ~[je-18.3.14-doris-SNAPSHOT.jar:18.3.14-doris-SNAPSHOT]
	at com.sleepycat.je.Environment.setupDatabase(Environment.java:864) ~[je-18.3.14-doris-SNAPSHOT.jar:18.3.14-doris-SNAPSHOT]
	at com.sleepycat.je.Environment.openDatabase(Environment.java:668) ~[je-18.3.14-doris-SNAPSHOT.jar:18.3.14-doris-SNAPSHOT]
	at org.apache.doris.journal.bdbje.BDBEnvironment.setup(BDBEnvironment.java:177) ~[doris-fe.jar:1.2-SNAPSHOT]
	at org.apache.doris.journal.bdbje.BDBJEJournal.open(BDBJEJournal.java:317) ~[doris-fe.jar:1.2-SNAPSHOT]
	at org.apache.doris.persist.EditLog.open(EditLog.java:1055) ~[doris-fe.jar:1.2-SNAPSHOT]
	at org.apache.doris.catalog.Env.initialize(Env.java:851) ~[doris-fe.jar:1.2-SNAPSHOT]
	at org.apache.doris.DorisFE.start(DorisFE.java:146) ~[doris-fe.jar:1.2-SNAPSHOT]
	at org.apache.doris.DorisFE.main(DorisFE.java:73) ~[doris-fe.jar:1.2-SNAPSHOT]

### What You Expected?

Why this error, my disk is sufficient

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by LemonLiTree** [comment]
Did you compile it yourself on mac?

**Comment by risebeforeshining** [comment]
I got the same problem. I ran doris on ubuntu 16 and with java 8.

**Comment by stalary** [comment]
Whether  already create doris-meta?

**Comment by risebeforeshining** [comment]
> I got the same problem. I ran doris on ubuntu 16 and with java 8.
