### ISSUE TITLE
[Bug] stream load may cause be core

### ISSUE THREAD

**Issue by nextdreamblue** [apache/doris#18651]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

1.2.3
master

### What's Wrong?

```
#0  extent_szind_set (szind=36, extent=0x0) at ../include/jemalloc/internal/extent_inlines.h:261
#1  arena_prof_demote (ptr=0x7f69680008c0, extent=0x0, tsdn=0x7f76174cd180) at ../src/arena.c:1585
#2  je_arena_dalloc_promoted (tsdn=0x7f76174cd180, ptr=0x7f69680008c0, tcache=0x7f76174cd370, slow_path=<optimized out>) at ../src/arena.c:1604
#3  0x00007f76f5c5b3a1 in pthread_create@@GLIBC_2.2.5 () from /lib64/libpthread.so.0
#4  0x000055909d641aa6 in doris::Thread::start_thread(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::function<void ()> const&, unsigned long, scoped_refptr<doris::Thread>*) (category=..., name=..., functor=..., flags=flags@entry=0, 
    holder=holder@entry=0x7f76d730a310) at /data/doris-1.x/incubator-doris/be/src/util/thread.cpp:408
#5  0x000055909d3c7ec0 in create<doris::stream_load::OlapTableSink::open(doris::RuntimeState*)::<lambda()> > (holder=0x7f76d730a310, f=..., name=..., category=...)
    at /var/local/ldb-toolchain/include/c++/11/bits/std_function.h:232
#6  doris::stream_load::OlapTableSink::open (this=this@entry=0x7f76d730a100, state=state@entry=0x7f748112d300) at /data/doris-1.x/incubator-doris/be/src/exec/tablet_sink.cpp:1044
#7  0x00005590a2175aae in doris::stream_load::VOlapTableSink::open (this=0x7f76d730a100, state=0x7f748112d300) at /data/doris-1.x/incubator-doris/be/src/vec/sink/vtablet_sink.cpp:456
#8  0x000055909d3bd38f in doris::PlanFragmentExecutor::open_vectorized_internal (this=this@entry=0x7f74c8ebc980) at /var/local/ldb-toolchain/include/c++/11/bits/unique_ptr.h:421
#9  0x000055909d3be89a in doris::PlanFragmentExecutor::open (this=this@entry=0x7f74c8ebc980) at /data/doris-1.x/incubator-doris/be/src/runtime/plan_fragment_executor.cpp:259
#10 0x000055909d39693e in doris::FragmentExecState::execute (this=0x7f74c8ebc900) at /data/doris-1.x/incubator-doris/be/src/runtime/fragment_mgr.cpp:260
#11 0x000055909d399d35 in doris::FragmentMgr::_exec_actual(std::shared_ptr<doris::FragmentExecState>, std::function<void (doris::PlanFragmentExecutor*)>) (this=this@entry=0x7f76f0d50000, 
    exec_state=std::shared_ptr (count 3, weak 0) 0x7f74c8ebc900, cb=...) at /var/local/ldb-toolchain/include/c++/11/bits/shared_ptr_base.h:1290
#12 0x000055909d39a45a in operator() (__closure=<optimized out>) at /var/local/ldb-toolchain/include/c++/11/ext/atomicity.h:109
#13 __invoke_impl<void, doris::FragmentMgr::exec_plan_fragment(const doris::TExecPlanFragmentParams&, doris::FragmentMgr::FinishCallback)::<lambda()>&> (__f=...)
    at /var/local/ldb-toolchain/include/c++/11/bits/invoke.h:61
#14 __invoke_r<void, doris::FragmentMgr::exec_plan_fragment(const doris::TExecPlanFragmentParams&, doris::FragmentMgr::FinishCallback)::<lambda()>&> (__fn=...)
    at /var/local/ldb-toolchain/include/c++/11/bits/invoke.h:111
#15 std::_Function_handler<void(), doris::FragmentMgr::exec_plan_fragment(const doris::TExecPlanFragmentParams&, doris::FragmentMgr::FinishCallback)::<lambda()> >::_M_invoke(const std::_Any_data &) (__functor=...) at /var/local/ldb-toolchain/include/c++/11/bits/std_function.h:291
#16 0x000055909d650725 in operator() (this=<optimized out>) at /var/local/ldb-toolchain/include/c++/11/bits/std_function.h:556
#17 run (this=<optimized out>) at /data/doris-1.x/incubator-doris/be/src/util/threadpool.cpp:46
#18 doris::ThreadPool::dispatch_thread (this=0x7f76f2346b40) at /data/doris-1.x/incubator-doris/be/src/util/threadpool.cpp:535
#19 0x000055909d645e5f in operator() (this=0x7f76d5b6a938) at /var/local/ldb-toolchain/include/c++/11/bits/std_function.h:556
#20 doris::Thread::supervise_thread (arg=0x7f76d5b6a920) at /data/doris-1.x/incubator-doris/be/src/util/thread.cpp:454
#21 0x00007f76f5c5aea5 in start_thread () from /lib64/libpthread.so.0
#22 0x00007f76f5f6d9fd in clone () from /lib64/libc.so.6
```

### What You Expected?

not core

it maybe can fix add a thread pool instead of new thread everytime

like https://github.com/apache/doris/pull/17212

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by xinyiZzz** [comment]
![image](https://user-images.githubusercontent.com/13197424/236987497-083c71ce-6948-403b-a23b-491502a0d14d.png)
may be the same problem

**Comment by yuxuan-luo** [comment]
> ![image](https://user-images.githubusercontent.com/13197424/236987497-083c71ce-6948-403b-a23b-491502a0d14d.png) may be the same problem

Did you solve this problem?
