### ISSUE TITLE
[Bug] [Daily] fe restart error when parsing create materialized view stmt

### ISSUE THREAD

**Issue by zhangy5** [apache/doris#18765]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

master

### What's Wrong?

2023-04-18 10:06:40,430 DEBUG (stateListener|100) [EditLog.loadJournal():551] opcode: 100, tid: 2399
2023-04-18 10:06:40,430 DEBUG (stateListener|100) [Env.replayJournal():2465] journal 11945 replayed.
2023-04-18 10:06:40,430 DEBUG (stateListener|100) [JournalObservable.notifyObservers():90] notify observers: journal: 11945, pos: 0, size: 0, obs: []
2023-04-18 10:06:40,430 DEBUG (stateListener|100) [JournalEntity.readFields():167] get opcode: 59
2023-04-18 10:06:40,430 DEBUG (stateListener|100) [EditLog.loadJournal():158] replay journal op code: 59
2023-04-18 10:06:40,430 DEBUG (stateListener|100) [Env.replayJournal():2465] journal 11946 replayed.
2023-04-18 10:06:40,430 DEBUG (stateListener|100) [JournalObservable.notifyObservers():90] notify observers: journal: 11946, pos: 0, size: 0, obs: []
2023-04-18 10:06:40,430 DEBUG (stateListener|100) [JournalEntity.readFields():167] get opcode: 121
2023-04-18 10:06:40,480 ERROR (stateListener|100) [BDBJournalCursor.next():116] fail to read journal entity key=11947, will exit
com.google.gson.JsonIOException: java.io.IOException: error happens when parsing create materialized view stmt: org.apache.doris.analysis.CreateMaterializedViewStmt@663182ec
        at com.google.gson.TypeAdapter.fromJsonTree(TypeAdapter.java:287) ~[gson-2.8.9.jar:?]
        at org.apache.doris.persist.gson.RuntimeTypeAdapterFactory$1.read(RuntimeTypeAdapterFactory.java:289) ~[doris-fe.jar:1.2-SNAPSHOT]
        at com.google.gson.TypeAdapter$1.read(TypeAdapter.java:199) ~[gson-2.8.9.jar:?]
        at com.google.gson.Gson.fromJson(Gson.java:963) ~[gson-2.8.9.jar:?]
        at com.google.gson.Gson.fromJson(Gson.java:928) ~[gson-2.8.9.jar:?]
        at com.google.gson.Gson.fromJson(Gson.java:877) ~[gson-2.8.9.jar:?]
        at com.google.gson.Gson.fromJson(Gson.java:848) ~[gson-2.8.9.jar:?]
        at org.apache.doris.alter.AlterJobV2.read(AlterJobV2.java:241) ~[doris-fe.jar:1.2-SNAPSHOT]
        at org.apache.doris.journal.JournalEntity.readFields(JournalEntity.java:597) ~[doris-fe.jar:1.2-SNAPSHOT]
        at org.apache.doris.journal.bdbje.BDBJournalCursor.next(BDBJournalCursor.java:114) ~[doris-fe.jar:1.2-SNAPSHOT]
        at org.apache.doris.catalog.Env.replayJournal(Env.java:2458) ~[doris-fe.jar:1.2-SNAPSHOT]
        at org.apache.doris.catalog.Env.transferToMaster(Env.java:1290) ~[doris-fe.jar:1.2-SNAPSHOT]
        at org.apache.doris.catalog.Env.access$1200(Env.java:286) ~[doris-fe.jar:1.2-SNAPSHOT]
        at org.apache.doris.catalog.Env$4.runOneCycle(Env.java:2379) ~[doris-fe.jar:1.2-SNAPSHOT]
        at org.apache.doris.common.util.Daemon.run(Daemon.java:116) ~[doris-fe.jar:1.2-SNAPSHOT]
Caused by: java.io.IOException: error happens when parsing create materialized view stmt: org.apache.doris.analysis.CreateMaterializedViewStmt@663182ec
        at org.apache.doris.alter.RollupJobV2.gsonPostProcess(RollupJobV2.java:875) ~[doris-fe.jar:1.2-SNAPSHOT]
        at org.apache.doris.persist.gson.GsonUtils$PostProcessTypeAdapterFactory$1.read(GsonUtils.java:472) ~[doris-fe.jar:1.2-SNAPSHOT]
        at com.google.gson.TypeAdapter.fromJsonTree(TypeAdapter.java:285) ~[gson-2.8.9.jar:?]
        ... 14 more
Caused by: java.lang.NullPointerException
        at org.apache.doris.mysql.privilege.AccessControllerManager.checkDbPriv(AccessControllerManager.java:138) ~[doris-fe.jar:1.2-SNAPSHOT]
        at org.apache.doris.analysis.FunctionCallExpr.analyzeImpl(FunctionCallExpr.java:1388) ~[doris-fe.jar:1.2-SNAPSHOT]
        at org.apache.doris.analysis.Expr.analyze(Expr.java:434) ~[doris-fe.jar:1.2-SNAPSHOT]
        at org.apache.doris.analysis.SelectStmt.analyze(SelectStmt.java:526) ~[doris-fe.jar:1.2-SNAPSHOT]
        at org.apache.doris.analysis.CreateMaterializedViewStmt.analyze(CreateMaterializedViewStmt.java:161) ~[doris-fe.jar:1.2-SNAPSHOT]
        at org.apache.doris.alter.RollupJobV2.gsonPostProcess(RollupJobV2.java:872) ~[doris-fe.jar:1.2-SNAPSHOT]
        at org.apache.doris.persist.gson.GsonUtils$PostProcessTypeAdapterFactory$1.read(GsonUtils.java:472) ~[doris-fe.jar:1.2-SNAPSHOT]
        at com.google.gson.TypeAdapter.fromJsonTree(TypeAdapter.java:285) ~[gson-2.8.9.jar:?]
        ... 14 more

### What You Expected?

fe restart success

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by liujiwen-up** [comment]
Can you try to start using the metadata recovery mode?

**Comment by zhangy5** [comment]
> Can you try to start using the metadata recovery mode?

still error

**Comment by liujiwen-up** [comment]
> 

We can take a look together, WeChat: Ljw919666

**Comment by zhuzhiqiangxx** [comment]
![image](https://github.com/apache/doris/assets/31675966/9182cbcb-ccfd-4d1f-9ed4-80eb60c08595)
Caused by: java.io.IOException: error happens when parsing create materialized view stmt: org.a
pache.doris.analysis.CreateMaterializedViewStmt@78f3de2e
