### ISSUE TITLE
[Bug] SimpleDateFormat throws exceptions because it is not thread-safe.

### ISSUE THREAD

**Issue by kaka11chen** [apache/doris#19192]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

all versions

### What's Wrong?

```
2023-04-28 01:14:31,419 WARN (thrift-server-pool-4|245) [FrontendServiceImpl.streamLoadPut():1251] catch unknown result.
java.lang.ArrayIndexOutOfBoundsException: 960
        at sun.util.calendar.BaseCalendar.getCalendarDateFromFixedDate(BaseCalendar.java:453) ~[?:1.8.0_131]
        at java.util.GregorianCalendar.computeFields(GregorianCalendar.java:2397) ~[?:1.8.0_131]
        at java.util.GregorianCalendar.computeFields(GregorianCalendar.java:2312) ~[?:1.8.0_131]
        at java.util.Calendar.setTimeInMillis(Calendar.java:1804) ~[?:1.8.0_131]
        at java.util.Calendar.setTime(Calendar.java:1770) ~[?:1.8.0_131]
        at java.text.SimpleDateFormat.format(SimpleDateFormat.java:943) ~[?:1.8.0_131]
        at java.text.SimpleDateFormat.format(SimpleDateFormat.java:936) ~[?:1.8.0_131]
        at java.text.DateFormat.format(DateFormat.java:345) ~[?:1.8.0_131]
        at org.apache.doris.planner.StreamLoadPlanner.plan(StreamLoadPlanner.java:272) ~[doris-fe.jar:1.2-SNAPSHOT]
        at org.apache.doris.service.FrontendServiceImpl.streamLoadPutImpl(FrontendServiceImpl.java:1284) ~[doris-fe.jar:1.2-SNAPSHOT]
        at org.apache.doris.service.FrontendServiceImpl.streamLoadPut(FrontendServiceImpl.java:1245) ~[doris-fe.jar:1.2-SNAPSHOT]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_131]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_131]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_131]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_131]
        at org.apache.doris.service.FeServer.lambda$start$0(FeServer.java:59) ~[doris-fe.jar:1.2-SNAPSHOT]
        at com.sun.proxy.$Proxy23.streamLoadPut(Unknown Source) ~[?:?]
        at org.apache.doris.thrift.FrontendService$Processor$streamLoadPut.getResult(FrontendService.java:2412) ~[doris-fe.jar:1.2-SNAPSHOT]
        at org.apache.doris.thrift.FrontendService$Processor$streamLoadPut.getResult(FrontendService.java:2392) ~[doris-fe.jar:1.2-SNAPSHOT]
        at org.apache.thrift.ProcessFunction.process(ProcessFunction.java:38) ~[libthrift-0.16.0.jar:0.16.0]
        at org.apache.thrift.TBaseProcessor.process(TBaseProcessor.java:38) ~[libthrift-0.16.0.jar:0.16.0]
        at org.apache.thrift.server.TThreadPoolServer$WorkerProcess.run(TThreadPoolServer.java:250) ~[libthrift-0.16.0.jar:0.16.0]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[?:1.8.0_131]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[?:1.8.0_131]
        at java.lang.Thread.run(Thread.java:748) ~[?:1.8.0_131]
```

### What You Expected?

No exception throws.

### Anything Else?

We will use `DateTimeFormatter` to replace `SimpleDateFormat` to guarantee thread safe.

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by CodeCooker17** [comment]
@kaka11chen I am willing to submit a PR to resolve it.

**Comment by kaka11chen** [comment]
> @kaka11chen I am willing to submit a PR to resolve it.

ok, thanks.
