### ISSUE TITLE
[Bug] FlinkCDC同步Mysql数据到Doris, [INTERNAL_ERROR]cancelled: sender is gone

### ISSUE THREAD

**Issue by yrg5101** [apache/doris#19461]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

Doris:1.2.4rc
Mysql:8.0.22
FlinkCDC:2.3
Flink:1.16.1

### What's Wrong?

Doris:1.2.4rc
Mysql:8.0.22
FlinkCDC:2.3
Flink:1.16.1

Caused by: java.lang.Exception: Could not perform checkpoint 53 for operator Source: MySQL CDC Source -> (Filter -> sink test123: Writer -> sink test123: Committer, Filter -> sink test234: Writer -> sink test234: Committer) (5/16)#0.
	at org.apache.flink.streaming.runtime.tasks.StreamTask.triggerCheckpointAsyncInMailbox(StreamTask.java:1141)
	at org.apache.flink.streaming.runtime.tasks.StreamTask.lambda$triggerCheckpointAsync$11(StreamTask.java:1088)
	at org.apache.flink.streaming.runtime.tasks.StreamTaskActionExecutor$1.runThrowing(StreamTaskActionExecutor.java:50)
	at org.apache.flink.streaming.runtime.tasks.mailbox.Mail.run(Mail.java:90)
	at org.apache.flink.streaming.runtime.tasks.mailbox.MailboxProcessor.processMailsWhenDefaultActionUnavailable(MailboxProcessor.java:338)
	at org.apache.flink.streaming.runtime.tasks.mailbox.MailboxProcessor.processMail(MailboxProcessor.java:324)
	at org.apache.flink.streaming.runtime.tasks.mailbox.MailboxProcessor.runMailboxLoop(MailboxProcessor.java:201)
	at org.apache.flink.streaming.runtime.tasks.StreamTask.runMailboxLoop(StreamTask.java:807)
	at org.apache.flink.streaming.runtime.tasks.StreamTask.invoke(StreamTask.java:756)
	at org.apache.flink.runtime.taskmanager.Task.runWithSystemExitMonitoring(Task.java:948)
	at org.apache.flink.runtime.taskmanager.Task.restoreAndInvoke(Task.java:927)
	at org.apache.flink.runtime.taskmanager.Task.doRun(Task.java:741)
	at org.apache.flink.runtime.taskmanager.Task.run(Task.java:563)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.doris.flink.exception.DorisRuntimeException: java.util.concurrent.ExecutionException: java.net.SocketTimeoutException: Read timed out
	at org.apache.doris.flink.sink.writer.DorisStreamLoad.stopLoad(DorisStreamLoad.java:220)
	at org.apache.doris.flink.sink.writer.DorisWriter.prepareCommit(DorisWriter.java:139)
	at org.apache.flink.streaming.api.transformations.SinkV1Adapter$SinkWriterV1Adapter.prepareCommit(SinkV1Adapter.java:151)
	at org.apache.flink.streaming.runtime.operators.sink.SinkWriterOperator.emitCommittables(SinkWriterOperator.java:198)
	at org.apache.flink.streaming.runtime.operators.sink.SinkWriterOperator.prepareSnapshotPreBarrier(SinkWriterOperator.java:168)
	at org.apache.flink.streaming.runtime.tasks.RegularOperatorChain.prepareSnapshotPreBarrier(RegularOperatorChain.java:89)
	at org.apache.flink.streaming.runtime.tasks.SubtaskCheckpointCoordinatorImpl.checkpointState(SubtaskCheckpointCoordinatorImpl.java:300)
	at org.apache.flink.streaming.runtime.tasks.StreamTask.lambda$performCheckpoint$12(StreamTask.java:1256)
	at org.apache.flink.streaming.runtime.tasks.StreamTaskActionExecutor$1.runThrowing(StreamTaskActionExecutor.java:50)
	at org.apache.flink.streaming.runtime.tasks.StreamTask.performCheckpoint(StreamTask.java:1244)
	at org.apache.flink.streaming.runtime.tasks.StreamTask.triggerCheckpointAsyncInMailbox(StreamTask.java:1129)
	... 13 more
Caused by: java.util.concurrent.ExecutionException: java.net.SocketTimeoutException: Read timed out
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at org.apache.doris.flink.sink.writer.DorisStreamLoad.stopLoad(DorisStreamLoad.java:218)
	... 23 more
Caused by: java.net.SocketTimeoutException: Read timed out
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
	at java.net.SocketInputStream.read(SocketInputStream.java:171)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at org.apache.http.impl.io.SessionInputBufferImpl.streamRead(SessionInputBufferImpl.java:139)
	at org.apache.http.impl.io.SessionInputBufferImpl.fillBuffer(SessionInputBufferImpl.java:155)
	at org.apache.http.impl.io.SessionInputBufferImpl.readLine(SessionInputBufferImpl.java:284)
	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:140)
	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:57)
	at org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:261)
	at org.apache.http.impl.DefaultBHttpClientConnection.receiveResponseHeader(DefaultBHttpClientConnection.java:165)
	at org.apache.http.impl.conn.CPoolProxy.receiveResponseHeader(CPoolProxy.java:167)
	at org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:272)
	at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:124)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:271)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:88)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:107)
	at org.apache.doris.flink.sink.writer.DorisStreamLoad.lambda$startLoad$0(DorisStreamLoad.java:248)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	... 1 more

Be日志：
W0509 17:54:57.858546 161810 stream_load_executor.cpp:80] fragment execute failed, query_id=a0497541bdcfad7f-510b41fe885b7797, err_msg=[INTERNAL_ERROR]cancelled: sender is gone, id=a0497541bdcfad7f-510b41fe885b7797, job_id=-1, txn_id=18031, label=label-GAIA_STORE_DATA67c73863-56fc-40c4-8d40-a2cf3056dc40_6_387, elapse(s)=1
W0509 17:57:45.168293 161959 scanner_scheduler.cpp:256] Scan thread read VScanner failed: [INTERNAL_ERROR]cancelled: sender is gone
W0509 17:57:45.168517 161871 fragment_mgr.cpp:118] query_id=b74af8c9d7d2aa8e-a79bd1490e27c282, instance_id=b74af8c9d7d2aa8e-a79bd1490e27c283 meet error status [INTERNAL_ERROR]cancelled: sender is gone
W0509 17:57:45.168582 161871 fragment_mgr.cpp:405] report error status: [INTERNAL_ERROR]cancelled: sender is gone to coordinator: TNetworkAddress(hostname=172.18.2.103, port=9020), query id: b74af8c9d7d2aa8e-a79bd1490e27c282, instance id: b74af8c9d7d2aa8e-a79bd1490e27c283
W0509 17:57:45.169206 161871 fragment_mgr.cpp:261] Got error while opening fragment b74af8c9d7d2aa8e-a79bd1490e27c283, query id: b74af8c9d7d2aa8e-a79bd1490e27c282: [INTERNAL_ERROR]cancelled: sender is gone
W0509 17:57:45.169502 161871 tablet_sink.cpp:156] cancel node channel VNodeChannel[441110-10005], load_id=b74af8c9d7d2aa8e-a79bd1490e27c282, txn_id=18037, node=172.18.2.106:8060, error message: [INTERNAL_ERROR]cancelled: sender is gone
W0509 17:57:45.169621 161871 tablet_sink.cpp:156] cancel node channel VNodeChannel[441110-10004], load_id=b74af8c9d7d2aa8e-a79bd1490e27c282, txn_id=18037, node=172.18.2.105:8060, error message: [INTERNAL_ERROR]cancelled: sender is gone
W0509 17:57:45.169683 161871 tablet_sink.cpp:156] cancel node channel VNodeChannel[441110-10003], load_id=b74af8c9d7d2aa8e-a79bd1490e27c282, txn_id=18037, node=172.18.2.104:8060, error message: [INTERNAL_ERROR]cancelled: sender is gone
W0509 17:57:45.170018 161871 stream_load_executor.cpp:80] fragment execute failed, query_id=b74af8c9d7d2aa8e-a79bd1490e27c282, err_msg=[INTERNAL_ERROR]cancelled: sender is gone, id=b74af8c9d7d2aa8e-a79bd1490e27c282, job_id=-1, txn_id=18037, label=label-test_tianyz_01e6ab150d-9fc0-409f-aaea-4904f1b272ae_0_3, elapse(s)=9

### What You Expected?

麻烦看看，谢谢

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by JNSimba** [comment]
Sender is gone means that the streamload http connection timed out, and the client canceled the connection. You can confirm whether it is an error reported by the network timeout

**Comment by yrg5101** [comment]
> 

Thanks for remind!

**Comment by maben996** [comment]
> Sender is gone means that the streamload http connection timed out, and the client canceled the connection. You can confirm whether it is an error reported by the network timeout

flink sql cdc mongodb2doris, doris version 1.2.4，配置了'sink.properties.timeout' = '7200'依然报错
```sql
DORIS_SINK param:
      'connector' = 'doris',
      'fenodes' = 'xxxxx:8030',
      'table.identifier' = 'xxxx.xxxxx',
      'username' = 'xxxx',
      'password' = 'xxxxxx',
      'sink.enable-delete' = 'false',
      'sink.enable-2pc' = 'false',
      'sink.properties.timeout' = '7200',
      'doris.request.retries' = '3',
      'doris.request.connect.timeout.ms' = '180000',
      'doris.request.read.timeout.ms' = '180000',
      'sink.label-prefix'='mongo2doris_compliance_msg_08'
```
```shell
W0630 00:19:39.061848 29103 stream_load_executor.cpp:233] 2PC commit transaction failed, errmsg=[ANALYSIS_ERROR]errCode = 2, detailMessage = transaction [55697] is already visible, not pre-committed.
W0630 00:21:21.691363 29103 stream_load_executor.cpp:233] 2PC commit transaction failed, errmsg=[ANALYSIS_ERROR]errCode = 2, detailMessage = transaction [55700] is already visible, not pre-committed.
W0630 00:45:06.584319 28656 scanner_scheduler.cpp:256] Scan thread read VScanner failed: [INTERNAL_ERROR]cancelled: sender is gone
W0630 00:45:06.584388 28558 fragment_mgr.cpp:118] query_id=164826560afd9a8e-f16b8300eb1b9489, instance_id=164826560afd9a8e-f16b8300eb1b948a meet error status [INTERNAL_ERROR]cancelled: sender is gone
W0630 00:45:06.584437 28558 fragment_mgr.cpp:405] report error status: [INTERNAL_ERROR]cancelled: sender is gone to coordinator: TNetworkAddress(hostname=10.1.64.9, port=9020), query id: 164826560afd9a8e-f16b8300eb1b9489, instance id: 164826560afd9a8e-f16b8300eb1b948a
W0630 00:45:06.584941 28558 fragment_mgr.cpp:261] Got error while opening fragment 164826560afd9a8e-f16b8300eb1b948a, query id: 164826560afd9a8e-f16b8300eb1b9489: [INTERNAL_ERROR]cancelled: sender is gone
W0630 00:45:06.585201 28558 tablet_sink.cpp:156] cancel node channel VNodeChannel[233525-10005], load_id=164826560afd9a8e-f16b8300eb1b9489, txn_id=55910, node=10.1.64.14:8060, error message: [INTERNAL_ERROR]cancelled: sender is gone
W0630 00:45:06.585237 28558 tablet_sink.cpp:156] cancel node channel VNodeChannel[233525-10004], load_id=164826560afd9a8e-f16b8300eb1b9489, txn_id=55910, node=10.1.64.13:8060, error message: [INTERNAL_ERROR]cancelled: sender is gone
W0630 00:45:06.585253 28558 tablet_sink.cpp:156] cancel node channel VNodeChannel[233525-10003], load_id=164826560afd9a8e-f16b8300eb1b9489, txn_id=55910, node=10.1.64.12:8060, error message: [INTERNAL_ERROR]cancelled: sender is gone
W0630 00:45:06.585364 28558 stream_load_executor.cpp:80] fragment execute failed, query_id=164826560afd9a8e-f16b8300eb1b9489, err_msg=[INTERNAL_ERROR]cancelled: sender is gone, id=164826560afd9a8e-f16b8300eb1b9489, job_id=-1, txn_id=55910, label=mongo2doris_compliance_msg_05_0_1688057019151, elapse(s)=87
```

**Comment by OldYoung-1990** [comment]
How did the problem be solved? Could you please elaborate on it

**Comment by hencylight** [comment]
> Sender is gone means that the streamload http connection timed out, and the client canceled the connection. You can confirm whether it is an error reported by the network timeout

@JNSimba @yrg5101 请问具体是怎么解决的，我目前也遇到了这个问题，求指教

`
java.io.IOException: Could not perform checkpoint 2496 for operator SinkMaterializer[885] -> customer_complaint_crms_info[885]: Writer -> customer_complaint_crms_info[885]: Committer (1/1)#170128.
	at org.apache.flink.streaming.runtime.tasks.StreamTask.triggerCheckpointOnBarrier(StreamTask.java:1256)
	at org.apache.flink.streaming.runtime.io.checkpointing.CheckpointBarrierHandler.notifyCheckpoint(CheckpointBarrierHandler.java:147)
	at org.apache.flink.streaming.runtime.io.checkpointing.SingleCheckpointBarrierHandler.triggerCheckpoint(SingleCheckpointBarrierHandler.java:287)
	at org.apache.flink.streaming.runtime.io.checkpointing.SingleCheckpointBarrierHandler.access$100(SingleCheckpointBarrierHandler.java:64)
	at org.apache.flink.streaming.runtime.io.checkpointing.SingleCheckpointBarrierHandler$ControllerImpl.triggerGlobalCheckpoint(SingleCheckpointBarrierHandler.java:488)
	at org.apache.flink.streaming.runtime.io.checkpointing.AbstractAlignedBarrierHandlerState.triggerGlobalCheckpoint(AbstractAlignedBarrierHandlerState.java:74)
	at org.apache.flink.streaming.runtime.io.checkpointing.AbstractAlignedBarrierHandlerState.barrierReceived(AbstractAlignedBarrierHandlerState.java:66)
	at org.apache.flink.streaming.runtime.io.checkpointing.SingleCheckpointBarrierHandler.lambda$processBarrier$2(SingleCheckpointBarrierHandler.java:234)
	at org.apache.flink.streaming.runtime.io.checkpointing.SingleCheckpointBarrierHandler.markCheckpointAlignedAndTransformState(SingleCheckpointBarrierHandler.java:262)
	at org.apache.flink.streaming.runtime.io.checkpointing.SingleCheckpointBarrierHandler.processBarrier(SingleCheckpointBarrierHandler.java:231)
	at org.apache.flink.streaming.runtime.io.checkpointing.CheckpointedInputGate.handleEvent(CheckpointedInputGate.java:181)
	at org.apache.flink.streaming.runtime.io.checkpointing.CheckpointedInputGate.pollNext(CheckpointedInputGate.java:159)
	at org.apache.flink.streaming.runtime.io.AbstractStreamTaskNetworkInput.emitNext(AbstractStreamTaskNetworkInput.java:118)
	at org.apache.flink.streaming.runtime.io.StreamOneInputProcessor.processInput(StreamOneInputProcessor.java:65)
	at org.apache.flink.streaming.runtime.tasks.StreamTask.processInput(StreamTask.java:550)
	at org.apache.flink.streaming.runtime.tasks.mailbox.MailboxProcessor.runMailboxLoop(MailboxProcessor.java:231)
	at org.apache.flink.streaming.runtime.tasks.StreamTask.runMailboxLoop(StreamTask.java:839)
	at org.apache.flink.streaming.runtime.tasks.StreamTask.invoke(StreamTask.java:788)
	at org.apache.flink.runtime.taskmanager.Task.runWithSystemExitMonitoring(Task.java:952)
	at org.apache.flink.runtime.taskmanager.Task.restoreAndInvoke(Task.java:931)
	at org.apache.flink.runtime.taskmanager.Task.doRun(Task.java:745)
	at org.apache.flink.runtime.taskmanager.Task.run(Task.java:562)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: org.apache.doris.flink.exception.DorisRuntimeException: java.util.concurrent.ExecutionException: java.net.SocketException: Connection timed out (Read failed)
	at org.apache.doris.flink.sink.writer.DorisStreamLoad.stopLoad(DorisStreamLoad.java:220)
	at org.apache.doris.flink.sink.writer.DorisWriter.prepareCommit(DorisWriter.java:155)
	at org.apache.flink.streaming.api.transformations.SinkV1Adapter$SinkWriterV1Adapter.prepareCommit(SinkV1Adapter.java:151)
	at org.apache.flink.streaming.runtime.operators.sink.SinkWriterOperator.emitCommittables(SinkWriterOperator.java:196)
	at org.apache.flink.streaming.runtime.operators.sink.SinkWriterOperator.prepareSnapshotPreBarrier(SinkWriterOperator.java:166)
	at org.apache.flink.streaming.runtime.tasks.RegularOperatorChain.prepareSnapshotPreBarrier(RegularOperatorChain.java:89)
	at org.apache.flink.streaming.runtime.tasks.SubtaskCheckpointCoordinatorImpl.checkpointState(SubtaskCheckpointCoordinatorImpl.java:321)
	at org.apache.flink.streaming.runtime.tasks.StreamTask.lambda$performCheckpoint$14(StreamTask.java:1299)
	at org.apache.flink.streaming.runtime.tasks.StreamTaskActionExecutor$1.runThrowing(StreamTaskActionExecutor.java:50)
	at org.apache.flink.streaming.runtime.tasks.StreamTask.performCheckpoint(StreamTask.java:1287)
	at org.apache.flink.streaming.runtime.tasks.StreamTask.triggerCheckpointOnBarrier(StreamTask.java:1244)
	... 22 more
Caused by: java.util.concurrent.ExecutionException: java.net.SocketException: Connection timed out (Read failed)
	at java.base/java.util.concurrent.FutureTask.report(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.get(Unknown Source)
	at org.apache.doris.flink.sink.writer.DorisStreamLoad.stopLoad(DorisStreamLoad.java:218)
	... 32 more
Caused by: java.net.SocketException: Connection timed out (Read failed)
	at java.base/java.net.SocketInputStream.socketRead0(Native Method)
	at java.base/java.net.SocketInputStream.socketRead(Unknown Source)
	at java.base/java.net.SocketInputStream.read(Unknown Source)
	at java.base/java.net.SocketInputStream.read(Unknown Source)
	at org.apache.http.impl.io.SessionInputBufferImpl.streamRead(SessionInputBufferImpl.java:137)
	at org.apache.http.impl.io.SessionInputBufferImpl.fillBuffer(SessionInputBufferImpl.java:153)
	at org.apache.http.impl.io.SessionInputBufferImpl.readLine(SessionInputBufferImpl.java:280)
	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:138)
	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:56)
	at org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:259)
	at org.apache.http.impl.DefaultBHttpClientConnection.receiveResponseHeader(DefaultBHttpClientConnection.java:163)
	at org.apache.http.impl.conn.CPoolProxy.receiveResponseHeader(CPoolProxy.java:157)
	at org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:273)
	at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:125)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:272)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108)
	at org.apache.doris.flink.sink.writer.DorisStreamLoad.lambda$startLoad$0(DorisStreamLoad.java:248)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	... 1 more
`

**Comment by Jiang-HT** [comment]
Caused by: org.apache.flink.table.api.ValidationException: Cannot discover a connector using option: 'connector'='doris'
Adding dependencies doesn't work either?
