### ISSUE TITLE
[Bug] (mysql connector ssl) some version of jdbc may result connect error

### ISSUE THREAD

**Issue by eldenmoon** [apache/doris#20365]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

master

### What's Wrong?

**some version of jdbc may result connect error:**
mysql connector version:
```
<dependency>
            <groupId>mysql</groupId>
            <artifactId>mysql-connector-java</artifactId>
            <version>8.0.16</version>
        </dependency>
```

This version of mysql connector will cause connection error

### What You Expected?

no connection error

### How to Reproduce?

use the above connect version and run regression-test

```
2023-06-02 12:16:04,166 DEBUG (mysql-nio-pool-52|45304) [MysqlProto.negotiate():193] switch to ssl mode.
2023-06-02 12:16:04,167 DEBUG (mysql-nio-pool-52|45304) [AcceptListener.lambda$handleEvent$1():99] connect processor exception because 
java.lang.IndexOutOfBoundsException: null
        at java.io.ByteArrayOutputStream.write(ByteArrayOutputStream.java:151) ~[?:1.8.0_131]
        at org.apache.doris.mysql.MysqlSerializer.writeBytes(MysqlSerializer.java:69) ~[doris-fe.jar:1.2-SNAPSHOT]
        at org.apache.doris.mysql.MysqlErrPacket.writeTo(MysqlErrPacket.java:55) ~[doris-fe.jar:1.2-SNAPSHOT]
        at org.apache.doris.mysql.MysqlProto.sendResponsePacket(MysqlProto.java:104) ~[doris-fe.jar:1.2-SNAPSHOT]
        at org.apache.doris.mysql.MysqlProto.negotiate(MysqlProto.java:198) ~[doris-fe.jar:1.2-SNAPSHOT]
        at org.apache.doris.mysql.AcceptListener.lambda$handleEvent$1(AcceptListener.java:67) ~[doris-fe.jar:1.2-SNAPSHOT]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[?:1.8.0_131]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[?:1.8.0_131]
        at java.lang.Thread.run(Thread.java:748) ~[?:1.8.0_131]
```

### Anything Else?
enable_ssl = false will pass regression-test
_No response_

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Yukang-Lian** [comment]
I will work on it.
