### ISSUE TITLE
[Bug] ERROR when upgrade 1.2.4.1 to 1.2.5

### ISSUE THREAD

**Issue by huiwenhan** [apache/doris#21081]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

1.2.5

### What's Wrong?

when start FE,get following error:

2023-06-21 16:59:38,615 ERROR (leaderCheckpointer|105) [TableProperty.buildReplicaAllocation():304] should not happen when build replica allocation
org.apache.doris.common.AnalysisException: errCode = 2, detailMessage = Total replication num should between 3 and 32767
        at org.apache.doris.common.util.PropertyAnalyzer.analyzeReplicaAllocation(PropertyAnalyzer.java:711) ~[doris-fe.jar:1.2-SNAPSHOT]
        at org.apache.doris.catalog.TableProperty.buildReplicaAllocation(TableProperty.java:301) ~[doris-fe.jar:1.2-SNAPSHOT]
        at org.apache.doris.catalog.TableProperty.read(TableProperty.java:337) ~[doris-fe.jar:1.2-SNAPSHOT]
        at org.apache.doris.catalog.OlapTable.readFields(OlapTable.java:1279) ~[doris-fe.jar:1.2-SNAPSHOT]
        at org.apache.doris.catalog.Table.read(Table.java:377) ~[doris-fe.jar:1.2-SNAPSHOT]
        at org.apache.doris.catalog.Database.readFields(Database.java:571) ~[doris-fe.jar:1.2-SNAPSHOT]
        at org.apache.doris.datasource.InternalCatalog.loadDb(InternalCatalog.java:3420) ~[doris-fe.jar:1.2-SNAPSHOT]
        at org.apache.doris.catalog.Env.loadDb(Env.java:1735) ~[doris-fe.jar:1.2-SNAPSHOT]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_362]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_362]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_362]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_362]
        at org.apache.doris.persist.meta.MetaReader.read(MetaReader.java:94) ~[doris-fe.jar:1.2-SNAPSHOT]
        at org.apache.doris.catalog.Env.loadImage(Env.java:1672) ~[doris-fe.jar:1.2-SNAPSHOT]
        at org.apache.doris.master.Checkpoint.doCheckpoint(Checkpoint.java:144) ~[doris-fe.jar:1.2-SNAPSHOT]
        at org.apache.doris.master.Checkpoint.runAfterCatalogReady(Checkpoint.java:76) ~[doris-fe.jar:1.2-SNAPSHOT]
        at org.apache.doris.common.util.MasterDaemon.runOneCycle(MasterDaemon.java:58) ~[doris-fe.jar:1.2-SNAPSHOT]
        at org.apache.doris.common.util.Daemon.run(Daemon.java:116) ~[doris-fe.jar:1.2-SNAPSHOT]

and can'nt access FE console from http://FE:8030

### What You Expected?

upgraded correctly

### How to Reproduce?

upgrade 1.2.4.1 to 1.2.5

### Anything Else?

also following error:

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2023-06-21 16:58:38,456 ERROR (UNKNOWN 10.122.196.66_9010_1684135528476(-1)|1) [SpringApplication.reportFailure():824] Application run failed
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'defaultValidator' defined in class path resource [org/springframework/boot/autoconfigure/validation/ValidationAutoConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.validation.beanvalidation.LocalValidatorFactoryBean]: Factory method 'defaultValidator' threw exception; nested exception is java.lang.UnsupportedClassVersionError: org/hibernate/validator/HibernateValidator has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
        at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:658) ~[spring-shade-5-1.0.2-SNAPSHOT.jar:1.0.2-SNAPSHOT]
        at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:638) ~[spring-shade-5-1.0.2-SNAPSHOT.jar:1.0.2-SNAPSHOT]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1352) ~[spring-shade-5-1.0.2-SNAPSHOT.jar:1.0.2-SNAPSHOT]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1195) ~[spring-shade-5-1.0.2-SNAPSHOT.jar:1.0.2-SNAPSHOT]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:582) ~[spring-shade-5-1.0.2-SNAPSHOT.jar:1.0.2-SNAPSHOT]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542) ~[spring-shade-5-1.0.2-SNAPSHOT.jar:1.0.2-SNAPSHOT]
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335) ~[spring-shade-5-1.0.2-SNAPSHOT.jar:1.0.2-SNAPSHOT]
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-shade-5-1.0.2-SNAPSHOT.jar:1.0.2-SNAPSHOT]
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333) ~[spring-shade-5-1.0.2-SNAPSHOT.jar:1.0.2-SNAPSHOT]
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208) ~[spring-shade-5-1.0.2-SNAPSHOT.jar:1.0.2-SNAPSHOT]
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:955) ~[spring-shade-5-1.0.2-SNAPSHOT.jar:1.0.2-SNAPSHOT]
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:918) ~[spring-context-5.3.22.jar:5.3.22]
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:583) ~[spring-context-5.3.22.jar:5.3.22]
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:147) ~[spring-boot-2.7.3.jar:2.7.3]
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:734) ~[spring-boot-2.7.3.jar:2.7.3]
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:408) ~[spring-boot-2.7.3.jar:2.7.3]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:308) ~[spring-boot-2.7.3.jar:2.7.3]
        at org.springframework.boot.builder.SpringApplicationBuilder.run(SpringApplicationBuilder.java:164) ~[spring-boot-2.7.3.jar:2.7.3]
        at org.apache.doris.httpv2.HttpServer.start(HttpServer.java:134) ~[doris-fe.jar:1.2-SNAPSHOT]
        at org.apache.doris.PaloFe.start(PaloFe.java:160) ~[doris-fe.jar:1.2-SNAPSHOT]
        at org.apache.doris.PaloFe.main(PaloFe.java:73) ~[doris-fe.jar:1.2-SNAPSHOT]
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.validation.beanvalidation.LocalValidatorFactoryBean]: Factory method 'defaultValidator' threw exception; nested exception is java.lang.UnsupportedClassVersionError: org/hibernate/validator/HibernateValidator has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
        at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:185) ~[spring-shade-5-1.0.2-SNAPSHOT.jar:1.0.2-SNAPSHOT]
        at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:653) ~[spring-shade-5-1.0.2-SNAPSHOT.jar:1.0.2-SNAPSHOT]
        ... 20 more
Caused by: java.lang.UnsupportedClassVersionError: org/hibernate/validator/HibernateValidator has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
        at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_362]
        at java.lang.ClassLoader.defineClass(ClassLoader.java:756) ~[?:1.8.0_362]
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[?:1.8.0_362]
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:473) ~[?:1.8.0_362]
        at java.net.URLClassLoader.access$100(URLClassLoader.java:74) ~[?:1.8.0_362]
        at java.net.URLClassLoader$1.run(URLClassLoader.java:369) ~[?:1.8.0_362]
        at java.net.URLClassLoader$1.run(URLClassLoader.java:363) ~[?:1.8.0_362]
        at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_362]
        at java.net.URLClassLoader.findClass(URLClassLoader.java:362) ~[?:1.8.0_362]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0_362]
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352) ~[?:1.8.0_362]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_362]
        at java.lang.Class.forName0(Native Method) ~[?:1.8.0_362]
        at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_362]
        at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:370) ~[?:1.8.0_362]
        at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:404) ~[?:1.8.0_362]
        at java.util.ServiceLoader$1.next(ServiceLoader.java:480) ~[?:1.8.0_362]
        at javax.validation.Validation$GetValidationProviderListAction.loadProviders(Validation.java:356) ~[validation-api-1.1.0.Final.jar:?]
        at javax.validation.Validation$GetValidationProviderListAction.run(Validation.java:329) ~[validation-api-1.1.0.Final.jar:?]
        at javax.validation.Validation$GetValidationProviderListAction.getValidationProviderList(Validation.java:316) ~[validation-api-1.1.0.Final.jar:?]
        at javax.validation.Validation$DefaultValidationProviderResolver.getValidationProviders(Validation.java:299) ~[validation-api-1.1.0.Final.jar:?]
        at javax.validation.Validation$GenericBootstrapImpl.configure(Validation.java:257) ~[validation-api-1.1.0.Final.jar:?]
        at org.springframework.boot.validation.MessageInterpolatorFactory.getMessageInterpolator(MessageInterpolatorFactory.java:79) ~[spring-boot-2.7.3.jar:2.7.3]
        at org.springframework.boot.validation.MessageInterpolatorFactory.getObject(MessageInterpolatorFactory.java:70) ~[spring-boot-2.7.3.jar:2.7.3]
        at org.springframework.boot.autoconfigure.validation.ValidationAutoConfiguration.defaultValidator(ValidationAutoConfiguration.java:62) ~[spring-boot-autoconfigure-2.7.3.jar:2.7.3]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_362]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_362]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_362]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_362]
        at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154) ~[spring-shade-5-1.0.2-SNAPSHOT.jar:1.0.2-SNAPSHOT]
        at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:653) ~[spring-shade-5-1.0.2-SNAPSHOT.jar:1.0.2-SNAPSHOT]
        ... 20 more

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by stalary** [comment]
Check that all of your lib packages have been replaced.

**Comment by architectpub** [comment]
> Check that all of your lib packages have been replaced.

according the document ,copy the meta-data of 1.2.4 to 1.2.5 ,still has issue with FE.

Finally installed the new empty 1.2.5
