### ISSUE TITLE
[Problem] notify new FE type transfer

### ISSUE THREAD

**Issue by leryn1122** [apache/doris#21479]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

v1.2.5 from Aliyun CDN

### What's Wrong?

A single FE instance was installed but failed to restart, where the FE log told:

```log
2023-07-04 14:56:07,619 INFO (UNKNOWN 10.74.16.2_9010_1688453756005(-1)|1) [BDBEnvironment.setup():162] add helper[10.74.16.2:9010] as ReplicationGroupAdmin
2023-07-04 14:56:07,619 WARN (UNKNOWN 10.74.16.2_9010_1688453756005(-1)|1) [Env.notifyNewFETypeTransfer():2377] notify new FE type transfer: UNKNOWN
[2023-07-04 14:56:07] notify new FE type transfer: UNKNOWN
2023-07-04 14:56:07,620 ERROR (UNKNOWN 10.74.16.2_9010_1688453756005(-1)|1) [BDBEnvironment.setup():201] error to open replicated environment. will exit.
com.sleepycat.je.rep.ReplicaWriteException: (JE 18.3.12) Problem closing transaction 20. The current state is:UNKNOWN. The node transitioned to this state at:Tue Jul 04 14:56:02 CST 2023
        at com.sleepycat.je.rep.txn.ReadonlyTxn.disallowReplicaWrite(ReadonlyTxn.java:114) ~[je-18.3.14-doris-SNAPSHOT.jar:18.3.14-doris-SNAPSHOT]
        at com.sleepycat.je.dbi.DbTree.checkReplicaWrite(DbTree.java:880) ~[je-18.3.14-doris-SNAPSHOT.jar:18.3.14-doris-SNAPSHOT]
        at com.sleepycat.je.dbi.DbTree.doCreateDb(DbTree.java:579) ~[je-18.3.14-doris-SNAPSHOT.jar:18.3.14-doris-SNAPSHOT]
        at com.sleepycat.je.dbi.DbTree.createDb(DbTree.java:486) ~[je-18.3.14-doris-SNAPSHOT.jar:18.3.14-doris-SNAPSHOT]
        at com.sleepycat.je.Database.initNew(Database.java:174) ~[je-18.3.14-doris-SNAPSHOT.jar:18.3.14-doris-SNAPSHOT]
        at com.sleepycat.je.Environment.setupDatabase(Environment.java:864) ~[je-18.3.14-doris-SNAPSHOT.jar:18.3.14-doris-SNAPSHOT]
        at com.sleepycat.je.Environment.openDatabase(Environment.java:668) ~[je-18.3.14-doris-SNAPSHOT.jar:18.3.14-doris-SNAPSHOT]
        at org.apache.doris.journal.bdbje.BDBEnvironment.setup(BDBEnvironment.java:182) ~[doris-fe.jar:1.2-SNAPSHOT]
        at org.apache.doris.journal.bdbje.BDBJEJournal.open(BDBJEJournal.java:303) ~[doris-fe.jar:1.2-SNAPSHOT]
        at org.apache.doris.persist.EditLog.open(EditLog.java:1038) ~[doris-fe.jar:1.2-SNAPSHOT]
        at org.apache.doris.catalog.Env.initialize(Env.java:863) ~[doris-fe.jar:1.2-SNAPSHOT]
        at org.apache.doris.PaloFe.start(PaloFe.java:138) ~[doris-fe.jar:1.2-SNAPSHOT]
        at org.apache.doris.PaloFe.main(PaloFe.java:73) ~[doris-fe.jar:1.2-SNAPSHOT]
```

`doris-meta/image/ROLE` shows below. I suppose it should be `Leader` maybe?

```
#Tue Jul 04 14:55:56 CST 2023
name=10.74.16.2_9010_1688453756005
role=FOLLOWER
```

`doris-meta/image/VERSION` shows:

```
#Tue Jul 04 14:55:56 CST 2023
token=6110227e-beb0-45c0-92f7-7b835a1f2952
clusterId=569363313
```

It successed starting in early stages. After I removed the data and added `lower_case_table_names` and done reinitialization, it failed to restart.
3 BE instances were running, but not added to FE yet BTW.

Configuration:

env: test
os: kylin
arch: x86_64
version: doris-1.2.5
jdk version: 1.8
cluster: 1 FE / 3BEs

`conf/be.conf` differs from default, see blow:

```ini
JAVA_HOME="$(cd -P "$(dirname $(readlink -f $(which java)))/.." && pwd || exit 1)"
LOG_DIR = /opt/doris-log
meta_dir = /opt/doris-meta
priority_networks = 10.74.16.0/2
lower_case_table_names = 1
```

Try:

I've skim the FAQ and issues but nothing found.
I tries to  reboot FE (and os) / remove leftover meta & log / stop BE instances (not added to FE yet).

### What You Expected?

Run a cluster consisted of 1 FE and 3 BEs as expected.

### How to Reproduce?

See above.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by stalary** [comment]
Leader alse ROLE=FOLLOWER in doris-meta/image/ROLE, this no problem.
Are you first start this cluster or upgrade?

**Comment by leryn1122** [comment]
Solved. Yes, first start new cluster, but I tried to reinitialize the cluster.

I reviewed issues related again today, it was found root cause is that my cooporation's vm template had inapproriate disk partitions in data dir in size of ~10G only. I've noticed SA to extend the volume.

However I don't why it started succussfully in the first time before reconfiguring `lower_case_table_names`.
