### ISSUE TITLE
[Bug] Failed to init stats cleaner java.lang.RuntimeException: DB: default_cluster:__internal_schema not exists

### ISSUE THREAD

**Issue by nizq** [apache/doris#21914]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

version: 2.0.0-alpha 
docker image: apache/doris:2.0.0_alpha-fe-x86_64

docker-compose.yml

```yaml
version: "3"
services:
   fe:
     image: apache/doris:2.0.0_alpha-fe-x86_64
     hostname: fe
     environment:
      - FE_SERVERS=fe1:172.16.2.103:9010
      - FE_ID=1
     volumes:
      - ./fe/doris-meta/:/opt/apache-doris/fe/doris-meta/
      - ./fe/log/:/opt/apache-doris/fe/log/
     network_mode: host
   be:
     image: apache/doris:2.0.0_alpha-be-x86_64
     hostname: be
     environment:
      - FE_SERVERS=fe1:172.16.2.103:9010
      - BE_ADDR=172.16.2.103:9050
     volumes:
      - ./be/storage/:/opt/apache-doris/be/storage/
      - ./be/script/:/docker-entrypoint-initdb.d/
     depends_on:
       - fe
     network_mode: host
```

### What's Wrong?

执行`docker compose up -d`之后，fe显示如下错误信息：

```
2023-07-18 05:50:11,578 INFO (stateListener|90) [Env.checkLowerCaseTableNames():1537] lower_case_table_names is 0
2023-07-18 05:50:11,579 INFO (stateListener|90) [Env.transferToMaster():1352] master finished to replay journal, can write now.
2023-07-18 05:50:11,582 INFO (stateListener|90) [Env$4.runOneCycle():2429] finished to transfer FE type to MASTER
2023-07-18 05:50:11,583 INFO (stateListener|90) [Env$4.runOneCycle():2342] begin to transfer FE type from MASTER to MASTER
2023-07-18 05:50:11,607 INFO (UNKNOWN 172.16.2.103_9010_1689659398444(-1)|1) [Env.waitForReady():891] catalog is ready. FE type: MASTER
2023-07-18 05:50:11,608 WARN (Statistics Table Cleaner|46) [StatisticsCleaner.init():110] Failed to init stats cleaner
java.lang.RuntimeException: DB: default_cluster:__internal_schema not exists
	at org.apache.doris.statistics.util.StatisticsUtil.lambda$findTable$1(StatisticsUtil.java:299) ~[doris-fe.jar:1.2-SNAPSHOT]
	at org.apache.doris.datasource.CatalogIf.getDbOrException(CatalogIf.java:99) ~[doris-fe.jar:1.2-SNAPSHOT]
	at org.apache.doris.statistics.util.StatisticsUtil.findTable(StatisticsUtil.java:298) ~[doris-fe.jar:1.2-SNAPSHOT]
	at org.apache.doris.statistics.StatisticsCleaner.init(StatisticsCleaner.java:101) ~[doris-fe.jar:1.2-SNAPSHOT]
	at org.apache.doris.statistics.StatisticsCleaner.clear(StatisticsCleaner.java:82) ~[doris-fe.jar:1.2-SNAPSHOT]
	at org.apache.doris.statistics.StatisticsCleaner.runAfterCatalogReady(StatisticsCleaner.java:78) ~[doris-fe.jar:1.2-SNAPSHOT]
	at org.apache.doris.common.util.MasterDaemon.runOneCycle(MasterDaemon.java:58) ~[doris-fe.jar:1.2-SNAPSHOT]
	at org.apache.doris.common.util.Daemon.run(Daemon.java:116) ~[doris-fe.jar:1.2-SNAPSHOT]
2023-07-18 05:50:11,616 INFO (leaderCheckpointer|91) [BDBJEJournal.getFinalizedJournalId():448] database names: 1 
2023-07-18 05:50:11,616 INFO (leaderCheckpointer|91) [Checkpoint.doCheckpoint():95] last checkpoint journal id: 0, current finalized journal id: 0
2023-07-18 05:50:11,657 INFO (stream_load_record_manager|34) [StreamLoadRecordMgr.runAfterCatalogReady():336] finished to pull stream load records of all backends. record size: 0, cost: 0 ms
```

### What You Expected?

-------------------------------

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wsmGo** [comment]
同问

**Comment by tonychen0716** [comment]
同问

**Comment by mickdelaney** [comment]
+1

**Comment by tudouzhao** [comment]
<img width="1054" alt="image" src="https://github.com/apache/doris/assets/22593171/fae174f0-15c9-43a7-a427-070fa4058f1f">
测试了下，这个是warn日志，其原因来自于线程检查的同时，该库尚未创建成功；后续会创建成功，不会影响服务的正常启动；如上述图示

**Comment by KONEONE** [comment]
我也遇到了，连访问web都不行

**Comment by ixzc** [comment]
Don't worry, this will not affect the normal use.

**Comment by tchivs** [comment]
我的也是，web都打不开，一直提示2023-11-10 15:13:22 2023-11-10 07:13:22,934 WARN (Thread-53|99) [InternalSchemaInitializer.run():75] Statistics storage initiated failed, will try again later
2023-11-10 15:13:22 org.apache.doris.common.DdlException: errCode = 2, detailMessage = Cluster default_cluster has no available capacity
