### ISSUE TITLE
[Bug] FE start failed on centos

### ISSUE THREAD

**Issue by chenjienn** [apache/doris#22002]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

2.0-beta

### What's Wrong?

按照部署文档，通过./bin/start_fe.sh --daemon命令启动后，在fe.log里先是报了下面的错：

> Failed to init stats cleaner
java.lang.RuntimeException: Table: `internal.default_cluster:__internal_schema.column_statistics` not exists
        at org.apache.doris.statistics.util.StatisticsUtil.findTable(StatisticsUtil.java:329) ~[doris-fe.jar:1.2-SNAPSHOT]
        at org.apache.doris.statistics.StatisticsCleaner.init(StatisticsCleaner.java:104) ~[doris-fe.jar:1.2-SNAPSHOT]
        at org.apache.doris.statistics.StatisticsCleaner.clear(StatisticsCleaner.java:82) ~[doris-fe.jar:1.2-SNAPSHOT]
        at org.apache.doris.statistics.StatisticsCleaner.runAfterCatalogReady(StatisticsCleaner.java:78) ~[doris-fe.jar:1.2-SNAPSHOT]
        at org.apache.doris.common.util.MasterDaemon.runOneCycle(MasterDaemon.java:58) ~[doris-fe.jar:1.2-SNAPSHOT]
        at org.apache.doris.common.util.Daemon.run(Daemon.java:116) ~[doris-fe.jar:1.2-SNAPSHOT]

然后就一直重复报下面的错：

> Statistics storage initiated failed, will try again later
org.apache.doris.common.DdlException: errCode = 2, detailMessage = System has no available disk capacity or no available BE nodes
        at org.apache.doris.system.SystemInfoService.checkAvailableCapacity(SystemInfoService.java:815) ~[doris-fe.jar:1.2-SNAPSHOT]
        at org.apache.doris.datasource.InternalCatalog.createTable(InternalCatalog.java:1072) ~[doris-fe.jar:1.2-SNAPSHOT]
        at org.apache.doris.catalog.InternalSchemaInitializer.createTbl(InternalSchemaInitializer.java:81) ~[doris-fe.jar:1.2-SNAPSHOT]
        at org.apache.doris.catalog.InternalSchemaInitializer.run(InternalSchemaInitializer.java:72) ~[doris-fe.jar:1.2-SNAPSHOT]

磁盘空间还剩40多G，BE还没启动，用datagrip连接fe的mysql，报上面的错，连不上

### What You Expected?

通过./bin/start_fe.sh --daemon命令能正常启动

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by tbwtd** [comment]
我目前2.01版本也是这个报错    这个不是bug  是配置问题吗？

**Comment by zfanswer** [comment]
+1 怎么关掉了，有解决方法吗

**Comment by zzccctv** [comment]
我目前也是这个报错

**Comment by sqnczzl** [comment]
目前我也遇到同样的问题，怎么解决？

**Comment by zzccctv** [comment]
问题已经解决了，需要修改fe.conf中的priority_networks = 这个配置，改成机器的实际网段

**Comment by sqnczzl** [comment]
fe,conf已经配置上priority_networks =，并且这个已经是机器的实际网段地址，但是fe 仍然是启动不起来

**Comment by zzccctv** [comment]
配置好之后，启动be，异常就没有了。

**Comment by shaotianfeng** [comment]
我也是这样（fe,conf已经配置上priority_networks =，并且这个已经是机器的实际网段地址，但是fe 仍然是启动不起来），be可以启动起来，但fe启动不起来，不知道哪里出了问题，  相同配置1.2.6版本没问题

**Comment by zzccctv** [comment]
一样的错，改网段后，启动fe然后通过mysql进行be配置,最后启动be就可以了.

**Comment by shaotianfeng** [comment]
网段也改了，是之前1.2.6版本的网段，然后起不起来。。。

**Comment by zzccctv** [comment]
配置完成后删除doris-meta试试

**Comment by khan-lau** [comment]
> 我目前2.01版本也是这个报错 这个不是bug 是配置问题吗？

多网卡指定 `priority_networks ` 能确保线路正确; 
如果是fe, 则需删除 `doris-meta`目录后重启

**Comment by xinghalo321** [comment]
```
2023-12-11 11:32:32,699 INFO (Thread-48|97) [InternalCatalog.createDb():423] create database[default_cluster:__internal_schema] which already exists
2023-12-11 11:32:32,700 WARN (Thread-48|97) [InternalSchemaInitializer.run():76] Statistics storage initiated failed, will try again later
org.apache.doris.common.DdlException: errCode = 2, detailMessage = System has no available disk capacity or no available BE nodes
	at org.apache.doris.system.SystemInfoService.checkAvailableCapacity(SystemInfoService.java:817) ~[doris-fe.jar:1.2-SNAPSHOT]
	at org.apache.doris.datasource.InternalCatalog.createTable(InternalCatalog.java:1085) ~[doris-fe.jar:1.2-SNAPSHOT]
	at org.apache.doris.catalog.InternalSchemaInitializer.createTbl(InternalSchemaInitializer.java:130) ~[doris-fe.jar:1.2-SNAPSHOT]
	at org.apache.doris.catalog.InternalSchemaInitializer.run(InternalSchemaInitializer.java:74) ~[doris-fe.jar:1.2-SNAPSHOT]
```

配置了priority_networks，也删除了doris-meta，还是不行；甚至重装了主机都无法修复....
是不是ip_v6的网段识别有问题：
priority_networks = FDBE:DC05:3::/48

**Comment by s-luping** [comment]
![Snipaste_2024-01-28_00-24-50](https://github.com/apache/doris/assets/53071081/dd3cb7c3-78ae-43d7-a303-e20edc957a85)

**Comment by s-luping** [comment]
![Uploading Snipaste_2024-01-28_00-26-01.png…]()

**Comment by s-luping** [comment]
![Snipaste_2024-01-28_00-26-01](https://github.com/apache/doris/assets/53071081/08c36cd6-ca3c-4052-9fce-dba43697bb1c)

**Comment by s-luping** [comment]
> ![Snipaste_2024-01-28_00-24-50](https://private-user-images.githubusercontent.com/53071081/300190631-dd3cb7c3-78ae-43d7-a303-e20edc957a85.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYzNzMxMTYsIm5iZiI6MTcwNjM3MjgxNiwicGF0aCI6Ii81MzA3MTA4MS8zMDAxOTA2MzEtZGQzY2I3YzMtNzhhZS00M2Q3LWEzMDMtZTIwZWRjOTU3YTg1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI3VDE2MjY1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFlNjVjNDMyM2I2NmFhNGQ4YzdkMDM1NzAxZmFlYTk5NzRkMmI4NWI3OTM0ZTZmYzM4ODBiODYwYzc3NmZkOTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-WoAcntHWoWgWQzdcOmf17RO4E8g7yjTPHdVRhl66ms)

需要把BE节点添加进去才行

**Comment by TanLingxiao** [comment]
The right way to start fe is  
```
1. ./bin/start_fe.sh --helper xx.xx.xx.xx:9010 --daemon
2. ALTER SYSTEM ADD FOLLOWER "10.10.10.3:9010";
```
[document](https://doris.apache.org/zh-CN/docs/admin-manual/cluster-management/elastic-expansion?_highlight=%E6%89%A9%E5%AE%B9#fe-%E6%89%A9%E5%AE%B9%E5%92%8C%E7%BC%A9%E5%AE%B9)

**Comment by baimafeima-yf** [comment]
> fe,conf已经配置上priority_networks =，并且这个已经是机器的实际网段地址，但是fe 仍然是启动不起来

你好 你解决了吗，我也遇到了这个问题 2.0.11版本

**Comment by baimafeima-yf** [comment]
> ```
> 2023-12-11 11:32:32,699 INFO (Thread-48|97) [InternalCatalog.createDb():423] create database[default_cluster:__internal_schema] which already exists
> 2023-12-11 11:32:32,700 WARN (Thread-48|97) [InternalSchemaInitializer.run():76] Statistics storage initiated failed, will try again later
> org.apache.doris.common.DdlException: errCode = 2, detailMessage = System has no available disk capacity or no available BE nodes
> 	at org.apache.doris.system.SystemInfoService.checkAvailableCapacity(SystemInfoService.java:817) ~[doris-fe.jar:1.2-SNAPSHOT]
> 	at org.apache.doris.datasource.InternalCatalog.createTable(InternalCatalog.java:1085) ~[doris-fe.jar:1.2-SNAPSHOT]
> 	at org.apache.doris.catalog.InternalSchemaInitializer.createTbl(InternalSchemaInitializer.java:130) ~[doris-fe.jar:1.2-SNAPSHOT]
> 	at org.apache.doris.catalog.InternalSchemaInitializer.run(InternalSchemaInitializer.java:74) ~[doris-fe.jar:1.2-SNAPSHOT]
> ```
> 
> 配置了priority_networks，也删除了doris-meta，还是不行；甚至重装了主机都无法修复.... 是不是ip_v6的网段识别有问题： priority_networks = FDBE:DC05:3::/48

您好 ，您解决了吗 ，我也是一样的问题，配置了priority_networks，也删除了doris-meta，还是不行

**Comment by AiTian1211** [comment]
你们其他FE节点第一次启动时是不是没有指定第一个FE节点？./fe/bin/start_fe.sh --helper 10.10.10.16:9010 --daemon
我也遇到这个问题，但我是其他节点第一次启动时忘记指定第一个启动的FE节点了，把doris-meta目录删除后通过./fe/bin/start_fe.sh --helper 10.10.10.16:9010 --daemon启动就解决了
