### ISSUE TITLE
[Bug] Mysql-JDBC  can not adapter match_all pr match_all fuction

### ISSUE THREAD

**Issue by chenchurong** [apache/doris#22161]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

2.0-beta (Latest)

### What's Wrong?

can not executeQuery by jdbc statement when i use [inverted index]

**i guess mysql driver can not Adapter  fuction match_all or match_any**

![Uploading image.png…]()

### What You Expected?

get result by query sql

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by chenchurong** [comment]
` org.springframework.jdbc.UncategorizedSQLException: StatementCallback; uncategorized SQLException for SQL [select count(*) from ( select   entity_code,   credit_code,   company_name_source from   dim_kp_company_main where company_name_source match_all  '万科' ) a]; SQL state [HY000]; error code [1105]; errCode = 2, detailMessage = Syntax error in line 1:
...where company_name_source match_all  '万科' ) a
                             ^
Encountered: IDENTIFIER
Expected: ||, COMMA
; nested exception is java.sql.SQLException: errCode = 2, detailMessage = Syntax error in line 1:
...where company_name_source match_all  '万科' ) a
                             ^
Encountered: IDENTIFIER
Expected: ||, COMMA

	at org.springframework.jdbc.core.JdbcTemplate.translateException(JdbcTemplate.java:1542)
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:393)
	at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:465)
	at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:475)
	at org.springframework.jdbc.core.JdbcTemplate.queryForObject(JdbcTemplate.java:508)
	at org.springframework.jdbc.core.JdbcTemplate.queryForObject(JdbcTemplate.java:515)
	at com.lighthouse.chaos.util.DorisQueryService.getTotalCount(DorisQueryService.java:128)
	at com.lighthouse.chaos.util.DorisQueryService.selectForPagination(DorisQueryService.java:49)
	at com.lighthouse.chaos.util.DorisQueryService$$FastClassBySpringCGLIB$$ae975b77.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:793)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763)
	at 
`

**Comment by echo-hhj** [comment]
What's your version of Doris?

**Comment by echo-hhj** [comment]
在2.0beta中使用倒排索引建表，并成功使用索引查询，您可以再尝试一下，或者把建表语句和查询语句给我，我帮您验证一下
<img width="703" alt="image" src="https://github.com/apache/doris/assets/50286010/54192cc1-9357-40f1-905c-51b6cee11377">
<img width="468" alt="image" src="https://github.com/apache/doris/assets/50286010/35e08389-f90b-482b-80a3-5c2c88eaea78">
<img width="930" alt="image" src="https://github.com/apache/doris/assets/50286010/23729556-4b80-4a9c-b747-bdcec04142de">

**Comment by echo-hhj** [comment]
![VWuodmehYX](https://github.com/apache/doris/assets/50286010/5767b4b8-7a32-416d-9ad7-e5159b8fc025)
