### ISSUE TITLE
[Bug] Setup Doris as Airbyte Destination failed! Communications link failure.

### ISSUE THREAD

**Issue by truonglac2603** [apache/doris#22994]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

Airbyte ver 0.50.16
Doris Docker container - both FE & BE images are 2.0.0-alpha

### What's Wrong?

When i was trying to setup an existing Doris to be a Destination in Airbyte, it kept throwing error: Communications link error

        at io.airbyte.integrations.destination.doris.DorisDestination.getConsumer(DorisDestination.java:81)
        ... 3 more
Caused by: com.mysql.cj.exceptions.CJCommunicationsException: Communications link failure
The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
        at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:61)
        at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:105)
        at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:151)
        at com.mysql.cj.exceptions.ExceptionFactory.createCommunicationsException(ExceptionFactory.java:167)
        at com.mysql.cj.protocol.a.NativeProtocol.negotiateSSLConnection(NativeProtocol.java:361)
        at com.mysql.cj.protocol.a.NativeAuthenticationProvider.negotiateSSLConnection(NativeAuthenticationProvider.java:777)
        at com.mysql.cj.protocol.a.NativeAuthenticationProvider.proceedHandshakeWithPluggableAuthentication(NativeAuthenticationProvider.java:486)
        at com.mysql.cj.protocol.a.NativeAuthenticationProvider.connect(NativeAuthenticationProvider.java:202)
        at com.mysql.cj.protocol.a.NativeProtocol.connect(NativeProtocol.java:1452)
        at com.mysql.cj.NativeSession.connect(NativeSession.java:165)
        at com.mysql.cj.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:955)
        at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:825)
        ... 10 more

### What You Expected?

create a Doris destination in Airbyte successfully after all information (host, ports, database, username) were configured correctly.

### How to Reproduce?

Create new Doris destination in Airbyte with Doris deployed with docker in server. 

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by truonglac2603** [comment]
So i changed from deploying with Docker (3FE&3BE) to standard deployment (1FE&1BE) and i worked, but i still did not figure out why.
Is this problem related to Docker, SSL or CA-Certificates?

**Comment by girishb89** [comment]
@truonglac2603 I have faced similar issue. It seems to be due to jdbc driver incompatibility. Updating mysql-connector-java to latest 8.0.33 should solve the problem. Would be great if someone looks into this, should be a simple fix.
