### ISSUE TITLE
[Bug] When passing Streamsets, an error is reported when extracting data to Doris through Oracle CDC

### ISSUE THREAD

**Issue by 126wang** [apache/doris#23562]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

apache-doris-2.0.0-bin-x64

### What's Wrong?

When passing Streamsets, an error is reported when extracting data to Doris through Oracle CDC：
Pipeline Status: RUNNING_ERROR: JDBC_14 - Error processing batch: [SQLState:HY000][ErrorCode:5025] Insert has filtered data in strict mode, tracking_url=http://10.0.142.38:8040/api/_load_error_log?file=__shard_113/error_log_insert_stmt_92aeec68b27e44bb-9768e33ea9dfbfca_92aeec68b27e44bb_9768e33ea9dfbfca SQLState: HY000 Error Code: 5025 Message: Insert has filtered data in strict mode, tracking_url=http://10.0.142.38:8040/api/_load_error_log?file=__shard_113/error_log_insert_stmt_92aeec68b27e44bb-9768e33ea9dfbfca_92aeec68b27e44bb_9768e33ea9dfbfca
com.streamsets.pipeline.api.StageException: JDBC_14 - Error processing batch: [SQLState:HY000][ErrorCode:5025] Insert has filtered data in strict mode, tracking_url=http://10.0.142.38:8040/api/_load_error_log?file=__shard_113/error_log_insert_stmt_92aeec68b27e44bb-9768e33ea9dfbfca_92aeec68b27e44bb_9768e33ea9dfbfca
SQLState: HY000
Error Code: 5025
Message: Insert has filtered data in strict mode, tracking_url=http://10.0.142.38:8040/api/_load_error_log?file=__shard_113/error_log_insert_stmt_92aeec68b27e44bb-9768e33ea9dfbfca_92aeec68b27e44bb_9768e33ea9dfbfca

	at com.streamsets.pipeline.lib.jdbc.JdbcBaseRecordWriter.handleSqlException(JdbcBaseRecordWriter.java:710)
	at com.streamsets.pipeline.lib.jdbc.JdbcGenericRecordWriter.handleBatchUpdateException(JdbcGenericRecordWriter.java:371)
	at com.streamsets.pipeline.lib.jdbc.JdbcGenericRecordWriter.processQueue(JdbcGenericRecordWriter.java:259)
	at com.streamsets.pipeline.lib.jdbc.JdbcGenericRecordWriter.write(JdbcGenericRecordWriter.java:175)
	at com.streamsets.pipeline.lib.jdbc.JdbcGenericRecordWriter.writeBatch(JdbcGenericRecordWriter.java:122)
	at com.streamsets.pipeline.lib.jdbc.JdbcUtil.write(JdbcUtil.java:1201)
	at com.streamsets.pipeline.stage.destination.jdbc.JdbcTarget.write(JdbcTarget.java:324)
	at com.streamsets.pipeline.stage.destination.jdbc.JdbcTarget.write(JdbcTarget.java:304)
	at com.streamsets.pipeline.api.base.configurablestage.DTarget.write(DTarget.java:34)
	at com.streamsets.datacollector.runner.StageRuntime.lambda$execute$2(StageRuntime.java:303)
	at com.streamsets.datacollector.runner.StageRuntime.execute(StageRuntime.java:244)
	at com.streamsets.datacollector.runner.StageRuntime.execute(StageRuntime.java:311)
	at com.streamsets.datacollector.runner.StagePipe.process(StagePipe.java:221)
	at com.streamsets.datacollector.execution.runner.common.ProductionPipelineRunner.processPipe(ProductionPipelineRunner.java:864)
	at com.streamsets.datacollector.execution.runner.common.ProductionPipelineRunner.lambda$executeRunner$3(ProductionPipelineRunner.java:908)
	at com.streamsets.datacollector.runner.PipeRunner.acceptConsumer(PipeRunner.java:207)
	at com.streamsets.datacollector.runner.PipeRunner.forEachInternal(PipeRunner.java:152)
	at com.streamsets.datacollector.runner.PipeRunner.executeBatch(PipeRunner.java:132)
	at com.streamsets.datacollector.execution.runner.common.ProductionPipelineRunner.executeRunner(ProductionPipelineRunner.java:907)
	at com.streamsets.datacollector.execution.runner.common.ProductionPipelineRunner.runSourceLessBatch(ProductionPipelineRunner.java:885)
	at com.streamsets.datacollector.execution.runner.common.ProductionPipelineRunner.runPollSource(ProductionPipelineRunner.java:609)
	at com.streamsets.datacollector.execution.runner.common.ProductionPipelineRunner.run(ProductionPipelineRunner.java:400)
	at com.streamsets.datacollector.runner.Pipeline.run(Pipeline.java:535)
	at com.streamsets.datacollector.execution.runner.common.ProductionPipeline.run(ProductionPipeline.java:112)
	at com.streamsets.datacollector.execution.runner.common.ProductionPipelineRunnable.run(ProductionPipelineRunnable.java:75)
	at com.streamsets.datacollector.execution.runner.standalone.StandaloneRunner.startInternal(StandaloneRunner.java:762)
	at com.streamsets.datacollector.execution.runner.standalone.StandaloneRunner.start(StandaloneRunner.java:755)
	at com.streamsets.datacollector.execution.runner.common.AsyncRunner.lambda$start$3(AsyncRunner.java:157)
	at com.streamsets.pipeline.lib.executor.SafeScheduledExecutorService$SafeCallable.lambda$call$0(SafeScheduledExecutorService.java:226)
	at com.streamsets.datacollector.security.GroupsInScope.execute(GroupsInScope.java:34)
	at com.streamsets.pipeline.lib.executor.SafeScheduledExecutorService$SafeCallable.call(SafeScheduledExecutorService.java:222)
	at com.streamsets.pipeline.lib.executor.SafeScheduledExecutorService$SafeCallable.lambda$call$0(SafeScheduledExecutorService.java:226)
	at com.streamsets.datacollector.security.GroupsInScope.execute(GroupsInScope.java:34)
	at com.streamsets.pipeline.lib.executor.SafeScheduledExecutorService$SafeCallable.call(SafeScheduledExecutorService.java:222)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at com.streamsets.datacollector.metrics.MetricSafeScheduledExecutorService$MetricsTask.run(MetricSafeScheduledExecutorService.java:100)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.sql.BatchUpdateException: Insert has filtered data in strict mode, tracking_url=http://10.0.142.38:8040/api/_load_error_log?file=__shard_113/error_log_insert_stmt_92aeec68b27e44bb-9768e33ea9dfbfca_92aeec68b27e44bb_9768e33ea9dfbfca
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.cj.util.Util.handleNewInstance(Util.java:192)
	at com.mysql.cj.util.Util.getInstance(Util.java:167)
	at com.mysql.cj.util.Util.getInstance(Util.java:174)
	at com.mysql.cj.jdbc.exceptions.SQLError.createBatchUpdateException(SQLError.java:224)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeBatchSerially(ClientPreparedStatement.java:853)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeBatchInternal(ClientPreparedStatement.java:435)
	at com.mysql.cj.jdbc.StatementImpl.executeBatch(StatementImpl.java:796)
	at com.zaxxer.hikari.pool.ProxyStatement.executeBatch(ProxyStatement.java:128)
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeBatch(HikariProxyPreparedStatement.java)
	at com.streamsets.pipeline.lib.jdbc.JdbcGenericRecordWriter.processQueue(JdbcGenericRecordWriter.java:253)
	... 38 more
Caused by: java.sql.SQLException: Insert has filtered data in strict mode, tracking_url=http://10.0.142.38:8040/api/_load_error_log?file=__shard_113/error_log_insert_stmt_92aeec68b27e44bb-9768e33ea9dfbfca_92aeec68b27e44bb_9768e33ea9dfbfca
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:129)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:953)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1092)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeBatchSerially(ClientPreparedStatement.java:832)
	... 43 more

### What You Expected?

I wish it was possible to use Doris with streamsets

### How to Reproduce?

![image](https://github.com/apache/doris/assets/63099173/87c852f2-e5a5-4ec1-8815-bb42d59aab1d)
This is the pipeline I use in streamsets.

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by JNSimba** [comment]
It is a data quality error, you can click on that url to see the detailed error

**Comment by 126wang** [comment]
This error seems to be a data quality problem, but I did not set non-empty restrictions in Doris. It stands to reason that this error should not occur. At the same time, I also wrote the data stream to the file and found no missing values.
