### ISSUE TITLE
[Bug] 在arm架构服务器下 部署 doris2.0版本失败，启动一台fe后通过jdbc连接报错，There is no scanNode Backend available

### ISSUE THREAD

**Issue by weAreFriendYo** [apache/doris#23567]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

2.0.0

### What's Wrong?

在arm架构下部署doris，通过jdbc连接fe，注册fe、be报错

### What You Expected?

java.sql.SQLException: errCode = 2, detailMessage = There is no scanNode Backend available.
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:129)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:828)
	at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:448)
	at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:241)
	at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:198)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:247)
	at com.example.demo2.Demo2Application.main(Demo2Application.java:33)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by ixzc** [comment]
it's a bug. we will fix it later.
You can use mysql client register be first to solve this problem.
