### ISSUE TITLE
[Bug] fe cannot restart base on latest master code.

### ISSUE THREAD

**Issue by zerozhaorui** [apache/doris#24807]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

2.0.1

### What's Wrong?

fe.out shows:

SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.slf4j.impl.Reload4jLoggerFactory]
[INFO] Env name of: {} is: {}ELECTABLEFE_STATEFULSET
[INFO] Env name of: {} is: {}BACKENDBE_STATEFULSET
[INFO] Env name of: {} is: {}BACKEND_CNCN_STATEFULSET
java.io.IOException: java.lang.reflect.InvocationTargetException
        at org.apache.doris.persist.meta.MetaReader.read(MetaReader.java:119)
        at org.apache.doris.catalog.Env.loadImage(Env.java:1777)
        at org.apache.doris.catalog.Env.initialize(Env.java:937)
        at org.apache.doris.DorisFE.start(DorisFE.java:163)
        at org.apache.doris.DorisFE.main(DorisFE.java:83)
Caused by: java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.doris.persist.meta.MetaReader.read(MetaReader.java:116)
        ... 4 more
Caused by: java.io.EOFException
        at java.io.DataInputStream.readFully(DataInputStream.java:197)
        at org.apache.doris.common.io.Text.readString(Text.java:415)
        at org.apache.doris.statistics.AnalysisManager.readAutoJobs(AnalysisManager.java:944)
        at org.apache.doris.statistics.AnalysisManager.readFields(AnalysisManager.java:922)
        at org.apache.doris.catalog.Env.loadAnalysisManager(Env.java:2101)
        ... 9 more

### What You Expected?

start success!!

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zerozhaorui** [comment]
I found a similar issue:  https://github.com/apache/doris/issues/12136
But the Exception is not same.
