### ISSUE TITLE
[Bug] doris的FE节点起不来

### ISSUE THREAD

**Issue by Charlie19961010** [apache/doris#25141]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

doris-1.2.4.1

### What's Wrong?

[2023-10-09 09:35:42] notify new FE type transfer: UNKNOWN
com.sleepycat.je.EnvironmentFailureException: (JE 18.3.12) Environment must be closed, caused by: com.sleepycat.je.EnvironmentFailureException: Environment invalid because of previous exception: (JE 18.3.12) 172.23.108.101_9010_1695259644078(7):/bigdata/doris-meta/bdb  Feeder: 172.23.108.103_9010_1695361282114(6). The environments have the same name: PALO_JOURNAL_GROUP but represent different environment instances. The environment at the master has UUID 1dd6dcc8-24cc-4c68-8cd5-1ce4681b2706, while the replica 172.23.108.101_9010_1695259644078 has UUID: c4bddb79-a8ec-4e63-b1e5-d81d5e596a42 HANDSHAKE_ERROR: Error during the handshake between two nodes. Some validity or compatibility check failed, preventing further communication between the nodes. Environment is invalid and must be closed.
	at com.sleepycat.je.EnvironmentFailureException.wrapSelf(EnvironmentFailureException.java:230)
	at com.sleepycat.je.dbi.EnvironmentImpl.checkIfInvalid(EnvironmentImpl.java:1835)
	at com.sleepycat.je.log.LogManager.getLogEntry(LogManager.java:848)
	at com.sleepycat.je.log.LogManager.getLogEntry(LogManager.java:802)
	at com.sleepycat.je.log.LogManager.getLogEntryHandleNotFound(LogManager.java:956)
	at com.sleepycat.je.dbi.DiskOrderedScanner.fetchEntry(DiskOrderedScanner.java:2068)
	at com.sleepycat.je.dbi.DiskOrderedScanner.fetchAndProcessBINs(DiskOrderedScanner.java:1640)
	at com.sleepycat.je.dbi.DiskOrderedScanner.scanSerial(DiskOrderedScanner.java:789)
	at com.sleepycat.je.dbi.DiskOrderedScanner.scan(DiskOrderedScanner.java:708)
	at com.sleepycat.je.dbi.DatabaseImpl.count(DatabaseImpl.java:1510)
	at com.sleepycat.je.Database.count(Database.java:2042)
	at org.apache.doris.journal.bdbje.BDBJEJournal.getMaxJournalId(BDBJEJournal.java:257)
	at org.apache.doris.journal.bdbje.BDBJEJournal.open(BDBJEJournal.java:339)
	at org.apache.doris.persist.EditLog.open(EditLog.java:1038)
	at org.apache.doris.catalog.Env.initialize(Env.java:863)
	at org.apache.doris.PaloFe.start(PaloFe.java:138)
	at org.apache.doris.PaloFe.main(PaloFe.java:73)
Caused by: com.sleepycat.je.EnvironmentFailureException: Environment invalid because of previous exception: (JE 18.3.12) 172.23.108.101_9010_1695259644078(7):/bigdata/doris-meta/bdb  Feeder: 172.23.108.103_9010_1695361282114(6). The environments have the same name: PALO_JOURNAL_GROUP but represent different environment instances. The environment at the master has UUID 1dd6dcc8-24cc-4c68-8cd5-1ce4681b2706, while the replica 172.23.108.101_9010_1695259644078 has UUID: c4bddb79-a8ec-4e63-b1e5-d81d5e596a42 HANDSHAKE_ERROR: Error during the handshake between two nodes. Some validity or compatibility check failed, preventing further communication between the nodes. Environment is invalid and must be closed.
	at com.sleepycat.je.rep.stream.ReplicaFeederHandshake.verifyMembership(ReplicaFeederHandshake.java:342)
	at com.sleepycat.je.rep.stream.ReplicaFeederHandshake.execute(ReplicaFeederHandshake.java:267)
	at com.sleepycat.je.rep.impl.node.Replica.initReplicaLoop(Replica.java:709)
	at com.sleepycat.je.rep.impl.node.Replica.runReplicaLoopInternal(Replica.java:485)
	at com.sleepycat.je.rep.impl.node.Replica.runReplicaLoop(Replica.java:412)
	at com.sleepycat.je.rep.impl.node.RepNode.run(RepNode.java:1869)

### What You Expected?

启动FE，将FE添加到集群

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Charlie19961010** [comment]
103是我现在集群的master节点，之前三台服务器时钟不同步导致102和103节点down了，重启后导致101节点down了现在起不来了，具体日志如上所示，求帮助，谢谢！

**Comment by Charlie19961010** [comment]
103是我现在集群的master节点，之前三台服务器时钟不同步导致102和103节点down了，重启后导致101节点down了现在起不来了，具体日志如上所示，求帮助，谢谢！

**Comment by wyx123654** [comment]
启动的时候有--helper启动吗？notify new FE type transfer: UNKNOWN。

**Comment by Charlie19961010** [comment]
> 启动的时候有--helper启动吗？notify new FE type transfer: UNKNOWN。

我刚才试了把节点删除了然后重启加了--helper，现在是起来了，但添加到集群中alive显示false

**Comment by Charlie19961010** [comment]
> 启动的时候有--helper启动吗？notify new FE type transfer: UNKNOWN。

现在三台都起来了，就是查看管理页面有两台join显示false是什么情况？
