### ISSUE TITLE
[Bug] Doris query hudi mor table can't use 'hoodie.datasource.merge.type'='payload_combine'

### ISSUE THREAD

**Issue by lucienoz** [apache/doris#28706]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

2.0.3

### What's Wrong?

[2023-12-20 14:06:56] [HY000][1105] errCode = 2, detailMessage = (idc-ops-k8s-n3)[CANCELLED][INTERNAL_ERROR]InternalError: null
[2023-12-20 14:06:56] 	0#  doris::JniUtil::GetJniExceptionMsg(JNIEnv_*, bool, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) at /root/src/doris-2.0/be/src/util/jni-util.h:110
[2023-12-20 14:06:56] 	1#  doris::vectorized::JniConnector::get_nex_block(doris::vectorized::Block*, unsigned long*, bool*) at /root/src/doris-2.0/be/src/vec/exec/jni_connector.cpp:0
[2023-12-20 14:06:56] 	2#  doris::vectorized::HudiJniReader::get_next_block(doris::vectorized::Block*, unsigned long*, bool*) at /root/src/doris-2.0/be/src/common/status.h:442
[2023-12-20 14:06:56] 	3#  doris::vectorized::VFileScanner::_get_block_impl(doris::RuntimeState*, doris::vectorized::Block*, bool*) at /root/src/doris-2.0/be/src/common/status.h:442
[2023-12-20 14:06:56] 	4#  doris::vectorized::VScanner::get_block(doris::RuntimeState*, doris::vectorized::Block*, bool*) at /root/src/doris-2.0/be/src/vec/exec/scan/vscanner.cpp:0
[2023-12-20 14:06:56] 	5#  doris::vectorized::ScannerScheduler::_scanner_scan(doris::vectorized::ScannerScheduler*, 
doris::vectorized::ScannerContext*, std::shared_ptr<doris::vectorized::VScanner>) at /root/src/doris-2.0/be/src/common/status.h:354
[2023-12-20 14:06:56] 	6#  std::_Function_handler<void (), doris::vectorized::ScannerScheduler::_schedule_scanners(doris::vectorized::ScannerContext*)::$_1::operator()() const::{lambda()#4}>::_M_invoke(std::_Any_data const&) at /var/local/ldb-toolchain/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/shared_ptr_base.h:701
[2023-12-20 14:06:56] 	7#  doris::WorkThreadPool<true>::work_thread(int) at /var/local/ldb-toolchain/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/atomic_base.h:646
[2023-12-20 14:06:56] 	8#  execute_native_thread_routine at /data/gcc-11.1.0/build/x86_64-pc-linux-gnu/libstdc++-v3/include/bits/unique_ptr.h:85
[2023-12-20 14:06:56] 	9#  start_thread
[2023-12-20 14:06:56] 	10# __clone

### What You Expected?

get latest result

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by lucienoz** [comment]
more error info:
`I1220 14:45:00.001947 1226832 pipeline_fragment_context.cpp:216] PipelineFragmentContext::prepare|query_id=1226111346f462b-8c679f20ea9423ad|instance_id=1226111346f462b-8c679f20ea9423af|backend_num=0|pthread_id=139679825471232
I1220 14:45:00.002338 1226832 pipeline_fragment_context.cpp:216] PipelineFragmentContext::prepare|query_id=1226111346f462b-8c679f20ea9423ad|instance_id=1226111346f462b-8c679f20ea9423ae|backend_num=1|pthread_id=139679825471232
W1220 14:45:00.151538 1226239 jni-util.cpp:241] java.lang.InternalError
        at org.apache.hadoop.io.compress.zlib.ZlibDecompressor.init(Native Method)
        at org.apache.hadoop.io.compress.zlib.ZlibDecompressor.<init>(ZlibDecompressor.java:114)
        at org.apache.hadoop.io.compress.GzipCodec$GzipZlibDecompressor.<init>(GzipCodec.java:229)
        at org.apache.hadoop.io.compress.GzipCodec.createDecompressor(GzipCodec.java:188)
        at org.apache.hadoop.io.compress.CodecPool.getDecompressor(CodecPool.java:183)
        at org.apache.parquet.hadoop.CodecFactory$HeapBytesDecompressor.<init>(CodecFactory.java:99)
        at org.apache.parquet.hadoop.CodecFactory.createDecompressor(CodecFactory.java:223)
        at org.apache.parquet.hadoop.CodecFactory.getDecompressor(CodecFactory.java:212)
        at org.apache.parquet.hadoop.CodecFactory.getDecompressor(CodecFactory.java:43)
        at org.apache.parquet.hadoop.ParquetFileReader$Chunk.readAllPages(ParquetFileReader.java:1664)
        at org.apache.parquet.hadoop.ParquetFileReader$Chunk.readAllPages(ParquetFileReader.java:1547)
        at org.apache.parquet.hadoop.ParquetFileReader.readChunkPages(ParquetFileReader.java:1157)
        at org.apache.parquet.hadoop.ParquetFileReader.internalReadRowGroup(ParquetFileReader.java:993)
        at org.apache.parquet.hadoop.ParquetFileReader.readNextRowGroup(ParquetFileReader.java:940)
        at org.apache.parquet.hadoop.ParquetFileReader.readNextFilteredRowGroup(ParquetFileReader.java:1082)
        at org.apache.spark.sql.execution.datasources.parquet.VectorizedParquetRecordReader.checkEndOfRowGroup(VectorizedParquetRecordReader.java:323)
        at org.apache.spark.sql.execution.datasources.parquet.VectorizedParquetRecordReader.nextBatch(VectorizedParquetRecordReader.java:278)
        at org.apache.spark.sql.execution.datasources.parquet.VectorizedParquetRecordReader.nextKeyValue(VectorizedParquetRecordReader.java:181)
        at org.apache.spark.sql.execution.datasources.RecordReaderIterator.hasNext(RecordReaderIterator.scala:39)
        at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:489)
        at org.apache.hudi.RecordMergingFileIterator.hasNextInternal(Iterators.scala:199)
        at org.apache.hudi.RecordMergingFileIterator.doHasNext(Iterators.scala:193)
        at org.apache.hudi.util.CachingIterator.hasNext(CachingIterator.scala:36)
        at org.apache.hudi.util.CachingIterator.hasNext$(CachingIterator.scala:36)
        at org.apache.hudi.LogFileIterator.hasNext(Iterators.scala:61)
        at org.apache.doris.hudi.HoodieMORRecordIterator.hasNext(HoodieRecordIterator.scala:129)
        at org.apache.doris.hudi.HudiJniScanner.getNext(HudiJniScanner.java:224)
        at org.apache.doris.common.jni.JniScanner.getNextBatchMeta(JniScanner.java:88)
W1220 14:45:00.151911 1226239 status.h:393] meet error status: [INTERNAL_ERROR]InternalError: null

        0#  doris::JniUtil::GetJniExceptionMsg(JNIEnv_*, bool, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) at /root/src/doris-2.0/be/src/util/jni-util.h:110
        1#  doris::vectorized::JniConnector::get_nex_block(doris::vectorized::Block*, unsigned long*, bool*) at /root/src/doris-2.0/be/src/vec/exec/jni_connector.cpp:0
        2#  doris::vectorized::HudiJniReader::get_next_block(doris::vectorized::Block*, unsigned long*, bool*) at /root/src/doris-2.0/be/src/common/status.h:442
        3#  doris::vectorized::VFileScanner::_get_block_impl(doris::RuntimeState*, doris::vectorized::Block*, bool*) at /root/src/doris-2.0/be/src/common/status.h:442
        4#  doris::vectorized::VScanner::get_block(doris::RuntimeState*, doris::vectorized::Block*, bool*) at /root/src/doris-2.0/be/src/vec/exec/scan/vscanner.cpp:0
        5#  doris::vectorized::ScannerScheduler::_scanner_scan(doris::vectorized::ScannerScheduler*, doris::vectorized::ScannerContext*, std::shared_ptr<doris::vectorized::VScanner>) at /root/src/doris-2.0/be/src/common/status.h:354
        6#  std::_Function_handler<void (), doris::vectorized::ScannerScheduler::_schedule_scanners(doris::vectorized::ScannerContext*)::$_1::operator()() const::{lambda()#4}>::_M_invoke(std::_Any_data const&) at /var/local/ldb-toolchain/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/shared_ptr_base.h:701
        7#  doris::WorkThreadPool<true>::work_thread(int) at /var/local/ldb-toolchain/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/atomic_base.h:646
        8#  execute_native_thread_routine at /data/gcc-11.1.0/build/x86_64-pc-linux-gnu/libstdc++-v3/include/bits/unique_ptr.h:85
        9#  start_thread
        10# __clone
W1220 14:45:00.151954 1226239 scanner_scheduler.cpp:396] Scan thread read VScanner failed: [INTERNAL_ERROR]InternalError: null

        0#  doris::JniUtil::GetJniExceptionMsg(JNIEnv_*, bool, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) at /root/src/doris-2.0/be/src/util/jni-util.h:110
        1#  doris::vectorized::JniConnector::get_nex_block(doris::vectorized::Block*, unsigned long*, bool*) at /root/src/doris-2.0/be/src/vec/exec/jni_connector.cpp:0
        2#  doris::vectorized::HudiJniReader::get_next_block(doris::vectorized::Block*, unsigned long*, bool*) at /root/src/doris-2.0/be/src/common/status.h:442
        3#  doris::vectorized::VFileScanner::_get_block_impl(doris::RuntimeState*, doris::vectorized::Block*, bool*) at /root/src/doris-2.0/be/src/common/status.h:442
        4#  doris::vectorized::VScanner::get_block(doris::RuntimeState*, doris::vectorized::Block*, bool*) at /root/src/doris-2.0/be/src/vec/exec/scan/vscanner.cpp:0
        5#  doris::vectorized::ScannerScheduler::_scanner_scan(doris::vectorized::ScannerScheduler*, doris::vectorized::ScannerContext*, std::shared_ptr<doris::vectorized::VScanner>) at /root/src/doris-2.0/be/src/common/status.h:354
        6#  std::_Function_handler<void (), doris::vectorized::ScannerScheduler::_schedule_scanners(doris::vectorized::ScannerContext*)::$_1::operator()() const::{lambda()#4}>::_M_invoke(std::_Any_data const&) at /var/local/ldb-toolchain/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/shared_ptr_base.h:701
        7#  doris::WorkThreadPool<true>::work_thread(int) at /var/local/ldb-toolchain/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/atomic_base.h:646
        8#  execute_native_thread_routine at /data/gcc-11.1.0/build/x86_64-pc-linux-gnu/libstdc++-v3/include/bits/unique_ptr.h:85
        9#  start_thread
        10# __clone
W1220 14:45:00.152067 1225642 task_scheduler.cpp:275] Pipeline task failed. reason: [INTERNAL_ERROR]InternalError: null

        0#  doris::JniUtil::GetJniExceptionMsg(JNIEnv_*, bool, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) at /root/src/doris-2.0/be/src/util/jni-util.h:110
        1#  doris::vectorized::JniConnector::get_nex_block(doris::vectorized::Block*, unsigned long*, bool*) at /root/src/doris-2.0/be/src/vec/exec/jni_connector.cpp:0
        2#  doris::vectorized::HudiJniReader::get_next_block(doris::vectorized::Block*, unsigned long*, bool*) at /root/src/doris-2.0/be/src/common/status.h:442
        3#  doris::vectorized::VFileScanner::_get_block_impl(doris::RuntimeState*, doris::vectorized::Block*, bool*) at /root/src/doris-2.0/be/src/common/status.h:442
        4#  doris::vectorized::VScanner::get_block(doris::RuntimeState*, doris::vectorized::Block*, bool*) at /root/src/doris-2.0/be/src/vec/exec/scan/vscanner.cpp:0
        5#  doris::vectorized::ScannerScheduler::_scanner_scan(doris::vectorized::ScannerScheduler*, doris::vectorized::ScannerContext*, std::shared_ptr<doris::vectorized::VScanner>) at /root/src/doris-2.0/be/src/common/status.h:354
        6#  std::_Function_handler<void (), doris::vectorized::ScannerScheduler::_schedule_scanners(doris::vectorized::ScannerContext*)::$_1::operator()() const::{lambda()#4}>::_M_invoke(std::_Any_data const&) at /var/local/ldb-toolchain/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/shared_ptr_base.h:701
        7#  doris::WorkThreadPool<true>::work_thread(int) at /var/local/ldb-toolchain/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/atomic_base.h:646
        8#  execute_native_thread_routine at /data/gcc-11.1.0/build/x86_64-pc-linux-gnu/libstdc++-v3/include/bits/unique_ptr.h:85
        9#  start_thread
        10# __clone
I1220 14:45:00.152148 1225642 runtime_state.h:172] task is cancelled, st = [CANCELLED][INTERNAL_ERROR]InternalError: null

        0#  doris::JniUtil::GetJniExceptionMsg(JNIEnv_*, bool, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) at /root/src/doris-2.0/be/src/util/jni-util.h:110
        1#  doris::vectorized::JniConnector::get_nex_block(doris::vectorized::Block*, unsigned long*, bool*) at /root/src/doris-2.0/be/src/vec/exec/jni_connector.cpp:0
        2#  doris::vectorized::HudiJniReader::get_next_block(doris::vectorized::Block*, unsigned long*, bool*) at /root/src/doris-2.0/be/src/common/status.h:442
        3#  doris::vectorized::VFileScanner::_get_block_impl(doris::RuntimeState*, doris::vectorized::Block*, bool*) at /root/src/doris-2.0/be/src/common/status.h:442
        4#  doris::vectorized::VScanner::get_block(doris::RuntimeState*, doris::vectorized::Block*, bool*) at /root/src/doris-2.0/be/src/vec/exec/scan/vscanner.cpp:0
        5#  doris::vectorized::ScannerScheduler::_scanner_scan(doris::vectorized::ScannerScheduler*, doris::vectorized::ScannerContext*, std::shared_ptr<doris::vectorized::VScanner>) at /root/src/doris-2.0/be/src/common/status.h:354
        6#  std::_Function_handler<void (), doris::vectorized::ScannerScheduler::_schedule_scanners(doris::vectorized::ScannerContext*)::$_1::operator()() const::{lambda()#4}>::_M_invoke(std::_Any_data const&) at /var/local/ldb-toolchain/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/shared_ptr_base.h:701
        7#  doris::WorkThreadPool<true>::work_thread(int) at /var/local/ldb-toolchain/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/atomic_base.h:646
        8#  execute_native_thread_routine at /data/gcc-11.1.0/build/x86_64-pc-linux-gnu/libstdc++-v3/include/bits/unique_ptr.h:85
        9#  start_thread
        10# __clone
W1220 14:45:00.152155 1225642 pipeline_fragment_context.cpp:162] PipelineFragmentContext Canceled. reason=[INTERNAL_ERROR]InternalError: null

        0#  doris::JniUtil::GetJniExceptionMsg(JNIEnv_*, bool, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) at /root/src/doris-2.0/be/src/util/jni-util.h:110
        1#  doris::vectorized::JniConnector::get_nex_block(doris::vectorized::Block*, unsigned long*, bool*) at /root/src/doris-2.0/be/src/vec/exec/jni_connector.cpp:0
        2#  doris::vectorized::HudiJniReader::get_next_block(doris::vectorized::Block*, unsigned long*, bool*) at /root/src/doris-2.0/be/src/common/status.h:442
        3#  doris::vectorized::VFileScanner::_get_block_impl(doris::RuntimeState*, doris::vectorized::Block*, bool*) at /root/src/doris-2.0/be/src/common/status.h:442
        4#  doris::vectorized::VScanner::get_block(doris::RuntimeState*, doris::vectorized::Block*, bool*) at /root/src/doris-2.0/be/src/vec/exec/scan/vscanner.cpp:0
        5#  doris::vectorized::ScannerScheduler::_scanner_scan(doris::vectorized::ScannerScheduler*, doris::vectorized::ScannerContext*, std::shared_ptr<doris::vectorized::VScanner>) at /root/src/doris-2.0/be/src/common/status.h:354
        6#  std::_Function_handler<void (), doris::vectorized::ScannerScheduler::_schedule_scanners(doris::vectorized::ScannerContext*)::$_1::operator()() const::{lambda()#4}>::_M_invoke(std::_Any_data const&) at /var/local/ldb-toolchain/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/shared_ptr_base.h:701
        7#  doris::WorkThreadPool<true>::work_thread(int) at /var/local/ldb-toolchain/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/atomic_base.h:646
        8#  execute_native_thread_routine at /data/gcc-11.1.0/build/x86_64-pc-linux-gnu/libstdc++-v3/include/bits/unique_ptr.h:85
        9#  start_thread
        10# __clone
W1220 14:45:00.152186 1225642 fragment_mgr.cpp:482] report error status: [CANCELLED][INTERNAL_ERROR]InternalError: null

        0#  doris::JniUtil::GetJniExceptionMsg(JNIEnv_*, bool, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) at /root/src/doris-2.0/be/src/util/jni-util.h:110
        1#  doris::vectorized::JniConnector::get_nex_block(doris::vectorized::Block*, unsigned long*, bool*) at /root/src/doris-2.0/be/src/vec/exec/jni_connector.cpp:0
        2#  doris::vectorized::HudiJniReader::get_next_block(doris::vectorized::Block*, unsigned long*, bool*) at /root/src/doris-2.0/be/src/common/status.h:442
        3#  doris::vectorized::VFileScanner::_get_block_impl(doris::RuntimeState*, doris::vectorized::Block*, bool*) at /root/src/doris-2.0/be/src/common/status.h:442
        4#  doris::vectorized::VScanner::get_block(doris::RuntimeState*, doris::vectorized::Block*, bool*) at /root/src/doris-2.0/be/src/vec/exec/scan/vscanner.cpp:0
        5#  doris::vectorized::ScannerScheduler::_scanner_scan(doris::vectorized::ScannerScheduler*, doris::vectorized::ScannerContext*, std::shared_ptr<doris::vectorized::VScanner>) at /root/src/doris-2.0/be/src/common/status.h:354
        6#  std::_Function_handler<void (), doris::vectorized::ScannerScheduler::_schedule_scanners(doris::vectorized::ScannerContext*)::$_1::operator()() const::{lambda()#4}>::_M_invoke(std::_Any_data const&) at /var/local/ldb-toolchain/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/shared_ptr_base.h:701
        7#  doris::WorkThreadPool<true>::work_thread(int) at /var/local/ldb-toolchain/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/atomic_base.h:646
        8#  execute_native_thread_routine at /data/gcc-11.1.0/build/x86_64-pc-linux-gnu/libstdc++-v3/include/bits/unique_ptr.h:85
        9#  start_thread
        10# __clone
 to coordinator: TNetworkAddress(hostname=172.16.99.21, port=9020), query id: 1226111346f462b-8c679f20ea9423ad, instance id: 1226111346f462b-8c679f20ea9423ae
I1220 14:45:00.153338 1226840 internal_service.cpp:521] cancel fragment, fragment_instance_id=1226111346f462b-8c679f20ea9423af, reason: INTERNAL_ERROR
I1220 14:45:00.153435 1226840 runtime_state.h:172] task is cancelled, st = [CANCELLED]
W1220 14:45:00.153447 1226840 pipeline_fragment_context.cpp:162] PipelineFragmentContext Canceled. reason=
W1220 14:45:00.153733 1225642 fragment_mgr.cpp:482] report error status: [CANCELLED][INTERNAL_ERROR]InternalError: null

        0#  doris::JniUtil::GetJniExceptionMsg(JNIEnv_*, bool, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) at /root/src/doris-2.0/be/src/util/jni-util.h:110
        1#  doris::vectorized::JniConnector::get_nex_block(doris::vectorized::Block*, unsigned long*, bool*) at /root/src/doris-2.0/be/src/vec/exec/jni_connector.cpp:0
        2#  doris::vectorized::HudiJniReader::get_next_block(doris::vectorized::Block*, unsigned long*, bool*) at /root/src/doris-2.0/be/src/common/status.h:442
        3#  doris::vectorized::VFileScanner::_get_block_impl(doris::RuntimeState*, doris::vectorized::Block*, bool*) at /root/src/doris-2.0/be/src/common/status.h:442
        4#  doris::vectorized::VScanner::get_block(doris::RuntimeState*, doris::vectorized::Block*, bool*) at /root/src/doris-2.0/be/src/vec/exec/scan/vscanner.cpp:0
        5#  doris::vectorized::ScannerScheduler::_scanner_scan(doris::vectorized::ScannerScheduler*, doris::vectorized::ScannerContext*, std::shared_ptr<doris::vectorized::VScanner>) at /root/src/doris-2.0/be/src/common/status.h:354
        6#  std::_Function_handler<void (), doris::vectorized::ScannerScheduler::_schedule_scanners(doris::vectorized::ScannerContext*)::$_1::operator()() const::{lambda()#4}>::_M_invoke(std::_Any_data const&`
