### ISSUE TITLE
[Bug] if port=9010 is used on host, it will deploy doris failed by docker-compose

### ISSUE THREAD

**Issue by laglangyue** [apache/doris#28960]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

2.0

### What's Wrong?

deploy doris by docker-compose

https://doris.apache.org/zh-CN/docs/install/construct-docker/run-docker-cluster

### What You Expected?

2023-12-25 06:02:50,876 WARN (main|1) [NetUtils.isPortAvailable():107] Edit log port 9010 is already in use. Please change the 'edit_log_port' in fe.conf and try again. But if this is not the first time your start this FE, please DO NOT change it.  You need to find the service that occupies the port and shut it down, and then return the port to Doris.
java.net.BindException: Address already in use (Bind failed)
	at java.net.PlainSocketImpl.socketBind(Native Method) ~[?:1.8.0_342]
	at java.net.AbstractPlainSocketImpl.bind(AbstractPlainSocketImpl.java:387) ~[?:1.8.0_342]
	at java.net.ServerSocket.bind(ServerSocket.java:390) ~[?:1.8.0_342]
	at java.net.ServerSocket.<init>(ServerSocket.java:252) ~[?:1.8.0_342]
	at java.net.ServerSocket.<init>(ServerSocket.java:143) ~[?:1.8.0_342]
	at org.apache.doris.common.util.NetUtils.isPortAvailable(NetUtils.java:101) ~[doris-fe.jar:1.2-SNAPSHOT]
	at org.apache.doris.DorisFE.checkAllPorts(DorisFE.java:193) ~[doris-fe.jar:1.2-SNAPSHOT]
	at org.apache.doris.DorisFE.start(DorisFE.java:129) ~[doris-fe.jar:1.2-SNAPSHOT]
	at org.apache.doris.DorisFE.main(DorisFE.java:73) ~[doris-fe.jar:1.2-SNAPSHOT]

### How to Reproduce?

if port port =9010 is used  on Host computer
deploy doris by 
https://doris.apache.org/zh-CN/docs/install/construct-docker/run-docker-cluster

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by laglangyue** [comment]
emm... doris on docker would be use 9010 on host ?
 Is there a way to modify the port, port mapping or env?

**Comment by laglangyue** [comment]
There are some issues with the Docker deploy provided on the official website.
there is a other question:
![image](https://github.com/apache/doris/assets/35491928/146d4e3b-2bc7-439f-95f0-6aab08df8b0e)
Beport  HttpPort BrpcPort are -1?

**Comment by hechao-ustc** [comment]
<img width="531" alt="image" src="https://github.com/apache/doris/assets/73096722/b42d209d-1586-4378-bede-8e74801c659a">

You should replace the IP here with the docker network. You can add such a statement to create a docker virtual network.
<img width="259" alt="image" src="https://github.com/apache/doris/assets/73096722/2c58c2b3-253e-4abb-b371-63c3ef7cd778">

**Comment by hechao-ustc** [comment]
You can check to see if 9010 is occupied by other programs.
Beport should not be -1, it should be that `priority_networks` is not configured.

**Comment by laglangyue** [comment]
Hmm… the docker-compose.yml on the official website is not plug-and-play.
So is there any test for it?
About this issue, I will rebuild a usable image.



> You can check to see if 9010 is occupied by other programs. Beport should not be -1, it should be that `priority_networks` is not configured.
