### ISSUE TITLE
[Bug] Packet for query is too large

### ISSUE THREAD

**Issue by marderary** [apache/doris#29021]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

2.0.3

### What's Wrong?

1.Build doris cluster with three nodes.
2.Set gloabal max_allowed_packet=1073741824.
3.Write lager size data to node1 at once, it works
4. Write lager size data to node2 or node3 at once, an "Packet for query is too large (57,067,527 > 4,194,304)"exception pops up.

### What You Expected?

Write to node2 and node3 correct.

### Anything Else?

The node1 which can be wrote in the matser FE,

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by yiguolei** [comment]
Could you please provide the error message stack?

**Comment by marderary** [comment]
Sorry for my delay.Here is the relate log below:

2024-03-04 04:29:05,845 INFO (mysql-nio-pool-3|8445) [MasterOpExecutor.forward():124] forward to master FE TNetworkAddress(hostname:172.25.0.11, port:9020), statement id: 20
2024-03-04 04:29:06,080 WARN (mysql-nio-pool-3|8445) [StmtExecutor.executeByLegacy():798] execute Exception. stmt[20, cbf9a73a00584d4a-87fab72ddd0ad3b6]
org.apache.doris.qe.MasterOpExecutor$ForwardToMasterException: forward to master FE TNetworkAddress(hostname:172.25.0.11, port:9020), statement id: 20 : failed, cause: Unknown exception
	at org.apache.doris.qe.MasterOpExecutor.forward(MasterOpExecutor.java:134) ~[doris-fe.jar:1.2-SNAPSHOT]
	at org.apache.doris.qe.MasterOpExecutor.execute(MasterOpExecutor.java:84) ~[doris-fe.jar:1.2-SNAPSHOT]
	at org.apache.doris.qe.StmtExecutor.forwardToMaster(StmtExecutor.java:865) ~[doris-fe.jar:1.2-SNAPSHOT]
	at org.apache.doris.qe.StmtExecutor.executeByLegacy(StmtExecutor.java:703) ~[doris-fe.jar:1.2-SNAPSHOT]
	at org.apache.doris.qe.StmtExecutor.execute(StmtExecutor.java:459) ~[doris-fe.jar:1.2-SNAPSHOT]
	at org.apache.doris.qe.StmtExecutor.execute(StmtExecutor.java:429) ~[doris-fe.jar:1.2-SNAPSHOT]
	at org.apache.doris.qe.ConnectProcessor.handleQuery(ConnectProcessor.java:435) ~[doris-fe.jar:1.2-SNAPSHOT]
	at org.apache.doris.qe.ConnectProcessor.dispatch(ConnectProcessor.java:583) ~[doris-fe.jar:1.2-SNAPSHOT]
	at org.apache.doris.qe.ConnectProcessor.processOnce(ConnectProcessor.java:834) ~[doris-fe.jar:1.2-SNAPSHOT]
	at org.apache.doris.mysql.ReadListener.lambda$handleEvent$0(ReadListener.java:52) ~[doris-fe.jar:1.2-SNAPSHOT]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_201]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_201]
	at java.lang.Thread.run(Thread.java:748) ~[?:1.8.0_201]
