### ISSUE TITLE
[Bug] 2.0.3版本因引入的jar包中slf4j冲突导致BE启动报错

### ISSUE THREAD

**Issue by ksdb1155228** [apache/doris#29122]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

2.0.3

### What's Wrong?

2.0.3版本因引入的jar包中slf4j冲突导致BE启动报错
备注（FE也有冲突问题，但是FE能启动，BE则无法启动）

start time: Wed Dec 27 13:14:55 CST 2023
INFO: java_cmd /opt/jdk1.8.0_211/bin/java
INFO: jdk_version 8
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/opt/apache-doris-2.0.3-bin-x64/be/lib/java_extensions/preload-extensions/preload-extensions-jar-with-dependencies.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/opt/apache-doris-2.0.3-bin-x64/be/lib/java_extensions/java-udf/java-udf-jar-with-dependencies.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/opt/apache-doris-2.0.3-bin-x64/be/lib/hadoop_hdfs/common/lib/slf4j-reload4j-1.7.36.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
log4j:ERROR setFile(null,true) call failed.
java.io.FileNotFoundException:  (No such file or directory)
        at java.io.FileOutputStream.open0(Native Method)
        at java.io.FileOutputStream.open(FileOutputStream.java:270)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:133)
        at org.apache.log4j.FileAppender.setFile(FileAppender.java:282)
        at org.apache.log4j.RollingFileAppender.setFile(RollingFileAppender.java:200)
        at org.apache.log4j.FileAppender.activateOptions(FileAppender.java:166)
        at org.apache.log4j.config.PropertySetter.activate(PropertySetter.java:284)
        at org.apache.log4j.config.PropertySetter.setProperties(PropertySetter.java:160)
        at org.apache.log4j.config.PropertySetter.setProperties(PropertySetter.java:100)
        at org.apache.log4j.PropertyConfigurator.parseAppender(PropertyConfigurator.java:802)
        at org.apache.log4j.PropertyConfigurator.parseCategory(PropertyConfigurator.java:738)
        at org.apache.log4j.PropertyConfigurator.configureRootCategory(PropertyConfigurator.java:630)
        at org.apache.log4j.PropertyConfigurator.doConfigure(PropertyConfigurator.java:516)
        at org.apache.log4j.PropertyConfigurator.doConfigure(PropertyConfigurator.java:577)
        at org.apache.log4j.helpers.OptionConverter.selectAndConfigure(OptionConverter.java:504)
        at org.apache.log4j.LogManager.<clinit>(LogManager.java:119)
        at org.slf4j.impl.Reload4jLoggerFactory.<init>(Reload4jLoggerFactory.java:67)
        at org.slf4j.impl.StaticLoggerBinder.<init>(StaticLoggerBinder.java:72)
        at org.slf4j.impl.StaticLoggerBinder.<clinit>(StaticLoggerBinder.java:45)
        at org.slf4j.LoggerFactory.bind(LoggerFactory.java:150)
        at org.slf4j.LoggerFactory.performInitialization(LoggerFactory.java:124)
        at org.slf4j.LoggerFactory.getILoggerFactory(LoggerFactory.java:417)
        at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:362)
        at org.apache.commons.logging.impl.SLF4JLogFactory.getInstance(SLF4JLogFactory.java:155)
        at org.apache.commons.logging.impl.SLF4JLogFactory.getInstance(SLF4JLogFactory.java:132)
        at org.apache.commons.logging.LogFactory.getLog(LogFactory.java:657)
        at org.apache.hadoop.fs.FileSystem.<clinit>(FileSystem.java:186)
SLF4J: Actual binding is of type [org.slf4j.impl.Reload4jLoggerFactory]
F1227 13:14:56.786144 28174 backend_options.cpp:108] wrong cidr format. cidr_str=
*** Check failure stack trace: ***
    @     0x561201b00219  google::LogMessageFatal::~LogMessageFatal()
    @     0x5611fa257eea  doris::BackendOptions::analyze_priority_cidrs()
    @     0x5611fa2579ae  doris::BackendOptions::init()
    @     0x5611f9770769  main
    @     0x7f20d9800c87  __libc_start_main
    @     0x5611f976f02a  _start
    @              (nil)  (unknown)
*** Query id: 0-0 ***
*** tablet id: 0 ***
*** Aborted at 1703654096 (unix time) try "date -d @1703654096" if you are using GNU date ***
*** Current BE git commitID: 37d31a5 ***
*** SIGABRT unknown detail explain (@0x6e0e) received by PID 28174 (TID 28174 OR 0x7f20da207e00) from PID 28174; stack trace: ***
 0# doris::signal::(anonymous namespace)::FailureSignalHandler(int, siginfo_t*, void*) at /root/src/doris-2.0/be/src/common/signal_handler.h:417
 1# 0x00007F20D981DF10 in /lib/x86_64-linux-gnu/libc.so.6
 2# raise in /lib/x86_64-linux-gnu/libc.so.6
 3# abort in /lib/x86_64-linux-gnu/libc.so.6
 4# 0x0000561201B061F9 in /opt/apache-doris-2.0.3-bin-x64/be/lib/doris_be
 5# google::LogMessage::SendToLog() in /opt/apache-doris-2.0.3-bin-x64/be/lib/doris_be
 6# google::LogMessage::Flush() in /opt/apache-doris-2.0.3-bin-x64/be/lib/doris_be
 7# google::LogMessageFatal::~LogMessageFatal() in /opt/apache-doris-2.0.3-bin-x64/be/lib/doris_be
 8# doris::BackendOptions::analyze_priority_cidrs(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::vector<doris::CIDR, std::allocator<doris::CIDR> >*) at /root/src/doris-2.0/be/src/service/backend_options.cpp:111
 9# doris::BackendOptions::init() at /root/src/doris-2.0/be/src/service/backend_options.cpp:44
10# main at /root/src/doris-2.0/be/src/service/doris_main.cpp:458
11# __libc_start_main in /lib/x86_64-linux-gnu/libc.so.6
12# _start in /opt/apache-doris-2.0.3-bin-x64/be/lib/doris_be

### What You Expected?

官网解决冲突

### How to Reproduce?

从官网下载好的二进制压缩包(zvx2)，解压后配置IP等常规参数后启动就会报错。

### Anything Else?

无

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by LemonLiTree** [comment]
priorty_network 怎么配置 的

**Comment by ksdb1155228** [comment]
> Priority_network怎么配置的

感谢回复，Priority_network 行尾有个特殊字符，修改后可以启动成功。
ps:依旧会报错冲突，但是可以使用。

**Comment by yiguolei** [comment]
@ksdb1155228 could you please provide the new error message?

**Comment by Bhupendrsingh** [comment]
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/opt/apache_doris/fe/lib/slf4j-reload4j-1.7.36.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/opt/apache_doris/fe/lib/log4j-slf4j-impl-2.18.0.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/opt/apache_doris/fe/lib/hive-catalog-shade-1.0.2.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.slf4j.impl.Reload4jLoggerFactory]
[2024-01-04 12:47:14] notify new FE type transfer: UNKNOWN
[2024-01-04 12:47:14] notify new FE type transfer: MASTER


hi getting above error while starting the fe server

**Comment by Player-ghq** [comment]
the same issue
