### ISSUE TITLE
spark read doris with condition error

### ISSUE THREAD

**Issue by sunriseXDM** [apache/doris#30222]
环境：
spark2.3
doris2.0.3

connector：spark-doris-connector-2.3_2.11-1.2.0

报错内容：
24/01/19 14:52:20 ERROR RowBatch: Schema size '1' is not equal to arrow field size '2'.
24/01/19 14:52:20 ERROR RowBatch: Schema size '1' is not equal to arrow field size '2'.
24/01/19 14:52:20 ERROR RowBatch: Read Doris Data failed because: 
org.apache.doris.spark.exception.DorisException: Load Doris data failed, schema size of fetch data is wrong.

定位问题：
doris建表语句：
CREATE TABLE vrc.`dim_platform_code` (
  `platform_code` varchar(64) NOT NULL COMMENT '业务类型code',
  `platform_code_name` varchar(64) NOT NULL COMMENT '全称',
  `filter` int NOT NULL COMMENT '过滤条件',
  `sort` int NOT NULL COMMENT '排序'
) 
DISTRIBUTED BY HASH(`platform_code`) BUCKETS 1
PROPERTIES (
"replication_allocation" = "tag.location.default: 3"
);

spark-shell：
>val dorisDF = spark.read.format("doris").option("doris.table.identifier", vrc.dim_platform_code).option("doris.fenodes", "192.168.1.20:8034,192.168.1.31:8034,192.168.1.22:8034,192.168.1.14:8034").option("user", "root").option("password", "").load()

>dorisDF.filter("filter<=2").createOrReplaceTempView("vrc__dim_platform_code")

>spark.sql("select platform_code from vrc__dim_platform_code").show()
24/01/22 15:38:38 WARN TaskSetManager: Lost task 0.0 in stage 1.0 (TID 1, c2, executor 2): org.apache.doris.spark.exception.DorisException: Load Doris data failed, schema size of fetch data is wrong.
        at org.apache.doris.spark.serialization.RowBatch.<init>(RowBatch.java:115)
        at org.apache.doris.spark.rdd.ScalaValueReader.hasNext(ScalaValueReader.scala:210)
        at org.apache.doris.spark.rdd.AbstractDorisRDDIterator.hasNext(AbstractDorisRDDIterator.scala:56)
        at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:409)
        at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIteratorForCodegenStage1.processNext(Unknown Source)
        at org.apache.spark.sql.execution.BufferedRowIterator.hasNext(BufferedRowIterator.java:43)
        at org.apache.spark.sql.execution.WholeStageCodegenExec$$anonfun$10$$anon$1.hasNext(WholeStageCodegenExec.scala:614)
        at org.apache.spark.sql.execution.SparkPlan$$anonfun$2.apply(SparkPlan.scala:253)
        at org.apache.spark.sql.execution.SparkPlan$$anonfun$2.apply(SparkPlan.scala:247)
        at org.apache.spark.rdd.RDD$$anonfun$mapPartitionsInternal$1$$anonfun$apply$25.apply(RDD.scala:836)
        at org.apache.spark.rdd.RDD$$anonfun$mapPartitionsInternal$1$$anonfun$apply$25.apply(RDD.scala:836)
        at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:49)
        at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:324)
        at org.apache.spark.rdd.RDD.iterator(RDD.scala:288)
        at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:49)
        at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:324)
        at org.apache.spark.rdd.RDD.iterator(RDD.scala:288)
        at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:87)
        at org.apache.spark.scheduler.Task.run(Task.scala:109)
        at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:345)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

>spark.sql("select platform_code,filter from vrc__dim_platform_code").show()
success！

只有字段有过滤条件的情况下才查询成功，请问如何解决

_Originally posted by @sunriseXDM in https://github.com/apache/doris/discussions/30134_

**Comment by gnehil** [comment]
Please try using version 1.3.0 of the connector.

**Comment by lxwcodemonkey** [comment]
要替换的例行任务比较多... 没有别的适配办法了吗...
