### ISSUE TITLE
[Bug] Query Left join Error When One Column Is Map Type

### ISSUE THREAD

**Issue by xujunwei916** [apache/doris#31059]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

2.0.3

### What's Wrong?

Query Left join Error When One Column Is Map Type ，I Have An Exception
```text
errCode = 2, detailMessage = Unexpected exception: org.apache.doris.common.AnalysisException: errCode = 2, detailMessage = No matching function with signature: if(boolean, null_type, MAP<varchar(512),varchar(512)>)
```

### What You Expected?

Query Left Join On Error When One Column Is Map Type , Map Type likely String Type When Right Table No Match Column Value Is NULL

### How to Reproduce?

Steps for bug occurrence

create a table
```sql
CREATE TABLE  IF NOT EXISTS `student_score`(
  `name`  VARCHAR(32),
  `type` VARCHAR(32),
  `score`  MAP<VARCHAR(512),VARCHAR(512)>
)
UNIQUE KEY(`name`,`type`)
DISTRIBUTED BY HASH(`name`) BUCKETS 1
PROPERTIES (
"replication_allocation" = "tag.location.default: 2"
);
```
Load some sample data
```text
# data
{"name":"Tom","type":"期中","score":{"maths":"80","english":"70","chinese":"90"}}
{"name":"Tom","type":"期末","score":{"maths":"80","english":"20","chinese":"95"}}
{"name":"Jim","type":"期中","score":{"maths":"100","english":"60","chinese":"90"}}
{"name":"Kevin","type":"期中","score":{"maths":"88","english":"35","chinese":"70"}}
{"name":"Kevin","type":"期末","score":{"maths":"66","english":"45","chinese":"73"}}
# stream load 
curl --location-trusted -u root -H "format: json" -H "read_json_by_line: true" -T data.json http://127.0.0.1:8030/api/test_doris/student_score/_stream_load
```
![image](https://github.com/apache/doris/assets/22388118/16053bae-7f99-43e2-a3c8-42d75b87f339)

Query Left Join 
```sql
SELECT t1.name,t1.interim,t2.terminal
FROM(
  SELECT name,score AS interim FROM student_score WHERE type='期中'
) t1
LEFT JOIN (
  SELECT name,score AS terminal FROM student_score WHERE type='期末'
) t2
ON t1.name =t2.name
```

Fe Exception :
```text
2024-02-18 16:46:45,150 WARN (mysql-nio-pool-7|933) [StmtExecutor.analyze():1009] Analyze failed. stmt[392, e21b9e3edcbc4378-b467a5bf4420c84c]
java.lang.IllegalStateException: org.apache.doris.common.AnalysisException: errCode = 2, detailMessage = No matching function with signature: if(boolean, null_type, MAP<varchar(512),varchar(512)>).
        at org.apache.doris.analysis.Expr.analyzeNoThrow(Expr.java:617) ~[doris-fe.jar:1.2-SNAPSHOT]
        at org.apache.doris.analysis.TupleIsNullPredicate.wrapExpr(TupleIsNullPredicate.java:167) ~[doris-fe.jar:1.2-SNAPSHOT]
        at org.apache.doris.analysis.TupleIsNullPredicate.wrapExprs(TupleIsNullPredicate.java:147) ~[doris-fe.jar:1.2-SNAPSHOT]
        at org.apache.doris.planner.JoinNodeBase.computeOutputTuple(JoinNodeBase.java:249) ~[doris-fe.jar:1.2-SNAPSHOT]
        at org.apache.doris.planner.HashJoinNode.init(HashJoinNode.java:282) ~[doris-fe.jar:1.2-SNAPSHOT]
        at org.apache.doris.planner.SingleNodePlanner.createJoinNodeBase(SingleNodePlanner.java:2165) ~[doris-fe.jar:1.2-SNAPSHOT]
        at org.apache.doris.planner.SingleNodePlanner.createJoinNode(SingleNodePlanner.java:2188) ~[doris-fe.jar:1.2-SNAPSHOT]
        at org.apache.doris.planner.SingleNodePlanner.createSelectPlan(SingleNodePlanner.java:1284) ~[doris-fe.jar:1.2-SNAPSHOT]
        at org.apache.doris.planner.SingleNodePlanner.createQueryPlan(SingleNodePlanner.java:264) ~[doris-fe.jar:1.2-SNAPSHOT]
        at org.apache.doris.planner.SingleNodePlanner.createSingleNodePlan(SingleNodePlanner.java:187) ~[doris-fe.jar:1.2-SNAPSHOT]
        at org.apache.doris.planner.OriginalPlanner.createPlanFragments(OriginalPlanner.java:160) ~[doris-fe.jar:1.2-SNAPSHOT]
        at org.apache.doris.planner.OriginalPlanner.plan(OriginalPlanner.java:101) ~[doris-fe.jar:1.2-SNAPSHOT]
        at org.apache.doris.qe.StmtExecutor.analyzeAndGenerateQueryPlan(StmtExecutor.java:1158) ~[doris-fe.jar:1.2-SNAPSHOT]
        at org.apache.doris.qe.StmtExecutor.analyze(StmtExecutor.java:992) ~[doris-fe.jar:1.2-SNAPSHOT]
        at org.apache.doris.qe.StmtExecutor.executeByLegacy(StmtExecutor.java:684) ~[doris-fe.jar:1.2-SNAPSHOT]
        at org.apache.doris.qe.StmtExecutor.execute(StmtExecutor.java:456) ~[doris-fe.jar:1.2-SNAPSHOT]
        at org.apache.doris.qe.StmtExecutor.execute(StmtExecutor.java:429) ~[doris-fe.jar:1.2-SNAPSHOT]
        at org.apache.doris.qe.ConnectProcessor.handleQuery(ConnectProcessor.java:435) ~[doris-fe.jar:1.2-SNAPSHOT]
        at org.apache.doris.qe.ConnectProcessor.dispatch(ConnectProcessor.java:583) ~[doris-fe.jar:1.2-SNAPSHOT]
        at org.apache.doris.qe.ConnectProcessor.processOnce(ConnectProcessor.java:834) ~[doris-fe.jar:1.2-SNAPSHOT]
        at org.apache.doris.mysql.ReadListener.lambda$handleEvent$0(ReadListener.java:52) ~[doris-fe.jar:1.2-SNAPSHOT]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
        at java.lang.Thread.run(Thread.java:829) ~[?:?]
Caused by: org.apache.doris.common.AnalysisException: errCode = 2, detailMessage = No matching function with signature: if(boolean, null_type, MAP<varchar(512),varchar(512)>).
        at org.apache.doris.analysis.FunctionCallExpr.analyzeImpl(FunctionCallExpr.java:1636) ~[doris-fe.jar:1.2-SNAPSHOT]
        at org.apache.doris.analysis.Expr.analyze(Expr.java:444) ~[doris-fe.jar:1.2-SNAPSHOT]
        at org.apache.doris.analysis.Expr.analyzeNoThrow(Expr.java:615) ~[doris-fe.jar:1.2-SNAPSHOT]
        ... 23 more
2024-02-18 16:46:45,151 WARN (mysql-nio-pool-7|933) [StmtExecutor.executeByLegacy():790] execute Exception. stmt[392, e21b9e3edcbc4378-b467a5bf4420c84c]
org.apache.doris.common.AnalysisException: errCode = 2, detailMessage = Unexpected exception: org.apache.doris.common.AnalysisException: errCode = 2, detailMessage = No matching function with signature: if(boolean, null_type, MAP<varchar(512),varchar(512)>).
        at org.apache.doris.qe.StmtExecutor.analyze(StmtExecutor.java:1010) ~[doris-fe.jar:1.2-SNAPSHOT]
        at org.apache.doris.qe.StmtExecutor.executeByLegacy(StmtExecutor.java:684) ~[doris-fe.jar:1.2-SNAPSHOT]
        at org.apache.doris.qe.StmtExecutor.execute(StmtExecutor.java:456) ~[doris-fe.jar:1.2-SNAPSHOT]
        at org.apache.doris.qe.StmtExecutor.execute(StmtExecutor.java:429) ~[doris-fe.jar:1.2-SNAPSHOT]
        at org.apache.doris.qe.ConnectProcessor.handleQuery(ConnectProcessor.java:435) ~[doris-fe.jar:1.2-SNAPSHOT]
        at org.apache.doris.qe.ConnectProcessor.dispatch(ConnectProcessor.java:583) ~[doris-fe.jar:1.2-SNAPSHOT]
        at org.apache.doris.qe.ConnectProcessor.processOnce(ConnectProcessor.java:834) ~[doris-fe.jar:1.2-SNAPSHOT]
        at org.apache.doris.mysql.ReadListener.lambda$handleEvent$0(ReadListener.java:52) ~[doris-fe.jar:1.2-SNAPSHOT]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
        at java.lang.Thread.run(Thread.java:829) ~[?:?]
```

### Anything Else?

I Search An Issue Likely this but that data type is Array
https://github.com/apache/doris/issues/12689

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by liugddx** [comment]
Let me see

**Comment by xujunwei916** [comment]
Full Join Has Same Error

**Comment by waywtdcc** [comment]
@liugddx  Hello, can I handle this issue?

**Comment by waywtdcc** [comment]
The master branch should have already addressed this issue
