### ISSUE TITLE
[Bug] Hardware Info in web home page loading and NPE in fe log

### ISSUE THREAD

**Issue by chaos-cn** [apache/doris#31979]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

2.1.0

### What's Wrong?

"Hardware Info" in web home page loading and NPE in fe log

```
2024-03-08 14:03:47,838 WARN (qtp1206580572-131|131) [RestApiExceptionHandler.unexpectedExceptionHandler():61] unexpected exception
java.lang.NullPointerException: null
	at oshi.hardware.CentralProcessor$ProcessorIdentifier.queryMicroarchitecture(CentralProcessor.java:825) ~[oshi-core-6.4.5.jar:6.4.5]
	at oshi.util.Memoizer$1.get(Memoizer.java:61) ~[oshi-core-6.4.5.jar:6.4.5]
	at oshi.hardware.CentralProcessor$ProcessorIdentifier.getMicroarchitecture(CentralProcessor.java:816) ~[oshi-core-6.4.5.jar:6.4.5]
	at oshi.hardware.common.AbstractCentralProcessor.toString(AbstractCentralProcessor.java:457) ~[oshi-core-6.4.5.jar:6.4.5]
	at java.lang.String.valueOf(String.java:2994) ~[?:1.8.0_241]
	at org.apache.doris.httpv2.controller.HardwareInfoController.getProcessor(HardwareInfoController.java:100) ~[doris-fe.jar:1.2-SNAPSHOT]
```

### What You Expected?

Show Hardware Info.

This error may be caused by [here](https://github.com/oshi/oshi/pull/2514)
I update [oshi-core.version](https://github.com/apache/doris/blob/2882115a65882f406fc97abdc1244c5308dbe2ca/fe/pom.xml#L289) to 6.4.13 , it works ok, please update it.  

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by chaos-cn** [comment]
@morrySnow 
Please troubleshoot this issues if possible. Thank you very much !

**Comment by morrySnow** [comment]
do u want to submit a PR to fix it? @chaos-cn

**Comment by chaos-cn** [comment]
> do u want to submit a PR to fix it? @chaos-cn

If you can, please help submit a PR to fix it, for some reason, my network here to access github is very unstable. tks @morrySnow
