### ISSUE TITLE
[Bug] In ARM 2.0.5 version, TPC-H query is failed due to RpcException, msg: send fragments failed

### ISSUE THREAD

**Issue by ikishore** [apache/doris#32422]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

2.0.5 Arm version, deployed in ARM machines

### What's Wrong?

TPC-H Query suite is failing always
after suite is failed, normal queries also failed with same reason

Caused by: java.lang.IllegalArgumentException: Invalid padding '14532160'. Padding must be between 0 and 256 (inclusive).
        at io.grpc.netty.shaded.io.netty.handler.codec.http2.Http2CodecUtil.verifyPadding(Http2CodecUtil.java:399) ~[grpc-netty-shaded-1.58.0.jar:1.58.0]
        at io.grpc.netty.shaded.io.netty.handler.codec.http2.DefaultHttp2FrameWriter.writeHeadersInternal(DefaultHttp2FrameWriter.java:495) ~[grpc-netty-shaded-1.58.0.jar:1.58.0]
        at io.grpc.netty.shaded.io.netty.handler.codec.http2.DefaultHttp2FrameWriter.writeHeaders(DefaultHttp2FrameWriter.java:268) ~[grpc-netty-shaded-1.58.0.jar:1.58.0]
        at io.grpc.netty.shaded.io.netty.handler.codec.http2.Http2OutboundFrameLogger.writeHeaders(Http2OutboundFrameLogger.java:60) ~[grpc-netty-shaded-1.58.0.jar:1.58.0]
        at io.grpc.netty.shaded.io.netty.handler.codec.http2.DecoratingHttp2FrameWriter.writeHeaders(DecoratingHttp2FrameWriter.java:53) ~[grpc-netty-shaded-1.58.0.jar:1.58.0]
        at io.grpc.netty.shaded.io.grpc.netty.NettyClientHandler$PingCountingFrameWriter.writeHeaders(NettyClientHandler.java:1005) ~[grpc-netty-shaded-1.58.0.jar:1.58.0]
        at io.grpc.netty.shaded.io.netty.handler.codec.http2.DefaultHttp2ConnectionEncoder.sendHeaders(DefaultHttp2ConnectionEncoder.java:181) ~[grpc-netty-shaded-1.58.0.jar:1.58.0]
        at io.grpc.netty.shaded.io.netty.handler.codec.http2.DefaultHttp2ConnectionEncoder.writeHeaders0(DefaultHttp2ConnectionEncoder.java:233) ~[grpc-netty-shaded-1.58.0.jar:1.58.0]
        at io.grpc.netty.shaded.io.netty.handler.codec.http2.DefaultHttp2ConnectionEncoder.writeHeaders(DefaultHttp2ConnectionEncoder.java:167) ~[grpc-netty-shaded-1.58.0.jar:1.58.0]
        at io.grpc.netty.shaded.io.netty.handler.codec.http2.DecoratingHttp2FrameWriter.writeHeaders(DecoratingHttp2FrameWriter.java:53) ~[grpc-netty-shaded-1.58.0.jar:1.58.0]
        at io.grpc.netty.shaded.io.netty.handler.codec.http2.StreamBufferingEncoder.writeHeaders(StreamBufferingEncoder.java:170) ~[grpc-netty-shaded-1.58.0.jar:1.58.0]
        at io.grpc.netty.shaded.io.netty.handler.codec.http2.StreamBufferingEncoder.writeHeaders(StreamBufferingEncoder.java:158) ~[grpc-netty-shaded-1.58.0.jar:1.58.0]
        at io.grpc.netty.shaded.io.grpc.netty.NettyClientHandler.createStreamTraced(NettyClientHandler.java:614) ~[grpc-netty-shaded-1.58.0.jar:1.58.0]
        at io.grpc.netty.shaded.io.grpc.netty.NettyClientHandler.createStream(NettyClientHandler.java:599) ~[grpc-netty-shaded-1.58.0.jar:1.58.0]
        at io.grpc.netty.shaded.io.grpc.netty.NettyClientHandler.write(NettyClientHandler.java:333) ~[grpc-netty-shaded-1.58.0.jar:1.58.0]
        at io.grpc.netty.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881) ~[grpc-netty-shaded-1.58.0.jar:1.58.0]
        at io.grpc.netty.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863) ~[grpc-netty-shaded-1.58.0.jar:1.58.0]
        at io.grpc.netty.shaded.io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968) ~[grpc-netty-shaded-1.58.0.jar:1.58.0]
        at io.grpc.netty.shaded.io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856) ~[grpc-netty-shaded-1.58.0.jar:1.58.0]
        at io.grpc.netty.shaded.io.netty.channel.DefaultChannelPipeline.write(DefaultChannelPipeline.java:1015) ~[grpc-netty-shaded-1.58.0.jar:1.58.0]
        at io.grpc.netty.shaded.io.netty.channel.AbstractChannel.write(AbstractChannel.java:301) ~[grpc-netty-shaded-1.58.0.jar:1.58.0]
        at io.grpc.netty.shaded.io.grpc.netty.WriteQueue$AbstractQueuedCommand.run(WriteQueue.java:206) ~[grpc-netty-shaded-1.58.0.jar:1.58.0]
        at io.grpc.netty.shaded.io.grpc.netty.WriteQueue.flush(WriteQueue.java:128) ~[grpc-netty-shaded-1.58.0.jar:1.58.0]
        at io.grpc.netty.shaded.io.grpc.netty.WriteQueue.access$000(WriteQueue.java:35) ~[grpc-netty-shaded-1.58.0.jar:1.58.0]
        at io.grpc.netty.shaded.io.grpc.netty.WriteQueue$1.run(WriteQueue.java:47) ~[grpc-netty-shaded-1.58.0.jar:1.58.0]
        at io.grpc.netty.shaded.io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) ~[grpc-netty-shaded-1.58.0.jar:1.58.0]
        at io.grpc.netty.shaded.io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167) ~[grpc-netty-shaded-1.58.0.jar:1.58.0]
        at io.grpc.netty.shaded.io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) ~[grpc-netty-shaded-1.58.0.jar:1.58.0]
        at io.grpc.netty.shaded.io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:403) ~[grpc-netty-shaded-1.58.0.jar:1.58.0]
        at io.grpc.netty.shaded.io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[grpc-netty-shaded-1.58.0.jar:1.58.0]
        at io.grpc.netty.shaded.io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[grpc-netty-shaded-1.58.0.jar:1.58.0]
        at io.grpc.netty.shaded.io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[grpc-netty-shaded-1.58.0.jar:1.58.0]
        ... 1 more

### What You Expected?

All queries to run without failure

### How to Reproduce?

loaded TPC-H 10G dataset
Run normal queries first like "select * from nation;" on tpc-h database, Query ran normally
Run TPC-H queries, Suite failed at Q9 with exception RpcException, msg: send fragments failed
Run normal query on tables like ""select * from nation;", Query failed with exception RpcException, msg: send fragments failed

### Anything Else?

[Arm-TPC-H_Query_failure_log.txt](https://github.com/apache/doris/files/14636860/Arm-TPC-H_Query_failure_log.txt)

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by cjj2010** [comment]
What is the Linux kernel version used by the ARM architecture machine？

**Comment by ikishore** [comment]
After much analysis, it is found that issue is due to old OpenJDK 8 version. After upgrading java 8 version it worked fine. This issue can be closed
