### ISSUE TITLE
[Bug] Query hang in org.xnio.channels.Channels.writeBlocking

### ISSUE THREAD

**Issue by cambyzju** [apache/doris#32539]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

1.2.8 found this bug.

### What's Wrong?

1. Some threads in FE hang, the jstack output like following:
```
"mysql-nio-pool-47624" #7497595 daemon prio=5 os_prio=0 cpu=6782.45ms elapsed=26101.55s tid=0x00007f5380470000 nid=0xcf799 runnable [0x00007f5373477000]
   java.lang.Thread.State: RUNNABLE
        at sun.nio.ch.EPollArrayWrapper.epollWait(Native Method)
        at sun.nio.ch.EPollArrayWrapper.poll(EPollArrayWrapper.java:269)
        at sun.nio.ch.EPollSelectorImpl.doSelect(EPollSelectorImpl.java:93)
        at sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:86)
        - locked <0x0000000674d6c800> (a sun.nio.ch.Util$3)
        - locked <0x0000000674d6c7e8> (a java.util.Collections$UnmodifiableSet)
        - locked <0x0000000669769168> (a sun.nio.ch.EPollSelectorImpl)
        at sun.nio.ch.SelectorImpl.select(SelectorImpl.java:97)
        at sun.nio.ch.SelectorImpl.select(SelectorImpl.java:101)
        at org.xnio.nio.SelectorUtils.await(SelectorUtils.java:51)
        at org.xnio.nio.NioSocketConduit.awaitWritable(NioSocketConduit.java:233)
        at org.xnio.conduits.ConduitStreamSinkChannel.awaitWritable(ConduitStreamSinkChannel.java:134)
        at org.xnio.channels.Channels.writeBlocking(Channels.java:149)
        at org.apache.doris.mysql.MysqlChannel.realNetSend(MysqlChannel.java:355)
        at org.apache.doris.mysql.MysqlChannel.flush(MysqlChannel.java:385)
        at org.apache.doris.mysql.MysqlChannel.writeBuffer(MysqlChannel.java:415)
        at org.apache.doris.mysql.MysqlChannel.sendOnePacket(MysqlChannel.java:448)
        at org.apache.doris.qe.StmtExecutor.sendResult(StmtExecutor.java:1188)
        at org.apache.doris.qe.StmtExecutor.handleQueryStmt(StmtExecutor.java:1131)
        at org.apache.doris.qe.StmtExecutor.execute(StmtExecutor.java:522)
        at org.apache.doris.qe.StmtExecutor.execute(StmtExecutor.java:409)
        at org.apache.doris.qe.ConnectProcessor.handleQuery(ConnectProcessor.java:338)
        at org.apache.doris.qe.ConnectProcessor.dispatch(ConnectProcessor.java:481)
        at org.apache.doris.qe.ConnectProcessor.processOnce(ConnectProcessor.java:708)
        at org.apache.doris.mysql.ReadListener.lambda$handleEvent$0(ReadListener.java:52)
        at org.apache.doris.mysql.ReadListener$$Lambda$1177/1312172733.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```

2. use `show proc "/current/queries"` command, we found the query exists. But use `show processlist` we found the connection already lost.

3. use jmap dump FE, and find out the remote address from dump file, then use `netstat` command, we cannot found the connection.

### What You Expected?

do not hang

### How to Reproduce?

I have tried many times, but can not reproduce it.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by cambyzju** [comment]
same as https://github.com/apache/doris/issues/28807
