### ISSUE TITLE
[Bug] doris truncate 操作很慢

### ISSUE THREAD

**Issue by weilai201** [apache/doris#34141]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

2.0.4

### What's Wrong?

我有一张test1的表，表结构如下：
`CREATE TABLE test3 (
  LSD_UUID varchar(40) NOT NULL,
  RECORD_UNIQUE_ID varchar(500) NULL,
  CHECK_BATCH_NO varchar(32) NULL,
  LSD_CREATETIME datetime NULL,
  CJSJ datetime NULL,
  CZDZ text NULL,
  TBSJ datetime NULL,
  SFZH text NULL,
  XM text NULL,
  RYBH text NULL,
  XB text NULL,
  JNDJ int(11) NULL,
  JG text NULL,
  NL int(11) NULL
) ENGINE = OLAP DUPLICATE KEY(`LSD_UUID`) COMMENT 'OLAP' DISTRIBUTED BY HASH(LSD_UUID) BUCKETS 3 PROPERTIES (
  "replication_allocation" = "tag.location.default: 1",
  "is_being_synced" = "false",
  "storage_format" = "V2",
  "light_schema_change" = "true",
  "disable_auto_compaction" = "false",
  "enable_single_replica_compaction" = "false"
);`

表中一共31条数据，我执行truncate 操作，大概需要2分钟，然后提示成功。查看表中数据确实没有了。但是查看fe日志，有如下错误：
`list: 10601, callback id: 587224922, coordinator: FE: 192.168.1.161, transaction status: VISIBLE, error replicas num: 7, replica ids: 14176,14161,14162,14179,14180, prepare time: 1714053066178, commit time: 1714053111199, finish time: 1714053111243, reason:  successfully, publish result: QUORUM_SUCC
2024-04-25 21:51:51,263 WARN (mysql-nio-pool-285|239169) [StmtExecutor.handleDdlStmt():2231] 
org.apache.doris.qe.QueryStateException: errCode = 2, detailMessage = {'label':'delete_da6bbd66-6af6-441d-9b61-bb35ed748ea6', 'status':'VISIBLE', 'txnId':'149689'}
        at org.apache.doris.load.DeleteHandler.commitJob(DeleteHandler.java:526) ~[doris-fe.jar:1.2-SNAPSHOT]
        at org.apache.doris.load.DeleteHandler.process(DeleteHandler.java:399) ~[doris-fe.jar:1.2-SNAPSHOT]
        at org.apache.doris.qe.DdlExecutor.execute(DdlExecutor.java:184) ~[doris-fe.jar:1.2-SNAPSHOT]
        at org.apache.doris.qe.StmtExecutor.handleDdlStmt(StmtExecutor.java:2226) ~[doris-fe.jar:1.2-SNAPSHOT]
        at org.apache.doris.qe.StmtExecutor.executeByLegacy(StmtExecutor.java:763) ~[doris-fe.jar:1.2-SNAPSHOT]
        at org.apache.doris.qe.StmtExecutor.execute(StmtExecutor.java:459) ~[doris-fe.jar:1.2-SNAPSHOT]
        at org.apache.doris.qe.StmtExecutor.execute(StmtExecutor.java:429) ~[doris-fe.jar:1.2-SNAPSHOT]
        at org.apache.doris.statistics.util.StatisticsUtil.execUpdate(StatisticsUtil.java:151) ~[doris-fe.jar:1.2-SNAPSHOT]
        at org.apache.doris.statistics.StatisticsRepository.executeDropSql(StatisticsRepository.java:223) ~[doris-fe.jar:1.2-SNAPSHOT]
        at org.apache.doris.statistics.StatisticsRepository.dropStatisticsByColName(StatisticsRepository.java:211) ~[doris-fe.jar:1.2-SNAPSHOT]
        at org.apache.doris.statistics.StatisticsRepository.dropStatistics(StatisticsRepository.java:188) ~[doris-fe.jar:1.2-SNAPSHOT]
        at org.apache.doris.statistics.AnalysisManager.dropStats(AnalysisManager.java:676) ~[doris-fe.jar:1.2-SNAPSHOT]
        at org.apache.doris.datasource.InternalCatalog.truncateTable(InternalCatalog.java:3060) ~[doris-fe.jar:1.2-SNAPSHOT]
        at org.apache.doris.catalog.Env.truncateTable(Env.java:4981) ~[doris-fe.jar:1.2-SNAPSHOT]
        at org.apache.doris.qe.DdlExecutor.execute(DdlExecutor.java:234) ~[doris-fe.jar:1.2-SNAPSHOT]
        at org.apache.doris.qe.StmtExecutor.handleDdlStmt(StmtExecutor.java:2226) ~[doris-fe.jar:1.2-SNAPSHOT]
        at org.apache.doris.qe.StmtExecutor.executeByLegacy(StmtExecutor.java:763) ~[doris-fe.jar:1.2-SNAPSHOT]
        at org.apache.doris.qe.StmtExecutor.execute(StmtExecutor.java:459) ~[doris-fe.jar:1.2-SNAPSHOT]
        at org.apache.doris.qe.StmtExecutor.execute(StmtExecutor.java:429) ~[doris-fe.jar:1.2-SNAPSHOT]
        at org.apache.doris.qe.ConnectProcessor.handleQuery(ConnectProcessor.java:435) ~[doris-fe.jar:1.2-SNAPSHOT]
        at org.apache.doris.qe.ConnectProcessor.dispatch(ConnectProcessor.java:583) ~[doris-fe.jar:1.2-SNAPSHOT]
        at org.apache.doris.qe.ConnectProcessor.processOnce(ConnectProcessor.java:834) ~[doris-fe.jar:1.2-SNAPSHOT]
        at org.apache.doris.mysql.ReadListener.lambda$handleEvent$0(ReadListener.java:52) ~[doris-fe.jar:1.2-SNAPSHOT]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_402]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_402]
        at java.lang.Thread.run(Thread.java:750) ~[?:1.8.0_402]`

### What You Expected?

truncate操作应该在秒级别执行成功

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by weilai201** [comment]
我使用unique 模型，truncate 操作就非常快！
