### ISSUE TITLE
[Bug] errors while publish version to all backends

### ISSUE THREAD

**Issue by Toms1999** [apache/doris#35455]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

2.1.3

### What's Wrong?

所有的数据写入失败，
ERROR 1105 (HY000): errCode = 2, detailMessage = current running txns on db 10002 is 1000, larger than limit 1000

### What You Expected?

可以写入数据

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Toms1999** [comment]
2024-05-27 18:59:49,297 ERROR (PUBLISH_VERSION|32) [PublishVersionDaemon.runAfterCatalogReady():66] errors while publish version to all backends
java.lang.NullPointerException: null
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) ~[?:1.8.0_345]
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) ~[?:1.8.0_345]
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) ~[?:1.8.0_345]
        at java.util.Iterator.forEachRemaining(Iterator.java:116) ~[?:1.8.0_345]
        at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801) ~[?:1.8.0_345]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482) ~[?:1.8.0_345]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472) ~[?:1.8.0_345]
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708) ~[?:1.8.0_345]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_345]
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:566) ~[?:1.8.0_345]
        at org.apache.doris.transaction.PublishVersionDaemon.getBaseTabletIdsForEachBe(PublishVersionDaemon.java:229) ~[doris-fe.jar:1.2-SNAPSHOT]
        at org.apache.doris.transaction.PublishVersionDaemon.publishVersion(PublishVersionDaemon.java:103) ~[doris-fe.jar:1.2-SNAPSHOT]
        at org.apache.doris.transaction.PublishVersionDaemon.runAfterCatalogReady(PublishVersionDaemon.java:64) ~[doris-fe.jar:1.2-SNAPSHOT]
        at org.apache.doris.common.util.MasterDaemon.runOneCycle(MasterDaemon.java:58) ~[doris-fe.jar:1.2-SNAPSHOT]
        at org.apache.doris.common.util.Daemon.run(Daemon.java:116) ~[doris-fe.jar:1.2-SNAPSHOT]
2024-05-27 18:59:49,307 ERROR (PUBLISH_VERSION|32) [PublishVersionDaemon.runAfterCatalogReady():66] errors while publish version to all backends
