### ISSUE TITLE
[Bug] FE start failure

### ISSUE THREAD

**Issue by yongjinhou** [apache/doris#35879]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

2.0.11

### What's Wrong?

启动fe失败，报错：
2024-06-04 20:16:29,894 WARN (main|1) [DorisFE.start():212] 
java.lang.NoSuchMethodError: 'java.util.stream.Collector com.google.common.collect.ImmutableList.toImmutableList()'
        at org.apache.doris.catalog.FunctionHelper$NamedFunc.<init>(FunctionHelper.java:110) ~[doris-fe.jar:1.2-SNAPSHOT]
        at org.apache.doris.catalog.FunctionHelper$ScalarFunc.<init>(FunctionHelper.java:117) ~[doris-fe.jar:1.2-SNAPSHOT]
        at org.apache.doris.catalog.FunctionHelper.scalar(FunctionHelper.java:66) ~[doris-fe.jar:1.2-SNAPSHOT]
        at org.apache.doris.catalog.BuiltinScalarFunctions.<init>(BuiltinScalarFunctions.java:365) ~[doris-fe.jar:1.2-SNAPSHOT]
        at org.apache.doris.catalog.BuiltinScalarFunctions.<clinit>(BuiltinScalarFunctions.java:701) ~[doris-fe.jar:1.2-SNAPSHOT]
        at org.apache.doris.catalog.FunctionRegistry.registerBuiltinFunctions(FunctionRegistry.java:187) ~[doris-fe.jar:1.2-SNAPSHOT]
        at org.apache.doris.catalog.FunctionRegistry.<init>(FunctionRegistry.java:63) ~[doris-fe.jar:1.2-SNAPSHOT]
        at org.apache.doris.catalog.Env.<init>(Env.java:623) ~[doris-fe.jar:1.2-SNAPSHOT]
        at org.apache.doris.catalog.Env.<init>(Env.java:576) ~[doris-fe.jar:1.2-SNAPSHOT]
        at org.apache.doris.catalog.Env.<init>(Env.java:291) ~[doris-fe.jar:1.2-SNAPSHOT]
        at org.apache.doris.catalog.Env$SingletonHolder.<clinit>(Env.java:572) ~[doris-fe.jar:1.2-SNAPSHOT]
        at org.apache.doris.catalog.Env.getCurrentEnv(Env.java:713) ~[doris-fe.jar:1.2-SNAPSHOT]
        at org.apache.doris.DorisFE.start(DorisFE.java:164) [doris-fe.jar:1.2-SNAPSHOT]
        at org.apache.doris.DorisFE.main(DorisFE.java:84) [doris-fe.jar:1.2-SNAPSHOT]

### What You Expected?

FE正常启动

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by fangshuai0119** [comment]
请问您解决了吗？
