### ISSUE TITLE
[Bug] 查询 tpch 测试库 lineitem 表，6亿数据报[CANCELLED]FullGC release wg overcommit mem, wg id:1, name:normal, used:19.96 GB,limit:8.44 GB,backend:192.168.56.121. cancel top memory used tracker <Query#Id=947104c521024a98-a10fa3843706e043> consumption 19.96 GB. details:os physical memory 31.26 GB. process memory used 27.36 GB, limit 28.14 GB, soft limit 25.32 GB. sys available memory 1.63 GB, low water mark 1.60 GB, warning water mark 3.20 GB. Refresh interval memory growth 0 B

### ISSUE THREAD

**Issue by andy1199** [apache/doris#36677]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

Doris 2.1.0，Doris 2.1.1，Doris 2.1.2，Doris 2.1.3，Doris 2.1.4-pre-releas /  oracle jdk-1.8.0-201 /linux-7.9 会报错
Doris 2.0.11  /  oracle jdk-1.8.0-201 /linux-7.9 可以正常执行

### What's Wrong?

String sql = "SELECT * from lineitem ";

        HikariConfig config = new HikariConfig();
        config.setJdbcUrl("jdbc:mysql://192.168.56.121:9030/tpch" + DORIS_CONNECTION_PARAMS);
        config.setUsername("root");
        config.setPassword("root");
        HikariDataSource hikariDataSource = new HikariDataSource(config);

        Connection connection = hikariDataSource.getConnection();

        PreparedStatement statement = connection.prepareStatement(sql, ResultSet.TYPE_FORWARD_ONLY, ResultSet.CONCUR_READ_ONLY);
    
        statement.setFetchSize(Integer.MIN_VALUE);

        ResultSet resultSet = statement.executeQuery();

        int i = 1;
        while (resultSet.next()) {
            /*String id = resultSet.getString("l_orderkey");
            System.out.println(id);*/
            if (i % 100000 == 0) {
                System.out.println(i);
            }
            i++;
        }

        System.out.println("流式读取资源结束");
        //先开后关原则
        resultSet.close();
        statement.close();
        connection.close();

Exception in thread "main" java.sql.SQLException: errCode = 2, detailMessage = (192.168.56.121)[CANCELLED]FullGC release wg overcommit mem, wg id:1, name:normal, used:19.96 GB,limit:8.44 GB,backend:192.168.56.121. cancel top memory used tracker <Query#Id=947104c521024a98-a10fa3843706e043> consumption 19.96 GB. details:os physical memory 31.26 GB. process memory used 27.36 GB, limit 28.14 GB, soft limit 25.32 GB. sys available memory 1.63 GB, low water mark 1.60 GB, warning water mark 3.20 GB. Refresh interval memory growth 0 B
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:965)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3978)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3914)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:871)
	at com.mysql.jdbc.MysqlIO.nextRow(MysqlIO.java:1999)
	at com.mysql.jdbc.RowDataDynamic.nextRecord(RowDataDynamic.java:374)
	at com.mysql.jdbc.RowDataDynamic.next(RowDataDynamic.java:354)
	at com.mysql.jdbc.ResultSetImpl.next(ResultSetImpl.java:6313)
	at com.zaxxer.hikari.pool.HikariProxyResultSet.next(HikariProxyResultSet.java)
	at com.ssnh.jdbc流式查询.DorisJdbcStreamReader.streamRead(DorisJdbcStreamReader.java:65)
	at com.ssnh.jdbc流式查询.DorisJdbc流式查询测试.main(DorisJdbc流式查询测试.java:17)

### What You Expected?

fix bug

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zheng594** [comment]
doris-2.1.2-rc04遇到了同样的问题，游标读取没生效

**Comment by Iran1112** [comment]
doris-3.0.1 Encountered similar problems, query the external table of iceberg 100 million data.
query sql:
select * from iceberg_wlgjjl1 where id = '2e41f452461eeb62ef27e8773c901470689e';
error msg:
ERROR 1105 (HY000):  errCode = 2, detailMessage = (10.47.75.3)[MEM_LIMIT_EXCEEDED]FullGC release wg overcommit mem, wg id:1, name:normal, used:40.58 GB,limit:16.94 GB,backend:10.47.75.3. cancel top memory used tracker &lt; Used :40.58 GB,limit:16.94 GB, Backend :10.47.75.3. Cancel top memory used tracker &lt; Query#Id=267e31e237d84dbd-81d3dd02258e23f3&gt;  consumption 40.58 GB. details:process memory used 33.25 GB exceed soft limit 50.83 GB or sys available memory 2.97 GB less than warning water mark 6.28 GB., Execute again after enough memory, details see be.INFO.

**Comment by yunxiaoyang01** [comment]
doris-2.1.5 遇到相同的问题。

**Comment by weilai201** [comment]
我也是，doris 2.1.5 查询5000万数据提示这个错误。如何解决啊
