### ISSUE TITLE
[Bug] show resource where name throw excetion

### ISSUE THREAD

**Issue by dataroaring** [apache/doris#36774]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

master

### What's Wrong?

2024-05-14 13:33:34,690 WARN (mysql-nio-pool-31|1938) [StmtExecutor.executeByLegacy():1052] execute Exception. stmt[32259, a9a4ba38e9004d62-9b7042b5a3262f73]
java.util.ConcurrentModificationException: null
	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1597) ~[?:?]
	at java.util.HashMap$EntryIterator.next(HashMap.java:1630) ~[?:?]
	at java.util.HashMap$EntryIterator.next(HashMap.java:1628) ~[?:?]
	at org.apache.doris.catalog.HdfsResource.getProcNodeData(HdfsResource.java:93) ~[doris-fe.jar:1.2-SNAPSHOT]
	at org.apache.doris.catalog.ResourceMgr$ResourceProcNode.fetchResult(ResourceMgr.java:248) ~[doris-fe.jar:1.2-SNAPSHOT]
	at org.apache.doris.catalog.ResourceMgr.getResourcesInfo(ResourceMgr.java:180) ~[doris-fe.jar:1.2-SNAPSHOT]
	at org.apache.doris.qe.ShowExecutor.handleShowResources(ShowExecutor.java:2129) ~[doris-fe.jar:1.2-SNAPSHOT]
	at org.apache.doris.qe.ShowExecutor.execute(ShowExecutor.java:387) ~[doris-fe.jar:1.2-SNAPSHOT]
	at org.apache.doris.qe.StmtExecutor.handleShow(StmtExecutor.java:2787) ~[doris-fe.jar:1.2-SNAPSHOT]
	at org.apache.doris.qe.StmtExecutor.executeByLegacy(StmtExecutor.java:1014) ~[doris-fe.jar:1.2-SNAPSHOT]
	at org.apache.doris.qe.StmtExecutor.execute(StmtExecutor.java:622) ~[doris-fe.jar:1.2-SNAPSHOT]
	at org.apache.doris.qe.StmtExecutor.execute(StmtExecutor.java:533) ~[doris-fe.jar:1.2-SNAPSHOT]
	at org.apache.doris.qe.ConnectProcessor.executeQuery(ConnectProcessor.java:368) ~[doris-fe.jar:1.2-SNAPSHOT]
	at org.apache.doris.qe.ConnectProcessor.handleQuery(ConnectProcessor.java:232) ~[doris-fe.jar:1.2-SNAPSHOT]
	at org.apache.doris.qe.MysqlConnectProcessor.handleQuery(MysqlConnectProcessor.java:177) ~[doris-fe.jar:1.2-SNAPSHOT]
	at org.apache.doris.qe.MysqlConnectProcessor.dispatch(MysqlConnectProcessor.java:205) ~[doris-fe.jar:1.2-SNAPSHOT]
	at org.apache.doris.qe.MysqlConnectProcessor.processOnce(MysqlConnectProcessor.java:258) ~[doris-fe.jar:1.2-SNAPSHOT]
	at org.apache.doris.mysql.ReadListener.lambda$handleEvent$0(ReadListener.java:52) ~[doris-fe.jar:1.2-SNAPSHOT]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:840) ~[?:?]
Attachments

### What You Expected?

no exception

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Suzzt** [comment]
Hi,I hope to try to solve it.

**Comment by jevinjiang** [comment]
@dataroaring 
 Is it okay to modify it to Concurrent HashMap?
