### ISSUE TITLE
```2.0.11版本 fe日志报错System has no available disk capacity or no available BE nodes

### ISSUE THREAD

**Issue by baimafeima-yf** [apache/doris#37105]
```
2023-12-11 11:32:32,699 INFO (Thread-48|97) [InternalCatalog.createDb():423] create database[default_cluster:__internal_schema] which already exists
2023-12-11 11:32:32,700 WARN (Thread-48|97) [InternalSchemaInitializer.run():76] Statistics storage initiated failed, will try again later
org.apache.doris.common.DdlException: errCode = 2, detailMessage = System has no available disk capacity or no available BE nodes
	at org.apache.doris.system.SystemInfoService.checkAvailableCapacity(SystemInfoService.java:817) ~[doris-fe.jar:1.2-SNAPSHOT]
	at org.apache.doris.datasource.InternalCatalog.createTable(InternalCatalog.java:1085) ~[doris-fe.jar:1.2-SNAPSHOT]
	at org.apache.doris.catalog.InternalSchemaInitializer.createTbl(InternalSchemaInitializer.java:130) ~[doris-fe.jar:1.2-SNAPSHOT]
	at org.apache.doris.catalog.InternalSchemaInitializer.run(InternalSchemaInitializer.java:74) ~[doris-fe.jar:1.2-SNAPSHOT]
```

配置了priority_networks，也删除了doris-meta，还是不行；甚至重装了主机都无法修复....
是不是ip_v6的网段识别有问题：
priority_networks = FDBE:DC05:3::/48

_Originally posted by @xinghalo321 in https://github.com/apache/doris/issues/22002#issuecomment-1849282422_

**Comment by kaantecik** [comment]
hi, did you solve this issue?

**Comment by AiTian1211** [comment]
你们其他FE节点第一次启动时是不是没有指定第一个FE节点？./fe/bin/start_fe.sh --helper 10.10.10.16:9010 --daemon
我也遇到这个问题，但我是其他节点第一次启动时忘记指定第一个启动的FE节点了，把doris-meta目录删除后通过./fe/bin/start_fe.sh --helper 10.10.10.16:9010 --daemon启动就解决了

**Comment by kubemain** [comment]
You need to add the backend

```
ALTER SYSTEM ADD BACKEND "10.102.23.2:9050";
```
