### ISSUE TITLE
[Bug] 2.1.5 create hdfs resource and set username=hdfs，be report error:   Permission denied), reason: RemoteException: Permission denied: user=root, access=WRITE

### ISSUE THREAD

**Issue by bestboy** [apache/doris#40311]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

2.1.5

### What's Wrong?

2.1.5 create hdfs resource and set username=hdfs，and no password .when cooldown ttl actived,be_log is error:

W20240903 14:42:27.155025  5471 status.h:412] meet error status: [INTERNAL_ERROR]create dir failed. (BE: 192.168.40.91) namenode: xxxxx.com:8020 path: /data/861609, err: (13), Permission denied), reason: RemoteException: **Permission denied:
 user=root, access=WRITE**, inode="/data":hdfs:hdfs:drwxr-xr-x
        at org.apache.hadoop.hdfs.server.namenode.FSPermissionChecker.check(FSPermissionChecker.java:506)
        at org.apache.hadoop.hdfs.server.namenode.FSPermissionChecker.checkPermission(FSPermissionChecker.java:346)
        at org.apache.hadoop.hdfs.server.namenode.FSPermissionChecker.checkPermissionWithContext(FSPermissionChecker.java:370)
        at org.apache.hadoop.hdfs.server.namenode.FSPermissionChecker.checkPermission(FSPermissionChecker.java:240)
        at org.apache.hadoop.hdfs.server.namenode.FSDirectory.checkPermission(FSDirectory.java:1943)
        at org.apache.hadoop.hdfs.server.namenode.FSDirectory.checkPermission(FSDirectory.java:1927)
        at org.apache.hadoop.hdfs.server.namenode.FSDirectory.checkAncestorAccess(FSDirectory.java:1886)
        at org.apache.hadoop.hdfs.server.namenode.FSDirMkdirOp.mkdirs(FSDirMkdirOp.java:60)
        at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.mkdirs(FSNamesystem.java:3405)
        at org.apache.hadoop.hdfs.server.namenode.NameNodeRpcServer.mkdirs(NameNodeRpcServer.java:1159)
        at org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolServerSideTranslatorPB.mkdirs(ClientNamenodeProtocolServerSideTranslatorPB.java:740)
        at org.apache.hadoop.hdfs.protocol.proto.ClientNamenodeProtocolProtos$ClientNamenodeProtocol$2.callBlockingMethod(ClientNamenodeProtocolProtos.java)
        at org.apache.hadoop.ipc.ProtobufRpcEngine2$Server$ProtoBufRpcInvoker.call(ProtobufRpcEngine2.java:604)
        at org.apache.hadoop.ipc.ProtobufRpcEngine2$Server$ProtoBufRpcInvoker.call(ProtobufRpcEngine2.java:572)
        at org.apache.hadoop.ipc.ProtobufRpcEngine2$Server$ProtoBufRpcInvoker.call(ProtobufRpcEngine2.java:556)
        at org.apache.hadoop.ipc.RPC$Server.call(RPC.java:1093)
        at org.apache.hadoop.ipc.Server$RpcCall.run(Server.java:1043)
        at org.apache.hadoop.ipc.Server$RpcCall.run(Server.java:971)
        at java.security.AccessController.doPrivileged(Native Method)
        at javax.security.auth.Subject.doAs(Subject.java:422)
        at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1878)
        at org.apache.hadoop.ipc.Server$Handler.run(Server.java:2976)

        0#  doris::io::HdfsFileWriter::_open() at /home/zcp/repo_center/doris_enterprise/doris/be/src/common/status.h:0
        1#  doris::io::HdfsFileWriter::appendv(doris::Slice const*, unsigned long) at /home/zcp/repo_center/doris_enterprise/doris/be/src/common/status.h:481
        2#  doris::Tablet::write_cooldown_meta() at /home/zcp/repo_center/doris_enterprise/doris/be/src/common/status.h:481
        3#  std::_Function_handler<void (), doris::WriteCooldownMetaExecutors::submit(std::shared_ptr<doris::Tablet>)::$_1>::_M_invoke(std::_Any_data const&) at /home/zcp/repo_center/doris_enterprise/doris/be/src/common/status.h:481
        4#  doris::WorkThreadPool<true>::work_thread(int) at /var/local/ldb-toolchain/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/atomic_base.h:646
        5#  execute_native_thread_routine at /data/gcc-11.1.0/build/x86_64-pc-linux-gnu/libstdc++-v3/include/bits/unique_ptr.h:85
        6#  start_thread
        7#  __clone

<img width="1304" alt="image" src="https://github.com/user-attachments/assets/5687738c-0c91-4b50-a740-c2ab060323d1">
<img width="1723" alt="image" src="https://github.com/user-attachments/assets/ca337929-569a-4dad-9ec3-d462e2ac4729">

### What You Expected?

when  connect  hdfs use property 'username=hdfs'

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by dataroaring** [comment]
There is a wrong point in doc. Please use   hadoop.username instead of username.
