### ISSUE TITLE
[Bug] PreparedStatement sql can't replace ? to real value

### ISSUE THREAD

**Issue by zhangtao106** [apache/doris#41736]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

doris version: 2.1.6

### What's Wrong?

use execute sql white mybatis, and in my xml use #{}, in audit log, I found much execute error, founded in executed sql ,the ? wasn't replace, and it error 2 types, the one :State=NOOP|ErrorCode=0|ErrorMessage=|Time(ms)=1|ScanBytes=0|ScanRows=0|ReturnRows=0,
the other :State=ERR|ErrorCode=1105|ErrorMessage=NullPointerException, msg: java.lang.NullPointerException: null|Time(ms)=1|ScanBytes=0|ScanRows=0|ReturnRows=0 

### What You Expected?

How to avoid this error

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zhangtao106** [comment]
[StmtExecutor.executeByLegacy():998] execute Exception. stmt[40------38, 4--------c08e51]
java.lang.NullPointerException: null
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:903) ~[guava-32.1.2-jre.jar:?]
	at org.apache.doris.catalog.ScalarType.getAssignmentCompatibleType(ScalarType.java:1148) ~[fe-common-1.2-SNAPSHOT.jar:1.2-SNAPSHOT]
	at org.apache.doris.catalog.ScalarType.isImplicitlyCastable(ScalarType.java:1176) ~[fe-common-1.2-SNAPSHOT.jar:1.2-SNAPSHOT]
	at org.apache.doris.catalog.Type.isImplicitlyCastable(Type.java:825) ~[fe-common-1.2-SNAPSHOT.jar:1.2-SNAPSHOT]
	at org.apache.doris.catalog.Function.isSubtype(Function.java:366) ~[doris-fe.jar:1.2-SNAPSHOT]
	at org.apache.doris.catalog.Function.compare(Function.java:341) ~[doris-fe.jar:1.2-SNAPSHOT]
	at org.apache.doris.catalog.FunctionSet.getFunction(FunctionSet.java:331) ~[doris-fe.jar:1.2-SNAPSHOT]
	at org.apache.doris.catalog.FunctionSet.getFunction(FunctionSet.java:259) ~[doris-fe.jar:1.2-SNAPSHOT]
	at org.apache.doris.catalog.FunctionSet.getFunction(FunctionSet.java:224) ~[doris-fe.jar:1.2-SNAPSHOT]
	at org.apache.doris.catalog.Env.getFunction(Env.java:5365) ~[doris-fe.jar:1.2-SNAPSHOT]

**Comment by zhangtao106** [comment]
and this error appear in Doris 2.1.3
