### ISSUE TITLE
[Bug] Fail to add follower node

### ISSUE THREAD

**Issue by SaelKimberly** [apache/doris#42155]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

3.0.2

### What's Wrong?

When I try to append a follower to a cluster, there is Java error:

```
RuntimeLogger 2024-10-21 04:50:04,070 INFO (main|23) [Env.getSelfHostPort():1435] get self node: HostInfo{host='fe-follower-1', port=9010}
RuntimeLogger 2024-10-21 04:50:04,071 INFO (main|23) [Env.getHelperNodes():1489] get helper nodes: [HostInfo{host='fe-master', port=9010}]
RuntimeLogger 2024-10-21 04:50:04,094 INFO (main|23) [Env.getFeNodeTypeAndNameFromHelpers():1417] get fe node type FOLLOWER, name fe_c272640a_5c2f_40d8_abc0_f40134ee4357 from fe-master:fe-master:8030
RuntimeLogger 2024-10-21 04:50:04,311 ERROR (main|23) [Throwable$WrappedPrintStream.println():763] java.lang.NoSuchMethodError: 'boolean org.apache.http.client.config.RequestConfig.isNormalizeUri()'
RuntimeLogger 2024-10-21 04:50:04,311 ERROR (main|23) [Throwable$WrappedPrintStream.println():763] 	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:133)
RuntimeLogger 2024-10-21 04:50:04,311 ERROR (main|23) [Throwable$WrappedPrintStream.println():763] 	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
RuntimeLogger 2024-10-21 04:50:04,311 ERROR (main|23) [Throwable$WrappedPrintStream.println():763] 	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
RuntimeLogger 2024-10-21 04:50:04,311 ERROR (main|23) [Throwable$WrappedPrintStream.println():763] 	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
RuntimeLogger 2024-10-21 04:50:04,312 ERROR (main|23) [Throwable$WrappedPrintStream.println():763] 	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:72)
RuntimeLogger 2024-10-21 04:50:04,312 ERROR (main|23) [Throwable$WrappedPrintStream.println():763] 	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:221)
RuntimeLogger 2024-10-21 04:50:04,312 ERROR (main|23) [Throwable$WrappedPrintStream.println():763] 	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:165)
RuntimeLogger 2024-10-21 04:50:04,312 ERROR (main|23) [Throwable$WrappedPrintStream.println():763] 	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:140)
RuntimeLogger 2024-10-21 04:50:04,312 ERROR (main|23) [Throwable$WrappedPrintStream.println():763] 	at org.apache.doris.httpv2.rest.manager.HttpUtils.executeRequest(HttpUtils.java:117)
RuntimeLogger 2024-10-21 04:50:04,312 ERROR (main|23) [Throwable$WrappedPrintStream.println():763] 	at org.apache.doris.httpv2.rest.manager.HttpUtils.doGet(HttpUtils.java:81)
RuntimeLogger 2024-10-21 04:50:04,312 ERROR (main|23) [Throwable$WrappedPrintStream.println():763] 	at org.apache.doris.master.MetaHelper.doGet(MetaHelper.java:77)
RuntimeLogger 2024-10-21 04:50:04,312 ERROR (main|23) [Throwable$WrappedPrintStream.println():763] 	at org.apache.doris.catalog.Env.getNewImage(Env.java:2017)
RuntimeLogger 2024-10-21 04:50:04,312 ERROR (main|23) [Throwable$WrappedPrintStream.println():763] 	at org.apache.doris.catalog.Env.getClusterIdAndRole(Env.java:1345)
RuntimeLogger 2024-10-21 04:50:04,312 ERROR (main|23) [Throwable$WrappedPrintStream.println():763] 	at org.apache.doris.catalog.Env.initialize(Env.java:1077)
RuntimeLogger 2024-10-21 04:50:04,312 ERROR (main|23) [Throwable$WrappedPrintStream.println():763] 	at org.apache.doris.DorisFE.start(DorisFE.java:178)
RuntimeLogger 2024-10-21 04:50:04,312 ERROR (main|23) [Throwable$WrappedPrintStream.println():763] 	at org.apache.doris.DorisFE.main(DorisFE.java:95)
RuntimeLogger 2024-10-21 04:50:04,312 WARN (main|23) [DorisFE.start():225] 
java.lang.NoSuchMethodError: 'boolean org.apache.http.client.config.RequestConfig.isNormalizeUri()'
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:133) ~[httpclient-4.5.13.jar:4.5.13]
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89) ~[httpclient-4.5.13.jar:4.5.13]
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110) ~[httpclient-4.5.13.jar:4.5.13]
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185) ~[httpclient-4.5.13.jar:4.5.13]
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:72) ~[httpclient-4.5.13.jar:4.5.13]
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:221) ~[httpclient-4.5.13.jar:4.5.13]
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:165) ~[httpclient-4.5.13.jar:4.5.13]
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:140) ~[httpclient-4.5.13.jar:4.5.13]
	at org.apache.doris.httpv2.rest.manager.HttpUtils.executeRequest(HttpUtils.java:117) ~[doris-fe.jar:1.2-SNAPSHOT]
	at org.apache.doris.httpv2.rest.manager.HttpUtils.doGet(HttpUtils.java:81) ~[doris-fe.jar:1.2-SNAPSHOT]
	at org.apache.doris.master.MetaHelper.doGet(MetaHelper.java:77) ~[doris-fe.jar:1.2-SNAPSHOT]
	at org.apache.doris.catalog.Env.getNewImage(Env.java:2017) ~[doris-fe.jar:1.2-SNAPSHOT]
	at org.apache.doris.catalog.Env.getClusterIdAndRole(Env.java:1345) ~[doris-fe.jar:1.2-SNAPSHOT]
	at org.apache.doris.catalog.Env.initialize(Env.java:1077) ~[doris-fe.jar:1.2-SNAPSHOT]
	at org.apache.doris.DorisFE.start(DorisFE.java:178) ~[doris-fe.jar:1.2-SNAPSHOT]
	at org.apache.doris.DorisFE.main(DorisFE.java:95) ~[doris-fe.jar:1.2-SNAPSHOT]
```

### What You Expected?

Successful append a follower FE node.

### How to Reproduce?

I've trying this configuration:
- Docker
- JDK base image: eclipse-temurin:17.0.12_7-jdk-ubi9-minimal
- Apache Doris build 3.0.2 x64 tar.gz distribution from official download page
- Python script, self written for ease of startup Doris, that do:
  1. Connect to master node, and register current node, by FQDN, as FOLLOWER
  2. Run start.sh with helper as master node FQDN
  3. Wrap and show logs until BaseException occurs (keyboard interrupt, system exit, etc.)
  4. Send SIGTERM to FE process, and wait for its shutdown

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by ixzc** [comment]
can you check whether there are more than one httpclient jar in fe/lib ?

**Comment by SaelKimberly** [comment]
So, I've checked, and there is really more than one.

![image](https://github.com/user-attachments/assets/c1f30216-47bf-4934-bdb4-6d56f937e998)

**Comment by SaelKimberly** [comment]
Maybe, I should remove some of them from `CLASSPATH` or entirely from this directory... But which of them? :thinking:
