### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by autelai2** [apache/doris#43775]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

2.1.6

### What's Wrong?

org.apache.doris.common.DdlException: errCode = 2, detailMessage = Failed to find enough backend, please check the replication num,replication tag and storage medium and avail capacity of backends.
Create failed replications:
replication tag: {"location" : "default"}, replication num: 1, storage medium: HDD
        at org.apache.doris.system.SystemInfoService.selectBackendIdsForReplicaCreation(SystemInfoService.java:551) ~[doris-fe.jar:1.2-SNAPSHOT]
        at org.apache.doris.datasource.InternalCatalog.createTablets(InternalCatalog.java:3156) ~[doris-fe.jar:1.2-SNAPSHOT]
        at org.apache.doris.datasource.InternalCatalog.createPartitionWithIndices(InternalCatalog.java:1995) ~[doris-fe.jar:1.2-SNAPSHOT]
        at org.apache.doris.datasource.InternalCatalog.createOlapTable(InternalCatalog.java:2824) ~[doris-fe.jar:1.2-SNAPSHOT]
        at org.apache.doris.datasource.InternalCatalog.createTable(InternalCatalog.java:1173) ~[doris-fe.jar:1.2-SNAPSHOT]
        at org.apache.doris.catalog.InternalSchemaInitializer.createTbl(InternalSchemaInitializer.java:160) ~[doris-fe.jar:1.2-SNAPSHOT]
        at org.apache.doris.catalog.InternalSchemaInitializer.run(InternalSchemaInitializer.java:80) ~[doris-fe.jar:1.2-SNAPSHOT]

### What You Expected?

org.apache.doris.common.DdlException: errCode = 2, detailMessage = Failed to find enough backend, please check the replication num,replication tag and storage medium and avail capacity of backends.
Create failed replications:
replication tag: {"location" : "default"}, replication num: 1, storage medium: HDD
        at org.apache.doris.system.SystemInfoService.selectBackendIdsForReplicaCreation(SystemInfoService.java:551) ~[doris-fe.jar:1.2-SNAPSHOT]
        at org.apache.doris.datasource.InternalCatalog.createTablets(InternalCatalog.java:3156) ~[doris-fe.jar:1.2-SNAPSHOT]
        at org.apache.doris.datasource.InternalCatalog.createPartitionWithIndices(InternalCatalog.java:1995) ~[doris-fe.jar:1.2-SNAPSHOT]
        at org.apache.doris.datasource.InternalCatalog.createOlapTable(InternalCatalog.java:2824) ~[doris-fe.jar:1.2-SNAPSHOT]
        at org.apache.doris.datasource.InternalCatalog.createTable(InternalCatalog.java:1173) ~[doris-fe.jar:1.2-SNAPSHOT]
        at org.apache.doris.catalog.InternalSchemaInitializer.createTbl(InternalSchemaInitializer.java:160) ~[doris-fe.jar:1.2-SNAPSHOT]
        at org.apache.doris.catalog.InternalSchemaInitializer.run(InternalSchemaInitializer.java:80) ~[doris-fe.jar:1.2-SNAPSHOT]

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by autelai2** [comment]
Statistics storage initiated failed, will try again later

**Comment by abrahammegantoro** [comment]
i got the same error too
