### ISSUE TITLE
[Bug-bdb-error] add fe follower error: conflicts with the socket already used by the member

### ISSUE THREAD

**Issue by francisoliverlee** [apache/doris#4949]
## Describe the bug
0.12.21.release, add fe follower error

## To Reproduce
1. use "kill -9" to kill one follower FE
2. delete the FE's meta dir, and start it but  fail
3. use "alter system" to drop the FE, clean the meta dir, use "alter system" to add it into the cluster 
and get the error

### droped fe error,  but return drop done in mysql client commandline:
```
2020-11-23 19:05:20,294 ERROR 250394 [BDBHA.removeElectableNode():199] the deleting electable node is not found 11.11.27.153_9010_1603291427805
com.sleepycat.je.rep.MemberNotFoundException: (JE 7.3.7) Node: 11.11.27.153_9010_1603291427805 is not a member of the group: PALO_JOURNAL_GROUP
        at com.sleepycat.je.rep.util.ReplicationGroupAdmin.checkMember(ReplicationGroupAdmin.java:563) ~[je-7.3.7.jar:7.3.7]
        at com.sleepycat.je.rep.util.ReplicationGroupAdmin.removeMember(ReplicationGroupAdmin.java:314) ~[je-7.3.7.jar:7.3.7]
        at org.apache.doris.ha.BDBHA.removeElectableNode(BDBHA.java:197) [palo-fe.jar:?]
        at org.apache.doris.catalog.Catalog.dropFrontend(Catalog.java:2540) [palo-fe.jar:?]
        at org.apache.doris.alter.SystemHandler.process(SystemHandler.java:184) [palo-fe.jar:?]
        at org.apache.doris.alter.Alter.processAlterCluster(Alter.java:340) [palo-fe.jar:?]
        at org.apache.doris.catalog.Catalog.alterCluster(Catalog.java:5342) [palo-fe.jar:?]
        at org.apache.doris.qe.DdlExecutor.execute(DdlExecutor.java:174) [palo-fe.jar:?]
        at org.apache.doris.qe.StmtExecutor.handleDdlStmt(StmtExecutor.java:892) [palo-fe.jar:?]
        at org.apache.doris.qe.StmtExecutor.execute(StmtExecutor.java:282) [palo-fe.jar:?]
        at org.apache.doris.qe.ConnectProcessor.proxyExecute(ConnectProcessor.java:456) [palo-fe.jar:?]
        at org.apache.doris.service.FrontendServiceImpl.forward(FrontendServiceImpl.java:579) [palo-fe.jar:?]
        at org.apache.doris.thrift.FrontendService$Processor$forward.getResult(FrontendService.java:1633) [palo-fe.jar:?]
        at org.apache.doris.thrift.FrontendService$Processor$forward.getResult(FrontendService.java:1618) [palo-fe.jar:?]
        at org.apache.thrift.ProcessFunction.process(ProcessFunction.java:39) [libthrift-0.9.3.jar:0.9.3]
        at org.apache.thrift.TBaseProcessor.process(TBaseProcessor.java:39) [libthrift-0.9.3.jar:0.9.3]
        at org.apache.thrift.server.TThreadPoolServer$WorkerProcess.run(TThreadPoolServer.java:286) [libthrift-0.9.3.jar:0.9.3]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_65]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_65]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_65]


```
### add fe error:
```
2020-11-23 13:13:59.722 UTC 警告 [11.11.27.153_9010_1606137216465] Exiting inner Replica loop with exception com.sleepycat.je.EnvironmentFailureException: (JE 7.3.7) 11.11.27.153_9010_1606137216465(-1):/data/doris-fe/doris-meta/bdb  Feeder: 11.11.27.152_9010_1603703245840(14). com.sleepycat.je.rep.impl.RepGroupImpl$NodeConflictException: (JE 7.3.7) New or moved node:11.11.27.153_9010_1606137216465, is configured with the socket address: /11.11.27.153:9010.  It conflicts with the socket already used by the member: 11.11.27.153_9010_1603291427805 HANDSHAKE_ERROR: Error during the handshake between two nodes. Some validity or compatibility check failed, preventing further communication between the nodes. Environment is invalid and must be closed.
com.sleepycat.je.EnvironmentFailureException: (JE 7.3.7) 11.11.27.153_9010_1606137216465(-1):/data/doris-fe/doris-meta/bdb  Feeder: 11.11.27.152_9010_1603703245840(14). com.sleepycat.je.rep.impl.RepGroupImpl$NodeConflictException: (JE 7.3.7) New or moved node:11.11.27.153_9010_1606137216465, is configured with the socket address: /11.11.27.153:9010.  It conflicts with the socket already used by the member: 11.11.27.153_9010_1603291427805 HANDSHAKE_ERROR: Error during the handshake between two nodes. Some validity or compatibility check failed, preventing further communication between the nodes. Environment is invalid and must be closed.
	at com.sleepycat.je.rep.stream.ReplicaFeederHandshake.verifyMembership(ReplicaFeederHandshake.java:334)
	at com.sleepycat.je.rep.stream.ReplicaFeederHandshake.execute(ReplicaFeederHandshake.java:259)
	at com.sleepycat.je.rep.impl.node.Replica.initReplicaLoop(Replica.java:691)
	at com.sleepycat.je.rep.impl.node.Replica.runReplicaLoopInternal(Replica.java:474)
	at com.sleepycat.je.rep.impl.node.Replica.runReplicaLoop(Replica.java:409)
	at com.sleepycat.je.rep.impl.node.RepNode.run(RepNode.java:1873)
```

## Additional context
```
i do some check and find out that the droped-node are still in bdb memory, the two variables bellowing
/com/sleepycat/je/7.3.7/je-7.3.7.jar!/com/sleepycat/je/rep/impl/RepGroupImpl.class

    /* All the nodes that form the replication group, indexed by Id. */
    private final Map<Integer, RepNodeImpl> nodesById =
        new HashMap<Integer, RepNodeImpl>();

    /*
     * All the nodes that form the replication group, indexed by node name.
     * This map is used exclusively for efficient lookups by name. The map
     * nodesById does all the heavy lifting.
     */
    private final Map<String, RepNodeImpl> nodesByName =
        new HashMap<String, RepNodeImpl>();


but in bdb image file , the droped node is not found. 
```

## my possible solution
```
1. restart all fe, fe would reload all fe nodes from image file, it would be droped for the droped fe node
2. bdb is a database, maybe we can delete the record for the dropped fe node
3. other....
```

## question
```
how bdb image content different from bdb memory happen?
```

**Comment by francisoliverlee** [comment]
checked, when adding one FE to the cluster,  VERY  IMPORTANT:
first, alter system add .....
then, start the fe service

todo:
why this happen, can we make it more easier to add one fe cause of human-error with the two steps
