### ISSUE TITLE
Doris imports data through stream load, resulting in connection reset or broken pipe write failed

### ISSUE THREAD

**Issue by 345362231** [apache/doris#6093]
My Doris version is 0.14，The script uses JDBC to connect Doris Fe to create a table, and at the same time uses steam_ Load stores data in the table. The error is below

2021-06-24 16:42:46.876 log [pool-42-thread-2] DEBUG c.c.d.g.p.doris.DorisStorePlugin - 开始发送doris http写请求：url=http://172.22.57.8:8030/api/datalake_hosp2_mix_hosp2his_em
r_lis_736035844_ods/EMRinstance_InstanceUserTemplate/_stream_load
2021-06-24 16:42:46.879 log [Thread-2] INFO  c.c.d.g.job.task.CacheTaskContainer - 任务【TRANS:CHUNK:datalake_CDSDBRMYY_HIS_hosp8his_ods_ZLHIS_zhuyuanfeiyongjilu_556937113】销>
毁完毕
2021-06-24 16:42:46.879 log [Thread-2] INFO  c.c.d.g.job.task.CacheTaskContainer - 任务【TRANS:CHUNK:datalake_hosp2_mix_hosp2his_emr_lis_736035844_ods_EMRinstance_InstanceUserT
emplate】开始销毁
2021-06-24 16:42:46.879 log [Thread-2] DEBUG c.c.d.g.p.doris.DorisStorePlugin - finished plugin
2021-06-24 16:42:46.888 log [pool-42-thread-2] INFO  o.a.http.impl.execchain.RetryExec - I/O exception (java.net.SocketException) caught when processing request to {}->http://1
72.22.57.8:8030: Connection reset
2021-06-24 16:42:46.888 log [pool-42-thread-2] ERROR c.c.d.g.p.doris.DorisStorePlugin - 导入数据错误
org.apache.http.client.ClientProtocolException: null
at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:187)
at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:72)
at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:221)
at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:165)
at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:140)
at com.cecdsc.dep.gateway.common.WebClient.sendStream(WebClient.java:152)
at com.cecdsc.dep.gateway.plugin.doris.DorisStorePlugin.sendDataToUrl(DorisStorePlugin.java:491)
at com.cecdsc.dep.gateway.plugin.doris.DorisStorePlugin.sendData(DorisStorePlugin.java:964)
at com.cecdsc.dep.gateway.plugin.AbstractStorePlugin.lambda$createSendTask$31(AbstractStorePlugin.java:105)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.http.client.NonRepeatableRequestException: Cannot retry request with a non-repeatable request entity
at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:108)
at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)... 13 common frames omittedCaused by: java.net.SocketException: Connection resetat java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:115)at java.net.SocketOutputStream.write(SocketOutputStream.java:155)at org.apache.http.impl.io.SessionOutputBufferImpl.streamWrite(SessionOutputBufferImpl.java:124)at org.apache.http.impl.io.SessionOutputBufferImpl.flushBuffer(SessionOutputBufferImpl.java:136)at org.apache.http.impl.io.SessionOutputBufferImpl.write(SessionOutputBufferImpl.java:167)at org.apache.http.impl.io.ChunkedOutputStream.flushCacheWithAppend(ChunkedOutputStream.java:122)at org.apache.http.impl.io.ChunkedOutputStream.write(ChunkedOutputStream.java:179)at org.apache.http.entity.InputStreamEntity.writeTo(InputStreamEntity.java:134)
at org.apache.http.impl.execchain.RequestEntityProxy.writeTo(RequestEntityProxy.java:121)

Be error， The error is below:
internal error：canceled

I don't know why there is a connection reset. Who can help？
Does Doris of 0.14 add any detection methods？

**Comment by WindyGao** [comment]
《Doris StreamLoad任务报错Connection reset》 https://blog.csdn.net/qq_37865420/article/details/118090756

**Comment by WindyGao** [comment]
disable httpv2 and then retry sit

`enable_http_server_v2 =false`

**Comment by WindyGao** [comment]
#6013 
#6070 
it can help you

**Comment by 345362231** [comment]
well,thank you very much ,it does work

**Comment by 345362231** [comment]
well,thank you,it does work

**Comment by 345362231** [comment]
ok

**Comment by WindyGao** [comment]
> well,thank you,it does work

well, the new version of StreamLoad starting from 0.14 has no upload file size limit configured
```
spring.servlet.multipart.max-file-size
spring.servlet.multipart.max-request-size
```
so StreamLoad generates an A error for the amount of data being uploaded

File uploads with small amounts of data that do not exceed the default limit will not have this problem

**Comment by 345362231** [comment]
thank you，enable httpv2 enable_http_server_v2 =true,I can't stream load to Doris when I set the file size below 100m，why？The default parameter is below 100m
