### ISSUE TITLE
pyflink已经 引入doris-flink-1.0-SNAPSHOT.jar 仍然报错

### ISSUE THREAD

**Issue by banjin** [apache/doris#6124]
Traceback (most recent call last):
  File "mysql_to_doris.py", line 142, in <module>
    t_env.execute_sql(sql).wait()
  File "/Library/Python/3.7/site-packages/pyflink/table/table_environment.py", line 804, in execute_sql
    return TableResult(self._j_tenv.executeSql(stmt))
  File "/Library/Python/3.7/site-packages/py4j/java_gateway.py", line 1286, in __call__
    answer, self.gateway_client, self.target_id, self.name)
  File "/Library/Python/3.7/site-packages/pyflink/util/exceptions.py", line 146, in deco
    return f(*a, **kw)
  File "/Library/Python/3.7/site-packages/py4j/protocol.py", line 328, in get_return_value
    format(target_id, ".", name), value)
py4j.protocol.Py4JJavaError: An error occurred while calling o4.executeSql.
: org.apache.flink.table.api.ValidationException: Unable to create a source for reading table 'default_catalog.default_database.flink_doris_source'.

Table options are:

'connector'='doris'
'fenodes'='doris域名:8030'
'password'=''
'table.identifier'='库.表'
'username'=''
	at org.apache.flink.table.factories.FactoryUtil.createTableSource(FactoryUtil.java:137)
	at org.apache.flink.table.planner.plan.schema.CatalogSourceTable.createDynamicTableSource(CatalogSourceTable.java:116)
	at org.apache.flink.table.planner.plan.schema.CatalogSourceTable.toRel(CatalogSourceTable.java:82)
	at org.apache.calcite.sql2rel.SqlToRelConverter.toRel(SqlToRelConverter.java:3585)
	at org.apache.calcite.sql2rel.SqlToRelConverter.convertIdentifier(SqlToRelConverter.java:2507)
	at org.apache.calcite.sql2rel.SqlToRelConverter.convertFrom(SqlToRelConverter.java:2144)
	at org.apache.calcite.sql2rel.SqlToRelConverter.convertFrom(SqlToRelConverter.java:2093)
	at org.apache.calcite.sql2rel.SqlToRelConverter.convertFrom(SqlToRelConverter.java:2050)
	at org.apache.calcite.sql2rel.SqlToRelConverter.convertSelectImpl(SqlToRelConverter.java:663)
	at org.apache.calcite.sql2rel.SqlToRelConverter.convertSelect(SqlToRelConverter.java:644)
	at org.apache.calcite.sql2rel.SqlToRelConverter.convertQueryRecursive(SqlToRelConverter.java:3438)
	at org.apache.calcite.sql2rel.SqlToRelConverter.convertQuery(SqlToRelConverter.java:570)
	at org.apache.flink.table.planner.calcite.FlinkPlannerImpl.org$apache$flink$table$planner$calcite$FlinkPlannerImpl$$rel(FlinkPlannerImpl.scala:170)
	at org.apache.flink.table.planner.calcite.FlinkPlannerImpl.rel(FlinkPlannerImpl.scala:162)
	at org.apache.flink.table.planner.operations.SqlToOperationConverter.toQueryOperation(SqlToOperationConverter.java:967)
	at org.apache.flink.table.planner.operations.SqlToOperationConverter.convertSqlQuery(SqlToOperationConverter.java:936)
	at org.apache.flink.table.planner.operations.SqlToOperationConverter.convert(SqlToOperationConverter.java:275)
	at org.apache.flink.table.planner.delegation.ParserImpl.parse(ParserImpl.java:101)
	at org.apache.flink.table.api.internal.TableEnvironmentImpl.executeSql(TableEnvironmentImpl.java:724)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.flink.api.python.shaded.py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at org.apache.flink.api.python.shaded.py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at org.apache.flink.api.python.shaded.py4j.Gateway.invoke(Gateway.java:282)
	at org.apache.flink.api.python.shaded.py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at org.apache.flink.api.python.shaded.py4j.commands.CallCommand.execute(CallCommand.java:79)
	at org.apache.flink.api.python.shaded.py4j.GatewayConnection.run(GatewayConnection.java:238)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NoSuchMethodError: org.apache.flink.table.factories.DynamicTableFactory$Context.getCatalogTable()Lorg/apache/flink/table/catalog/CatalogTable;
	at org.apache.doris.flink.table.DorisDynamicTableFactory.createDynamicTableSource(DorisDynamicTableFactory.java:192)
	at org.apache.flink.table.factories.FactoryUtil.createTableSource(FactoryUtil.java:134)
	... 29 more

**Comment by JNSimba** [comment]
It looks like the jar package conflicts，what is the flink version and scala version you are using？

**Comment by banjin** [comment]
> It looks like the jar package conflicts，what is the flink version and scala version you are using？

flink version: 1.13
scala version: 2.12

**Comment by JNSimba** [comment]
flink-doris-connector version may need to be upgraded,  It is currently possible to access doris through datastream.

**Comment by banjin** [comment]
> The flink1.13.0 **DynamicTableFactory** part has been updated，flink-doris-connector version may need to be upgraded, It is currently possible to access doris through datastream.

这是我的代码
```
from pyflink.datastream import StreamExecutionEnvironment
from pyflink.table import StreamTableEnvironment, DataTypes
from pyflink.common.typeinfo import Types


# create a blink streaming TableEnvironment from a StreamExecutionEnvironment
s_env = StreamExecutionEnvironment.get_execution_environment()
s_env.add_jars("file:///project/flink/usrlib/doris-flink-1.0-SNAPSHOT.jar;"
               "file:///project/flink/usrlib/flink-connector-jdbc_2.11-1.13.0.jar")
t_env = StreamTableEnvironment.create(stream_execution_environment=s_env)

dorisTableSource = """
    CREATE TABLE flink_doris_source (
    id INT,
    ip VARCHAR
    )
    WITH (
      'connector' = 'doris',
      'fenodes' = 'doris域名:8030',
      'table.identifier' = '库.表',
      'username' = '',
      'password' = ''
)
"""

t_env.execute_sql(dorisTableSource)

sql = "select * from flink_doris_source"
# 第三步注册表到flink
t_env.execute_sql(sql).wait()
```

但是还是报上述错误？请问有pyflink使用doris的示例吗？ 谢谢

@JNSimba

**Comment by JNSimba** [comment]
The error report is a problem of flink-doris-connector，Currently, the operation mode of flinksql does not support flink1.13.0.
After upgrading flink-doris-connector to 1.13.0, this problem can be solved, but it is not compatible with versions before 1.13. So you can modify the pom file of flink-doris-connector to **<flink.version>1.13.0</flink.version>** in the source code, and this problem can be solved after repackaging.

**Comment by banjin** [comment]
> The error report is a problem of flink-doris-connector，Currently, the operation mode of flinksql does not support flink1.13.0.
> After upgrading flink-doris-connector to 1.13.0, this problem can be solved, but it is not compatible with versions before 1.13. So you can modify the pom file of flink-doris-connector to **<flink.version>1.13.0</flink.version>** in the source code, and this problem can be solved after repackaging.

我尝试编译新的版本，只是缺乏文档，不是很清楚如何编译？是单独在flink-doris-connector下编译吗？在编译时候<thriftExecutable>${doris.thirdparty}/installed/bin/thrift</thriftExecutable>--> 找不到此路径,麻烦您指导一下，谢谢

**Comment by JNSimba** [comment]
> > The error report is a problem of flink-doris-connector，Currently, the operation mode of flinksql does not support flink1.13.0.
> > After upgrading flink-doris-connector to 1.13.0, this problem can be solved, but it is not compatible with versions before 1.13. So you can modify the pom file of flink-doris-connector to **<flink.version>1.13.0</flink.version>** in the source code, and this problem can be solved after repackaging.
> 
> 我尝试编译新的版本，只是缺乏文档，不是很清楚如何编译？是单独在flink-doris-connector下编译吗？在编译时候${doris.thirdparty}/installed/bin/thrift--> 找不到此路径,麻烦您指导一下，谢谢

sh build.sh in the root directory of flink-doris-connector
