### ISSUE TITLE
Stream Load failed

### ISSUE THREAD

**Issue by lijinwang-web** [apache/doris#6312]
经DataX智能分析,该任务最可能的错误原因是:
com.alibaba.datax.common.exception.DataXException: Code:[DBUtilErrorCode-05], Description:[往您配置的写入表中写入数据时失败.].  - java.lang.RuntimeException: Writing records to Doris failed.
        at com.dorisdb.connector.datax.plugin.writer.doriswriter.manager.DorisWriterManager.checkFlushException(DorisWriterManager.java:141)
        at com.dorisdb.connector.datax.plugin.writer.doriswriter.manager.DorisWriterManager.writeRecord(DorisWriterManager.java:37)
        at com.dorisdb.connector.datax.plugin.writer.doriswriter.DorisWriter$Task.startWrite(DorisWriter.java:117)
        at com.alibaba.datax.core.taskgroup.runner.WriterRunner.run(WriterRunner.java:56)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.IOException: java.io.IOException: Unable to flush data to doris: unknown result status.
        at com.dorisdb.connector.datax.plugin.writer.doriswriter.manager.DorisWriterManager.asyncFlush(DorisWriterManager.java:127)
        at com.dorisdb.connector.datax.plugin.writer.doriswriter.manager.DorisWriterManager.access$000(DorisWriterManager.java:15)
        at com.dorisdb.connector.datax.plugin.writer.doriswriter.manager.DorisWriterManager$1.run(DorisWriterManager.java:94)
        ... 1 more
Caused by: java.io.IOException: Unable to flush data to doris: unknown result status.
        at com.dorisdb.connector.datax.plugin.writer.doriswriter.manager.DorisStreamLoadVisitor.doStreamLoad(DorisStreamLoadVisitor.java:58)
        at com.dorisdb.connector.datax.plugin.writer.doriswriter.manager.DorisWriterManager.asyncFlush(DorisWriterManager.java:121)
        ... 3 more
 - java.lang.RuntimeException: Writing records to Doris failed.

**Comment by wangyne** [comment]
解决了么

**Comment by ywhfzy** [comment]
MySQL同步至Doris 也报错这个，有懂的大佬吗？

**Comment by bymeycc** [comment]
有大佬分析什么问题原因嘛？
