### ISSUE TITLE
[Bug] Can't stop canal sync job which thread state is waiting on condition

### ISSUE THREAD

**Issue by kylinmac** [apache/doris#8143]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Version

f227472db2d8ec207efac2fc144b08a969acb98f

### What's Wrong?

Canal同步job，查看线程状态一直处于waiting on condition状态 (canal同步库的binlog被重置了，位置对不上，这个应该是导致问题的主要原因)
```
"Thread-108" #283 daemon prio=5 os_prio=0 tid=0x00007f24b4299000 nid=0x5820 waiting on condition [0x00007f24a7089000]
   java.lang.Thread.State: WAITING (parking)
        at sun.misc.Unsafe.park(Native Method)
        - parking to wait for  <0x00000006ce14c9a0> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
        at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
        at java.util.concurrent.LinkedBlockingQueue.put(LinkedBlockingQueue.java:350)
        at org.apache.doris.load.sync.canal.CanalSyncDataConsumer.put(CanalSyncDataConsumer.java:301)
        at org.apache.doris.load.sync.canal.CanalSyncDataReceiver.process(CanalSyncDataReceiver.java:105)
        at org.apache.doris.load.sync.SyncLifeCycle$2.run(SyncLifeCycle.java:48)
        at java.lang.Thread.run(Thread.java:748)

   Locked ownable synchronizers:
        - None
```
因为我自己加过日志输出，代码行数有偏差，定位是停在 CanalSyncDataConsumer的dataBlockingQueue.put(dataEvents)；
```
mysql> show sync job;
+-------+---------+-------+---------+----------------------------+-------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------+---------------------+---------------------+--------------+------------+------+
| JobId | JobName | Type  | State   | Channel                    | Status
                               | JobConfig
                    | CreateTime          | LastStartTime       | LastStopTime | FinishTime | Msg  |
+-------+---------+-------+---------+----------------------------+-------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------+---------------------+---------------------+--------------+------------+------+
| 20096 | job11   | CANAL | RUNNING | db.canal_test->canal_test | position:[binlog.000398:160412032], executeTime:[2022-02-14 09:53:29], delay:5260ms | address:ip:port,destination:ba_sync,batchSize:8192,mode:null,namesrv:null,topic:null,group:null | 2022-02-08 16:07:52 | 2022-02-08 16:07:56 | NULL         | NULL       | NULL |
+-------+---------+-------+---------+----------------------------+-------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------+---------------------+---------------------+--------------+------------+------+
1 row in set (0.00 sec)
mysql> stop sync job `job11`;
```
此时stop sync job线程状态如下，尝试执行过多次，所以找到不止一个
```
"doris-mysql-nio-pool-158" #14279 daemon prio=5 os_prio=0 tid=0x00007f24f43be800 nid=0x1e3d waiting on condition [0x00007f24a1750000]
   java.lang.Thread.State: WAITING (parking)
        at sun.misc.Unsafe.park(Native Method)
        - parking to wait for  <0x00000006ce0dfe28> (a java.util.concurrent.locks.ReentrantLock$FairSync)
        at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
        - parking to wait for  <0x00000006ce0dfe28> (a java.util.concurrent.locks.ReentrantLock$FairSync)
        at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(AbstractQueuedSynchronizer.java:836)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireQueued(AbstractQueuedSynchronizer.java:870)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquire(AbstractQueuedSynchronizer.java:1199)
        at java.util.concurrent.locks.ReentrantLock$FairSync.lock(ReentrantLock.java:224)
        at java.util.concurrent.locks.ReentrantLock.lock(ReentrantLock.java:285)
        at org.apache.doris.load.sync.canal.SyncCanalClient.lock(SyncCanalClient.java:48)
        at org.apache.doris.load.sync.canal.SyncCanalClient.shutdown(SyncCanalClient.java:84)
        at org.apache.doris.load.sync.canal.CanalSyncJob.unprotectedStopClient(CanalSyncJob.java:271)
        at org.apache.doris.load.sync.canal.CanalSyncJob.cancel(CanalSyncJob.java:216)
        at org.apache.doris.load.sync.SyncJobManager.stopSyncJob(SyncJobManager.java:201)
        at org.apache.doris.qe.DdlExecutor.execute(DdlExecutor.java:279)
        at org.apache.doris.qe.StmtExecutor.handleDdlStmt(StmtExecutor.java:1488)
        at org.apache.doris.qe.StmtExecutor.execute(StmtExecutor.java:425)
        at org.apache.doris.qe.StmtExecutor.execute(StmtExecutor.java:300)
        at org.apache.doris.qe.ConnectProcessor.handleQuery(ConnectProcessor.java:212)
        at org.apache.doris.qe.ConnectProcessor.dispatch(ConnectProcessor.java:349)
        at org.apache.doris.qe.ConnectProcessor.processOnce(ConnectProcessor.java:538)
        at org.apache.doris.mysql.nio.ReadListener.lambda$handleEvent$0(ReadListener.java:50)
        at org.apache.doris.mysql.nio.ReadListener$$Lambda$687/307584650.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

   Locked ownable synchronizers:
        - <0x00000006cd0c5d58> (a java.util.concurrent.ThreadPoolExecutor$Worker)

"doris-mysql-nio-pool-149" #13297 daemon prio=5 os_prio=0 tid=0x00007f24f43f3000 nid=0x3ae1 in Object.wait() [0x00007f24a0740000]
   java.lang.Thread.State: WAITING (on object monitor)
        at java.lang.Object.wait(Native Method)
        at java.lang.Thread.join(Thread.java:1252)
        - locked <0x00000006ccea0c90> (a java.lang.Thread)
        at java.lang.Thread.join(Thread.java:1326)
        at org.apache.doris.load.sync.SyncLifeCycle.stop(SyncLifeCycle.java:71)
        at org.apache.doris.load.sync.canal.SyncCanalClient.shutdown(SyncCanalClient.java:87)
        at org.apache.doris.load.sync.canal.CanalSyncJob.unprotectedStopClient(CanalSyncJob.java:271)
        at org.apache.doris.load.sync.canal.CanalSyncJob.cancel(CanalSyncJob.java:216)
        at org.apache.doris.load.sync.SyncJobManager.stopSyncJob(SyncJobManager.java:201)
        at org.apache.doris.qe.DdlExecutor.execute(DdlExecutor.java:279)
        at org.apache.doris.qe.StmtExecutor.handleDdlStmt(StmtExecutor.java:1488)
        at org.apache.doris.qe.StmtExecutor.execute(StmtExecutor.java:425)
        at org.apache.doris.qe.StmtExecutor.execute(StmtExecutor.java:300)
        at org.apache.doris.qe.ConnectProcessor.handleQuery(ConnectProcessor.java:212)
        at org.apache.doris.qe.ConnectProcessor.dispatch(ConnectProcessor.java:349)
        at org.apache.doris.qe.ConnectProcessor.processOnce(ConnectProcessor.java:538)
        at org.apache.doris.mysql.nio.ReadListener.lambda$handleEvent$0(ReadListener.java:50)
        at org.apache.doris.mysql.nio.ReadListener$$Lambda$687/307584650.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

   Locked ownable synchronizers:
        - <0x00000006ccf9e3f8> (a java.util.concurrent.ThreadPoolExecutor$Worker)
        - <0x00000006ce0dfe28> (a java.util.concurrent.locks.ReentrantLock$FairSync)

```
停不掉了-_-!

### What You Expected?

stop the job 

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by xy720** [comment]
dataBlockingQueue就是任务的消息消费队列。
看起来是receiver线程阻塞在队列的插入上了，但是从你提供的日志还不知道为什么阻塞在了队列的插入上
有一种可能是队列另一端的消费线程也卡住了
如果可以的话你看看能不能定位是不是有线程卡在consumer的其他位置上了

**Comment by kylinmac** [comment]
我触发的原因是MySQL的binlog被重置了
