### ISSUE TITLE
[Bug] core dump on BrokerScanNode with clang

### ISSUE THREAD

**Issue by BiteTheDDDDt** [apache/doris#8317]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Version

master

### What's Wrong?

```cpp
#0  0x0000000002c4fef1 in doris::LzopDecompressor::decompress (this=<optimized out>, input=<optimized out>,
    input_len=<optimized out>, input_bytes_read=<optimized out>,
    output=0x26cea000 "-36\t-22732\t-1532265668\t2829445325163033223\t132328487688451240408893329791690904962\t0sa0XLp1rcPboUcBJZo3u\t6YMuzzTwz4h5qNy4PVQ9jpzfqpGtnum7jhFPUamNrtuiUS7bxqBa35WDEybLJCnogrfRLCw5guucWvaCt5tkvHNLl9Lpr0q"..., output_max_len=8388608,
    decompressed_len=0x7f6033710a38, stream_end=0x1e0dce6a, more_input_bytes=0x1e0dce70, more_output_bytes=0x1e0dce78)
    at /home/disk2/pxl/dev/baidu/bdg/doris/core/be/src/exec/lzo_decompressor.cpp:92
#1  0x0000000002c3a380 in doris::PlainTextLineReader::read_line (this=0x1e0dcdd0, ptr=0x7f6033710d70, size=0x7f6033710d78,
    eof=0xa6e1dbc) at /home/disk2/pxl/dev/baidu/bdg/doris/core/be/src/exec/plain_text_line_reader.cpp:281
#2  0x0000000002c47897 in doris::BrokerScanner::get_next (this=0xa6e1c00, tuple=0x262be000, tuple_pool=0xbcc5ab8,
    eof=0x7f6033710f47, fill_tuple=0x7f6033710f10) at /home/disk2/pxl/dev/baidu/bdg/doris/core/be/src/exec/broker_scanner.cpp:105
#3  0x0000000002c2d497 in doris::BrokerScanNode::scanner_scan (this=this@entry=0x1a58b600, scan_range=..., conjunct_ctxs=...,
    counter=counter@entry=0x7f60337111a0) at /home/disk2/pxl/dev/baidu/bdg/doris/core/be/src/exec/broker_scan_node.cpp:288
#4  0x0000000002c2c030 in doris::BrokerScanNode::scanner_worker (this=0x720, start_idx=<optimized out>, length=<optimized out>)
    at /home/disk2/pxl/dev/baidu/bdg/doris/core/be/src/exec/broker_scan_node.cpp:359
#5  0x00000000066cda00 in execute_native_thread_routine ()
#6  0x000000318b207851 in start_thread () from /lib64/libpthread.so.0
#7  0x000000318aee767d in clone () from /lib64/libc.so.6
```

Only core dump on clang release (but ASAN+O3 is ok, gcc is ok also)

### What You Expected?

fix

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by dataroaring** [comment]
Does it show the core dump reason, like segment fault?

**Comment by BiteTheDDDDt** [comment]
> Does it show the core dump reason, like segment fault?

yes, the reason is segmentation fault.
