### ISSUE TITLE
[Bug] regression-test fail for aggregate

### ISSUE THREAD

**Issue by SWJTU-ZhangLei** [apache/doris#8922]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Version

MySQL [regression_test_zhanglei_aggregate]> select stddev_pop(distinct c_bigint), stddev_pop(c_double) from datetype;
+---------------------------------+------------------------+
| stddev_pop(DISTINCT `c_bigint`) | stddev_pop(`c_double`) |
+---------------------------------+------------------------+
|              3145.0576394647451 |     35.210273031541988 |
+---------------------------------+------------------------+
1 row in set (0.008 sec)

MySQL [regression_test_zhanglei_aggregate]> select stddev_pop(c_bigint), stddev_pop(c_double) from datetype;
+------------------------+------------------------+
| stddev_pop(`c_bigint`) | stddev_pop(`c_double`) |
+------------------------+------------------------+
|     3037.0783723835643 |     35.210273031541995 |
+------------------------+------------------------+
1 row in set (0.005 sec)

MySQL [regression_test_zhanglei_aggregate]> show globals;
ERROR 1105 (HY000): errCode = 2, detailMessage = Syntax error in line 1:
show globals
     ^
Encountered: IDENTIFIER
Expected

MySQL [regression_test_zhanglei_aggregate]> select stddev_pop(c_bigint), stddev_pop(c_double) from datetype;
+------------------------+------------------------+
| stddev_pop(`c_bigint`) | stddev_pop(`c_double`) |
+------------------------+------------------------+
|     3037.0783723835643 |     35.210273031541995 |
+------------------------+------------------------+
1 row in set (0.006 sec)

MySQL [regression_test_zhanglei_aggregate]> select stddev_pop(c_bigint), stddev_pop(c_double) from datetype;
+------------------------+------------------------+
| stddev_pop(`c_bigint`) | stddev_pop(`c_double`) |
+------------------------+------------------------+
|     3037.0783723835643 |     35.210273031541995 |
+------------------------+------------------------+
1 row in set (0.005 sec)

MySQL [regression_test_zhanglei_aggregate]> select stddev_pop(distinct c_bigint), stddev_pop(c_double) from datetype;
+---------------------------------+------------------------+
| stddev_pop(DISTINCT `c_bigint`) | stddev_pop(`c_double`) |
+---------------------------------+------------------------+
|              3145.0576394647451 |     35.210273031541988 |
+---------------------------------+------------------------+
1 row in set (0.004 sec)

MySQL [regression_test_zhanglei_aggregate]> show variables;
+--------------------------------------+-------------------------------+
| Variable_name                        | Value                         |
+--------------------------------------+-------------------------------+
| SQL_AUTO_IS_NULL                     | false                         |
| allow_partition_column_nullable      | true                          |
| auto_increment_increment             | 1                             |
| autocommit                           | true                          |
| batch_size                           | 1024                          |
| block_encryption_mode                |                               |
| character_set_client                 | utf8                          |
| character_set_connection             | utf8                          |
| character_set_results                | utf8                          |
| character_set_server                 | utf8                          |
| codegen_level                        | 0                             |
| collation_connection                 | utf8_general_ci               |
| collation_database                   | utf8_general_ci               |
| collation_server                     | utf8_general_ci               |
| cpu_resource_limit                   | -1                            |
| default_rowset_type                  | beta                          |
| delete_without_partition             | false                         |
| disable_colocate_plan                | false                         |
| disable_join_reorder                 | false                         |
| disable_streaming_preaggregations    | false                         |
| div_precision_increment              | 4                             |
| enable_bucket_shuffle_join           | true                          |
| enable_cost_based_join_reorder       | false                         |
| enable_exchange_node_parallel_merge  | false                         |
| enable_fold_constant_by_be           | false                         |
| enable_infer_predicate               | false                         |
| enable_insert_strict                 | false                         |
| enable_lateral_view                  | false                         |
| enable_odbc_transcation              | false                         |
| enable_parallel_outfile              | false                         |
| enable_partition_cache               | false                         |
| enable_profile                       | false                         |
| enable_spilling                      | false                         |
| enable_sql_cache                     | false                         |
| enable_vectorized_engine             | true                          |
| event_scheduler                      | OFF                           |
| exec_mem_limit                       | 10737418240                   |
| extract_wide_range_expr              | true                          |
| forward_to_master                    | true                          |
| init_connect                         |                               |
| insert_visible_timeout_ms            | 10000                         |
| interactive_timeout                  | 3600                          |
| language                             | /palo/share/english/          |
| license                              | Apache License, Version 2.0   |
| load_mem_limit                       | 0                             |
| lower_case_table_names               | 0                             |
| max_allowed_packet                   | 1048576                       |
| max_pushdown_conditions_per_column   | -1                            |
| max_scan_key_num                     | -1                            |
| net_buffer_length                    | 16384                         |
| net_read_timeout                     | 60                            |
| net_write_timeout                    | 60                            |
| parallel_exchange_instance_num       | -1                            |
| parallel_fragment_exec_instance_num  | 1                             |
| partition_prune_algorithm_version    | 2                             |
| performance_schema                   | OFF                           |
| prefer_join_method                   | broadcast                     |
| query_cache_size                     | 1048576                       |
| query_cache_type                     | 0                             |
| query_timeout                        | 3600                          |
| resource_group                       | normal                        |
| return_object_data_as_binary         | false                         |
| rewrite_count_distinct_to_bitmap_hll | true                          |
| runtime_bloom_filter_max_size        | 16777216                      |
| runtime_bloom_filter_min_size        | 1048576                       |
| runtime_bloom_filter_size            | 2097152                       |
| runtime_filter_max_in_num            | 1024                          |
| runtime_filter_mode                  | GLOBAL                        |
| runtime_filter_type                  | IN_OR_BLOOM_FILTER            |
| runtime_filter_wait_time_ms          | 1000                          |
| runtime_filters_max_num              | 10                            |
| send_batch_parallelism               | 1                             |
| show_hidden_columns                  | false                         |
| sql_mode                             |                               |
| sql_quote_show_create                | true                          |
| sql_safe_updates                     | 0                             |
| sql_select_limit                     | 9223372036854775807           |
| storage_engine                       | olap                          |
| system_time_zone                     | Asia/Shanghai                 |
| test_materialized_view               | false                         |
| time_zone                            | Asia/Shanghai                 |
| transaction_isolation                | REPEATABLE-READ               |
| transaction_read_only                | false                         |
| tx_isolation                         | REPEATABLE-READ               |
| tx_read_only                         | false                         |
| use_v2_rollup                        | false                         |
| version                              | 5.7.37                        |
| version_comment                      | Doris version trunk-c87ac2270 |
| wait_timeout                         | 28800                         |
+--------------------------------------+-------------------------------+
89 rows in set (0.005 sec)

MySQL [regression_test_zhanglei_aggregate]> select @@version_comment;
+-------------------------------+
| @@version_comment             |
+-------------------------------+
| Doris version trunk-c87ac2270 |
+-------------------------------+
1 row in set (0.002 sec)

MySQL [regression_test_zhanglei_aggregate]> show backends;
+-----------+-----------------+--------------+---------------+--------+----------+----------+---------------------+---------------------+-------+----------------------+-----------------------+-----------+------------------+---------------+---------------+---------+----------------+--------------------------+--------+-----------------+-------------------------------------------------------------------------------------------------------------------------------+
| BackendId | Cluster         | IP           | HeartbeatPort | BePort | HttpPort | BrpcPort | LastStartTime       | LastHeartbeat       | Alive | SystemDecommissioned | ClusterDecommissioned | TabletNum | DataUsedCapacity | AvailCapacity | TotalCapacity | UsedPct | MaxDiskUsedPct | Tag                      | ErrMsg | Version         | Status                                                                                                                        |
+-----------+-----------------+--------------+---------------+--------+----------+----------+---------------------+---------------------+-------+----------------------+-----------------------+-----------+------------------+---------------+---------------+---------+----------------+--------------------------+--------+-----------------+-------------------------------------------------------------------------------------------------------------------------------+
| 10004     | default_cluster | 172.21.16.12 | 9050          | 9060   | 8040     | 8060     | 2022-04-08 16:19:39 | 2022-04-08 16:44:59 | true  | false                | false                 | 221       | 91.511 GB        | 3.415 TB      | 8.447 TB      | 59.57 % | 85.23 %        | {"location" : "default"} |        | trunk-c87ac2270 | {"lastSuccessReportTabletsTime":"2022-04-08 16:44:22","lastStreamLoadTime":-1,"isQueryDisabled":false,"isLoadDisabled":false} |
| 10005     | default_cluster | 172.21.16.15 | 9050          | 9060   | 8040     | 8060     | 2022-04-08 16:19:39 | 2022-04-08 16:44:59 | true  | false                | false                 | 208       | 85.433 GB        | 3.193 TB      | 9.255 TB      | 65.49 % | 75.10 %        | {"location" : "default"} |        | trunk-c87ac2270 | {"lastSuccessReportTabletsTime":"2022-04-08 16:44:11","lastStreamLoadTime":-1,"isQueryDisabled":false,"isLoadDisabled":false} |
| 10002     | default_cluster | 172.21.16.2  | 9050          | 9060   | 8040     | 8060     | 2022-04-08 16:19:39 | 2022-04-08 16:44:59 | true  | false                | false                 | 254       | 26.557 GB        | 3.156 TB      | 10.562 TB     | 70.12 % | 88.66 %        | {"location" : "default"} |        | trunk-c87ac2270 | {"lastSuccessReportTabletsTime":"2022-04-08 16:44:10","lastStreamLoadTime":-1,"isQueryDisabled":false,"isLoadDisabled":false} |
| 10003     | default_cluster | 172.21.16.6  | 9050          | 9060   | 8040     | 8060     | 2022-04-08 16:19:39 | 2022-04-08 16:44:59 | true  | false                | false                 | 275       | 32.354 GB        | 3.239 TB      | 9.216 TB      | 64.85 % | 79.58 %        | {"location" : "default"} |        | trunk-c87ac2270 | {"lastSuccessReportTabletsTime":"2022-04-08 16:44:10","lastStreamLoadTime":-1,"isQueryDisabled":false,"isLoadDisabled":false} |
+-----------+-----------------+--------------+---------------+--------+----------+----------+---------------------+---------------------+-------+----------------------+-----------------------+-----------+------------------+---------------+---------------+---------+----------------+--------------------------+--------+-----------------+-------------------------------------------------------------------------------------------------------------------------------+
4 rows in set (0.008 sec)

### What's Wrong?

2022-04-08 16:29:43.185 INFO [pool-3-thread-1] (Suite.groovy:129) - Execute tag: aggregate, sql:  select max(upper(c_string)), min(upper(c_string)) from datetype
2022-04-08 16:29:43.251 INFO [pool-3-thread-1] (Suite.groovy:129) - Execute tag: aggregate, sql:  select avg(c_bigint), avg(c_double) from datetype
2022-04-08 16:29:43.263 INFO [pool-3-thread-1] (Suite.groovy:129) - Execute tag: aggregate, sql:  select avg(distinct c_bigint), avg(distinct c_double) from datetype
2022-04-08 16:29:43.269 INFO [pool-3-thread-1] (Suite.groovy:129) - Execute tag: aggregate, sql:  select count(c_bigint),count(c_double),count(c_string),count(c_date),count(c_timestamp),count(c_boolean) from datetype
2022-04-08 16:29:43.279 INFO [pool-3-thread-1] (Suite.groovy:129) - Execute tag: aggregate, sql:  select count(distinct c_bigint),count(distinct c_double),count(distinct c_string),count(distinct c_date),count(distinct c_timestamp),count(distinct c_boolean) from datetype
2022-04-08 16:29:43.287 INFO [pool-3-thread-1] (Suite.groovy:129) - Execute tag: aggregate, sql:  select max(c_bigint), max(c_double),max(c_string), max(c_date), max(c_timestamp) from datetype
2022-04-08 16:29:43.299 INFO [pool-3-thread-1] (Suite.groovy:129) - Execute tag: aggregate, sql:  select min(c_bigint), min(c_double), min(c_string), min(c_date), min(c_timestamp) from datetype
2022-04-08 16:29:43.311 INFO [pool-3-thread-1] (Suite.groovy:129) - Execute tag: aggregate, sql:  select count(c_string), max(c_double), avg(c_bigint) from datetype
2022-04-08 16:29:43.322 INFO [pool-3-thread-1] (Suite.groovy:129) - Execute tag: aggregate, sql:  select stddev_pop(c_bigint), stddev_pop(c_double) from datetype
2022-04-08 16:29:43.331 INFO [pool-3-thread-1] (Suite.groovy:129) - Execute tag: aggregate, sql:  select stddev_pop(distinct c_bigint), stddev_pop(c_double) from datetype
2022-04-08 16:29:43.351 ERROR [pool-3-thread-1] (RegressionTest.groovy:173) - Run aggregate in /home/zhanglei/doris/regression-test/suites/aggregate/aggregate.groovy group aggregate elapsed 1036 failed
java.lang.IllegalStateException: 'aggregate' line not match . Detailed results is : 'Tag 'aggregate' wrong, line not match.
Expect line is: 3145.0576394647455      35.21027303154199
But real is   : 3145.057639464745       35.21027303154199'
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
        at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:72)
        at org.codehaus.groovy.reflection.CachedConstructor.doConstructorInvoke(CachedConstructor.java:59)
        at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrap.callConstructor(ConstructorSite.java:84)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallConstructor(CallSiteArray.java:59)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:263)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:277)
        at org.apache.doris.regression.suite.Suite.quickTest(Suite.groovy:165)
        at org.apache.doris.regression.suite.Suite.quickTest(Suite.groovy)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1268)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1035)
        at groovy.lang.DelegatingMetaClass.invokeMethod(DelegatingMetaClass.java:147)
        at groovy.lang.MetaObjectProtocol$invokeMethod$0.call(Unknown Source)
        at org.apache.doris.regression.suite.Suite.invokeMethod(Suite.groovy:198)
        at org.codehaus.groovy.runtime.callsite.PogoInterceptableSite.call(PogoInterceptableSite.java:45)
        at org.codehaus.groovy.runtime.callsite.PogoInterceptableSite.callCurrent(PogoInterceptableSite.java:55)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:194)
        at org.apache.doris.regression.suite.Suite.invokeMethod(Suite.groovy:183)
        at org.codehaus.groovy.runtime.callsite.PogoInterceptableSite.call(PogoInterceptableSite.java:45)
        at org.codehaus.groovy.runtime.callsite.PogoInterceptableSite.callCurrent(PogoInterceptableSite.java:55)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:51)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:171)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:185)
        at aggregate.run(aggregate.groovy:86)
        at org.apache.doris.regression.RegressionTest$_runSuite_closure5.doCall(RegressionTest.groovy:166)
        at org.apache.doris.regression.RegressionTest$_runSuite_closure5.call(RegressionTest.groovy)
        at org.codehaus.groovy.runtime.IOGroovyMethods.withCloseable(IOGroovyMethods.java:1607)
        at org.apache.doris.regression.RegressionTest.runSuite(RegressionTest.groovy:160)
        at org.apache.doris.regression.RegressionTest$_runGroupSuites_closure10$_lambda16.doCall(RegressionTest.groovy:212)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
2022-04-08 16:29:43.360 INFO [pool-2-thread-1] (RegressionTest.groovy:244) - Test 1 suites, failed 1 suites
2022-04-08 16:29:43.361 INFO [pool-2-thread-1] (RegressionTest.groovy:259) - Failure suites:
/home/zhanglei/doris/regression-test/suites/aggregate/aggregate.groovy: group=aggregate, name=aggregate
2022-04-08 16:29:43.361 INFO [pool-2-thread-1] (RegressionTest.groovy:277) - Some suites failed.
 _____ _    ___ _     _____ ____
|  ___/ \  |_ _| |   | ____|  _ \
| |_ / _ \  | || |   |  _| | | | |
|  _/ ___ \ | || |___| |___| |_| |
|_|/_/   \_\___|_____|_____|____/

### What You Expected?

/home/zhanglei/doris/regression-test/suites/aggregate/aggregate.groovy group aggregate elapsed 1036 failed
java.lang.IllegalStateException: 'aggregate' line not match . Detailed results is : 'Tag 'aggregate' wrong, line not match.
Expect line is: 3145.0576394647455      35.21027303154199
But real is   : 3145.057639464745       35.21027303154199'

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by SWJTU-ZhangLei** [comment]
https://github.com/trinodb/trino/blob/master/testing/trino-product-tests/src/main/resources/sql-tests/testcases/aggregate/stddev_popDistinct.result


trion result

-- delimiter: |; ignoreOrder: false;
3145.057639464745|40.0906295771357413|

**Comment by BiteTheDDDDt** [comment]
#8930 This pr is used to fix this problem.
