### ISSUE TITLE
[Bug]Hadoop high availability is currently not supported[Bug] 

### ISSUE THREAD

**Issue by cnmrzhou** [apache/doris#9129]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Version

1.0 

### What's Wrong?

use hive external table on thrift ,but response message: ERROR 1105 (HY000): errCode = 2, detailMessage = connect failed. hdfs://nameservice2

### What You Expected?

use hive external table on thrift ,but response message: ERROR 1105 (HY000): errCode = 2, detailMessage = connect failed. hdfs://nameservice2

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Jibing-Li** [comment]
The following hdfs ha related configuration items are missing.
```
        ("dfs.nameservices", "hacluster");
        ("dfs.ha.namenodes.hacluster", "3,4");
        ("dfs.namenode.rpc-address.hacluster.3", "192.168.0.93:8020");
        ("dfs.namenode.rpc-address.hacluster.4", "192.168.0.189:8020");
        ("dfs.client.failover.proxy.provider.hacluster", "org.apache.hadoop.hdfs.server.namenode.ha.ConfiguredFailoverProxyProvider");
```
Need to find a way to pass the above parameters to Doris hive external table. We will fix this very soon.

**Comment by wangmiao1002** [comment]
> 以下hdfs ha相关配置项缺失。
> 
> ```
>         ("dfs.nameservices", "hacluster");
>         ("dfs.ha.namenodes.hacluster", "3,4");
>         ("dfs.namenode.rpc-address.hacluster.3", "192.168.0.93:8020");
>         ("dfs.namenode.rpc-address.hacluster.4", "192.168.0.189:8020");
>         ("dfs.client.failover.proxy.provider.hacluster", "org.apache.hadoop.hdfs.server.namenode.ha.ConfiguredFailoverProxyProvider");
> ```
> 
> 需要想办法把上面的参数传给Doris hive外部表。我们将很快解决这个问题。

To add the above configuration, but it still doesn't work. Please give some instructions on how to modify the above errors. The specific logs are as follows:
org.apache.doris.common.UserException: errCode = 2, detailMessage = connect failed. hdfs://namesericve1
        at org.apache.doris.qe.Coordinator.getNext(Coordinator.java:806)
        at org.apache.doris.qe.StmtExecutor.handleQueryStmt(StmtExecutor.java:960)
        at org.apache.doris.qe.StmtExecutor.execute(StmtExecutor.java:383)
        at org.apache.doris.qe.StmtExecutor.execute(StmtExecutor.java:300)
        at org.apache.doris.qe.ConnectProcessor.handleQuery(ConnectProcessor.java:212)
        at org.apache.doris.qe.ConnectProcessor.dispatch(ConnectProcessor.java:349)
        at org.apache.doris.qe.ConnectProcessor.processOnce(ConnectProcessor.java:538)
        at org.apache.doris.mysql.nio.ReadListener.lambda$handleEvent$0(ReadListener.java:50)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

**Comment by Jibing-Li** [comment]
https://github.com/apache/incubator-doris/pull/9151
